### ISSUE TITLE
Inspect command does not show fleet server config

### ISSUE THREAD

**Issue by michalpristas** [elastic/elastic-agent#103]
**Problem Statement:**
Often for troubleshooting purposes the configuration form the agents needs to be gathered for further analysis. We need to ensure that our CLI is consistent across all entities to make troubleshooting less difficult.

When running agent with fleet server integration running
`./elastic-agent output -o default -p fleet-server` 
returns 
```
Error: program 'fleet-server' is not recognized within output 'default', try running `elastic-agent inspect output` to find available outputs
``` 

when running 
`./elastic-agent output -o default`
fleet server is not part of the output but it is when checking with 
`./elastic-agent output`

This issue is considered fixed when all commands provide valid results.
Check also endpoint and apm configs.

**Comment by michel-laterman** [comment]
Testing shows that endpoint, and apm both show in the `inspect` output. However `fleet-server` does not.

In a policy that just has the fleet integration, the input for it is:
```yaml
- data_stream:
    namespace: default
  id: fleet-server-fleet_server-5c9a92c6-8018-4461-adb8-0de6bbdbad10
  meta:
    package:
      name: fleet_server
      version: 1.1.1
  name: fleet_server-2
  revision: 1
  server:
    host: 0.0.0.0
    port: 8220
  type: fleet-server
  use_output: default
```
However the actual config is found as part of `fleet-server.yml`:
```yaml
fleet:
  enabled: true
  access_api_key: REDACTED
  protocol: http
  host: localhost:8220
  ssl:
    verification_mode: none
    renegotiation: never
  timeout: 10m0s
  proxy_disable: true
  reporting:
    threshold: 10000
    check_frequency_sec: 30
  agent:
    id: ""
  server:
    policy:
      id: ee6d0400-aa20-11ec-a452-9bb7648ff598
    output:
      elasticsearch:
        protocol: https
        hosts:
        - abd7095af01e4d71a7b9634c02092f5f.us-central1.gcp.qa.cld.elstc.co:443
        service_token: REDACTED
        proxy_disable: false
        proxy_headers: {}
    host: localhost
    port: 8220
    internal_port: 8221
```
Should we output the fleet section of the `fleet.yml` file in this case?
