### ISSUE TITLE
Docker agent moves to Unhealthy state on adding linux integration.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/elastic-agent#1454]
**Kibana version:** 8.5 Snapshot Kibana cloud environment

**Host OS:** 
Ubuntu 22 ARM64
GCP Container Optimized

**Build details:**
VERSION: 8.5 Snapshot
BUILD: 56952
COMMIT: 565ddb404984c516dab6ce46fd0c82c42d0c9dc3

**Preconditions:**
1. 8.5 Snapshot Kibana cloud environment should be available.
2. Docker setup should be done.

**Steps to reproduce:**
1. Install a docker agent using below command:
```
sudo docker run \
--env FLEET_ENROLL=1 \
--env FLEET_URL=<Fleet Server host URL> \
--env FLEET_ENROLLMENT_TOKEN=<enrollment token>
--rm docker.elastic.co/beats/elastic-agent:8.5.0-4f4df9f4-SNAPSHOT
```
2. Add linux integration to this policy and observe agent goes Unhealthy. 

**Expected Result:**
Docker agent should remain healthy on adding linux integration.

**Screen Recording:**

https://user-images.githubusercontent.com/77374876/194816752-234d86b4-3c88-4271-b091-08c4341db364.mp4

**Logs:**
[Docker Logs.txt](https://github.com/elastic/elastic-agent/files/9743977/Docker.Logs.txt)

**Elastic-Agent.yml:**
[elastic-agent (1).zip](https://github.com/elastic/elastic-agent/files/9743972/elastic-agent.1.zip)

**Comment by amolnater-qasource** [comment]
@manishgupta-qasource Please review.

**Comment by manishgupta-qasource** [comment]
Secondary review for this ticket is Done

**Comment by joshdover** [comment]
This seems to be the interesting error from the logs:

```
{"log.level":"error","@timestamp":"2022-10-10T06:41:56.571Z","log.origin":{"file.name":"status/reporter.go","file.line":326},"message":"Elastic Agent status changed to \"error\": \"app metricbeat--8.5.0-SNAPSHOT-4373eb9e: 1 error occurred:\\n\\t* 2 errors: Error creating runner from config: 1 error: error connecting to dbus: error getting connection to system bus: dial unix /var/run/dbus/system_bus_socket: connect: no such file or directory; Error creating runner from config: 1 error: error connecting to dbus: dial unix /var/run/dbus/system_bus_socket: connect: no such file or directory\\n\\n\"","ecs.version":"1.6.0"}
```

**Comment by belimawr** [comment]
Metricbeat is trying to access the `/var/run/dbus/system_bus_socket` from the host, but because it's on a docker container, it can't find it.

One thing to try is to give Metricbeat access to this socket, you can add `--volume="/var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket:ro"` (you need to try to know if read-only is enough). You might also need to add `--user=root` to run with more privileges inside the container.

Another thing that might help is looking at the documentation for [Metricbeat on Docker monitoring the host machine](https://www.elastic.co/guide/en/beats/metricbeat/current/running-on-docker.html#monitoring-host). Elastic-Agent is going to run a Metricbeat, so the Docker permissions/mounts will have to be the same.

**Comment by joshdover** [comment]
@belimawr this sounds like a breaking change in 8.5, right? Shouldn't Metricbeat handle this more gracefully to avoid breaking users who upgrade from previous versions

**Comment by belimawr** [comment]
Yes, it seems to be a breaking change. I did some quick testing with `8.4.3` and `8.5.0-SNAPSHOT` (both the Stack and Elastic-Agent). I can add the Linux Metrics integration, but the dashboard `[Metrics Linux] Host Services Overview` is always empty and it does not seem to be collecting any host metrics. However all agents are healthy.

One thing I noticed from the policy provided in the provided by @amolnater-qasource is that it seems to be running on a ARM host, if you look at the policy you'll see things like:
```
      indices:
        - names:
            - metrics-linux.entropy-arm_docker
          privileges: *ref_0
        - names:
            - metrics-linux.network_summary-arm_docker
          privileges: *ref_0
        - names:
            - metrics-linux.raid-arm_docker
          privileges: *ref_0
        - names:
            - metrics-linux.service-arm_docker
          privileges: *ref_0
        - names:
            - metrics-linux.socket-arm_docker
          privileges: *ref_0
        - names:
            - metrics-linux.users-arm_docker
          privileges: *ref_0
        - names:
            - metrics-linux.conntrack-arm_docker
          privileges: *ref_0
        - names:
            - metrics-linux.iostat-arm_docker
          privileges: *ref_0
        - names:
            - metrics-linux.ksm-arm_docker
          privileges: *ref_0
        - names:
            - metrics-linux.memory-arm_docker
          privileges: *ref_0
        - names:
            - metrics-linux.pageinfo-arm_docker
          privileges: *ref_0
```

Maybe that's an issue related to the ARM architecture?

For reference, here is my policy:
```
id: e5715670-4968-11ed-9f1f-93bcb7bec4cc
revision: 2
outputs:
  default:
    type: elasticsearch
    hosts:
      - >-
        https://my-8.5.0-SNAPSHOT.deployment-on.elastic-cloud.com:443
output_permissions:
  default:
    _elastic_agent_monitoring:
      indices:
        - names:
            - logs-elastic_agent.apm_server-default
          privileges: &ref_0
            - auto_configure
            - create_doc
        - names:
            - metrics-elastic_agent.apm_server-default
          privileges: *ref_0
        - names:
            - logs-elastic_agent.auditbeat-default
          privileges: *ref_0
        - names:
            - metrics-elastic_agent.auditbeat-default
          privileges: *ref_0
        - names:
            - logs-elastic_agent.cloudbeat-default
          privileges: *ref_0
        - names:
            - metrics-elastic_agent.cloudbeat-default
          privileges: *ref_0
        - names:
            - logs-elastic_agent-default
          privileges: *ref_0
        - names:
            - metrics-elastic_agent.elastic_agent-default
          privileges: *ref_0
        - names:
            - metrics-elastic_agent.endpoint_security-default
          privileges: *ref_0
        - names:
            - logs-elastic_agent.endpoint_security-default
          privileges: *ref_0
        - names:
            - logs-elastic_agent.filebeat-default
          privileges: *ref_0
        - names:
            - metrics-elastic_agent.filebeat-default
          privileges: *ref_0
        - names:
            - logs-elastic_agent.fleet_server-default
          privileges: *ref_0
        - names:
            - metrics-elastic_agent.fleet_server-default
          privileges: *ref_0
        - names:
            - logs-elastic_agent.heartbeat-default
          privileges: *ref_0
        - names:
            - metrics-elastic_agent.heartbeat-default
          privileges: *ref_0
        - names:
            - logs-elastic_agent.metricbeat-default
          privileges: *ref_0
        - names:
            - metrics-elastic_agent.metricbeat-default
          privileges: *ref_0
        - names:
            - logs-elastic_agent.osquerybeat-default
          privileges: *ref_0
        - names:
            - metrics-elastic_agent.osquerybeat-default
          privileges: *ref_0
        - names:
            - logs-elastic_agent.packetbeat-default
          privileges: *ref_0
        - names:
            - metrics-elastic_agent.packetbeat-default
          privileges: *ref_0
    _elastic_agent_checks:
      cluster:
        - monitor
    bf69818c-aa47-41c0-8aa2-c82dc716d80d:
      indices:
        - names:
            - logs-system.auth-default
          privileges: *ref_0
        - names:
            - logs-system.syslog-default
          privileges: *ref_0
        - names:
            - logs-system.application-default
          privileges: *ref_0
        - names:
            - logs-system.security-default
          privileges: *ref_0
        - names:
            - logs-system.system-default
          privileges: *ref_0
        - names:
            - metrics-system.cpu-default
          privileges: *ref_0
        - names:
            - metrics-system.diskio-default
          privileges: *ref_0
        - names:
            - metrics-system.filesystem-default
          privileges: *ref_0
        - names:
            - metrics-system.fsstat-default
          privileges: *ref_0
        - names:
            - metrics-system.load-default
          privileges: *ref_0
        - names:
            - metrics-system.memory-default
          privileges: *ref_0
        - names:
            - metrics-system.network-default
          privileges: *ref_0
        - names:
            - metrics-system.process-default
          privileges: *ref_0
        - names:
            - metrics-system.process.summary-default
          privileges: *ref_0
        - names:
            - metrics-system.socket_summary-default
          privileges: *ref_0
        - names:
            - metrics-system.uptime-default
          privileges: *ref_0
    ff8d66c3-6417-4319-a72a-4501d0c907d2:
      indices:
        - names:
            - metrics-linux.network_summary-default
          privileges: *ref_0
        - names:
            - metrics-linux.iostat-default
          privileges: *ref_0
        - names:
            - metrics-linux.memory-default
          privileges: *ref_0
agent:
  download:
    source_uri: 'https://artifacts.elastic.co/downloads/'
  monitoring:
    enabled: true
    use_output: default
    namespace: default
    logs: true
    metrics: true
inputs:
  - id: logfile-system-bf69818c-aa47-41c0-8aa2-c82dc716d80d
    name: system-1
    revision: 1
    type: logfile
    use_output: default
    meta:
      package:
        name: system
        version: 1.19.5
    data_stream:
      namespace: default
    package_policy_id: bf69818c-aa47-41c0-8aa2-c82dc716d80d
    streams:
      - id: logfile-system.auth-bf69818c-aa47-41c0-8aa2-c82dc716d80d
        data_stream:
          dataset: system.auth
          type: logs
        ignore_older: 72h
        paths:
          - /var/log/auth.log*
          - /var/log/secure*
        exclude_files:
          - .gz$
        multiline:
          pattern: ^\s
          match: after
        tags:
          - hashicorp-vault-log
        processors:
          - add_locale: null
      - id: logfile-system.syslog-bf69818c-aa47-41c0-8aa2-c82dc716d80d
        data_stream:
          dataset: system.syslog
          type: logs
        paths:
          - /var/log/messages*
          - /var/log/syslog*
        exclude_files:
          - .gz$
        multiline:
          pattern: ^\s
          match: after
        processors:
          - add_locale: null
        ignore_older: 72h
  - id: winlog-system-bf69818c-aa47-41c0-8aa2-c82dc716d80d
    name: system-1
    revision: 1
    type: winlog
    use_output: default
    meta:
      package:
        name: system
        version: 1.19.5
    data_stream:
      namespace: default
    package_policy_id: bf69818c-aa47-41c0-8aa2-c82dc716d80d
    streams:
      - id: winlog-system.application-bf69818c-aa47-41c0-8aa2-c82dc716d80d
        name: Application
        data_stream:
          dataset: system.application
          type: logs
        condition: '${host.platform} == ''windows'''
        ignore_older: 72h
      - id: winlog-system.security-bf69818c-aa47-41c0-8aa2-c82dc716d80d
        name: Security
        data_stream:
          dataset: system.security
          type: logs
        condition: '${host.platform} == ''windows'''
        ignore_older: 72h
      - id: winlog-system.system-bf69818c-aa47-41c0-8aa2-c82dc716d80d
        name: System
        data_stream:
          dataset: system.system
          type: logs
        condition: '${host.platform} == ''windows'''
        ignore_older: 72h
  - id: system/metrics-system-bf69818c-aa47-41c0-8aa2-c82dc716d80d
    name: system-1
    revision: 1
    type: system/metrics
    use_output: default
    meta:
      package:
        name: system
        version: 1.19.5
    data_stream:
      namespace: default
    package_policy_id: bf69818c-aa47-41c0-8aa2-c82dc716d80d
    streams:
      - id: system/metrics-system.cpu-bf69818c-aa47-41c0-8aa2-c82dc716d80d
        data_stream:
          dataset: system.cpu
          type: metrics
        metricsets:
          - cpu
        cpu.metrics:
          - percentages
          - normalized_percentages
        period: 10s
      - id: system/metrics-system.diskio-bf69818c-aa47-41c0-8aa2-c82dc716d80d
        data_stream:
          dataset: system.diskio
          type: metrics
        metricsets:
          - diskio
        diskio.include_devices: null
        period: 10s
      - id: system/metrics-system.filesystem-bf69818c-aa47-41c0-8aa2-c82dc716d80d
        data_stream:
          dataset: system.filesystem
          type: metrics
        metricsets:
          - filesystem
        period: 1m
        processors:
          - drop_event.when.regexp:
              system.filesystem.mount_point: ^/(sys|cgroup|proc|dev|etc|host|lib|snap)($|/)
      - id: system/metrics-system.fsstat-bf69818c-aa47-41c0-8aa2-c82dc716d80d
        data_stream:
          dataset: system.fsstat
          type: metrics
        metricsets:
          - fsstat
        period: 1m
        processors:
          - drop_event.when.regexp:
              system.fsstat.mount_point: ^/(sys|cgroup|proc|dev|etc|host|lib|snap)($|/)
      - id: system/metrics-system.load-bf69818c-aa47-41c0-8aa2-c82dc716d80d
        data_stream:
          dataset: system.load
          type: metrics
        metricsets:
          - load
        condition: '${host.platform} != ''windows'''
        period: 10s
      - id: system/metrics-system.memory-bf69818c-aa47-41c0-8aa2-c82dc716d80d
        data_stream:
          dataset: system.memory
          type: metrics
        metricsets:
          - memory
        period: 10s
      - id: system/metrics-system.network-bf69818c-aa47-41c0-8aa2-c82dc716d80d
        data_stream:
          dataset: system.network
          type: metrics
        metricsets:
          - network
        period: 10s
        network.interfaces: null
      - id: system/metrics-system.process-bf69818c-aa47-41c0-8aa2-c82dc716d80d
        data_stream:
          dataset: system.process
          type: metrics
        metricsets:
          - process
        period: 10s
        process.include_top_n.by_cpu: 5
        process.include_top_n.by_memory: 5
        process.cmdline.cache.enabled: true
        process.cgroups.enabled: false
        process.include_cpu_ticks: false
        processes:
          - .*
      - id: >-
          system/metrics-system.process.summary-bf69818c-aa47-41c0-8aa2-c82dc716d80d
        data_stream:
          dataset: system.process.summary
          type: metrics
        metricsets:
          - process_summary
        period: 10s
      - id: >-
          system/metrics-system.socket_summary-bf69818c-aa47-41c0-8aa2-c82dc716d80d
        data_stream:
          dataset: system.socket_summary
          type: metrics
        metricsets:
          - socket_summary
        period: 10s
      - id: system/metrics-system.uptime-bf69818c-aa47-41c0-8aa2-c82dc716d80d
        data_stream:
          dataset: system.uptime
          type: metrics
        metricsets:
          - uptime
        period: 10s
  - id: system/metrics-system-ff8d66c3-6417-4319-a72a-4501d0c907d2
    name: linux-1
    revision: 1
    type: system/metrics
    use_output: default
    meta:
      package:
        name: linux
        version: 0.6.8
    data_stream:
      namespace: default
    package_policy_id: ff8d66c3-6417-4319-a72a-4501d0c907d2
    streams:
      - id: >-
          system/metrics-linux.network_summary-ff8d66c3-6417-4319-a72a-4501d0c907d2
        data_stream:
          dataset: linux.network_summary
          type: metrics
        metricsets:
          - network_summary
        condition: '${host.platform} == ''linux'''
        period: 10s
        processors:
          - drop_fields:
              fields: event.module
  - id: linux/metrics-system-ff8d66c3-6417-4319-a72a-4501d0c907d2
    name: linux-1
    revision: 1
    type: linux/metrics
    use_output: default
    meta:
      package:
        name: linux
        version: 0.6.8
    data_stream:
      namespace: default
    package_policy_id: ff8d66c3-6417-4319-a72a-4501d0c907d2
    streams:
      - id: linux/metrics-linux.iostat-ff8d66c3-6417-4319-a72a-4501d0c907d2
        data_stream:
          dataset: linux.iostat
          type: metrics
        metricsets:
          - iostat
        condition: '${host.platform} == ''linux'''
        period: 10s
      - id: linux/metrics-linux.memory-ff8d66c3-6417-4319-a72a-4501d0c907d2
        data_stream:
          dataset: linux.memory
          type: metrics
        metricsets:
          - memory
        condition: '${host.platform} == ''linux'''
        period: 10s
fleet:
  hosts:
    - >-
      https://my-8.5.0-SNAPSHOT.deployment-on.elastic-cloud.com:443
```
