### ISSUE TITLE
Add system-level info to elastic-agent diagnostics command 

### ISSUE THREAD

**Issue by fearful-symmetry** [elastic/elastic-agent#1680]
CC @cmacknz 

So, in my experience, a lot of applications with a diagnostics/error-dump-uploader/whatever helper usually report fairly detailed operating system configs. While `elastic-agent diagnostics` doesn't run on core dump or whatever, it might be helpful to report basic system config details to speed up the support process, since a _lot_ of time can get burned asking for system/application states that aren't provided up-front.

Some basic things to collect:

- OS Version/Kernel revision 
- For linux, the specific distro
- Basic meta-configuration for elastic-agent. How it was installed, what directory we're running in, if we're containerized, etc

In addition, this can be expanded to be a hook-based system that calls different diagnostics depending on what integrations are configured. For example, if the user is running a redis integration, they can run something like `./elastic-agent diagnostics --integration redis,system` and get a basic connection status for the redis DB, as well as raw system metrics values that can be valuable for debugging issues with system metrics. We might just be able to implement that via a special `RegisterDiagnosticHook` call?

**Comment by cmacknz** [comment]
Agreed, I think it makes sense to include more detailed information about the system the agent is running on in the diagnostics bundle. We should be able to add a new file with system and installation information to the meta directory currently included in the agent diagnostics bundle.

Allowing for integration specific diagnostics is an interesting idea as well, but it may make more sense to make it easy and cheap enough to collect that information all the time rather than making it optional. In the long term I feel this would create too many variants of the diagnostics command, and create too much back and forth with users when debugging problems.

Let's at least keep the scope of this issue to including OS and installation information in diagnostics so we don't have to parse this information out of the logs manually. I would open a separate issue for how we should include integration specific diagnostics. This may overlap somewhat with a design for per integration health reporting.

**Comment by cmacknz** [comment]
If you look at the variables.yml file output in a V2 diagnostics bundle it will have almost all of the items you've requested, including every environment variable.

Example from an arbitrary Windows agent:

```yaml
variables:
- agent:
    id: 740e67a7-5a21-4cf6-888d-e7a0afd8b045
    version:
      build_time: 2022-12-07 22:11:44 +0000 UTC
      commit: 196b861d69ad62ab4d3fef2827864abeee8e914c
      snapshot: false
      version: 8.6.0
  env:
    ALLUSERSPROFILE: C:\ProgramData
    APPDATA: C:\Windows\system32\config\systemprofile\AppData\Roaming
    AWS_EXECUTION_ENV: EC2
    COMPUTERNAME: EC2AMAZ-TC0OAJR
    ComSpec: C:\Windows\system32\cmd.exe
    CommonProgramFiles: C:\Program Files\Common Files
    CommonProgramFiles(x86): C:\Program Files (x86)\Common Files
    CommonProgramW6432: C:\Program Files\Common Files
    DriverData: C:\Windows\System32\Drivers\DriverData
    EC2LAUNCH_TELEMETRY: "1"
    LOCALAPPDATA: C:\Windows\system32\config\systemprofile\AppData\Local
    NUMBER_OF_PROCESSORS: "2"
    OS: Windows_NT
    PATHEXT: .COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
    PROCESSOR_ARCHITECTURE: AMD64
    PROCESSOR_IDENTIFIER: Intel64 Family 6 Model 79 Stepping 1, GenuineIntel
    PROCESSOR_LEVEL: "6"
    PROCESSOR_REVISION: 4f01
    PSModulePath: C:\Program Files\WindowsPowerShell\Modules;C:\Windows\system32\WindowsPowerShell\v1.0\Modules;C:\Program
      Files (x86)\AWS Tools\PowerShell\
    PUBLIC: C:\Users\Public
    Path: C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program
      Files\Amazon\cfn-bootstrap\;C:\Windows\system32\config\systemprofile\AppData\Local\Microsoft\WindowsApps
    ProgramData: C:\ProgramData
    ProgramFiles: C:\Program Files
    ProgramFiles(x86): C:\Program Files (x86)
    ProgramW6432: C:\Program Files
    SystemDrive: 'C:'
    SystemRoot: C:\Windows
    TEMP: C:\Windows\TEMP
    TMP: C:\Windows\TEMP
    USERDOMAIN: WORKGROUP
    USERNAME: EC2AMAZ-TC0OAJR$
    USERPROFILE: C:\Windows\system32\config\systemprofile
    windir: C:\Windows
  host:
    architecture: x86_64
    id: 867f6f41-b15a-4202-9ff1-bf002da3b872
    ip:
    - <redacted>
    - <redacted>
    - ::1/128
    - 127.0.0.1/8
    mac:
    - <redacted>
    name: <redacted>
    platform: windows
  kubernetes_leaderelection: {}
  kubernetes_secrets: {}
  local: {}
  path:
    config: C:\Program Files\Elastic\Agent
    data: C:\Program Files\Elastic\Agent\data
    home: C:\Program Files\Elastic\Agent\data\elastic-agent-196b86
    logs: C:\Program Files\Elastic\Agent
```
