### ISSUE TITLE
${host.platform} != 'windows' conditional is not respected in agent policy

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/elastic-agent#1697]
**Kibana version:** 8.6 SNAPSHOT Kibana cloud environment

**Host OS:** Windows

**Build details:**
VERSION: 8.6 SNAPSHOT
BUILD: 58038
COMMIT: b02d976a3b8466ae4e0b1ec9840175dce1790719

**Preconditions:**
1. 8.6 SNAPSHOT Kibana cloud environment should be available.
2. Windows agent should be installed.

**Steps to reproduce:**
1. Navigate to Agents tab and then agent Logs page.
2. Change logging level to `debug`.
3. Observe metricbeat fails to restart in agent logs.

**Expected Result:**
Metricbeat fails should restart successfully on changing logging level for windows agent.

**Screenshots:**
![1](https://user-images.githubusercontent.com/77374876/200762581-8a31259b-0e6f-4b91-a8da-ba1f67aa7825.JPG)
![2](https://user-images.githubusercontent.com/77374876/200762595-75fe5c65-8428-4ca8-b6e4-8ed5fe3255ca.JPG)
![3](https://user-images.githubusercontent.com/77374876/200762599-a7723012-c33f-4784-a312-a354052d8508.JPG)

**Agent Logs:**
[elastic-agent-diagnostics-2022-11-09T07-09-06Z-00.zip](https://github.com/elastic/elastic-agent/files/9968276/elastic-agent-diagnostics-2022-11-09T07-09-06Z-00.zip)

**Comment by amolnater-qasource** [comment]
@manishgupta-qasource Please review.

**Comment by manishgupta-qasource** [comment]
Secondary review for this ticket is Done

**Comment by cmacknz** [comment]
I see the `system/load` metricset in the policy but it is behind conditional that should prevent it from being included on Windows:

```yaml
  - condition: ${host.platform} != 'windows'
    data_stream:
      dataset: system.load
      type: metrics
    id: system/metrics-system.load-cd4542f8-f25f-4d58-b3a2-d566178082d1
    metricsets:
    - load
    period: 10s
```

The bug here is likely that this conditional isn't applied correctly.
