### ISSUE TITLE
Input IDs are not unique at runtime when dynamic providers are used

### ISSUE THREAD

**Issue by belimawr** [elastic/elastic-agent#1751]
# Description
When dynamic providers are used on a integration, they end up creating 'multiple instances' of the input defined in the policy, one for each value the variable resolves. This leads to duplicated input IDs at runtime, which makes the Elastic-Agent to be stuck in a unhealthy state.

## Example:

1. Given the Kubernetes integration, it will generate an input like this:
```yaml
- id: filestream-container-logs-78ab239f-a490-4d13-8c46-ef0f14844f88
  name: kubernetes-1
  revision: 1
  type: filestream
  use_output: default
  meta:
    package:
      name: kubernetes
      version: 1.27.1
  data_stream:
    namespace: default
  package_policy_id: 78ab239f-a490-4d13-8c46-ef0f14844f88
  streams:
    - id: kubernetes-container-logs-${kubernetes.pod.name}-${kubernetes.container.id}
      data_stream:
        dataset: kubernetes.container_logs
        type: logs
      paths:
        - '/var/log/containers/*${kubernetes.container.id}.log'
      prospector.scanner.symlinks: true
      parsers:
        - container:
            stream: all
            format: auto
```

2. For each `kubernetes.container.id` one instance of this whole input will be rendered, looking like this (focus on the `streams` array):
```yaml
---
data_stream:
  namespace: default
name: kubernetes-1
revision: 1
type: filestream
id: filestream-container-logs-78ab239f-a490-4d13-8c46-ef0f14844f88
meta:
  package:
    name: kubernetes
    version: 1.27.1
package_policy_id: 78ab239f-a490-4d13-8c46-ef0f14844f88
streams:
- data_stream:
    dataset: kubernetes.container_logs
    type: logs
  id: kubernetes-container-logs-kube-controller-manager-kind-control-plane-3574f560581101546c1b9448b9396e13f0abbd08e7e59f7ae711427247e11873
  parsers:
  - container:
      format: auto
      stream: all
  paths:
  - "/var/log/containers/*3574f560581101546c1b9448b9396e13f0abbd08e7e59f7ae711427247e11873.log"
  prospector.scanner.symlinks: true
```

3. The 'input ID' will then not be unique anymore because there are 'multiple instances' of this input, however the 'streams[].id' will be unique (that's required by Filebeat to use the Filestream input as in the example)

4. The problem arises because the Elastic-Agent tries to ensure the 'input ID' is unique at runtime
https://github.com/elastic/elastic-agent/blob/dcbeb9da166826f88e18e236c3ebf23b09dcdd87/pkg/component/component.go#L485-L487

5. The [PR introducing this change](https://github.com/elastic/elastic-agent/pull/1061) mention it's required under V2
6. I'm not quite sure about the implications of either removing this check or changing it to ensure that `inputs[].streams[].id` is unique.

# Steps to Reproduce
1. create a local k8s cluster with kind kind create cluster --config kind-cluster.yaml

```yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    kubeadmConfigPatches:
```

7. bring up elastic stack versions 8.6.0-SNAPSHOT with elastic package

```elastic-package stack up --version=8.6.0-SNAPSHOT -v -d```

8. Connect both docker networks with the following script

```bash
#! /bin/bash

for i in $(docker ps | grep kindest | awk '{ print $1 }'); do
    docker network connect elastic-package-stack_default   "$i"
done
```

9. Create a policy with kubernetes integration and follow UI instructions on running agent on k8s.
10. You will see agents not collecting anything and reporting the following error:
```json
{"log.level":"error","@timestamp":"2022-11-17T16:23:29.316Z","log.origin":{"file.name":"coordinator/coordinator.go","file.line":544},"message":"failed to render components: invalid 'inputs.8.id', has a duplicate id \"filestream-container-logs-78ab239f-a490-4d13-8c46-ef0f14844f88\" (id is required to be unique)","ecs.version":"1.6.0"}
```

# Related issues
 - https://github.com/elastic/integrations/pull/3672#issuecomment-1318452349
