### ISSUE TITLE
V2: Endpoint policy yml has an empty "policy" section while yml seen in Kibana in Fleet has correct settings

### ISSUE THREAD

**Issue by kevinlog** [elastic/elastic-agent#1757]
When I add the Elastic Defend integration to an Agent Policy, I see that the configuration saved in policy yml seen in Kibana is not propagated to the Endpoint.  As a result, the Endpoint doesn't stream any Events to the stack since it isn't getting the proper configuration.  I'm not sure if this is an Agent or Endpoint bug right now, I will move to the right repo if we determine one way or another.

See the yml in Kibana:

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/56395104/202746480-665f3c82-c482-437e-975a-e2f07d4c2b4b.png">

Example of Eventing options turned on in Fleet UI:

<img width="1711" alt="image" src="https://user-images.githubusercontent.com/56395104/202749112-00bc2ec9-c7a7-4234-8565-65f8a0143213.png">

See the Policy that ends up on the Endpoint on the host machine:

<img width="1221" alt="image" src="https://user-images.githubusercontent.com/56395104/202747034-5bd36a41-91f2-4335-891f-d5e2228f01a7.png">

Find the full yml for each below.  I redacted API keys, just ping me if you want the full versions.

[policy_yml.zip](https://github.com/elastic/elastic-agent/files/10042937/policy_yml.zip)

Agent logs:

[elastic-agent.log](https://github.com/elastic/elastic-agent/files/10042912/elastic-agent.log)

Endpoint logs:

[endpoint.log](https://github.com/elastic/elastic-agent/files/10042913/endpoint.log)

- Version:
Elastic Agent version:
```
Binary: 8.6.0-SNAPSHOT (build: 28b7624d33e751451bd2450b9f539016d2fb93cd at 2022-11-18 05:20:53 +0000 UTC)
```

Endpoint version:
```
version: 8.6.0-SNAPSHOT, compiled: Fri Nov 18 01:00:00 2022, branch: 8.6, commit: ab924991d4cdbb23c011489dd81703142cffafe4
```

- Operating System: Linux ARM Agent/Endpoint, unconfirmed if it's affecting other OSs

- Steps to Reproduce:
1. Get the 8.6.0-SNAPSHOT Agent, versions are above
2. Install the Agent with the Elastic Defend Integration
3. See that the policy is saved correctly in Kibana with default Eventing options enabled.
4. See that the Endpoint policy does not have the `policy: {}` section in its yml.  `elastic-endpoint.yml` is located at `/opt/Elastic/Endpoint` in a normal installation.

**Comment by kevinlog** [comment]
cc @ferullo @softengchick @nfritts

**Comment by brian-mckinney** [comment]
Any chance we can dump the checkin that is being sent to the endpoint?  The fact that much of the policy is being written, except for the `policy` field tells me that we are getting the checkin and at least translating part of it.  Perhaps the format has changed slightly since when we did our informal e2e test.

I'm attaching a dump of the CheckinExpected message that the endpoint is expecting right now.  It is what we are using in our mocked test environment.  I'd like to rule out any format inconsistencies with how the policy is being defined in protobuf exchange.
[checkin_expected.zip](https://github.com/elastic/elastic-agent/files/10043866/checkin_expected.zip)

**Comment by kevinlog** [comment]
@brian-mckinney I'm attaching the `check_v2_serialized.bin` file from the special Endpoint that was built.  I am seeing the same behavior as described in this bug where `policy:{}` in the endpoint policy yml and Eventing is disabled.

Let me know if there's anything else I can provide at this time.

[checkin_v2_serialized.bin.zip](https://github.com/elastic/elastic-agent/files/10050773/checkin_v2_serialized.bin.zip)

**Comment by intxgo** [comment]
I've checked the bin file by opening it in Vim. AFAIK all the yaml keys should be visible as plain strings in the binary dump. I can see the `policy` key, but not `linux`|`windows`|`mac`, `events`, etc. any other deeper nested policy config key. It really looks like the policy section is empty. Could someone on Agent side verify that the policy is really serialized and send?

**Comment by kevinlog** [comment]
@intxgo thank you for taking a look

> It really looks like the policy section is empty. Could someone on Agent side verify that the policy is really serialized and send inside protobuf message?

@cmacknz @aleksmaus fyi on the above, any ideas on the Agent side on what could be going wrong?  Any other information I can look to gather?  Currently in this this ticket, I have:

- Policy ymls seen in Kibana and Endpoint: [policy_yml.zip](https://github.com/elastic/elastic-agent/files/10042937/policy_yml.zip)

- Agent logs: [elastic-agent.log](https://github.com/elastic/elastic-agent/files/10042912/elastic-agent.log)

- Endpoint logs: [endpoint.log](https://github.com/elastic/elastic-agent/files/10042913/endpoint.log)

- Actual checkin dump: [checkin_v2_serialized.bin.zip](https://github.com/elastic/elastic-agent/files/10050773/checkin_v2_serialized.bin.zip)

- Expected checkin dump: [checkin_expected.zip](https://github.com/elastic/elastic-agent/files/10043866/checkin_expected.zip)

**Comment by cmacknz** [comment]
It is odd that we would only be sending part of the payload here. I'll investigate to see what is happening on the agent side.

**Comment by ferullo** [comment]
@cmacknz is there any progress on this? I'd like to raise it as a critical blocker since it blocks all Endpoint testing.

**Comment by cmacknz** [comment]
No major updates, just that I can reproduce it. I am working through finding the root cause.

**Comment by cmacknz** [comment]
I think I've found the problem.

We seem to have some logic to unconditionally inject the policy revision into each input configuration, but it is colliding the `policy` key endpoint already uses: https://github.com/elastic/elastic-agent/blob/28b7624d33e751451bd2450b9f539016d2fb93cd/pkg/component/component.go#L219-L229

If I remove this (or make it conditional on a policy key not existing already) then we get endpoint's policy section as expected. I am inclined to just remove this entirely once I confirm we aren't relying on it anywhere else.

**Comment by kevinlog** [comment]
@cmacknz thank you for taking a look!  I have one question about the "revision".  Currently, in the Security Kibana UI, we do make use of a `revision` field, I just want to make sure that one will still be there.

Ex:
```
...
inputs:
- meta:
    package:
      version: 8.5.0
      name: endpoint
  data_stream:
    namespace: default
  revision: 1
  type: endpoint
  package_policy_id: 304041ba-efe2-45e6-a62f-b0ebb8be3c96
  id: 304041ba-efe2-45e6-a62f-b0ebb8be3c96
  policy: {}
  name: endpoint-1
...
```

Above is a snippet of the policy yml that currently ends up on the Endpoint (note that `policy:{}`).  We make use of the `revision: 1` field that you also see there.  We've used this field for a couple years now.  From your change it looks like that it was a new injection into the policy field and the top level `revision` is still there, so I think we're OK.  I just wanted to double check.  Thanks!

**Comment by ferullo** [comment]
> it looks like that it was a new injection into the policy field and the top level revision is still there

I think what you're seeing @kevinlog is Endpoint that moves `inputs[0].policy.revision` to the top level and deletes it from the path Agent puts it at, because Endpoint is massaging the v2 protocol fields to match the original v1 config format.

So if `inputs[0].policy.revision` is removed and put somewhere else then Endpoint will have to change where it reads it from to move it to the top level.

@brian-mckinney please correct me if I'm wrong.

Is there a chance the Agent changes can be merged in time for BC2 tomorrow? Endpoint can adapt to the new revision field location in time if Agent's fix will be ready and we know where to read it from.

**Comment by ferullo** [comment]
Also, if Agent can just insert `revision` into `policy.*` without blowing away the original `policy.*` fieldset then no Endpoint changes are needed.

**Comment by cmacknz** [comment]
I can get this change merged tonight as long as we are convinced the change won't just break something else.

To clarify, the top level `revision` field is still there. I am removing the unconditional creation of a `policy.revision` object and key in addition to that.

```yaml
inputs:
- meta:
    package:
      version: 8.5.0
      name: endpoint
  data_stream:
    namespace: default
  revision: 1 <-- Which is separate from this input.revision, which is as it was before
  type: endpoint
  package_policy_id: 304041ba-efe2-45e6-a62f-b0ebb8be3c96
  id: 304041ba-efe2-45e6-a62f-b0ebb8be3c96
  policy:       # <--- These two keys are what is being removed.
    revision: 4 # <--- They unconditionally overwrite the entire endpoint policy object.
  name: endpoint-1
```

The `policy.revision` key that was added matches the top level `revision` key in an agent policy viewed in fleet. I think this was an attempt to make this accessible to individual agent sub-processes:

```yaml
id: e25d1ae0-69d0-11ed-b8bb-79914057f4b9
revision: 4 #<--- This is the revision that was injected in policy.revision
outputs:
  default:
    type: elasticsearch
    hosts:
      - cloud.com:443
output_permissions:
  # ...
agent:
  # ...
inputs:
  - id: logfile-system-56ecc506-11a3-452c-8bab-68dafd92a3ac
    name: system-1
    revision: 1
    type: logfile
    # ...
```

**Comment by ferullo** [comment]
that sounds right to me. as i recall, the top level revision isn't sent to endpoint in v2, but endpoint needs it, which is why it's injected into something endpoint does receive.

**Comment by cmacknz** [comment]
Going through the endpoint code for this in AgentContext.cpp (which I won't link from here because it's a public issue) it looks like endpoint does try to parse out `policy.revision`.

So the correct thing for agent do is to add a `policy.revision` key, but without overwriting the entire `policy` object like it does now. I'll make that change and get it merged.

**Comment by cmacknz** [comment]
Fix is merged to main and 8.6, hopefully we can confirm this is fixed in the next BC and leave it closed.

**Comment by simitt** [comment]
For what it's worth, the APM Server also uses the `revision` from the `input` configuration. But afaiu, you solved the issue not by removing, but by injecting the `revision` without overwriting other policy data; so it should still work for apm.

**Comment by kevinlog** [comment]
@amolnater-qasource the `elastic-agent.yml` file you provided looks correct.  However, to properly verify, we need to see the `elastic-endpoint.yml` file.

Can you share the file located at `/opt/Elastic/Endpoint/elastic-endpoint.yml` ?  If the `policy` field in that file is populated then the bug is fixed.  If it is still populated as `policy: {}` then the bug is still present.  

One thing to note, when sharing the above file, it contains two fields `access_api_key` and `api_key`.  Could you delete these fields before sharing so as not to share them in this public issue?

**Comment by kevinlog** [comment]
@amolnater-qasource I did a verification on my side with the latest and everything looks good on my end.

The `elastic-endpoint.yml` file has the `policy` section properly populated.
```
revision: 2
fleet:
  protocol: http
  timeout: 10m0s
  access_api_key: XXXXX
  host:
    id: 3787c48ab74047b28638ef2ddc97be6c
  enabled: true
  ssl:
    renegotiation: never
    verification_mode: none
  agent:
    id: b36ca33c-6e22-4f5f-a306-f2c5933fec02
  hosts:
  - http://10.0.0.199:8220
output:
  elasticsearch:
    type: elasticsearch
    api_key: XXXXXX
    hosts:
    - http://10.0.0.199:9200
inputs:
- package_policy_id: 2d2620aa-ffb9-4852-9c45-0f5805089b87
  id: 2d2620aa-ffb9-4852-9c45-0f5805089b87
  name: Protect
  artifact_manifest:
    artifacts:
      endpoint-exceptionlist-linux-v1:
        compression_algorithm: zlib
        encoded_sha256: f8e6afa1d5662f5b37f83337af774b5785b5b7f1daee08b7b00c2d6813874cda
        decoded_size: 14
        encryption_algorithm: none
        encoded_size: 22
        relative_url: /api/fleet/artifacts/endpoint-exceptionlist-linux-v1/d801aa1fb7ddcc330a5e3173372ea6af4a3d08ec58074478e85aa5603e926658
        decoded_sha256: d801aa1fb7ddcc330a5e3173372ea6af4a3d08ec58074478e85aa5603e926658
      endpoint-hostisolationexceptionlist-windows-v1:
        compression_algorithm: zlib
        encoded_size: 22
        encryption_algorithm: none
        relative_url: /api/fleet/artifacts/endpoint-hostisolationexceptionlist-windows-v1/d801aa1fb7ddcc330a5e3173372ea6af4a3d08ec58074478e85aa5603e926658
        encoded_sha256: f8e6afa1d5662f5b37f83337af774b5785b5b7f1daee08b7b00c2d6813874cda
        decoded_sha256: d801aa1fb7ddcc330a5e3173372ea6af4a3d08ec58074478e85aa5603e926658
        decoded_size: 14
      endpoint-eventfilterlist-linux-v1:
        encoded_size: 22
        encryption_algorithm: none
        relative_url: /api/fleet/artifacts/endpoint-eventfilterlist-linux-v1/d801aa1fb7ddcc330a5e3173372ea6af4a3d08ec58074478e85aa5603e926658
        decoded_sha256: d801aa1fb7ddcc330a5e3173372ea6af4a3d08ec58074478e85aa5603e926658
        encoded_sha256: f8e6afa1d5662f5b37f83337af774b5785b5b7f1daee08b7b00c2d6813874cda
        compression_algorithm: zlib
        decoded_size: 14
      endpoint-trustlist-windows-v1:
        encryption_algorithm: none
        relative_url: /api/fleet/artifacts/endpoint-trustlist-windows-v1/d801aa1fb7ddcc330a5e3173372ea6af4a3d08ec58074478e85aa5603e926658
        decoded_size: 14
        compression_algorithm: zlib
        encoded_sha256: f8e6afa1d5662f5b37f83337af774b5785b5b7f1daee08b7b00c2d6813874cda
        encoded_size: 22
        decoded_sha256: d801aa1fb7ddcc330a5e3173372ea6af4a3d08ec58074478e85aa5603e926658
      endpoint-eventfilterlist-windows-v1:
        compression_algorithm: zlib
        decoded_sha256: d801aa1fb7ddcc330a5e3173372ea6af4a3d08ec58074478e85aa5603e926658
        decoded_size: 14
        encoded_size: 22
        encoded_sha256: f8e6afa1d5662f5b37f83337af774b5785b5b7f1daee08b7b00c2d6813874cda
        relative_url: /api/fleet/artifacts/endpoint-eventfilterlist-windows-v1/d801aa1fb7ddcc330a5e3173372ea6af4a3d08ec58074478e85aa5603e926658
        encryption_algorithm: none
      endpoint-trustlist-macos-v1:
        encoded_size: 22
        encryption_algorithm: none
        relative_url: /api/fleet/artifacts/endpoint-trustlist-macos-v1/d801aa1fb7ddcc330a5e3173372ea6af4a3d08ec58074478e85aa5603e926658
        decoded_sha256: d801aa1fb7ddcc330a5e3173372ea6af4a3d08ec58074478e85aa5603e926658
        compression_algorithm: zlib
        encoded_sha256: f8e6afa1d5662f5b37f83337af774b5785b5b7f1daee08b7b00c2d6813874cda
        decoded_size: 14
      endpoint-hostisolationexceptionlist-linux-v1:
        compression_algorithm: zlib
        decoded_size: 14
        decoded_sha256: d801aa1fb7ddcc330a5e3173372ea6af4a3d08ec58074478e85aa5603e926658
        relative_url: /api/fleet/artifacts/endpoint-hostisolationexceptionlist-linux-v1/d801aa1fb7ddcc330a5e3173372ea6af4a3d08ec58074478e85aa5603e926658
        encoded_size: 22
        encryption_algorithm: none
        encoded_sha256: f8e6afa1d5662f5b37f83337af774b5785b5b7f1daee08b7b00c2d6813874cda
      endpoint-blocklist-macos-v1:
        encoded_sha256: f8e6afa1d5662f5b37f83337af774b5785b5b7f1daee08b7b00c2d6813874cda
        encoded_size: 22
        decoded_sha256: d801aa1fb7ddcc330a5e3173372ea6af4a3d08ec58074478e85aa5603e926658
        encryption_algorithm: none
        relative_url: /api/fleet/artifacts/endpoint-blocklist-macos-v1/d801aa1fb7ddcc330a5e3173372ea6af4a3d08ec58074478e85aa5603e926658
        compression_algorithm: zlib
        decoded_size: 14
      endpoint-blocklist-windows-v1:
        relative_url: /api/fleet/artifacts/endpoint-blocklist-windows-v1/d801aa1fb7ddcc330a5e3173372ea6af4a3d08ec58074478e85aa5603e926658
        decoded_sha256: d801aa1fb7ddcc330a5e3173372ea6af4a3d08ec58074478e85aa5603e926658
        encoded_sha256: f8e6afa1d5662f5b37f83337af774b5785b5b7f1daee08b7b00c2d6813874cda
        compression_algorithm: zlib
        encryption_algorithm: none
        encoded_size: 22
        decoded_size: 14
      endpoint-trustlist-linux-v1:
        encoded_sha256: f8e6afa1d5662f5b37f83337af774b5785b5b7f1daee08b7b00c2d6813874cda
        decoded_sha256: d801aa1fb7ddcc330a5e3173372ea6af4a3d08ec58074478e85aa5603e926658
        encoded_size: 22
        encryption_algorithm: none
        relative_url: /api/fleet/artifacts/endpoint-trustlist-linux-v1/d801aa1fb7ddcc330a5e3173372ea6af4a3d08ec58074478e85aa5603e926658
        decoded_size: 14
        compression_algorithm: zlib
      endpoint-exceptionlist-windows-v1:
        encoded_sha256: f8e6afa1d5662f5b37f83337af774b5785b5b7f1daee08b7b00c2d6813874cda
        encoded_size: 22
        decoded_sha256: d801aa1fb7ddcc330a5e3173372ea6af4a3d08ec58074478e85aa5603e926658
        encryption_algorithm: none
        relative_url: /api/fleet/artifacts/endpoint-exceptionlist-windows-v1/d801aa1fb7ddcc330a5e3173372ea6af4a3d08ec58074478e85aa5603e926658
        decoded_size: 14
        compression_algorithm: zlib
      endpoint-blocklist-linux-v1:
        encoded_size: 22
        encoded_sha256: f8e6afa1d5662f5b37f83337af774b5785b5b7f1daee08b7b00c2d6813874cda
        compression_algorithm: zlib
        relative_url: /api/fleet/artifacts/endpoint-blocklist-linux-v1/d801aa1fb7ddcc330a5e3173372ea6af4a3d08ec58074478e85aa5603e926658
        decoded_sha256: d801aa1fb7ddcc330a5e3173372ea6af4a3d08ec58074478e85aa5603e926658
        decoded_size: 14
        encryption_algorithm: none
      endpoint-eventfilterlist-macos-v1:
        relative_url: /api/fleet/artifacts/endpoint-eventfilterlist-macos-v1/d801aa1fb7ddcc330a5e3173372ea6af4a3d08ec58074478e85aa5603e926658
        compression_algorithm: zlib
        decoded_sha256: d801aa1fb7ddcc330a5e3173372ea6af4a3d08ec58074478e85aa5603e926658
        decoded_size: 14
        encoded_sha256: f8e6afa1d5662f5b37f83337af774b5785b5b7f1daee08b7b00c2d6813874cda
        encryption_algorithm: none
        encoded_size: 22
      endpoint-exceptionlist-macos-v1:
        decoded_sha256: d801aa1fb7ddcc330a5e3173372ea6af4a3d08ec58074478e85aa5603e926658
        compression_algorithm: zlib
        decoded_size: 14
        relative_url: /api/fleet/artifacts/endpoint-exceptionlist-macos-v1/d801aa1fb7ddcc330a5e3173372ea6af4a3d08ec58074478e85aa5603e926658
        encoded_size: 22
        encoded_sha256: f8e6afa1d5662f5b37f83337af774b5785b5b7f1daee08b7b00c2d6813874cda
        encryption_algorithm: none
      endpoint-hostisolationexceptionlist-macos-v1:
        compression_algorithm: zlib
        encryption_algorithm: none
        decoded_sha256: d801aa1fb7ddcc330a5e3173372ea6af4a3d08ec58074478e85aa5603e926658
        encoded_size: 22
        relative_url: /api/fleet/artifacts/endpoint-hostisolationexceptionlist-macos-v1/d801aa1fb7ddcc330a5e3173372ea6af4a3d08ec58074478e85aa5603e926658
        decoded_size: 14
        encoded_sha256: f8e6afa1d5662f5b37f83337af774b5785b5b7f1daee08b7b00c2d6813874cda
    schema_version: v1
    manifest_version: 1.0.0
  meta:
    package:
      version: 8.5.0
      name: endpoint
  integration_config:
    endpointConfig:
      preset: NGAV
    type: endpoint
  type: endpoint
  data_stream:
    namespace: default
  policy:
    linux:
      memory_protection:
        supported: true
        mode: prevent
      popup:
        malware:
          message: ""
          enabled: true
        behavior_protection:
          enabled: true
          message: ""
        memory_protection:
          message: ""
          enabled: true
      logging:
        file: info
      behavior_protection:
        supported: true
        mode: prevent
      malware:
        blocklist: true
        mode: prevent
      events:
        process: true
        tty_io: false
        network: false
        session_data: false
        file: false
    windows:
      ransomware:
        supported: true
        mode: prevent
      attack_surface_reduction:
        credential_hardening:
          enabled: true
      antivirus_registration:
        enabled: false
      logging:
        file: info
      behavior_protection:
        mode: prevent
        supported: true
      malware:
        mode: prevent
        blocklist: true
      popup:
        behavior_protection:
          message: ""
          enabled: true
        ransomware:
          message: ""
          enabled: true
        memory_protection:
          message: ""
          enabled: true
        malware:
          message: ""
          enabled: true
      memory_protection:
        supported: true
        mode: prevent
      events:
        dns: false
        network: false
        security: false
        file: false
        process: true
        registry: false
        dll_and_driver_load: false
    mac:
      events:
        file: false
        network: false
        process: true
      behavior_protection:
        mode: prevent
        supported: true
      logging:
        file: info
      popup:
        behavior_protection:
          enabled: true
          message: ""
        memory_protection:
          enabled: true
          message: ""
        malware:
          enabled: true
          message: ""
      memory_protection:
        mode: prevent
        supported: true
      malware:
        mode: prevent
        blocklist: true
  revision: 1
```

Further, the Endpoint is streaming data as expected.  Below are a bunch of process events.

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/56395104/203557813-21a9d1d6-08fb-4eea-8c9a-43dd5bbd588e.png">

We can see in the Endpoint policy response that Eventing is properly enabled.

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/56395104/203558291-aed2986c-df97-421a-9a22-d8b408f61675.png">

Also, I checked to see that our UI functionality that makes use of the `revision` still works and it does!  We can still see "Out of Date" when we update policies and display the revision number.

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/56395104/203558209-19e17f72-a3a0-4ae3-aa1d-cc4e61fa3b99.png">

Let me know if you see the same.  Given the above, I think we this ticket is verified.
