### ISSUE TITLE
Unable to connect to fleet-server in the same cluster - certificate signed by unknown authority

### ISSUE THREAD

**Issue by sjoukedv** [elastic/elastic-agent#1797]
<details>
<summary>Agent manifest (excluding RBAC)</summary>

```
apiVersion: agent.k8s.elastic.co/v1alpha1
kind: Agent
metadata: 
  name: elastic-agent
spec:
  version: 8.5.2
  kibanaRef:
    name: kibana
  fleetServerRef: 
    name: fleet-server
  mode: fleet
  daemonSet:
    podTemplate:
      spec:
        serviceAccountName: elastic-agent
        hostNetwork: true
        dnsPolicy: ClusterFirstWithHostNet
        automountServiceAccountToken: true
        securityContext:
          runAsUser: 0
```
</details>

<details>
<summary>Fleet server manifest (excluding RBAC)</summary>

```
apiVersion: agent.k8s.elastic.co/v1alpha1
kind: Agent
metadata:
  name: fleet-server
  namespace: {{ .Release.Namespace }}
spec:
  version: {{ .Values.elastic_version }}
  kibanaRef:
    name: kibana
  elasticsearchRefs:
  - name: elasticsearch
  mode: fleet
  fleetServerEnabled: true
  policyID: eck-fleet-server
  deployment:
    replicas: 1
    podTemplate:
      spec:
        serviceAccountName: fleet-server
        automountServiceAccountToken: true
        securityContext:
          runAsUser: 0  
```
</details>

```
{"log.level":"error","@timestamp":"2022-11-26T15:23:20.592Z","log.origin":{"file.name":"fleet/fleet_gateway.go","file.line":204},"message":"failed to dispatch actions, error: fail to communicate with Fleet Server API client hosts: all hosts failed: 1 error occurred:\n\t* requester 0/1 to host https://<external-ingress-host>:443/ errored: Get \"https://<external-ingress-host>:443/api/status?\": x509: certificate signed by unknown authority\n\n","ecs.version":"1.6.0"}
````

The endpoint is reachable from outside the cluster and from within the pod itself (`kubectl exec -it <agent-pod> -- sh`), with:

```
curl https://<external-ingress-host>:443/api/status
{"name":"fleet-server","status":"HEALTHY"}
```

I can see that the CA are added through volume mounts and the path is available in the environment variables. Passing the certificate also makes the internal endpoint work:

```
# curl https://<fleet-server-svc>.svc:8220/api/status
curl: (60) SSL certificate problem: self signed certificate in certificate chain
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.

curl --cacert <value of FLEET_CA env var> https://<fleet-server-svc>.svc:8220/api/status
{"name":"fleet-server","status":"HEALTHY"}
````
