### ISSUE TITLE
[Windows]: Windows agent goes to Unhealthy state on installation with policy having System integration.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/elastic-agent#1800]
**Kibana version:**  8.6 BC3 kibana cloud environment

**Host OS and Browser version:** Windows, All

**Build details:**
```
VERSION: 8.6.0 BC3 Kibana cloud environment
BUILD: 58560
COMMIT: d4567dc2eaa4f59503c1822e1f10bf0292b97066
Artifact Link: https://staging.elastic.co/8.6.0-94db6bc6/downloads/beats/elastic-agent/elastic-agent-8.6.0-windows-x86_64.zip
```

**Preconditions:**
1. 8.6 BC3 kibana cloud environment should be available.

**Steps to reproduce:**
1. Navigate to Fleet tab.
2. Install agent using Agent policy having only System integration.
3. Observe agent gets Unhealthy after installation under Agents tab.

**elastic-agent.yml:**
[elastic-agent.zip](https://github.com/elastic/elastic-agent/files/10101509/elastic-agent.zip)

**Logs:**
[logs.zip](https://github.com/elastic/elastic-agent/files/10101519/logs.zip)

**Screenshot:**
![6](https://user-images.githubusercontent.com/77374876/204221468-b2a4e094-1abf-4969-95e1-06348b20af2a.JPG)

**Expected Result:**
Windows agent should remain Healthy on installation with policy having System integration.

**Comment by amolnater-qasource** [comment]
@manishgupta-qasource Please review.

**Comment by manishgupta-qasource** [comment]
Secondary review for this ticket is Done

**Comment by cmacknz** [comment]
I can only see one error in the logs where winglogbeat reports as healthy with a failed input: `Error reloading input: 3 errors: Error creating runner from config: No paths were defined for input accessing config;`

```json
{"log.level":"info","@timestamp":"2022-11-25T06:03:59.702Z","log.origin":{"file.name":"coordinator/coordinator.go","file.line":325},"message":"Existing component state changed","component":{"id":"winlog-default","state":"Healthy","message":"Healthy: communicating with pid '6028'","inputs":[{"id":"winlog-default-winlog-system-160a5e1a-bf9c-4fd3-85e1-33cc1c5c03ad","state":"Failed","message":"Error reloading input: 3 errors: Error creating runner from config: No paths were defined for input accessing config; Error creating runner from config: No paths were defined for input accessing config; Error creating runner from config: No paths were defined for input accessing config"}],"output":{"id":"winlog-default","state":"Configuring","message":"reloading output component"}},"ecs.version":"1.6.0"}
```

This is new, we haven't seen this before.

**Comment by cmacknz** [comment]
@andrewkroh since this is winlogbeat, is `Error creating runner from config: No paths were defined for input accessing config;` an error you've seen before?

This is the winglog configuration used, which does seem to be missing `paths` but I'm not sure what winglog input configurations usually look like:

```yaml
  - id: winlog-system-160a5e1a-bf9c-4fd3-85e1-33cc1c5c03ad
    name: system-1
    revision: 1
    type: winlog
    use_output: default
    meta:
      package:
        name: system
        version: 1.20.4
    data_stream:
      namespace: windows
    package_policy_id: 160a5e1a-bf9c-4fd3-85e1-33cc1c5c03ad
    streams:
      - id: winlog-system.application-160a5e1a-bf9c-4fd3-85e1-33cc1c5c03ad
        name: Application
        data_stream:
          dataset: system.application
          type: logs
        condition: '${host.platform} == ''windows'''
        ignore_older: 72h
      - id: winlog-system.security-160a5e1a-bf9c-4fd3-85e1-33cc1c5c03ad
        name: Security
        data_stream:
          dataset: system.security
          type: logs
        condition: '${host.platform} == ''windows'''
        ignore_older: 72h
      - id: winlog-system.system-160a5e1a-bf9c-4fd3-85e1-33cc1c5c03ad
        name: System
        data_stream:
          dataset: system.system
          type: logs
        condition: '${host.platform} == ''windows'''
        ignore_older: 72h
```
