### ISSUE TITLE
Unable to read fleet.ssl options: Invalid TLS validation configuration - endpoint security integration

### ISSUE THREAD

**Issue by narph** [elastic/elastic-agent#184]
Ex configuration:

`elastic-agent.yml`:

```
....
fleet:
  hosts:
    - 'https://fleet.test.com:8220'
```

`fleet.yml`

```
ssl:
certificate_authorities:
- |
-----BEGIN CERTIFICATE-----
...
```

Generated `elastic-endpoint.yaml`

```
....
fleet:
  access_api_key: ....
  agent:
    id: ....
    logging:
      level: info
    monitoring:
      http:
        enabled: false
        host: ""
        port: ...
  enabled: true
  host:
    id: ....
  hosts:
  - https://fleet.test.com:8220
  protocol: http
  reporting:
    check_frequency_sec: 30
    threshold: 10000
  ssl:
    certificate_authorities:
    - .....
    renegotiation: never
    verification_mode: ""
....
```

Following errors are seen in the endpoint logs:

```
{"@timestamp":"2022-02-21T20:49:48.6605404Z","agent":{"id":"...","type":"endpoint"},"ecs":{"version":"1.11.0"},"log":{"level":"error","origin":{"file":{"line":285,"name":"Config.cpp"}}},"message":"Config.cpp:285 Unable to read fleet.ssl options: Invalid TLS validation configuration","process":{"pid":21240,"thread":{"id":7176}}}
{"@timestamp":"2022-02-21T21:09:48.7862266Z","agent":{"id":"...","type":"endpoint"},"ecs":{"version":"1.11.0"},"log":{"level":"info","origin":{"file":{"line":160,"name":"TlsConfig.cpp"}}},"message":"TlsConfig.cpp:160 Unrecognized fleet.ssl.verification_mode: ","process":{"pid":21240,"thread":{"id":7176}}}
```
This is due to the validation in endpoint where empty string verification mode is not recognized https://github.com/elastic/endpoint-dev/blob/4e2c19673e9654dd83e26d32ec8d045f81c931e9/Plugins/Policy/Lib/TlsConfig.cpp#L180-L208

It looks like empty string might be an accepted verification mode option https://github.com/elastic/beats/blob/main/libbeat%2Fcommon%2Ftransport%2Ftlscommon%2Ftypes.go#L133 and it is considered `full`.
