### ISSUE TITLE
Fleet logging level is not being sent to the endpoint in 8.6 BC4

### ISSUE THREAD

**Issue by brian-mckinney** [elastic/elastic-agent#1853]
When installing the Elastic Defend integration via agent, the endpoint is installed, but once configured no longer logs.

I confirmed via local e2e testing that the `logging` field is not being set in the fleet section of the config.  Without that set, endpoint will no longer write to its log file

Fleet section of the endpoint config once applied:
```
fleet:
  hosts:
  - [https://900222ff884e447ea0585fb7f869a7a7.fleet.us-central1.gcp.foundit.no:443](https://900222ff884e447ea0585fb7f869a7a7.fleet.us-central1.gcp.foundit.no/)
  timeout: 10m0s
  access_api_key: V1J5QXlZUUJ0QjVjblVGeVo5YnI6Nm9HMVlHRWRSU2lpTEJiYng0ZUp4UQ==
  ssl:
    verification_mode: full
    renegotiation: never
  enabled: true
  agent:
    id: 0e22f9ef-009d-49d9-ae37-9a35f7db6d23
  host:
    id: 4ae5ff9d-8442-423b-8d2c-839a8564aeb3
  protocol: http
```

@ferullo @cmacknz

**Comment by brian-mckinney** [comment]
relevant discussion: https://github.com/elastic/endpoint-dev/issues/12190#issuecomment-1332300105

**Comment by ferullo** [comment]
I'm going to raise this as a critical blocker. A lack of logging will leave us without a way to diagnose issues in production. It's also affecting our ability to debug issues in testing, so a fix sooner than later would be appreciated.

**Comment by cmacknz** [comment]
This should be quick to fix. We just need to add the key back when we inject the Fleet configuration for endpoint:

https://github.com/elastic/elastic-agent/blob/3a40c5ded8655cf825ba314fd4da49b12fe1fa69/internal/pkg/agent/application/fleet_server_bootstrap.go#L87-L104

**Comment by cmacknz** [comment]
@blakerouse or @aleksmaus can you confirm this is as simple as adding the missing logging key back in the Fleet component modifier we use to provide the Fleet configuration to endpoint and APM?

**Comment by cmacknz** [comment]
Aleks is looking at this

**Comment by aleksmaus** [comment]
@brian-mckinney @ferullo Don't see the ```logging``` anywhere in the fleet section in the raw policy in kibana. 
But there is a ```logging``` under endpoint integration policy. Is it the one that EP suppose to use?
What is the expectation for the fleet configuration ```logging```? Do you have an example? Where this ```logging``` property for ```fleet``` suppose to be taken from?

**Comment by ferullo** [comment]
Endpoint reads the log level from the below structure.

```yaml
fleet:
  agent:
    logging:
      level: info
```
