### ISSUE TITLE
Removal of all conditional streams should remove the entire input

### ISSUE THREAD

**Issue by blakerouse** [elastic/elastic-agent#1868]
When an input has conditions on all of its streams and the conditions result in all streams being removed from the input the entire input should be removed. This is because the input should not be ran anymore because it doesn't have any streams. The should only apply in the cases that an input defines streams with conditions. If an input doesn't define streams then nothing should be done in that case.

Breakdown should be:

1. Does the input have streams defined?
2. Did the evaluation of all conditions on the streams result in no streams?
3. Remove the input if result is no streams

This solves the issue described here https://github.com/elastic/integrations/issues/4725 without having to change the integration. I think it provides a better experience than also having a condition on the input.

The following input would result in it being completely removed when not running on Windows. Without this change winlog will still try to be ran on other OS's.

```
  - id: winlog-system-4e851f19-cee3-42fc-8799-9cce99aad6b1
    name: system-1
    revision: 1
    type: winlog
    use_output: default
    meta:
      package:
        name: system
        version: 1.20.4
    data_stream:
      namespace: default
    package_policy_id: 4e851f19-cee3-42fc-8799-9cce99aad6b1
    streams:
      - id: winlog-system.application-4e851f19-cee3-42fc-8799-9cce99aad6b1
        name: Application
        data_stream:
          dataset: system.application
          type: logs
        condition: '${host.platform} == ''windows'''
        ignore_older: 72h
      - id: winlog-system.security-4e851f19-cee3-42fc-8799-9cce99aad6b1
        name: Security
        data_stream:
          dataset: system.security
          type: logs
        condition: '${host.platform} == ''windows'''
        ignore_older: 72h
      - id: winlog-system.system-4e851f19-cee3-42fc-8799-9cce99aad6b1
        name: System
        data_stream:
          dataset: system.system
          type: logs
        condition: '${host.platform} == ''windows'''
        ignore_older: 72h
```

For confirmed bugs, please report:
- Version: 8.6+
- Operating System: All
