### ISSUE TITLE
[Self-Managed]: Logs for `elastic-agent` datasets are generated for `default` namespace when non-default namespace is used for installed standalone agent under Data Streams tab.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/elastic-agent#1886]
**Kibana version:**  8.6 BC5 kibana self-managed environment

**Host OS and Browser version:** All, All

**Build details:**
```
VERSION: 8.6.0 BC5 Kibana self-managed environment
BUILD: 58693
COMMIT: ed40c16ce9999cc47ad55c11bb097d2e443b31a6
```

**Preconditions:**
1. 8.6 BC5 kibana self-managed environment should be available.

**Steps to reproduce:**
1. Navigate to Agents tab.
2. Create an Agent policy with non-default namespace, say `standalone` and install standalone agent.
3. Observe logs for `elastic-agent` datasets are generated for `default` namespace 

**Logs:**
[elastic-agent-diagnostics-2022-12-05T10-14-36Z-00.zip](https://github.com/elastic/elastic-agent/files/10153107/elastic-agent-diagnostics-2022-12-05T10-14-36Z-00.zip)

**elastic-agent.yml:**
[elastic-agent.zip](https://github.com/elastic/elastic-agent/files/10153116/elastic-agent.zip)

**Expected Result:**
Logs for `elastic-agent` datasets should be generated for `non-default` namespace when `non-default` namespace is used for installed standalone agent under Data Streams tab.

**Screenshot:**

![5](https://user-images.githubusercontent.com/77374876/205612905-a6bce505-d46d-482a-9967-a87ee0fe821b.JPG)
![6](https://user-images.githubusercontent.com/77374876/205612913-0803c688-7b05-40e0-930c-3ec7b5808ad3.JPG)
![7](https://user-images.githubusercontent.com/77374876/205612916-813d9d1c-5c96-4c42-a321-04e4558195fb.JPG)

**Comment by karanbirsingh-qasource** [comment]
Secondary review for this ticket is Done

**Comment by cmacknz** [comment]
Looking at the agent policy I see this is changing the namespace component of the data stream name:

```yaml
agent:
  download:
    source_uri: https://artifacts.elastic.co/downloads/
  monitoring:
    enabled: true
    logs: true
    metrics: true
    namespace: standalone
    use_output: default
host:
  id: fb6c603d-9cfc-454f-903b-7745b8b843f0
id: 66475790-7484-11ed-9d85-e7786183bac7
inputs:
- data_stream:
    namespace: standalone
```

@blakerouse I can't see anything on the agent side that would cause us not to change the data stream of the monitoring beats, but it would be good to confirm.

https://github.com/elastic/elastic-agent/blob/d3496acb1fcd0da7e4f6a837c339c9b5cd174c82/internal/pkg/agent/application/monitoring/v1_monitor.go#L281-L296
