### ISSUE TITLE
Diagnostics should include agent ID

### ISSUE THREAD

**Issue by joshdover** [elastic/elastic-agent#190]
When running `elastic-agent diagnostics collect` the Agent's ID should be included somewhere in the report. This is helpful for SDHs to help users with identifying data coming from this given Agent. However, today (I'm using Agent 8.1.0) the `config/elastic-agent-local.yaml` file has an empty string for the agent.id field, for example:

```yaml
fleet:
  enabled: true
  access_api_key: XXXXX
  protocol: http
  host: XXXXX
  hosts:
  - XXXXX
  ssl:
    verification_mode: full
    renegotiation: never
  timeout: 10m0s
  reporting:
    threshold: 10000
    check_frequency_sec: 30
  agent:
    id: "" # this is empty!
```
