### ISSUE TITLE
[Synthetics] Browser integration does not support segmented data sets

### ISSUE THREAD

**Issue by emilioalvap** [elastic/elastic-agent#1931]
### Summary

`synthetics/browser` integrations support segmented data streams with different retention policies through heartbeat. These are by default:
- `browser`
- `browser.network`
- `browser.screenshot`

Heartbeat [dynamically](https://github.com/elastic/beats/blob/01f9d43c96bdbcb46ed4f1d6e75363906a34112b/x-pack/heartbeat/monitors/browser/synthexec/enrich.go#LL150C26-L150C26) assigns data streams depending on the event that is generated while running the integration. This is how it's reflected in the integration structure:

```yaml
streams:
    - id: ab70b5e3-4932-41c1-855f-7df4ce33f143
      data_stream:
        dataset: browser
        type: synthetics
      ...
    - id: >-
        synthetics/browser-browser.network-ab70b5e3-4932-41c1-855f-7df4ce33f143-0973e900-7a35-11ed-9acb-b3da42cd0b97-default
      data_stream:
        dataset: browser.network
        type: synthetics
      ...
    - id: >-
        synthetics/browser-browser.screenshot-ab70b5e3-4932-41c1-855f-7df4ce33f143-0973e900-7a35-11ed-9acb-b3da42cd0b97-default
      data_stream:
        dataset: browser.screenshot
        type: synthetics
```

After V2 changes, segmentation streams are being ignored and all events are being written to `synthetics-browser-default`. These data stream configs are being surfaced to heartbeat as valid monitor configs, which they aren't:

```bash
{"log.level":"error","@timestamp":"2022-12-12T18:10:17.428Z","message":"Error creating runner from config: could not parse
 cfg for datastream error unpacking monitor plugin config: string value is not set accessing 'type'","component":
{"binary":"heartbeat","dataset":"elastic_agent.heartbeat","id":"synthetics/browser-
default","type":"synthetics/browser"},"ecs.version":"1.6.0","log.logger":"centralmgmt","log.origin":
{"file.line":109,"file.name":"cfgfile/list.go"},"service.name":"heartbeat","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2022-12-12T18:10:17.428Z","message":"Error creating runner from config: could not parse
 cfg for datastream error unpacking monitor plugin config: string value is not set accessing 'type'","component":
{"binary":"heartbeat","dataset":"elastic_agent.heartbeat","id":"synthetics/browser-
default","type":"synthetics/browser"},"service.name":"heartbeat","ecs.version":"1.6.0","log.logger":"centralmgmt","log.origin":
{"file.line":109,"file.name":"cfgfile/list.go"},"ecs.version":"1.6.0"}
```

- [elastic-agent-diagnostics-2022-12-12T17-37-18Z-00.zip](https://github.com/elastic/elastic-agent/files/10211091/elastic-agent-diagnostics-2022-12-12T17-37-18Z-00.zip)
- [elastic-agent_policy.txt](https://github.com/elastic/elastic-agent/files/10211116/elastic-agent_policy.txt)

**Comment by emilioalvap** [comment]
cc @andrewvc @cmacknz @fearful-symmetry

**Comment by cmacknz** [comment]
Editing out a few fields we don't care about in the agent policy, I can see this being configured in the agent policy (from the pre-config.yaml file in the agent diagnostics):

```yaml
inputs:
    - data_stream:
        namespace: default
      id: synthetics/browser-synthetics-ab70b5e3-4932-41c1-855f-7df4ce33f143-0973e900-7a35-11ed-9acb-b3da42cd0b97-default
      meta:
        package:
          name: synthetics
          version: 0.11.4
      streams:
        data_stream:
          dataset: browser
          type: synthetics
        id: ab70b5e3-4932-41c1-855f-7df4ce33f143
        type: browser
      - data_stream:
          dataset: browser.network
          elasticsearch:
            privileges:
              indices:
              - auto_configure
              - create_doc
              - read
          type: synthetics
```

This is setting up a stream with type `browser` which should target a data stream named `synthetics-browser.network-default`.

We can look at the beat configuration generated from this agent policy snippet by inspecting the `components/synthetics-browser-default/synthetics-browser-synthetics-ab70b5e3-4932-41c1-855f-7df4ce33f143-0973e900-7a35-11ed-9acb-b3da42cd0b97-default/beat-rendered-config` YAML file in the diagnostics output:

For `browser.network` I see us generating the following Beat configuration:

```yaml
- data_stream:
    dataset: browser.network
    elasticsearch:
      privileges:
        indices:
        - auto_configure
        - create_doc
        - read
    type: synthetics
  id: synthetics/browser-browser.network-ab70b5e3-4932-41c1-855f-7df4ce33f143-0973e900-7a35-11ed-9acb-b3da42cd0b97-default
  index: synthetics-browser.network-default
  processors:
  - add_fields:
      fields:
        id: 96a6dddd-8895-4412-8d13-61d11fc48f5a
        snapshot: true
        version: 8.7.0
      target: elastic_agent
  - add_fields:
      fields:
        id: 96a6dddd-8895-4412-8d13-61d11fc48f5a
      target: agent
  - add_fields:
      fields:
        input_id: synthetics/browser-synthetics-ab70b5e3-4932-41c1-855f-7df4ce33f143-0973e900-7a35-11ed-9acb-b3da42cd0b97-default
      target: '@metadata'
  - add_fields:
      fields:
        dataset: browser.network
        namespace: default
        type: synthetics
      target: data_stream
  - add_fields:
      fields:
        dataset: browser.network
      target: event
  - add_fields:
      fields:
        stream_id: synthetics/browser-browser.network-ab70b5e3-4932-41c1-855f-7df4ce33f143-0973e900-7a35-11ed-9acb-b3da42cd0b97-default
      target: '@metadata'
  - add_observer_metadata:
      geo:
        name: Fleet managed
  - add_fields:
      fields:
        monitor:
          fleet_managed: true
      target: ""
- data_stream:
    dataset: browser.screenshot
    elasticsearch:
      privileges:
        indices:
        - auto_configure
        - create_doc
        - read
    type: synthetics
```

Nothing in there looks explicitly wrong to me, I see the index configured as `index: synthetics-browser.network-default` for example and the processor with `target: data_stream` uses the right data stream name. 

@emilioalvap looking at the configuration above, is this what Heartbeat is expecting to receive from the agent? Are we including or missing something that Heartbeat expects?

**Comment by emilioalvap** [comment]
@cmacknz I think this could be related to a bit of unnesting we do here: https://github.com/elastic/beats/blob/main/heartbeat/monitors/stdfields/unnest.go.

It could be that the data heartbeat expects has changed, I should be able to confirm tomorrow when I can test it.

**Comment by fearful-symmetry** [comment]
so, about the `string value is not set accessing 'type'` error, I was going over some of the fields that @emilioalvap sent me, and I noticed that some streams have a type field, while others don't example, from the `browser` input (redacted so it's not a hundred lines long):
```
  - id: >-
      synthetics/browser-synthetics-f3973f74-1b2c-49e4-bee3-58ad73a7fd9f-f64239e0-7232-11ed-bbbc-5d005fd86b91-default
...
    streams:
      - id: f3973f74-1b2c-49e4-bee3-58ad73a7fd9f
        name: test1
        type: browser # we have a type here
        enabled: true
      - id: >-
          synthetics/browser-browser.network-f3973f74-1b2c-49e4-bee3-58ad73a7fd9f-f64239e0-7232-11ed-bbbc-5d005fd86b91-default
        data_stream:
          dataset: browser.network
          type: synthetics
        processors:
          - add_observer_metadata:
              geo:
                name: Fleet managed
          - add_fields:
              target: ''
              fields:
                monitor.fleet_managed: true
      - id: >- # no type here
          synthetics/browser-browser.screenshot-f3973f74-1b2c-49e4-bee3-58ad73a7fd9f-f64239e0-7232-11ed-bbbc-5d005fd86b91-default
        data_stream:
          dataset: browser.screenshot
          type: synthetics

```

This would lead to that type error we're seeing in heartbeat. The question is if this is a new error in integrations, or if there's some old logic from V1 that hasn't been reproduced in V2. 

One thing that I noticed is that the streams that are missing the `type` are also missing the `enabled: true` field. I wonder if there was some old logic buried in the agent or the AST that would skip over heartbeat streams that weren't explicitly enabled?

**Comment by fearful-symmetry** [comment]
Can this just be an issue with the integrations? Looking at the data @emilioalvap sent me, the two streams that are missing the `type` field are `browser.network` and `browser.screenshot`. Neither of those have a `type` or `enabled` field in the handlebars files:

```
$cat agent/stream/browser.screenshot.yml.hbs
processors:
  - add_observer_metadata:
      geo:
        name: Fleet managed
  - add_fields:
      target: ''
      fields:
        monitor.fleet_managed: true
```

**Comment by emilioalvap** [comment]
@cmacknz @fearful-symmetry Looking for a sanity check while I continue to find the problem. In the original policy, there should only be _one_ input with three data streams:

```yaml
inputs:
- data_stream:
    namespace: default
  id: synthetics/browser-synthetics-ab70b5e3-4932-41c1-855f-7df4ce33f143-0973e900-7a35-11ed-9acb-b3da42cd0b97-default
  ...
  streams:
  - __ui:
      ...
    data_stream:
      ...
  - data_stream:
      ...
  - data_stream:
      ...
  type: synthetics/browser
```

But from the logs and the analytincs, it seems heartbeat in being invoked as if there were three inputs, instead of one. From `beat-rendere-config.yml:`
```yaml
inputs:
- __ui:
    ...
  type: browser
- data_stream:
    ...
- data_stream:
    ...
```

Is this expected?
