### ISSUE TITLE
Fields added by processors in filestream input are not populated into Elasticsearch

### ISSUE THREAD

**Issue by MichaelKatsoulis** [elastic/elastic-agent#1943]
Agent diagnostic file:
[elastic-agent-diagnostics-2022-12-14T10-29-31Z-00.zip](https://github.com/elastic/elastic-agent/files/10227674/elastic-agent-diagnostics-2022-12-14T10-29-31Z-00.zip)

Checking the `computed_config.yaml` and I can see the processors being added but they are at the higher level of input. Example:

```
- data_stream:
    namespace: default
  id: filestream-container-logs-e36ece52-2118-4351-bd1c-878476fb78ce-kubernetes-54075aa3-aa9b-46f0-8fe9-d0cc4317b012.kindnet-cni
  meta:
    package:
      name: kubernetes
      version: 1.29.2
  name: kubernetes-1
  original_id: filestream-container-logs-e36ece52-2118-4351-bd1c-878476fb78ce
  package_policy_id: e36ece52-2118-4351-bd1c-878476fb78ce
  policy:
    revision: 4
  processors:
  - add_fields:
      fields:
        id: c699fc238f42bc2453bcc9c2f6638f7b3d73b80a23cc7f6d17c0e6faad84709b
        image:
          name: docker.io/kindest/kindnetd:v20210326-1e038dc5
        runtime: containerd
      target: container
  - add_fields:
      fields:
        cluster:
          name: kind
          url: kind-control-plane:6443
      target: orchestrator
  - add_fields:
      fields:
        container:
          name: kindnet-cni
        daemonset:
          name: kindnet
        labels:
          app: kindnet
          controller-revision-hash: 5b547684d9
          k8s-app: kindnet
          pod-template-generation: "1"
          tier: node
        namespace: kube-system
        namespace_labels:
          kubernetes_io/metadata_name: kube-system
        namespace_uid: 441aaf27-f736-4860-b07e-896c63e61fd4
        node:
          hostname: kind-worker2
          labels:
            beta_kubernetes_io/arch: amd64
            beta_kubernetes_io/os: linux
            kubernetes_io/arch: amd64
            kubernetes_io/hostname: kind-worker2
            kubernetes_io/os: linux
          name: kind-worker2
          uid: 43854694-93ab-422e-8f30-0e20fb2e7b85
        pod:
          ip: 172.18.0.3
          name: kindnet-8b884
          uid: 54075aa3-aa9b-46f0-8fe9-d0cc4317b012
      target: kubernetes
  revision: 2
  streams:
  - data_stream:
      dataset: kubernetes.container_logs
      type: logs
    id: kubernetes-container-logs-kindnet-8b884-c699fc238f42bc2453bcc9c2f6638f7b3d73b80a23cc7f6d17c0e6faad84709b
    parsers:
    - container:
        format: auto
        stream: all
    paths:
    - /var/log/containers/*c699fc238f42bc2453bcc9c2f6638f7b3d73b80a23cc7f6d17c0e6faad84709b.log
    prospector.scanner.symlinks: true
  type: filestream
```

But the fields added by the processors are not populated into elasticsearch. Maybe the higher lever processors are not respected in the lower level streams? 

_Originally posted by @MichaelKatsoulis in https://github.com/elastic/elastic-agent/issues/1894#issuecomment-1351169638_

**Comment by cmacknz** [comment]
This is the Beat config that is generated in this case, which is indeed omitting the processors:

From `elastic-agent-diagnostics-2022-12-14T10-29-31Z-00/components/filestream-92408750-7b86-11ed-8e60-1ff6d9b1b365/filestream-container-logs-e36ece52-2118-4351-bd1c-878476fb78ce-kubernetes-2db5857a-300a-4f41-a60f-17af959fb3ad.kube-proxy/beat-rendered-config`:
```yaml
inputs:
- data_stream:
    dataset: kubernetes.container_logs
    type: logs
  id: kubernetes-container-logs-redis-66f42c91781f0ea927820167b139618d2a005e61d4806602b5b1ce25e5e8d6dc
  index: logs-kubernetes.container_logs-default
  parsers:
  - container:
      format: auto
      stream: all
  paths:
  - /var/log/containers/*66f42c91781f0ea927820167b139618d2a005e61d4806602b5b1ce25e5e8d6dc.log
  processors:
  - add_fields:
      fields:
        id: a89f21aa-26f4-4262-bcf2-26505ba8e43e
        snapshot: true
        version: 8.6.0
      target: elastic_agent
  - add_fields:
      fields:
        id: a89f21aa-26f4-4262-bcf2-26505ba8e43e
      target: agent
  - add_fields:
      fields:
        input_id: filestream-container-logs-e36ece52-2118-4351-bd1c-878476fb78ce-kubernetes-eb7b4809-5281-4f4c-92ea-bb621a3ba11d.redis
      target: '@metadata'
  - add_fields:
      fields:
        dataset: kubernetes.container_logs
        namespace: default
        type: logs
      target: data_stream
  - add_fields:
      fields:
        dataset: kubernetes.container_logs
      target: event
  - add_fields:
      fields:
        stream_id: kubernetes-container-logs-redis-66f42c91781f0ea927820167b139618d2a005e61d4806602b5b1ce25e5e8d6dc
      target: '@metadata'
  prospector:
    scanner:
      symlinks: true
  type: filestream
outputs:
  elasticsearch:
    api_key: <redacted>
    bulk_max_size: 50
    hosts:
    - https://elasticsearch:9200
    monitoring:
      cluster_uuid: <redacted>
    ssl:
      verification_mode: none
    type: elasticsearch
```
