### ISSUE TITLE
Error Starting Elastic Agent with Autodiscover Templates

### ISSUE THREAD

**Issue by drenze-athene** [elastic/elastic-agent#2029]
When loading Elastic Agent autodiscovery templates with an `initContainer` per the instructions in [the documentation][docs], I receive the following error in the Elastic Agent logs:

```json
{"log.level":"error","@timestamp":"2022-12-29T18:34:51.018Z","log.origin":{"file.name":"status/reporter.go","file.line":326},"message":"Elastic Agent status changed to \"error\": \"app heartbeat--8.5.3-69602ec6: 1 error occurred:\\n\\t* 4 errors: Error creating runner from config: could not parse cfg for datastream error unpacking monitor plugin config: missing required field accessing 'schedule'; Error creating runner from config: could not parse cfg for datastream error unpacking monitor plugin config: missing required field accessing 'schedule'; Error creating runner from config: could not parse cfg for datastream error unpacking monitor plugin config: missing required field accessing 'schedule'; Error creating runner from config: could not parse cfg for datastream error unpacking monitor plugin config: missing required field accessing 'schedule'\\n\\n\"","ecs.version":"1.6.0"}
```

Additionally, no autodiscovery inputs appear to function while this error is present; no logs or metrics are ingested for any enabled autodiscovery containers (none of my enabled autodiscovery inputs would ingest until I resolved this issue).

This issue appears to be tied to the `synthetics.yml` package. Adding the following to the init container commands as a workaround removes this error and allows all autodiscovery inputs to function as expected:

```bash
# Disable anything which contains a reference to synthetics
cd ${ELASTIC_AGENT_INPUTS_D}
for f in $(grep synthetics *.yml | sed 's|:.*||g' | sort | uniq); do
  mv ${f} ${f}.disabled
done
```

# Additional Information

## Version

This issue was observed using Elastic Agent 8.5.3 deployed to a Kubernetes cluster with the container image from Elastic and managed by the Elastic Operator.

## Steps to Reproduce

1. Install templates into the pod using the instructions in [the documentation][docs].
2. Set the following in the Elastic Agent configuration:
    ```yaml
    providers:
      kubernetes:
        hints.enabled: true
    ```
3. Deploy

[docs]: https://www.elastic.co/guide/en/fleet/current/elastic-agent-kubernetes-autodiscovery.html

**Comment by cmacknz** [comment]
@andrewvc the error error looks like it is coming from Heartbeat, can someone from your team take a look at this?

`heartbeat--8.5.3-69602ec6: 1 error occurred:\\n\\t* 4 errors: Error creating runner from config: could not parse cfg for datastream error unpacking monitor plugin config: missing required field accessing 'schedule'`

**Comment by VenturiEffect02** [comment]
Hello, this happened to me as well with agents 8.5.3 but I do not have auto discovery enabled.
here's an excerpt of my agent synthetics tcp configuration

```yaml
      - id: minio
        name: minio
        type: synthetics/tcp
        use_output: default
        data_stream:
          namespace: staging
        streams:
          - id: minio
            name: minio
            type: tcp
            enabled: true
            data_stream:
              dataset: tcp
              type: synthetics
            __ui:
              is_tls_enabled: false
              is_zip_url_tls_enabled: false
            # origin: ui
            run_from.id: staging
            run_from.geo.name: staging
            hosts: "minio.default:9000"
            schedule: "0-59/5 7-18 * * 1-5"
            timeout: 16s
            proxy_use_local_resolver: false
            tags: ["sev3"]
            condition: '${kubernetes_leaderelection.leader} == true'
```
