### ISSUE TITLE
Failing to index some logs from Elastic-Agent when using a different monitoring cluster

### ISSUE THREAD

**Issue by belimawr** [elastic/elastic-agent#2131]
Whenever the Elastic-Agent is run with a monitoring clustuster different from the cluster the data is sent to, some events from Metricbeat logs are dropped due to mapping issues

For confirmed bugs, please report:
- Version: `main` 
- Operating System: Linux (confirmed on Arch Linux and Ubuntu 20.04)

## Steps to Reproduce
1. Get two different Elastic-Cloud clusters (or any other clusters)

2. Deploy a stand alone Elastic-Agent sending data to one cluster and the monitoring data to the other, with a policy like that:
<details><summary>elastic-agent.yml</summary>

```yaml
id: standalone-policy-hand-crafted
outputs:
  default:
    type: elasticsearch
    password: bar
    username: elastic
    allow_older_versions: true
    hosts:
      - >-
        https://data-cluster.elastic-cloud.com:443
  monitoring-output:
    type: elasticsearch
    password: foo
    username: elastic
    allow_older_versions: true
    hosts:
      - 'https://monitoring-cluster.elastic-cloud.com:443'
agent:
  download:
    sourceURI: 'https://artifacts.elastic.co/downloads/'
  monitoring:
    enabled: true
    use_output: monitoring-output
    namespace: default
    logs: true
    metrics: true
inputs:
  - id: log-input-like-the-integration-input-id
    name: log-input
    type: logfile
    use_output: default
    data_stream:
      namespace: default
    streams:
      - id: log-input-like-the-integration-stream-id
        data_stream:
          dataset: generic
        paths:
          - /tmp/flog*

```

</details>

3. Start the Elastic-Agent in standalone mode
```
./elastic-agent -c elastic-agent.yml
```

4. Wait for a while and you will see logs like those:

<details><summary>Events dropped logs</summary>
I have anonymised  all IP/Mac addresses.

```
{"log.level":"warn","@timestamp":"2023-01-17T20:12:12.533Z","message":"Cannot index event publisher.Event{Content:beat.Event{Timestamp:time.Date(2023, time.January, 17, 20, 12, 9, 149000000, time.UTC), Meta:{\"input_id\":\"filestream-monitoring-agent\",\"raw_index\":\"logs-elastic_agent.metricbeat-default\",\"stream_id\":\"filestream-monitoring-agent\"}, Fields:{\"agent\":{\"ephemeral_id\":\"b12ea210-5273-46f0-a95e-6f1d64380813\",\"id\":\"c129f4df-ec30-4f10-b460-c25c35a63c4f\",\"name\":\"archlinux\",\"type\":\"filebeat\",\"version\":\"8.7.0\"},\"component\":{\"binary\":\"metricbeat\",\"dataset\":\"elastic_agent.metricbeat\",\"id\":\"beat/metrics-monitoring\",\"type\":\"beat/metrics\"},\"container\":{\"id\":\"elastic-agent-13136c\"},\"data_stream\":{\"dataset\":\"elastic_agent.metricbeat\",\"namespace\":\"default\",\"type\":\"logs\"},\"ecs\":{\"version\":\"8.0.0\"},\"elastic_agent\":{\"id\":\"c129f4df-ec30-4f10-b460-c25c35a63c4f\",\"snapshot\":true,\"version\":\"8.7.0\"},\"event\":{\"dataset\":\"elastic_agent.metricbeat\"},\"host\":{\"architecture\":\"x86_64\",\"containerized\":false,\"hostname\":\"archlinux\",\"id\":\"21282bcb80a74c08a0d14a047372256c\",\"ip\":[\"10.0.1.2\",\"aaaa::aaa:ffff:bbbb:cccc\",\"172.17.0.1\"],\"mac\":[\"BA-BA-BA-BA-BA-BA\",\"AA-AA-BB-BB-BB-BB\"],\"name\":\"archlinux\",\"os\":{\"build\":\"rolling\",\"family\":\"\",\"kernel\":\"6.1.5-arch2-1\",\"name\":\"Arch Linux\",\"platform\":\"arch\",\"type\":\"linux\",\"version\":\"\"}},\"input\":{\"type\":\"filestream\"},\"log\":{\"file\":{\"path\":\"/home/vagrant/elastic-agent-8.7.0-SNAPSHOT-linux-x86_64/data/elastic-agent-13136c/logs/elastic-agent-20230117.ndjson\"},\"offset\":38537},\"log.level\":\"info\",\"log.logger\":\"beat\",\"log.origin\":{\"file.line\":1111,\"file.name\":\"instance/beat.go\"},\"message\":\"Host info\",\"service.name\":\"metricbeat\",\"system_info\":{\"ecs.version\":\"1.6.0\",\"host\":{\"architecture\":\"x86_64\",\"boot_time\":\"2023-01-17T18:35:01Z\",\"containerized\":false,\"id\":\"21282bcb80a74c08a0d14a047372256c\",\"ip\":[\"127.0.0.1/8\",\"::1/128\",\"10.0.2.15/24\",\"ffff::ccc:aaaa:baba:abab/64\",\"172.17.0.1/16\"],\"kernel_version\":\"6.1.5-arch2-1\",\"mac\":[\"BB:BB:BB:CC:CC:CC\",\"AA:BB:CC:DD:EE:FF\"],\"name\":\"archlinux\",\"os\":{\"build\":\"rolling\",\"family\":\"\",\"major\":0,\"minor\":0,\"name\":\"Arch Linux\",\"patch\":0,\"platform\":\"arch\",\"type\":\"linux\",\"version\":\"\"},\"timezone\":\"UTC\",\"timezone_offset_sec\":0}}}, Private:(*input_logfile.updateOp)(0xc000f09cb0), TimeSeries:false}, Flags:0x1, Cache:publisher.EventCache{m:mapstr.M(nil)}} (status=400): {\"type\":\"mapper_parsing_exception\",\"reason\":\"failed to parse field [system_info.host.ip] of type [ip] in document with id 'hARcwYUBOhEXiMJ_VjvY'. Preview of field's value: '127.0.0.1/8'\",\"caused_by\":{\"type\":\"illegal_argument_exception\",\"reason\":\"'127.0.0.1/8' is not an IP string literal.\"}}, dropping event!","component":{"binary":"filebeat","dataset":"elastic_agent.filebeat","id":"filestream-monitoring","type":"filestream"},"ecs.version":"1.6.0","log.logger":"elasticsearch","log.origin":{"file.line":429,"file.name":"elasticsearch/client.go"},"service.name":"filebeat","ecs.version":"1.6.0"}
```

</details>

## Other details

Pretty printing the `fields` field from the rejected event we have:
<details><summary>Event</summary>
I have anonymised  all IP/Mac addresses.

```json
{
  "agent": {
    "ephemeral_id": "b12ea210-5273-46f0-a95e-6f1d64380813",
    "id": "c129f4df-ec30-4f10-b460-c25c35a63c4f",
    "name": "archlinux",
    "type": "filebeat",
    "version": "8.7.0"
  },
  "component": {
    "binary": "metricbeat",
    "dataset": "elastic_agent.metricbeat",
    "id": "beat/metrics-monitoring",
    "type": "beat/metrics"
  },
  "container": {
    "id": "elastic-agent-13136c"
  },
  "data_stream": {
    "dataset": "elastic_agent.metricbeat",
    "namespace": "default",
    "type": "logs"
  },
  "ecs": {
    "version": "8.0.0"
  },
  "elastic_agent": {
    "id": "c129f4df-ec30-4f10-b460-c25c35a63c4f",
    "snapshot": true,
    "version": "8.7.0"
  },
  "event": {
    "dataset": "elastic_agent.metricbeat"
  },
  "host": {
    "architecture": "x86_64",
    "containerized": false,
    "hostname": "archlinux",
    "id": "21282bcb80a74c08a0d14a047372256c",
    "ip": [
      "10.0.1.2",
      "aaaa::aaa:ffff:bbbb:cccc",
      "172.17.0.1"
    ],
    "mac": [
      "BA-BA-BA-BA-BA-BA",
      "AA-AA-BB-BB-BB-BB"
    ],
    "name": "archlinux",
    "os": {
      "build": "rolling",
      "family": "",
      "kernel": "6.1.5-arch2-1",
      "name": "Arch Linux",
      "platform": "arch",
      "type": "linux",
      "version": ""
    }
  },
  "input": {
    "type": "filestream"
  },
  "log": {
    "file": {
      "path": "/home/vagrant/elastic-agent-8.7.0-SNAPSHOT-linux-x86_64/data/elastic-agent-13136c/logs/elastic-agent-20230117.ndjson"
    },
    "offset": 38537
  },
  "log.level": "info",
  "log.logger": "beat",
  "log.origin": {
    "file.line": 1111,
    "file.name": "instance/beat.go"
  },
  "message": "Host info",
  "service.name": "metricbeat",
  "system_info": {
    "ecs.version": "1.6.0",
    "host": {
      "architecture": "x86_64",
      "boot_time": "2023-01-17T18:35:01Z",
      "containerized": false,
      "id": "21282bcb80a74c08a0d14a047372256c",
      "ip": [
        "127.0.0.1/8",
        "::1/128",
        "10.0.2.15/24",
        "ffff::ccc:aaaa:baba:abab/64",
        "172.17.0.1/16"
      ],
      "kernel_version": "6.1.5-arch2-1",
      "mac": [
        "BB:BB:BB:CC:CC:CC",
        "AA:BB:CC:DD:EE:FF"
      ],
      "name": "archlinux",
      "os": {
        "build": "rolling",
        "family": "",
        "major": 0,
        "minor": 0,
        "name": "Arch Linux",
        "patch": 0,
        "platform": "arch",
        "type": "linux",
        "version": ""
      },
      "timezone": "UTC",
      "timezone_offset_sec": 0
    }
  }
}


```

</details>

The problem is with the `system_info.host.ip` field that contains an array of IPs + their subnet mask:
<details><summary>system_info.host.ip</summary>
I have anonymised  all IP/Mac addresses.

```json
  "system_info": {
    "host": {
      "ip": [
        "127.0.0.1/8",
        "::1/128",
        "10.0.2.15/24",
        "ffff::ccc:aaaa:baba:abab/64",
        "172.17.0.1/16"
      ]
    }
  }
```

</details>

**Comment by alexsapran** [comment]
I saw the same even if I had set in the config to ship the logs into the same output cluster. 

```yaml
monitoring:
    enabled: true
    use_output: default
    namespace: default
    logs: true
    metrics: true
```
I constantly got the `Cannot index event publisher.Event`
