### ISSUE TITLE
Enum values in diagnostics YAML files should be rendered as strings

### ISSUE THREAD

**Issue by cmacknz** [elastic/elastic-agent#2137]
This affects the state.yaml file the most, but this should apply to any enumeration value written as part of the new diagnostics format in 8.6.0.

For example, in the state.yaml file in 8.6.0 all of the enumeration values that are defined for the control protocol in [elastic-agent-client.proto](https://github.com/elastic/elastic-agent-client/blob/4477e3ace394ef1abfec55afa5cc5e1f6f87980c/elastic-agent-client.proto#L165-L201) are written in their numeric representation:

```yaml
  state:
    state: 2
    message: 'Healthy: communicating with pid ''48399'''
    units:
      ? unittype: 1
        unitid: log-default
      : state: 2
        message: Healthy
      ? unittype: 0
        unitid: log-default-logfile-system-1cc3ec08-0192-43c8-b6c9-3e1cdd8a38ba
      : state: 2
        message: Healthy
```

This adds a significant mental burden to quickly analyzing diagnostics, as you must either memorize or cross-reference the meaning of the numbers. Instead we should render the enum values as strings to make analysis much easier:

```yaml
  state:
    state: HEALTHY
    message: 'Healthy: communicating with pid ''48399'''
    units:
      ? unittype: OUTPUT
        unitid: log-default
      : state: HEALTHY
        message: Healthy
      ? unittype: INPUT
        unitid: log-default-logfile-system-1cc3ec08-0192-43c8-b6c9-3e1cdd8a38ba
      : state: HEALTHY
        message: Healthy
```
