### ISSUE TITLE
Split up the contents of the state.yaml file in diagnostics to make it faster to analyze

### ISSUE THREAD

**Issue by cmacknz** [elastic/elastic-agent#2139]
The new state.yaml file puts the entire state of the running components and units in a single file. It includes the overall state of the agent, and then for each the component it lists the id, input spec, unit list, and the component's state. Having all of this in one place seems convenient, but the volume of information actually makes it harder to analyze the source of problems. I have seen `state.yaml` files that are 8000+ lines long.

After several rounds of root cause analysis I've found the `state` information in `state.yaml` is the most valuable, and being able to quickly scan and see the current state of each component would improve the ergonomics of diagnostics analysis considerably.

I propose we do the following:

1. Rename `components.yaml` to `components_expected.yaml` or similar since it contains the expected configuration for each component.
2. Create a `components_actual.yaml` that contains the actual running component configuration for each component. This would be the current contents of `state.yaml` with the `state` information  stripped out.
3. Leave `state.yaml` with its current name but have it only contain the component ID and the state information for the components and units. An example would be:

```yaml
state: 3
message: 1 or more components/units in a degraded state
components:
- component:
    id: log-default
  state:
    state: 2
    message: 'Healthy: communicating with pid ''48399'''
    units:
      ? unittype: 1
        unitid: log-default
      : state: 2
        message: Healthy
      ? unittype: 0
        unitid: log-default-logfile-system-1cc3ec08-0192-43c8-b6c9-3e1cdd8a38ba
      : state: 2
        message: Healthy
    version_info:
      name: beat-v2-client
      version: 8.6.0
      meta:
        build_time: 2023-01-04 01:28:11 +0000 UTC
        commit: 561a3e1839f1a50ce832e8e114de399b2bee2542
- component:
    id: winlog-default
  state:
    state: 2
    message: 'Healthy: communicating with pid ''5984'''
    units:
      ? unittype: 0
        unitid: winlog-default-winlog-system-b856919c-ade6-4a47-9e0c-28d4822b7ada
      : state: 4
        message: '[output unit has no config]'
      ? unittype: 1
        unitid: winlog-default
      : state: 4
        message: '[output unit has no config]'
    version_info:
      name: beat-v2-client
      version: 8.6.0
      meta:
        build_time: 2023-01-04 01:28:12 +0000 UTC
        commit: 561a3e1839f1a50ce832e8e114de399b2bee2542
```

Splitting the state into a separate file would additionally solve the most challenging part of https://github.com/elastic/elastic-agent/issues/1907 by moving the composite keys many YAML parsers struggle to parse into a file that does not need redaction.
