### ISSUE TITLE
Report FQDN on `host.name` enabled by a feature flag

### ISSUE THREAD

**Issue by AndersonQ** [elastic/elastic-agent#2185]
**Describe the enhancement:**

Following up on https://github.com/elastic/beats/issues/1070, and https://github.com/elastic/ecs/pull/2122 the Elastic Agent should be able to report the FQDN on `host.name`. This should be configurable by a feature flag on the agent policy.

**Describe a specific use case for the enhancement or feature:**
There are cases in which different hosts share the same hostname but have different domains. Currently they have the same `host.name` values, which isn't ideal. Allowing to populate `host.name` with the FQDN solves that problem. ALso having it behind a feature flag won't make it a breaking change as the user will have the option to enable it or not.

## Implementation details

Feature flag generic config:
```
agent:
  features:
    feature_1:
      enabled:
      config1:
      config2:
      ...
      configN:
    feature_2:
      enabled:
      config1:
      config2:
      ...
      configN:
    ...
    feature_N:
      enabled:
      config1:
      config2:
      ...
      configN:
```

Feature flag for FQDN:
```
agent.features.fqdn.enabled: true|false
```

Related Issues:
 - Blocked by: https://github.com/elastic/go-sysinfo/pull/144
