### ISSUE TITLE
Inspect command not working as expected with `--variables-wait` flag

### ISSUE THREAD

**Issue by ChrsMark** [elastic/elastic-agent#2206]
Given the following configuration:

```yml
providers.kubernetes:
  enabled: true
  kube_config: /home/chrismark/.kube/config

inputs:
  - id: logfile-logs-ddeb4552-cde0-4fdb-a2f8-a60cb1a28bc5
    name: peripheral-awt-mail-mail.log
    revision: 12
    type: logfile
    use_output: default
    meta:
      package:
        name: log
        version: 1.0.0
    data_stream:
      namespace: logging
    streams:
      - id: logfile-log.b1a28bc5
        condition: ${kubernetes.labels.app} == 'redis'
        data_stream:
          dataset: peripheral.awtmail.mail.log
        paths:
          - /var/log/awtech/awt-mail/mail/path.log
```

running `./elastic-agent inspect --variables` I get an empty policy back which shows that the variable substitution is not taking place. Then trying with `./elastic-agent inspect --variables-wait 10s` I get the same policy that I have defined with the condition: `${kubernetes.labels.app} == 'redis'` in place and not substituted.

`insepct` command is quite useful in troubleshooting and development specially for the `kubernetes` area. In this, we should ensure it is working as expected and can cover our needs.

Something that looks similar to this but comes from a diagnostics result is the configuration at https://github.com/elastic/integrations/issues/4466#issuecomment-1406245562. As we can see there too, the conditions are not replaced/evaluated when getting the diagnostics.

cc: @cmacknz @blakerouse
