### ISSUE TITLE
Load `fleet.ssl.certificate_authorities` from agent policy

### ISSUE THREAD

**Issue by joshdover** [elastic/elastic-agent#2247]
Similar to https://github.com/elastic/elastic-agent/pull/2172 we need to support respecting the certificate authority provided in an agent policy from Fleet:

```
key: my-cert-key
fleet:
  hosts:
    - 'https://test-fs.com:8220/'
  proxy_url: 'https://my-proxy'
  ssl:
    certificate_authorities:
      - my-ca
```

This is already provided by Fleet in 8.7, so marking this as a bug on the agent side. Backporting to 8.7 is preferable. See the parent (private) issue for more details.
