### ISSUE TITLE
Load `fleet.ssl.certificate` and `fleet.ssl.key` from agent policy

### ISSUE THREAD

**Issue by joshdover** [elastic/elastic-agent#2248]
Similar to https://github.com/elastic/elastic-agent/pull/2172 we need to support respecting the `certificate` and `key` values provided in an agent policy from Fleet which will be added in https://github.com/elastic/kibana/issues/150709 for the next release. This is to support mTLS with proxies when connecting to Fleet.

The policy from Fleet will have the form:
```yaml
fleet:
  hosts:
    - 'https://test-fs.com:8220/'
  proxy_url: 'https://my-proxy'
  ssl:
    certificate_authorities:
      - my-ca
    certificate: my-cert
    key: my-key
```

See the parent (private) issue for more details.
