### ISSUE TITLE
Config parameters aren't passed through to the shipper output in Beats

### ISSUE THREAD

**Issue by faec** [elastic/elastic-agent#2351]
When ingesting through the shipper via the Beats shipper output, e.g. with a configuration like:

```yml
outputs:
  default:
    type: elasticsearch
    log_level: debug
    enabled: true
    hosts: [https://127.0.0.1:9200]
    username: "elastic"
    password: [password]
    bulk_max_size: 4096
    shipper:
      enabled: true
```

Agent does not pass through `bulk_max_size` or any other parameters except the ones it synthesizes itself. The config parameters the shipper output receives are:

```
type
server
ssl.certificate
ssl.key
ssl.certificate_authorities
```

note that `type` is not actually a field of the shipper output's config (though it may be used elsewhere in the pipeline). However there are several other fields that are in the shipper output config:

```
timeout
max_retries
bulk_max_size
ack_polling_interval
backoff.init
backoff.max
```

and none of these are ever set.

This issue is possibly more for discussion / awareness than an immediate fix, since we might have good reasons not to expose those settings through the agent policy, at least in production. But it also means that right now we have "configuration parameters" on the shipper output that can only be changed by rebuilding with a new hard-coded default, which at a minimum was not obvious to me when I wanted to run tests depending on `bulk_max_size` :-) So we might want to think about a way to safely expose the full config, at least for internal testing.
