### ISSUE TITLE
elastic-agent standalone not collecting logs from multiples containers at the same pod

### ISSUE THREAD

**Issue by framsouza** [elastic/elastic-agent#2375]
We're currently having some issues running elastic-agent standalone with Hints annotations-based autodiscovery, the agent is currently collecting logs only from one container inside the pod.

To test that, you can spin up Elasticseach with ECK and enable the hints annotations, you'll see something similar the following:
![image-20230228-131823](https://user-images.githubusercontent.com/16880741/225438069-a098a13b-5466-4c12-9643-ad842ba2a9e8.png)

I can see below we're getting only the `elastic-internal-init-filesystem` which is a sidecar container, but we don't get any logs from the elasticsearch container itself. 

Checking the logs inside the container, you'll see that the logs are being properly generated but not being shipped:

```
> kubectl -n elastic-agent exec --stdin --tty elastic-agent-pcrsj -- /bin/bash
> ls /var/log/containers/ | grep dep-c81e0127a37f4d6a90492a46fb4dd04c
es-es-index-75c7b5848f-dt7bj_dep-c81e0127a37f4d6a90492a46fb4dd04c_elastic-internal-init-filesystem-9aa7ad9b000247c36857e9da8c1999caca25ee32efb3def9a978ddc66b195270.log
es-es-index-75c7b5848f-dt7bj_dep-c81e0127a37f4d6a90492a46fb4dd04c_elasticsearch-a8f4b9c70b318fed12ff46ba08f270f8e769332fac58415237698112a93c8703.log
es-es-search-55f95d9584-grcgz_dep-c81e0127a37f4d6a90492a46fb4dd04c_elastic-internal-init-filesystem-527502045dbf631c2331eb4f69d55a248c1c9b2f04a8727e972e174898d12687.log
es-es-search-55f95d9584-grcgz_dep-c81e0127a37f4d6a90492a46fb4dd04c_elasticsearch-f23ece635ee7e04eb5d60491662e6ded539446352c71df39190b1603a14eb591.log
kb-ui-kb-b86c99f6f-nrxjs_dep-c81e0127a37f4d6a90492a46fb4dd04c_elastic-internal-init-config-9bd46a48daa2ba5f37a54a4ca4f698dc0598fbd66ffa31e51f9842b542b15b92.log
kb-ui-kb-b86c99f6f-nrxjs_dep-c81e0127a37f4d6a90492a46fb4dd04c_elastic-internal-init-keystore-a0d5c67083d680a7eeb8b7ae33a92084663120b061e26d98b19adf5b6d3376b1.log
kb-ui-kb-b86c99f6f-nrxjs_dep-c81e0127a37f4d6a90492a46fb4dd04c_kibana-7b6bcbba08af4924610cbb57f4c2d5d944bb4f5dd53f9487378b7258aac4648e.log
```

I had a look at the [hints.go](https://github.com/elastic/elastic-agent/blob/main/internal/pkg/composable/providers/kubernetes/hints.go) code and it seems the function responsible for collecting those logs has a`containerID` parameter mapped as  _`string`_  and I think it should be a _`struct`_ instead to be able to collect more than one containerID, [see](https://github.com/elastic/elastic-agent/blob/6ed1e14736ecd850e50627395cd5bfbe84100d21/internal/pkg/composable/providers/kubernetes/hints.go#L137)

**Comment by ChrsMark** [comment]
Hey @framsouza , thanks for filing this issue.

The function you mention is called once per container, since we loop over the Pod's containers at https://github.com/elastic/elastic-agent/blob/f772a3deab4bab4894e37f11ad731b1be3ea93aa/internal/pkg/composable/providers/kubernetes/pod.go#L320. 

We will need to investigate this a bit to check what's going wrong here.

**Comment by framsouza** [comment]
@ChrsMark I'll provide the elastic-agent diagnostic shortly. Just for clarity, this problem is happening when there's an InitContainer and not a sidecar, if you spin up ECK you'll see an initContainer called _elastic-internal-init-filesystem_ , only the logs from this initContainer are being ingested, we're missing the logs from the main container

**Comment by ChrsMark** [comment]
Thanks for clarifying @framsouza . Could you also provide the annotations you use and how you configure Elastic Agent (the k8s manifest would be enough) ?

**Comment by framsouza** [comment]
@ChrsMark the test was performed on the MKI environment, you can check the labels that were being used [here](https://github.com/elastic/platform-observability-charts/pull/26)

**Comment by framsouza** [comment]
@ChrsMark the test was performed on the MKI environment, you can check the labels that were being used [here](https://github.com/elastic/platform-observability-charts/pull/26)

**Comment by framsouza** [comment]
@ChrsMark I'm running this configmap:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: elastic-agent-inputs
  labels:
    k8s-app: elastic-agent
data:
  inputs.yml: |-
    inputs:
      - name: container-log
        condition: startsWith(${kubernetes.pod.name}, "elastic-agent") != true && ${kubernetes.hints.enabled} == true
        type: filestream
        processors:
          - add_fields:
              target: orchestrator.cluster
              fields:
                name: {{ .Values.cluster.name }}
        use_output: logs
        meta:
          package:
            name: kubernetes
            version: 1.9.0
        data_stream:
          namespace: default
        streams:
          - data_stream:
              dataset: kubernetes.container_logs
              type: logs
            prospector.scanner.symlinks: true
            parsers:
              - container: ~
              - ndjson:
                  target: json
                  add_error_key: true
                  message_key: message
                  overwrite_keys: true
                  ignore_decoding_error: true
              # - multiline:
              #     type: pattern
              #     pattern: '^\['
              #     negate: true
              #     match: after
            paths:
              - /var/log/containers/*${kubernetes.container.id}.log
```
And,

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: elastic-agent-datastreams
  labels:
    k8s-app: elastic-agent
data:
  elastic-agent.yml: |-  
    outputs:
      metrics:
        type: elasticsearch
        hosts:
          - >-
            ${ELASTICSEARCH_METRICS_HOST}
        username: ${ELASTICSEARCH_METRICS_USERNAME}
        password: ${ELASTICSEARCH_METRICS_PASSWORD}
      logs:
        type: elasticsearch
        allow_older_versions: true
        hosts:
          - >-
            ${ELASTICSEARCH_LOGS_HOST}
        username: ${ELASTICSEARCH_LOGS_USERNAME}
        password: ${ELASTICSEARCH_LOGS_PASSWORD}
      monitoring:
        type: elasticsearch
        allow_older_versions: true
        hosts:
          - >-
            ${ELASTICSEARCH_MONITORING_HOST}
        username: ${ELASTICSEARCH_MONITORING_USERNAME}
        password: ${ELASTICSEARCH_MONITORING_PASSWORD}
    agent:
      monitoring:
        enabled: true
        logs: true
        metrics: true
        use_output: monitoring
      logging:
        level: {{ .Values.agent.log_level | default "info" }}
        to_stderr: true
        json: true
        use_output: logs
    providers:
      kubernetes_leaderelection:
        enabled: false
      kubernetes:
        node: ${NODE_NAME}
        scope: node
        hints.enabled: true
```

With the following daemonset:

```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: elastic-agent
  labels:
    app: elastic-agent
spec:
  selector:
    matchLabels:
      app: elastic-agent
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 34%
  template:
    metadata:
      labels:
        app: elastic-agent
    spec:    
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
      serviceAccountName: elastic-agent
      hostNetwork: false
      dnsPolicy: ClusterFirstWithHostNet
      initContainers:
#      - name: k8s-templates-downloader
#        image: busybox:1.28
#        command: ['sh']
#        args:
#          - -c
#          - >-
#            mkdir -p /etc/elastic-agent/inputs.d &&
#            wget -O - https://github.com/elastic/elastic-agent/archive/main.tar.gz | tar xz -C /etc/elastic-agent/inputs.d --strip=5 "elastic-agent-main/deploy/kubernetes/elastic-agent-standalone/templates.d"
#        volumeMounts:
#          - name: external-inputs
#            mountPath: /etc/elastic-agent/inputs.d       
      containers:       
        - name: elastic-agent
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          args: [
              "-c", "/etc/elastic-agent/elastic-agent.yml",
              "-e",
          ]
          envFrom:
            - secretRef:
                name: elastic-agent-secrets
{{- if .Values.extraEnvsFrom }}
{{ toYaml .Values.extraEnvsFrom | nindent 12 }}
{{- end }}
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: CONFIG_PATH
              value: "/etc/elastic-agent/"
{{- if .Values.extraEnvs }}
{{ toYaml .Values.extraEnvs | nindent 12 }}
{{- end }}
          securityContext:
            runAsUser: 0
          resources:
            limits:
              memory: {{ .Values.agent.daemonset.resources.limits.memory }}
            requests:
              cpu: {{ .Values.agent.daemonset.resources.requests.cpu }}
              memory: {{ .Values.agent.daemonset.resources.requests.memory }}
          volumeMounts:
            - name: datastreams
              mountPath: /etc/elastic-agent/elastic-agent.yml
              readOnly: true
              subPath: elastic-agent.yml
            - name: inputs
              mountPath: /etc/elastic-agent/inputs.d/
              readOnly: true
            - name: proc
              mountPath: /hostfs/proc
              readOnly: true
            - name: cgroup
              mountPath: /hostfs/sys/fs/cgroup
              readOnly: true
            - name: varlibdockercontainers
              mountPath: /var/lib/docker/containers
              readOnly: true
            - name: varlog
              mountPath: /var/log
              readOnly: true
            - name: journald
              mountPath: /var/log/journal
              readOnly: true
            - name: dockersock
              mountPath: /var/run/docker.sock          
      volumes:
#        - name: external-inputs
#          emptyDir: {}
        - name: datastreams
          configMap:
            defaultMode: 0640
            name:  elastic-agent-datastreams
        - name: inputs
          projected:
            sources:
            - configMap:
                name:  elastic-agent-inputs
        - name: proc
          hostPath:
            path: /proc
        - name: cgroup
          hostPath:
            path: /sys/fs/cgroup
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
        - name: varlog
          hostPath:
            path: /var/log
        - name: journald
          hostPath:
            path: /var/log/journal
        - name: dockersock
          hostPath:
            path: /var/run/docker.sock
```


Against the [vault-ci-dev GKE cluster](https://console.cloud.google.com/kubernetes/clusters/details/us-central1/elastic-apps-vault-ci-dev/details?project=elastic-apps-163815), there's a vault statefulset running on vault-ci-dev namespace, the logs outputs are being sent to the [logging cluster (RLC)](https://logging.us-central1.gcp.foundit.no/). If you check access the cluster, you'll see the following output for the vault-ci-dev namespace

```
kubectl get pods -n vault-ci-dev            
NAME             READY   STATUS    RESTARTS   AGE
vault-ci-dev-0   3/3     Running   0          27d
vault-ci-dev-1   3/3     Running   0          27d
vault-ci-dev-2   3/3     Running   0          27d
```
vault container has 3 pods (filebeat, logrotate and vault), if you check the [Saved search,](https://logging.us-central1.gcp.foundit.no/app/discover#/view/287c67e0-c81a-11ed-8844-7bbcc3baca41?_g=h@c823129&_a=h@f98925a) you'll see we only see the logs from the filebeat container , we're missing logs from vault and logrotate.

See elastic-agent inject output:
[inspect.txt](https://github.com/elastic/elastic-agent/files/11033016/inspect.txt)

**Comment by framsouza** [comment]
attaching the elastic-agent diagnostic, 
[elastic-agent-diagnostics-2023-03-21T21-37-37Z-00.zip](https://github.com/elastic/elastic-agent/files/11033987/elastic-agent-diagnostics-2023-03-21T21-37-37Z-00.zip)

**Comment by ChrsMark** [comment]
Thanks for the extra info @framsouza!

Let me try to put all these into an order.

So first of all we have the following input:

```yml
    inputs:
      - name: container-log
        condition: startsWith(${kubernetes.pod.name}, "elastic-agent") != true && ${kubernetes.hints.logs.enabled} == true
        type: filestream
        processors:
          - add_fields:
              target: orchestrator.cluster
              fields:
                name: {{ .Values.cluster.name }}
        use_output: logs
        meta:
          package:
            name: kubernetes
            version: 1.9.0
        data_stream:
          namespace: default
        streams:
          - data_stream:
              dataset: kubernetes.container_logs
              type: logs
            prospector.scanner.symlinks: true
            parsers:
              - container: ~
              - ndjson:
                  target: json
                  add_error_key: true
                  message_key: message
                  overwrite_keys: true
                  ignore_decoding_error: true
              # - multiline:
              #     type: pattern
              #     pattern: '^\['
              #     negate: true
              #     match: after
            paths:
              - /var/log/containers/*${kubernetes.container.id}.log
```

So here I see that you mix 2 different things. First you use the `kubernetes.hints.logs.enabled` in the condition which implies that you expect a mapping coming from `hints` and then you use `- /var/log/containers/*${kubernetes.container.id}.log`.
These 2 are 2 different things because the kubernetes provider from Agent will either emit `kubernetes.hints.*` mappings or `kubernetes.*` mappings without the `hints` prefix.

Also I see that you have remove the init container that downloads the hints templates but that's ok since you try to define your own templates.


Having said this a working template should look the one at https://github.com/elastic/elastic-agent/blob/main/deploy/kubernetes/elastic-agent-standalone/templates.d/cassandra.yml#L21, see that the path is like `/var/log/containers/*${kubernetes.hints.container_id}.log`.

So in that case I wonder how the provided config was working but definitely the templates need to be fixed.

Can you please fix this and try again. It would also help if you can provide a minimal example with target Pods with multiple containers so as to have a specific example to reproduce. Apparently debugging against am active [vault-ci-dev GKE cluster](https://console.cloud.google.com/kubernetes/clusters/details/us-central1/elastic-apps-vault-ci-dev/details?project=elastic-apps-163815) is not a good idea.

For reference I have spotted an issue in hints codebase. At https://github.com/elastic/elastic-agent/blob/f772a3deab4bab4894e37f11ad731b1be3ea93aa/internal/pkg/composable/providers/kubernetes/pod.go#L385 we only emit hints mappings for containers that have defined Ports. This means that containers with no Ports defined will not have an emitted mapping. This is an issue and I will push a fix for it, however I will wait to see if we can spot any additional issues here.

**Comment by framsouza** [comment]
This PR seems to be a potential fix https://github.com/elastic/elastic-agent/pull/2386

**Comment by framsouza** [comment]
I've performed the changes as @ChrsMark mentioned above, the daemonset now is using the initContainer to download the templates,

```
      initContainers:
      - name: k8s-templates-downloader
        image: busybox:1.28
        command: ['sh']
        args:
          - -c
          - >-
            mkdir -p /etc/elastic-agent/inputs.d &&
            wget -O - https://github.com/elastic/elastic-agent/archive/main.tar.gz | tar xz -C /etc/elastic-agent/inputs.d --strip=5 "elastic-agent-main/deploy/kubernetes/elastic-agent-standalone/templates.d"
        volumeMounts:
          - name: external-inputs
            mountPath: /etc/elastic-agent/inputs.d       
```

However, once I applied the new configuration the logs stopped flowing and as @ChrsMark mentioned, it might be because we missed a generic input for all the container on the [templates.d/](https://github.com/elastic/elastic-agent/tree/be61de1b002e9beb425eb26cb0511d1916cff7d6/deploy/kubernetes/elastic-agent-standalone/templates.d)
