### ISSUE TITLE
Filestream monitoring processors used to prevent error loops are wrong

### ISSUE THREAD

**Issue by cmacknz** [elastic/elastic-agent#2388]
We attempt to automatically drop error logs from the filestream monitoring instance to avoid failing to ship an event, logging it, then failing to ship the logged event, and so in an infinite failure loop.

Today these processors are defined as:

https://github.com/elastic/elastic-agent/blob/be61de1b002e9beb425eb26cb0511d1916cff7d6/internal/pkg/agent/application/monitoring/v1_monitor.go#L324-L353

This results in the following in the `beat-rendered-config` of the filestream-monitoring input:

```yaml
  - drop_event:
      when:
        or:
        - equals:
            component:
              dataset: elastic_agent.filestream_monitoring
        - equals:
            component:
              dataset: elastic_agent.beats_metrics_monitoring
        - equals:
            component:
              dataset: elastic_agent.http_metrics_monitoring
```

The problem is that the datasets are wrong. Looking at sample events the dataset identifier is actually:

```json
{
  "component": {
    "binary": "filebeat",
    "dataset": "elastic_agent.filebeat",
    "id": "filestream-monitoring",
    "type": "filestream"
  }
}
```

Likely this was broken when we moved away from per process data stream names and reverted to the names in the 8.5.x and earlier released. See https://github.com/elastic/elastic-agent/issues/1814
