### ISSUE TITLE
Elastic agent produces duplicate ecs.version json key

### ISSUE THREAD

**Issue by honzakral** [elastic/elastic-agent#2398]
Please post all questions and issues concerning the Elastic Agent on https://discuss.elastic.co/c/beats
before opening a Github Issue. Your questions will reach a wider audience there,
and if we confirm that there is a bug, then you can open a new issue.

For security vulnerabilities please only send reports to security@elastic.co.
See https://www.elastic.co/community/security for more information.

Please include configurations and logs if available.

For confirmed bugs, please report:
- Version: 8.6.2
- Operating System: Linux (k8s)
- Steps to Reproduce:

with a config of:
```yaml
agent:
  logging:
    level: warning
    metrics.enabled: false
  download:
    sourceURI: https://artifacts.elastic.co/downloads/
  monitoring:
    enabled: true
    logs: false
    metrics: true
    use_output: default
    namespace: ${NAMESPACE}
  reload:
    enabled: false
outputs:
  default:
    type: elasticsearch
    hosts: ["${ES_HOST}"]
    api_key: ${API_KEY}
inputs:
  - ...
```

Elastic agent pod produces logs that contain (for example):
```json
{"log.level":"error","@timestamp":"2023-03-25T16:52:40.879Z","message":".....","component":{"binary":"filebeat","dataset":"elastic_agent.filebeat","id":"filestream-default","type":"filestream"},"log":{"source":"filestream-default"},"id":"6B22CE6262FCE2A2","log.logger":"input.filestream","log.origin":{"file.line":168,"file.name":"input-logfile/harvester.go"},"service.name":"filebeat","source_file":"filestream::.global::native::398408-2049","ecs.version":"1.6.0","ecs.version":"1.6.0"}
```

While this is technically allowed by the json RFC it states (https://www.rfc-editor.org/rfc/rfc8259#section-4) that:
> When the names within an object are not unique, the behavior of software that receives such an object is unpredictable.
