### ISSUE TITLE
[Standalone] Simplify the required config for inputs

### ISSUE THREAD

**Issue by joshdover** [elastic/elastic-agent#2416]
Using Elastic Agent with basic inputs has some rough edges that could be smoothed out in order to make simple “tail a file” and related use cases easier to get right. There’s just too many papercuts that make these simple use cases hard to use standalone Agent for.

A very basic “tail a file” configuration for standalone agent looks like this today: 

```yaml
inputs:
  - id: my-file
    name: my-file
    type: logfile
    use_output: default
    data_stream:
      namespace: default
    streams:
      - id: my-file-1
        paths:
          - /var/log/my-file/my.log*
```

We could simplify this by:
- Making the `streams` block optional, only require if multiple streams on the same input are used
- Support “dot-notation” on all fields - currently `data_stream.dataset` does not work
- Adding validation to the configuration to throw errors early on unrecognized keys or invalid values
- Making `use_output` optional (maybe already the case?)
- Beats 8.6 does not require `data_stream.* fields`  and instead will use reasonable defaults based on the input type (eg. logs-generic-default or metrics-generic-default). We should update our example configuration and agent policy generated by Fleet to take advantage of this change.

An ideal minimal configuration for tailing a log should look like this:

```yaml
inputs:
  - type: logfile
    paths:
      - /var/log/my-file/my.log*
```

- `data_stream.*` field are filled with defaults for the input type
- `use_output` defaults to `default` or, if there is only 1 output, whatever output that is. Otherwise throws an error to force the user to specify an output.
- `name` is not required
- `id` is not required (unless you have multiple inputs)
- `stream` block is not required

### Open questions
- [ ] How should we handle name conflicts between input options and the base structure for the `inputs` array?
- [ ] What validation can we reasonably add to input options? What could we accomplish just for the `logfile` and `filestream` inputs?

**Comment by jlind23** [comment]
@belimawr For this issue worth setting up a kick off call with the o11y folks in order to agree on the scope and outcomes.

**Comment by belimawr** [comment]
After talking with the Observability folks, @cmacknz and @joshdover we got to the following minimal config and considerations:
```yaml
inputs:
  - type: filestream
    id: unique-id-per-input
    paths:
      - /var/log/my-file/my.log*
```
* This simpler input configuration will be handled as a special case
* It will not support the `streams` key.
* The `id` needs to be unique per policy and will act as both:
    *  The Elastic-Agent input ID
    * Filestream input ID
* Additional configurations like `parsers` and `processors` will also be supported.
* `data_stream.*` can already be omitted and the Elastic-Agent will use the default ones
* `use_output` will be omitted (needs implementing), the `default` or the only output available will be used. If more than one output is configured, it will cause an error preventing the Elastic-Agent from starting. This could be extended to all inputs.
* If the `streams` key is present, it will cause an error preventing the Elastic-Agent from starting.
* We need to be very clear when writing documentation and highlight when to use this simpler case.

**Comment by belimawr** [comment]
I did some testing and the following configuration already works:
```yaml
outputs:
  default:
    type: elasticsearch
    hosts:
      - http://localhost:9200
    username: "elastic"
    password: "changeme"

inputs:
  - id: elastic-agent-input-id
    type: filestream
    streams:
      - id: filestream-input-id
        paths:
          - /tmp/log.log
```

**Comment by ruflin** [comment]
One key bit that I think is missing is the support for the `data_stream.*` settings on this level which if I remember correctly currently doesn't work:

```yaml
inputs:
  - type: filestream
    id: unique-id-per-input
    data_stream.dataset: mystuff
    paths:
      - /var/log/my-file/my.log*
 ```

Another thing that should be tested that I stumbled over in the past with this, that this only worked as an object and not flattened. What I mean by that is that the above would not work but the one below does. Both should just work.

```yaml
inputs:
  - type: filestream
    id: unique-id-per-input
    data_stream:
      dataset: mystuff
    paths:
      - /var/log/my-file/my.log*
 ```

Some questions on the above points:

 * "This simpler input configuration will be handled as a special case": I'm ok with this if it simplifies things but ideally other inputs like syslog, tcp, udp would work exactly the same.
 * "It will not support the streams key.": Also supportive of this but if this requires extra checks to be added this could come later.
