### ISSUE TITLE
Agent monitoring server is binding to all interfaces instead of localhost

### ISSUE THREAD

**Issue by andrewkroh** [elastic/elastic-agent#2509]
For confirmed bugs, please report:
- Version: 8.6.2 (build: 913c02bea9b13dec4d5c5f3057b5b397344e3298 at 2023-02-13 16:52:36 +0000 UTC)
- Operating System: macOS 13.3.1 (22E261)
- Steps to Reproduce:
1. Deploy a Fleet managed Elastic Agent on macOS.
2. Observe the listening ports. (use netstat, Little Snitch, etc)

```json
[
  {
    "connections": [
      {
        "bytesDown": "0",
        "bytesUp": "0",
        "interface": "",
        "localAddress": "::",
        "localPort": "6791",
        "protocol": "TCP",
        "remoteAddress": "::",
        "remoteHostName": "::",
        "remotePort": "0",
        "state": "Listen"
      }
    ],
    "process": {
      "path": "/Library/Elastic/Agent/data/elastic-agent-913c02/elastic-agent.app/Contents/MacOS/elastic-agent",
      "pid": "837",
      "signature(s)": {
        "signatureStatus": 100013
      }
    }
  }
]
```

```
netstat -an | grep 6791
tcp46      0      0  *.6791                 *.*                    LISTEN
```

I expected to see something like this where it binding only to the loopback interface.

```
# MOCK DATA
tcp4       0      0  127.0.0.1.6791         *.*                    LISTEN
```

This may be a bug because the Agent code already appears to bind to localhost by default.

https://github.com/elastic/elastic-agent/blob/d7adf66bc4e462abed24b95ee48b0671b8a952ab/internal/pkg/core/monitoring/config/config.go#L56-L60

**Comment by WiegerElastic** [comment]
Wanted to share the output on my machine (MacOS 13.3.1) running Agent version 8.7.0.

<img width="640" alt="image" src="https://user-images.githubusercontent.com/97174155/232885118-18de52a1-37f8-47b6-9e65-b8748a48386f.png">

<img width="779" alt="image" src="https://user-images.githubusercontent.com/97174155/232887402-74e260af-8e3a-4a9c-ac4b-59bebb9beb0f.png">

**Comment by SpencerLN** [comment]
Are there any plans to prioritize fixing this? 

I noticed that `elastic-agent` seems to listen on all interfaces even when `agent.monitoring.http.enabled: false` is set:
```
agent:
  download:
    sourceURI: https://artifacts.elastic.co/downloads/
  features: null
  headers: null
  id: 3ab3a5fc-a6e7-4efd-8204-e745f6a63e5d
  logging:
    level: info
  monitoring:
    enabled: true
    http:
      buffer: null
      enabled: false
      host: ""
      port: 6791
```

```
% sudo lsof -PiTCP -sTCP:LISTEN +c0 | grep elastic-agent
elastic-agent              59884  root    9u  IPv6 0x68956d5be803a143      0t0  TCP *:6791 (LISTEN)
elastic-agent              59884  root   16u  IPv4 0x68956d6574fc23ab      0t0  TCP localhost:6789 (LISTEN)
elastic-agent              59884  root   17u  IPv4 0x68956d6574fde3ab      0t0  TCP localhost:6788 (LISTEN)
```
