### ISSUE TITLE
numbers in policies aren't working as expected in 8.7.0

### ISSUE THREAD

**Issue by leehinman** [elastic/elastic-agent#2522]
Observed with custom log integration.

If you have a processor defined like this:

```
  - extract_array:
      field: my_csv_array
      fail_on_error: false
      mappings:
        _temp1: 2
```

You get an error:

```
[elastic_agent.filebeat][error] Error creating runner from config: bad extract_array mapping for field _temp1: 2 is not a positive integer accessing 'processors.11.extract_array'
```

But if you use the same definition in a filebeat.yml config file it works fine.  Also if you change the `_temp1: 2` to `_temp1: "2"` that works fine.  This works because the [code](https://github.com/elastic/beats/blob/7929f6bf1975d2b9e5ed9654af528a7c5840bc85/libbeat/common/coerce.go#L24) that is throwing the error will try to convert the string to a number.  I think the bug is that the type of "2" isn't an int but a float since the code wouldn't handle that.  But that is a guess at this point.

If you grab the policy from fleet or `elastic-agent inspect` the definition "looks" correct:

```
          - extract_array:
              mappings:
                _temp1: 2
              field: my_csv_array
              fail_on_error: false
```
