### ISSUE TITLE
[Elastic Agent] Allow the source_uri address to be reachable via a proxy server

### ISSUE THREAD

**Issue by nimarezainia** [elastic/elastic-agent#2610]
**Describe the enhancement:**
Today we can configure a proxy for connectivity to Fleet-Server and Outputs. Users have the flexibility to modify these via the UI and get the agent to reach these components via any of their proxies. If the user has a proxy to the internet, then they would need the same treatment for the source_uri that points to Artifact.elastic.co

Currently we can only do this globally by setting the HTTPS_PROXY environment variables.

**Describe a specific use case for the enhancement or feature:**
the user is a service provider or a large enterprise with many tenants each in their own DMZ environment. These networks are protected by a proxy and a firewall. The user doesn't (or finds t costly) to install and manage a local http-server in each region and would like the agents to reach the artifact repo that is globally available via the proxy.

** What is the definition of done?**
- When the agent can be successfully upgraded from the internet in presence of a proxy.

**Comment by pierrehilbert** [comment]
@nimarezainia what is expected here from @zombieFox? Could you please add more details?

**Comment by nimarezainia** [comment]
@pierrehilbert @zombieFox 

in the fleet settings page we allow the user to add a proxy:
<img width="992" alt="image" src="https://github.com/elastic/elastic-agent/assets/13442829/8fd0c422-fc89-4d66-8de0-4d3ba1d101b0">

for Outputs and Fleet Server we allow the user to tell us which proxy (that they just added) should be used to reach the Output or Fleet Server (note the proxy drop down):
<img width="507" alt="image" src="https://github.com/elastic/elastic-agent/assets/13442829/a4a25472-f48f-45bf-96c9-ac1ecc596cc1">

Also in the fleet settings page we have the ability to identify the Agent binary download location:
<img width="994" alt="image" src="https://github.com/elastic/elastic-agent/assets/13442829/2e5cddde-8218-4ceb-a299-de9c3f8204a1">

The original idea discussed was to add the proxy drop down here in the Agent download definition flyout also:
<img width="523" alt="image" src="https://github.com/elastic/elastic-agent/assets/13442829/9b8ba908-f6af-4bfb-ad76-30193dcfef9b">

so once that the proxy is defined, agents will send the request via that proxy to the ultimate Agent Binary download server.

@zombieFox does this flow make sense to you? if not I can create a mockup.
@pierrehilbert I am not sure what changes are required on the Agent to support this. I suspect majority of the effort is here.

(cc: @joshdover @cmacknz )

**Comment by cmacknz** [comment]
The proxy URL will need to be configurable in the agent policy along side the binary source URL.

I think we already expose this in the agent policy, but it can't be configured from Fleet and may not be documented anywhere.

The upgrade artifact configuration embeds an HTTP configuration object:

https://github.com/elastic/elastic-agent/blob/5eb21378540411c105c230214727d86371d7aec9/internal/pkg/agent/application/upgrade/artifact/config.go#L60-L62

This embeds proxy settings:

https://github.com/elastic/elastic-agent/blob/5eb21378540411c105c230214727d86371d7aec9/internal/pkg/agent/application/upgrade/artifact/config.go#L60-L62

This implements `proxy_url`:

https://github.com/elastic/elastic-agent/blob/5eb21378540411c105c230214727d86371d7aec9/internal/pkg/agent/application/upgrade/artifact/config.go#L60-L62

So it should already be possible to configure the following in a standalone agent policy:

```yaml
agent.download:
  # source of the artifacts, requires elastic like structure and naming of the binaries
  # e.g /windows-x86.zip
  sourceURI: "https://artifacts.elastic.co/downloads/beats/"
  proxy_url: "https://some.proxy.url"
```

**Comment by nimarezainia** [comment]
@cmacknz should we move to the Fleet UI team then  for implementation/completion?

**Comment by juliaElastic** [comment]
> So it should already be possible to configure the following in a standalone agent policy:
```
agent.download:
  # source of the artifacts, requires elastic like structure and naming of the binaries
  # e.g /windows-x86.zip
  sourceURI: "https://artifacts.elastic.co/downloads/beats/"
  proxy_url: "https://some.proxy.url"
```

This should already be possible with the override API, so no work needed on Fleet UI side. We just need to verify that it works, see https://github.com/elastic/kibana/issues/158699#issuecomment-1609143328
