### ISSUE TITLE
Extend spec runtime conditions to include managed/standalone mode

### ISSUE THREAD

**Issue by emilioalvap** [elastic/elastic-agent#2699]
**Describe the enhancement:**
Agent supports runtime conditions to be specified in each spec: https://github.com/elastic/elastic-agent/blob/0af676d2c10ff5b0d5e2446270786f4718bc8e19/specs/cloud-defend.spec.yml#L14.

This request is to extend the provided conditions to include a flag indicating whether the agent is running in managed or standalone mode:
https://github.com/elastic/elastic-agent/blob/0af676d2c10ff5b0d5e2446270786f4718bc8e19/pkg/component/component.go#L156

**Describe a specific use case for the enhancement or feature:**
Heartbeat is interested in restricting some integrations to run only under managed mode, that's not something we can easily detect from the beat.

** What is the definition of done?**
Something like this is possible:
```yaml
runtime:
      preventions:
        - condition: ${runtime.managed} == false
          message: "Heartbeat integration can only run on managed agents"
```
