### ISSUE TITLE
Fleet Server configuration does not contain all the hosts available in the Elasticsearch cluster

### ISSUE THREAD

**Issue by mrodm** [elastic/elastic-agent#2784]
- Version: 8.7.1 (and probably newer versions)
- Operating System: Linux
- Discuss Forum URL: N/A

Following the instructions to enroll a new Fleet Server, if the host used in the install command is down or stopped, fleet-server becomes unhealhty (and all the agents connected to it).

## Steps to Reproduce:

- Setup a Elastic stack cluster with 3 Elasticsearch hosts and 1 Kibana.
    - Ensure that the 3 ES hosts are accessible to port 9200
        - In this example, these ES hosts are accessible through:
            - https://10.13.233.1:9200
            - https://10.13.233.1:9201
            - https://10.13.233.1:9202
    - Ensure that Kibana has configured the 3 ES hosts in its configuration.
- Add in the Fleet Settings, all three hosts available in the Output
  ![fleet output configuration](https://github.com/elastic/elastic-agent/assets/5330827/2a359441-de6f-4ffa-bbd8-678eaa735686)

- Create a new VM. In this VM, enroll a new fleet-server using the command suggested by the UI in another VM.
    - NOTE: there is just one ES host set in the `--fleet-server-es` parameter
    - Added some parameters to avoid issues with SSL/TLS
      ```bash
      sudo ./elastic-agent install \
        --fleet-server-es=https://10.13.233.1:9200 \
        --fleet-server-es-ca=/home/ubuntu/ca/ca.crt \
        --fleet-server-es-insecure \
        --insecure \
        --fleet-server-service-token=<token> \
        --fleet-server-policy=fleet-server-policy
      ```
- Create another VM. In this VM, enroll a new agent following the instructions too.
    - Adding `--insecure` to avoid issues with SSL/TLS
      ```
      sudo ./elastic-agent install \
        --url=https://fleetserver:8220 \
        --enrollment-token=<token> \
        --insecure
      ```
- Confirm that there are logs in Elasticsearch
  ![logs from fleet server and agent](https://github.com/elastic/fleet-server/assets/5330827/5fade219-bd41-4b6a-b5f0-7353a1c5fa05)

At this point, this new fleet-server should be shown in the Fleet view along with the agents:
![fleet healthy](https://github.com/elastic/fleet-server/assets/5330827/40c8db94-5259-4823-8026-60604cdcb3d9)

In this stage, if any ES host different to the one used in the `install` command is stopped, there are no issues with fleet-server or any agent that has been installed:
- Agents and fleet server are healthy
- Agents and Fleet server are ingesting logs

However, if the ES host (`https://10.13.233.1:9200`) used in the install command (`--fleet-server-es`) is down:
- fleet-server becomes **unhealhty** as well as the agents.
- both fleet-server and agents are still sending data (logs) to Elasticsearch

![unhealthy fleet server and agents](https://github.com/elastic/fleet-server/assets/5330827/a0611abf-b429-46cc-8448-76f7ed663346)

![logs still are sent](https://github.com/elastic/fleet-server/assets/5330827/336f5f39-41f4-4061-bc2a-7bcdc5ea7093)

Output of the `elastic-agent status`:
```
$ sudo elastic-agent status
State: HEALTHY
Message: Running
Fleet State: FAILED
Fleet Message: status code: 503, fleet-server returned an error: ServiceUnavailable, message: Fleet server unable to communicate with Elasticsearch
Components:
  * beat/metrics    (HEALTHY)
                    Healthy: communicating with pid '32799'
  * http/metrics    (HEALTHY)
                    Healthy: communicating with pid '32798'
  * system/metrics  (HEALTHY)
                    Healthy: communicating with pid '32761'
  * log             (HEALTHY)
                    Healthy: communicating with pid '32768'
  * fleet-server    (HEALTHY)
                    Healthy: communicating with pid '32714'
  * filestream      (HEALTHY)
                    Healthy: communicating with pid '32773'
```

Thanks to this PR https://github.com/elastic/fleet-server/pull/2632, when the fleet-server was healthy, a diagnostics bundle was generated and in the fleet-server configuration there is just one Elasticsearch host (the one used in the install command).

```yaml
fleet:
    agent:
        id: e1a89fa0-5c2a-41ed-a267-b615ebb34f92
        version: 8.7.1
        logging:
            level: info
    host:
        id: ""
        name: ""
output:
    elasticsearch:
        protocol: https
        hosts:
            - 10.13.233.1:9200
        path: ""
        headers: {}
        apikey: ""
        servicetoken: '[redacted]'
        proxyurl: ""
        proxydisable: false
        proxyheaders: {}
        tls:
            verification_mode: none
            certificate_authorities:
                - /home/ubuntu/ca/ca.crt
            renegotiation: never
        maxretries: 3
        maxconnperhost: 128
        timeout: 1m30s
        maxcontentlength: 104857600
...
```

**Comment by blakerouse** [comment]
Yes I forgot. Elasticsearch output configuration for the Fleet Server only every uses what it was bootstrapped with. It does not use the configuration that comes from the policy. It has been that way since it was implemented.

**Comment by cmacknz** [comment]
I think we should change it, we support multiple hosts for exactly the reason in the descriptions and the current design prevents ever failing over to another host.

**Comment by IanLee1521** [comment]
End user here, can confirm that I see what sounds like exactly the same behavior. Definitely +1 from me on updating the agent so that it has that redundancy in place to talk to other elasticsearch backends even if the one from the initial configuration is unavailable.

**Comment by lucabelluccini** [comment]
Bumping this as this is quite tough also to troubleshoot as the Elastic Agent Diagnostic reports in some files the ES output is used (from the policy), but the `local-config.yml`, `components-expected.yml` and `components-actual.yml` are the only ones reporting the host which was provided via `--fleet-server-es` at install time.

It is also counter-intuitive as Fleet UI denies to set outputs different from ES if the policy contains Fleet Server integration, which makes users think the actual ES Outputs of the policy will be used.

**Comment by nimarezainia** [comment]
@lucabelluccini the cluster that the fleet server is bootstrapped with (the main cluster that fleet server is attached to) holds all the hidden indices used to build Fleet. These indeces are not replicated across multiple clusters so I don't really see a benefit of high resiliency. I am not sure what it would mean to have multiple hosts as such defined (or even have a loadbalancer between FS and group of clusters).

We probably need to go down the path of better documenting this behavior, if needed (and possible) prevent it from the UI.

To support Elasticsearch resiliency or high availability is a major feature that we would need to spend sometime. Not sure it can be addressed in context of this issue.

**Comment by lucabelluccini** [comment]
Hello @nimarezainia, thank you for the answer.

I'm aware one cannot switch a Fleet Server ES Host, but if it is not our intention to switch this, then:
- We document this behavior, explaining what would be necessary to do in order to eventually switch host (a valid use case is changing the hostname from one node to another of the same cluster)
- Allow to provide multiple ES Hosts via the  `--fleet-server-es` flag in order to have a fallback behavior (or otherwise users are obliged to setup a reverse proxy / load balancer to do so)
- Make it clear in diagnostics that the ES host used is different from the one in the policy (see below)

In the diagnostic, in `local-config.yml` we see:
```
fleet:
    access_api_key: <REDACTED>
    agent:
        id: <REDACTED>
    enabled: true
    host: localhost:8221
    protocol: https
    proxy_disable: true
    server:
        host: 0.0.0.0
        internal_port: 8221
        output:
            elasticsearch:
                hosts:
                    - <ES HOST PROVIDED AT INSTALL TIME VIA CLI>:9200
                protocol: https
                proxy_disable: false
                proxy_headers: {}
                service_token: <REDACTED>
```

In the `computed-config.yml` we see:
```
fleet:
    hosts:
        - https://<FLEET SERVER HOST>:8220
host:
    id: <REDACTED>
id: <REDACTED>
inputs:
    - data_stream:
        namespace: default
      id: fleet-server-fleet_server-<REDACTED>
      meta:
        package:
            name: fleet_server
            version: 1.3.1
      name: fleet_server-2
      package_policy_id: <REDACTED>
      policy:
        revision: 90
      revision: 4
      type: fleet-server
      unused_key: not_used
...
outputs:
    fleet-default-output:
        api_key: <REDACTED>
        hosts:
            - https://<ES HOST 1>:9200 <<< Those are ES Hosts coming from the policy (ES Output)
            - https://<ES HOST 2>:9200
            - https://<ES HOST 3>:9200
        type: elasticsearch
```

And in the `fleet-server.yml` generated by EA we get:
```
fleet:
    agent:
        id: <REDACTED>
        version: 8.11.3
        logging:
            level: info
    host:
        id: ""
        name: ""
output:
    elasticsearch:
        protocol: https
        hosts:
            - <ES HOST PROVIDED AT INSTALL TIME VIA CLI>:9200
        path: ""
        headers: {}
        servicetoken: '[redacted]'
        servicetokenpath: ""
        proxyurl: ""
        proxydisable: false
        proxyheaders: {}
        tls:
            verification_mode: full
            certificate_authorities:
                - <REDACTED>
            renegotiation: never
        maxretries: 3
        maxconnperhost: 128
        timeout: 1m30s
        maxcontentlength: 104857600
    extra: {}
```

At least for me, it is not obvious to troubleshoot this as I would have expected the Fleet Server component in the `computed-config` to show it's using `<ES HOST PROVIDED AT INSTALL TIME VIA CLI>` and not the ES hosts specified in the `fleet-default-output`.

Yes, one could say that the Fleet Server unit doesn't show `"use_output": "fleet-default-output"`, but that's very tough to spot without digging on every single file of the diagnostic.

Do we have some problem in EA merging to reflect the currently used settings?

> These indices are not replicated across multiple clusters so I don't really see a benefit of high resiliency. 

Yes, but on-premise you can have multiple ES hosts within the same cluster and this implies:
- you cannot update the ES host (imagine a hostname change or the server is decommissioned and you want to point to another host
- you need to have a load balancer or reverse proxy in front of the ES cluster and use it to load balance across nodes of the same cluster

In ESS this is easy as we have an endpoint hiding the complications of multiple ES hosts. If one node goes down, the reverse proxy on our side will point to another ES node.

> [...] if needed (and possible) prevent it from the UI.

It's really about deciding what is the source of truth.
The Fleet UI has nothing to do in this imho.

1. You create a Fleet Server policy in the Fleet UI. You set 3 ES nodes as Output (ESNodeA, ESNodeB, ESNodeC)
1. You install a Fleet Server providing `--fleet-server-es ESNodeY`, where ESNodeY is part of the same cluster of ESNode{A,B,C}.
1. Fleet Server works anyway
1. ESNodeY needs to be decommissioned or is down.
1. The user thinks "no problem, as we have set 3 ES Nodes{A,B,C}
1. You decommission ESNodeY
1. Fleet Server goes down (cannot checkin), it can only send data as the integrations use the correct ES output
1. To understand this problem you have to dig into the diags, logs and recall you initially installed using ESNodeY

To recover, it is enough to re-enroll Fleet Server with ESNodeA or ESNodeB or ESNodeC, or setup a load balancer/reverse proxy in front of the 3.

The same example applies for users who had initially only 1 ES node, they scale up to 3 and they expect their Fleet Server to use the same ES Output setting specified in the Fleet policy and not the original one used via CLI.

I am 100% with you on the fact we also have to prevent users from switching using the ES Host used by Fleet Server at will without checking the ES cluster it the same and/or the policy exists on that ES cluster.
