### ISSUE TITLE
8.2.0-BC1 sometimes does not send api_key through Elasticsearch output config

### ISSUE THREAD

**Issue by axw** [elastic/elastic-agent#285]
Version: 8.2.0-BC1 (https://staging.elastic.co/8.2.0-8ea0c40f/summary-8.2.0.html)

1. Download the files in https://gist.github.com/axw/76ab9279f1c87adc70a753786ffd9f6b
2. Run `docker-compose up -d`
3. Wait for the Agent's status to be Healthy
4. Run `docker-compose exec fleet-server elastic-agent inspect`; there should be an api_key in the Elasticsearch output config
5. Edit the "apm" integration policy in Kibana, changing the host from "localhost:8200" to ":8200"
6. Wait for the policy update to propagate
7. Run `docker-compose exec fleet-server elastic-agent inspect`; there will no longer be an api_key in the Elasticsearch output config

Note also in the fleet-server container's logs errors like:

`fleet-server_1   | {"log.level":"error","@timestamp":"2022-04-04T04:15:48.765Z","log.origin":{"file.name":"log/reporter.go","file.line":36},"message":"2022-04-04T04:15:48Z - message: Application: filebeat--8.2.0--36643631373035623733363936343635[9871ad6d-6f0f-4318-a126-b23f9fa5d9ba]: State changed to FAILED: failed to stop after 30s: application stopping timed out - type: 'ERROR' - sub_type: 'FAILED'","ecs.version":"1.6.0"}`

**Comment by ph** [comment]
@axw I am taking a look, we did some changes in the output logic for elastic output. I see you have tested with the BC1 I am going to test with the daily snapshots.

**Comment by ph** [comment]
I've tested with the 8.2.0-snapshot and not the BC1 and I don't have this behavior, I wonder if this is related to the changes in default configuration we have reverted. I am going to try our with the BC.

**Comment by ph** [comment]
Preconditions using 8.2.0 snapshots (8.2.0-f531236e-SNAPSHOT)

## Test: 1 => Worked

```yaml
outputs:
  default:
    api_key: qSSX9H8Bi0EtYSr758-4:xpZ_egM2R4iKbiPHygb3pQ
    hosts:
    - http://elasticsearch:9200
    type: elasticsearch
revision: 2
```

## Test: 2 => Worked

```yaml
outputs:
  default:
    api_key: 3u-d9H8BC8wHwkPTgUvh:TPUvfSvbRPGQYDtVOgFIvg
    hosts:
    - http://elasticsearch:9200
    type: elasticsearch
revision: 2
```

## Test: 3 => Worked

```yaml
outputs:
  default:
    api_key: 3u-d9H8BC8wHwkPTgUvh:TPUvfSvbRPGQYDtVOgFIvg
    hosts:
    - http://elasticsearch:9200
    type: elasticsearch
revision: 2
```

## Test 4 => Worked

```yaml
outputs:
  default:
    api_key: 3u-d9H8BC8wHwkPTgUvh:TPUvfSvbRPGQYDtVOgFIvg
    hosts:
    - http://elasticsearch:9200
    type: elasticsearch
revision: 2
```

## Test: 5 => Worked

```yaml
outputs:
  default:
    api_key: 3u-d9H8BC8wHwkPTgUvh:TPUvfSvbRPGQYDtVOgFIvg
    hosts:
    - http://elasticsearch:9200
    type: elasticsearch
revision: 2
```
