### ISSUE TITLE
Upgrade capability semantics conflict with other types

### ISSUE THREAD

**Issue by faec** [elastic/elastic-agent#2949]
`capabilities.yml` provides a way for local configuration to block specific input/output types or upgrade actions initiated by Fleet. For example:

```yml
capabilities:
  - input: linux/metrics
    rule: allow
  - input: */metrics
    rule: deny
```

The capabilities are evaluated in order. This example allows the `linux/metrics` input, but will prevent any other metrics inputs from running.

The upgrade capabilities are apparently similar, but use an EQL condition to check if an upgrade should proceed. However, their allow/deny semantics are different:

```yml
- upgrade: "startsWith(${version}, '8.9')"
  rule: allow
- upgrade: "startsWith(${version}, '8')"
  rule: deny
```

This will prevent _all_ upgrades unconditionally, because upgrade capabilities only succeed if _every_ condition individually passes regardless of order. Similarly:

```yml
# i trust upgrades to version 8.8 or 8.9
- upgrade: "startsWith(${version}, '8.8')"
  rule: allow
- upgrade: "startsWith(${version}, '8.9')"
  rule: allow
```

will block all upgrades because no version can start with both "8.8" and "8.9".

The intention here needs to be clarified:
- It is clearly intentional that, e.g., `"${version} == '8.8.1'"` should block upgrades to other versions -- there are tests to confirm it.
- On the other hand, there is plenty of code to handle multiple upgrade conditions, so it was meant to be possible to use more than one -- however, none of the tests ever try applying more than one at once, so how the semantics were meant to generalize is unclear.

The simplest thing to do would be to follow the same fall-through semantics as input/output capabilities, which is how users will likely interpret these fields if they notice them. The only potential hitch is that it would technically be a breaking change to how `capabilities.yml` works -- however, it seems that upgrade capabilities are quite rarely used and their behavior isn't documented, so it might be reasonable to call this a bug and fix it regardless, since I don't believe these outcomes were intentional.
