### ISSUE TITLE
Input/output capabilities miss input types defined by variables

### ISSUE THREAD

**Issue by faec** [elastic/elastic-agent#2950]
Input/output capabilities provide a way to block specific input/output types on a local machine even when they appear in a Fleet policy. For example:

```yml
# this node shouldn't use the linux/metrics input type
capabilities:
  - input: linux/metrics
    rule: deny
```

However, the filters on input/output names are run on raw policies before variable substitution, meaning it would not catch this potential match:

```yml
inputs:
  - id: my-input
    type: ${metrics_type}
```

(where variable substitution might invoke one of the blocked types). While we usually think of local and Fleet administrators as working cooperatively, a policy change could also use this intentionally to avoid capability blocks:

```yml
inputs:
  - id: my-forced-input
    type: ${nonexistent_var | "linux/metrics"}
```

This would run the target type on all nodes regardless of the configured capabilities.

Capability filters on input/output names should be applied after variable substitution.
