### ISSUE TITLE
[Elastic Agent ] Support of processors functionality with hints autodiscovery

### ISSUE THREAD

**Issue by gizas** [elastic/elastic-agent#2959]
**Describe the enhancement:**
Currently Elastic Agent Autodiscovery with Hints supports specific list of annotations. 
The full list of both required and  optional annotations supported can be found in 
https://www.elastic.co/guide/en/fleet/current/hints-annotations-autodiscovery.html#_required_hints

This feature will introduce an additional annotation: `co.elastic.hints/processor` and the goal is the users with this annotation to specify the addition of a new processor 

**Describe a specific use case for the enhancement or feature:**

Users will define eg. 
The following annotations
```yaml
co.elastic.hints/processors.1.add_fields.target: "project"
co.elastic.hints/processors.1.add_fields.fields.name: "myproject"
```

Elastic agent will emmit the following configuration:

```yaml
processors:
  - add_fields:
      target: project
      fields:
        name: myproject
```

**What is the definition of done?**

- To support the list of https://www.elastic.co/guide/en/fleet/current/elastic-agent-processor-configuration.html
- To provide examples of working processors through annotations configuration and 
- Update the relevant documentation

**Related Issue**
- https://github.com/elastic/elastic-agent/issues/735

```[tasklist]
### Tasks
- [ ] https://github.com/elastic/elastic-agent/pull/3107
- [ ] https://github.com/elastic/ingest-docs/pull/379
```

**Comment by ChrsMark** [comment]
@gizas we just need to make sure we document that processors from hints will only be added on integration/input/package level and not on data_stream level. 

As a first iteration this is fine but let's make sure document it and even file an issue for Elastic Agent team to evaluate if we can tune the providers' interface so as to emit processors also on data_stream's level (this happens at https://github.com/elastic/elastic-agent/blob/05e7d689cd39e55a018b26f14cf70014f2695f00/internal/pkg/composable/providers/kubernetes/pod.go#L218 as already mentioned)

**Comment by gizas** [comment]
Sure sure! Lets first evaluate and test this and we will do!!! Thanks man once more @ChrsMark !

**Comment by gizas** [comment]
I have pushed latest changes in :
https://github.com/elastic/elastic-agent/tree/processorhints_enhancement

I build the above elastic agent image and load it to elastic-standalone by following https://github.com/elastic/elastic-agent#testing-elastic-agent-on-kubernetes

Please have in mind that this is a draft.

So the goal is to read the processors annotations from pod and append those in the processor map that is going to be emitted.

In more details:
Agent config:
```yaml
providers.kubernetes:
      node: ${NODE_NAME}
      scope: node
      hints:
        enabled: true
        default_container_logs: false 
```

And I mount the /etc/elastic-agent/inputs.d/container_logs.yml template of https://github.com/elastic/elastic-agent/blob/main/deploy/kubernetes/elastic-agent-standalone/templates.d/container_logs.yml

nginx.yml
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
  namespace: default
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
      annotations:
        co.elastic.hints/package: "container_logs"
        co.elastic.hints/processors.1.add_fields.target: "project"
        co.elastic.hints/processors.1.add_fields.fields.name: "myproject"  
    spec:
      containers:
      - image: nginx
        name: nginx
```

Nginx is installed with id:
```bash
k describe pod nginx-65c56f67cb-2svvr | grep -i id
    Container ID:   containerd://52efcae02df01b7cdd359914dc3d16eb6b419236c9a4fd0f9f6b88e84c67574c
```
So I see the following flow:
1. hitns autodiscovery starts https://github.com/elastic/elastic-agent/blob/processorhints_enhancement/internal/pkg/composable/providers/kubernetes/pod.go#L213
2. For specific nginx pod this new part of the code works and retrieves the processor added: https://github.com/elastic/elastic-agent/blob/processorhints_enhancement/internal/pkg/composable/providers/kubernetes/pod.go#L553 
We return the processorMapping
3. Then line 484: https://github.com/elastic/elastic-agent/blob/processorhints_enhancement/internal/pkg/composable/providers/kubernetes/pod.go#L484 handles correctly the processors list

This is what is in processorlist
![Screenshot 2023-07-19 at 3 45 30 PM](https://github.com/elastic/elastic-agent/assets/1685415/4f14fdba-d2df-434b-b75b-7c7fd8750966)

This is what is in final processor map https://github.com/elastic/elastic-agent/blob/processorhints_enhancement/internal/pkg/composable/providers/kubernetes/pod.go#L493

![Screenshot 2023-07-19 at 3 46 10 PM](https://github.com/elastic/elastic-agent/assets/1685415/265b833c-3423-4542-80b2-3d0ba2abb4a7)

But when I resume the debugger and expect that the final configuration will be emitted in agent, it **does not** !

See output:
```bash
elastic-agent inspect -v --variables --variables-wait 2s
I0719 12:52:22.681261      91 leaderelection.go:248] attempting to acquire leader lease kube-system/elastic-agent-cluster-leader...
I0719 12:52:22.688726      91 leaderelection.go:258] successfully acquired lease kube-system/elastic-agent-cluster-leader
agent:
  logging:
    to_stderr: true
inputs:
- data_stream.namespace: default
  id: unique-system-metrics-input
  streams:
  - data_stream.dataset: system.cpu
    metricsets:
    - cpu
  - data_stream.dataset: system.memory
    metricsets:
    - memory
  - data_stream.dataset: system.network
    metricsets:
    - network
  - data_stream.dataset: system.filesystem
    metricsets:
    - filesystem
  type: system/metrics
  use_output: default
outputs:
  default:
    hosts: http://elasticsearch:9200
    password: changeme
    type: elasticsearch
    username: elastic

```

**Comment by ChrsMark** [comment]
@gizas I'm not sure if the `inspect` command honors the templates that are in the `inputs.d` directory.
Actually I see that the inputs are not being populated at all.

Did you try to put the template within the `agent.yml` main configuration file instead and try the `inspect` command?
I usually follow this workflow to avoid the extra overhead of the `inputs.d` directory. See the testing notes from https://github.com/elastic/elastic-agent/pull/2386 to get an idea.

**Comment by gizas** [comment]
Hmm sth seems broken as still not works, and inspect does not show anything
but when I change the image to the ones that we have not build all populate

**Comment by ChrsMark** [comment]
If you comment out the part that extends the processors list at https://github.com/elastic/elastic-agent/commit/e4d1c95060f3b476567d9311eb686192893f253d#diff-ed933ad9cf09eb9ca797c5c89b5e8991624cbe5301d88f996d9bd947f4e3ea16R450-R455 for example, what do you see?

Also I would try to add a dummy processor body there as an initial step and see it it works.
We need to ensure that we can extend this list without an issue. I guess it should be ok but we need to verify this.

Also maybe adding some unit tests will help here to debug it easier.

If none of these help, I can find some time to checkout the branch and try it on my end.

**Comment by gsantoro** [comment]
hey @gizas ,
I was able to replicate the behaviour but I had to use 

```bash
./elastic-agent inspect -c /etc/elastic-agent/agent.yml -v --variables --variables-wait 2s
```

when running the command from the elastic-agent pod. Notice the param `-c` with the configuration to use mounted from the ConfigMap.

**Comment by gsantoro** [comment]
hey @gizas and @ChrsMark  I am not able to replicate the outcome. I was able to build the code from your feature branch, run the debugger, but the output elastic-agent config doesn't look the same as yours.

**Comment by gsantoro** [comment]
hello @gizas and @ChrsMark I finally managed to get the correct policy printed by elastic-agent and the data to be correctly printed into ES. I'm not sure if it was me not being aware of how hints work but it took me an entire day to replicate this issue. This is what I have done:

1. Started elastic-agent built from feature branch `processorhints_enhancement` with the following agent.yml config

```yaml
outputs:
  default:
    type: elasticsearch
    hosts:
      - >-
        ${ES_HOST}
    protocol: https
    ssl.verification_mode: "${ES_SSL_VERIFICATION_MODE}"
    allow_older_versions: ${ES_ALLOW_OLDER_VERSIONS}
    username: ${ES_USERNAME}
    password: ${ES_PASSWORD}
agent:
  monitoring:
    enabled: true
    use_output: default
    logs: true
    metrics: true
providers.kubernetes:
  node: ${NODE_NAME}
  scope: node
  #Uncomment to enable hints' support
  hints.enabled: true
inputs:
  # Collecting system metrics
  - name: filestream-generic
    id: hints-container-logs-${kubernetes.hints.container_id}
    type: filestream
    use_output: default
    processors:
      - add_fields:
          fields:
            name: myproject
            id: '574734885120952459'
    streams:
      - condition: ${kubernetes.hints.kubernetes.container_logs.enabled} == true
        data_stream:
          dataset: kubernetes.container_logs
          type: logs
        exclude_files: [ ]
        exclude_lines: [ ]
        parsers:
          - container:
              format: auto
              stream: ${kubernetes.hints.kubernetes.container_logs.stream|'all'}
        paths:
          - /var/log/containers/*${kubernetes.hints.container_id}.log
        prospector:
          scanner:
            symlinks: true
    data_stream.namespace: default
```

To notice from above that:
- I'm using `kubernetes.hints.kubernetes.container_logs` instead of `kubernetes.hints.generic_logs.container_logs` 
- I've never used `kube_config: /Users/andreasgkizas/.kube/config`. I don't know what it is but we don't need it

I used a pod with the following annotations

```yaml
annotations:
  co.elastic.hints/package: "kubernetes"
  co.elastic.hints/data_streams: "container_logs"
  co.elastic.hints/processors.1.add_fields.target: "project"
  co.elastic.hints/processors.1.add_fields.fields.name: "myproject"
```

To notice that I "guessed" those hints from looking at the redis docs at https://github.com/elastic/elastic-agent/pull/2386. 


3. I didn't use the config

```yaml
default_container_logs: false 
```

I don't know what it is but we don't need it.

4. I used the following command to get the generated policy into my laptop

```bash
kubectl exec -n kube-system -it elastic-agent-standalone-f422w -- ./elastic-agent inspect -c /etc/elastic-agent/agent.yml --variables --variables-wait 2s > ./policy.yaml
```

Clearly you need to adapt the previous command to the elastic-agent pod that you are running.

5. The output policy has both the fixed field set in the original policy and the extra field from the hints

```yaml
inputs:
- data_stream.namespace: default
  id: hints-container-logs-ddcae4cf518fc3645461f6ae903da145713376bc73c128d6a05ded1dbb0421f0-kubernetes-fdf67bc3-394c-495c-b87e-02b11b90898f.nginx
  name: filestream-generic
  original_id: hints-container-logs-ddcae4cf518fc3645461f6ae903da145713376bc73c128d6a05ded1dbb0421f0
  processors:
  - add_fields:
      fields:
        id: ddcae4cf518fc3645461f6ae903da145713376bc73c128d6a05ded1dbb0421f0
        image:
          name: nginx:1.23.1-alpine
        runtime: containerd
      target: container
  - add_fields:
      fields:
        name: myproject
      target: project
  - add_fields:
      fields:
        id: "574734885120952459"
        name: myproject
  streams:
  - data_stream:
      dataset: kubernetes.container_logs
      type: logs
    exclude_files: []
    exclude_lines: []
    parsers:
    - container:
        format: auto
        stream: all
    paths:
    - /var/log/containers/*ddcae4cf518fc3645461f6ae903da145713376bc73c128d6a05ded1dbb0421f0.log
    prospector:
      scanner:
        symlinks: true
  type: filestream
  use_output: default
```

I hope that's all we wanted to test.

**Comment by ChrsMark** [comment]
I think that `default_container_logs: false` is needed for this test.

Also the 
```yml
annotations:
  co.elastic.hints/package: "kubernetes"
  co.elastic.hints/data_streams: "container_logs"
  co.elastic.hints/processors.1.add_fields.target: "project"
  co.elastic.hints/processors.1.add_fields.fields.name: "myproject"
```
looks weird to me. There is no `kubernetes` package-template as far as I can I see in the templates dir. It works because you defined the hints as `kubernetes.hints.kubernetes.container_logs.enabled`. 
Also see how the template looks like at https://github.com/elastic/elastic-agent/blob/main/deploy/kubernetes/elastic-agent-standalone/templates.d/container_logs.yml#L7.

Not sure what else you might have missed here:).

I could reproduce the feature locally even without running from inside the Pod. Note that the `inspect` command can be executed from your local machine outside the kind cluster if you point to the proper `kube_config`.

Here is what I use:

```yml
providers:
  kubernetes:
    kube_config: /home/chrismark/.kube/config
    node: "kind-worker"
    hints.enabled: true
    hints.default_container_logs: false

inputs:
  - name: hints-filestream-container-logs
    id: hints-filestream-container-logs-${kubernetes.hints.container_id}
    type: filestream
    use_output: default
    streams:
      - condition: ${kubernetes.hints.container_logs.enabled} == true
        data_stream:
          dataset: kubernetes.container_logs
          type: logs
        parsers:
          - container:
              format: auto
              stream: ${kubernetes.hints.container_logs.stream|'all'}
        paths:
          - /var/log/containers/*${kubernetes.hints.container_id}.log
        prospector:
          scanner:
            symlinks: true
    data_stream.namespace: default
```

I run `./elastic-agent inspect -v --variables --variables-wait 2s`

to get:

```yml
agent:
  logging:
    to_stderr: true
inputs:
- data_stream.namespace: default
  id: hints-filestream-container-logs-d8af5ef2c60a2b5bdb7f2bd239d6994a5015f71bf70cb5584f6a3b86ed0f82ca-kubernetes-e46a6433-dd51-496c-a987-45d78a63b50f.nginx
  name: hints-filestream-container-logs
  original_id: hints-filestream-container-logs-d8af5ef2c60a2b5bdb7f2bd239d6994a5015f71bf70cb5584f6a3b86ed0f82ca
  processors:
  - add_fields:
      fields:
        id: d8af5ef2c60a2b5bdb7f2bd239d6994a5015f71bf70cb5584f6a3b86ed0f82ca
        image:
          name: nginx
        runtime: containerd
      target: container
  - add_fields:
      fields:
        container:
          name: nginx
        deployment:
          name: nginx
        labels:
          app: nginx
          pod-template-hash: 678f56544b
        namespace: default
        namespace_labels:
          kubernetes_io/metadata_name: default
        namespace_uid: ba30ee51-a9ac-4044-96bc-c110183aeb2d
        node:
          hostname: kind-worker
          labels:
            beta_kubernetes_io/arch: amd64
            beta_kubernetes_io/os: linux
            kubernetes_io/arch: amd64
            kubernetes_io/hostname: kind-worker
            kubernetes_io/os: linux
          name: kind-worker
          uid: 2f643ef8-be15-45b1-9972-ceb7c91c81f6
        pod:
          ip: 10.244.1.124
          name: nginx-678f56544b-wd892
          uid: e46a6433-dd51-496c-a987-45d78a63b50f
        replicaset:
          name: nginx-678f56544b
      target: kubernetes
  - add_fields:
      fields:
        cluster:
          name: kind-kind
          url: https://127.0.0.1:37345
      target: orchestrator
  - add_fields:
      fields:
        name: myproject
      target: project
  - rename:
      fail_on_error: "false"
      fields:
        "0":
          from: a.g
        "1":
          to: e.d
  streams:
  - data_stream:
      dataset: kubernetes.container_logs
      type: logs
    parsers:
    - container:
        format: auto
        stream: all
    paths:
    - /var/log/containers/*d8af5ef2c60a2b5bdb7f2bd239d6994a5015f71bf70cb5584f6a3b86ed0f82ca.log
    prospector:
      scanner:
        symlinks: true
  type: filestream
  use_output: default
outputs:
  default:
    api_key: example-key
    hosts:
    - 127.0.0.1:9200
    type: elasticsearch
providers:
  kubernetes:
    hints:
      default_container_logs: false
      enabled: true
    kube_config: /home/chrismark/.kube/config
    node: kind-worker
```
