### ISSUE TITLE
Introducing kubernetes.state_namespace datastream in k8s integration

### ISSUE THREAD

**Issue by gizas** [elastic/elastic-agent#3100]
**Describe the enhancement:**

Currently in our kubernetes integration we dont collect the namespace metrics from Kube State metrics. For more info see https://github.com/kubernetes/kube-state-metrics/blob/main/docs/namespace-metrics.md

This enhancement request will introduce the new kubernetes.state_namespace datastream collection. The main goal is to collect the `kube_namespace_status_condition` that will help users identify the status of namespace creation.

**Describe a specific use case for the enhancement or feature:**
Users want easily to understand if their namespace creation is running or failing. Until now this was not feasible and users could not track the namespace status

**What is the definition of done?**

- [x] Merge beats code for the enhancement: https://github.com/elastic/beats/pull/36406
- [x] Update [metricbeat manifest files](https://github.com/elastic/beats/tree/main/deploy/kubernetes): https://github.com/elastic/beats/pull/36978
- [x] Create new version for Elastic Agent Kubernetes Integration: https://github.com/elastic/integrations/pull/8329
- [ ] ~~Add visualization to Overview dashboard:~~ https://github.com/elastic/integrations/pull/8377
     - It was considered unnecessary for now
- [x] Update [EA manifest files](https://github.com/elastic/elastic-agent/tree/main/deploy/kubernetes): https://github.com/elastic/elastic-agent/pull/3750
- [ ] Provide e2e test results for functionality introduced
- [x] Update relevant documentation

**Comment by constanca-m** [comment]
Adding `kubernetes.namespace` metricset problems:

1. `kubernetes.namespace` already exists as a field. Because of this, we cannot create a new metricset with the same name. Otherwise, we will keep running into this error:
    ```
    {\"type\":\"document_parsing_exception\",\"reason\":\"[1:2039] object mapping for [kubernetes.namespace] tried to parse field [namespace] as object, but found a concrete value\"}, dropping event!","service.name":"metricbeat","ecs.version":"1.6.0"}
    ```
   Workarounds are:
   - Change the existent field `kubernetes.namespace` so we can create a new metricset with the same name. However, this would cause breaking changes: we would have to update all metricsets that use it and the dashboards.
   - Name this metricset differently. It breaks the logic of the names of all metricsets, but it does not cause any breaking change.
     - **Question**: What would be the best name? `namespace_metrics`?


2. If we have the `add_cloud_metadata:` processor, the document will look like:
    ```json
    {
       ...
       "kubernetes":{
          "labels":{
             "kubernetes_io/metadata_name":"kube-public"
          },
          "namespace":{
             "name":"kube-public",
             "uid":"87c48044-5618-4233-8ad5-73b7c5fc588b"
          },
          "namespace_metrics":{
             "created":{
                "sec":1692688692
             },
             "name":"kube-public",
             "status":{
                "active":true,
                "terminating":false
             }
          }
       },
       "metricset":{
          "name":"state_namespace_metrics",
          "period":10000
       },
       ...
    }
    ```
   We have again an error because `kubernetes.namespace` here is an object and in other metricsets it is a string:
    ```
   {\"type\":\"document_parsing_exception\",\"reason\":\"[1:197] failed to parse field [kubernetes.namespace] of type [keyword] in document with id 'NVqtIYoB0cxQspDSc2pG'. Preview of field's value: '{uid=87c48044-5618-4233-8ad5-73b7c5fc588b, name=kube-public}'
   ```
    So we need to drop these fields before they are sent to ES.

**Comment by ChrsMark** [comment]
I see this is a tough one 😞 . In order to be precise we would need to either convert `kubernetes.namespace` from string to an object or come with sth like `namespace_state`. This would end up with sth like the following:

```json
{
   ...
   "kubernetes":{
      "labels":{
         "kubernetes_io/metadata_name":"kube-public"
      },
      "namespace": "kube-public",
      "namespace_uuid": "asdf",
      "namespace_labels": {},
      "namespace_annotations": {},
      "namespace_state":{
         "created":{
            "sec":1692688692
         },
         "status":{
            "active":true,
            "terminating":false
         }
      }
   },
   "metricset":{
      "name":"state_namespace",
      "period":10000
   },
   ...
}
```

@constanca-m do you think that `namespace_state` (describes the state of the namespace) would be representative of the data we plan to collect? 
Also `metricset.name` should be aligned with what we have in other metricsets: equals to `state_namespace`.
And we should store the name of the namespace within the `kubernetes.namespace` field.

Note that we already have the `kubernetes.namespace_labels` and others for the same reasons: https://github.com/elastic/elastic-agent-autodiscover/blob/8d7196695cfe60ff29a977e1f1f99759001a1f29/kubernetes/metadata/namespace_test.go#L78-L84

In any other case we would need to hit the breaking change's impact...

cc: @tommyers-elastic @ruflin @gizas

**Comment by constanca-m** [comment]
Yes, for now I am using `state_namespace`. Although it is not ideal, it seems better than changing `kubernetes.namespace` in everything. It looks like this:

```yml
{
    "@timestamp": "2019-03-01T08:05:34.853Z",
    "event": {
        "dataset": "kubernetes.state_namespace",
        "duration": 115000,
        "module": "kubernetes"
    },
    "kubernetes": {
        "state_namespace": {
            "created": {
                "sec": 1691566342
            },
            "name": "local-path-storage",
            "status": {
                "active": true,
                "terminating": false
            }
        }
    },
    "metricset": {
        "name": "state_namespace",
        "period": 10000
    },
    "service": {
        "address": "127.0.0.1:55555",
        "type": "kubernetes"
    }
}
```

The problem now is to find a solution to avoid introducing `kubernetes.namespace` object when adding the kubernetes processor.
