### ISSUE TITLE
[Elastic Agent] Add support for parsers configuration for Hints Autodiscover

### ISSUE THREAD

**Issue by gizas** [elastic/elastic-agent#3102]
**Describe the enhancement:**

We need hint support for json and multiline parsers from annotations that defined from the users

**Describe a specific use case for the enhancement or feature:**

Agent configuration:

```yaml
      providers:
        - type: kubernetes
          node: ${NODE_NAME}
          hints.enabled: true
          hints.default_config:
            type: filestream
            prospector.scanner.symlinks: true
            id: filestream-kubernetes-pod-${data.kubernetes.container.id}
            take_over: true
            paths:
            - /var/log/containers/*-${data.kubernetes.container.id}.log
            parsers:
            - container: ~
```      

See above that type: filestream

The user will define in the pod:
```yaml
annotations:
        co.elastic.hints/json.add_error_key: "true"
        co.elastic.hints/json.expand_keys: "true"
        co.elastic.hints/json.ignore_decoding_error: "true"
        co.elastic.hints/json.keys_under_root: "true"
        co.elastic.hints/json.message_key: "message"
```

And those will produce the following block:

```yaml
parsers:
   - ndjson: 
         ignore_decoding_error: "true"
         expand_keys: "true"
         keys_under_root: "true"
         message_key: "message"
```

**What is the definition of done?**

- To support the list of parsers https://www.elastic.co/guide/en/beats/filebeat/master/filebeat-input-filestream.html#_parsers
- To provide examples of working parsers through annotations configuration and
- Update the relevant documentation

**Comment by gizas** [comment]
@cmacknz , @rdner (because you worked in filestream input in the past) I cc you here in order to investigate how we can update the parsers configuration from a given user's input. 

In beats we had the `co.elastic.logs/json` see https://www.elastic.co/guide/en/beats/filebeat/current/configuration-autodiscover-hints.html#_co_elastic_logsjson and we could configure the json log input.

But now in agent and filestream input we would like to offer the same flexibility to our users and through `co.elastic.hints/json` to configure the respective ndjson parser of filstream block.

For processors (see eg. https://github.com/elastic/elastic-agent/pull/3107/files#diff-ed933ad9cf09eb9ca797c5c89b5e8991624cbe5301d88f996d9bd947f4e3ea16R455) we have the relative map exposed and we can configure/ update the new list. I am struggling to find a way to see how I can edit parsers config. Any help here really appreciated

**Comment by cmacknz** [comment]
This is more of an agent composable provider question than a filestream question.

The `parsers` section goes at the root of the input configuration just like `processors`, so you can probably just clone or reuse the code that adds processors to add parsers. It should work exactly the same way, the name and options are just different. You will have to modify the code you linked.

**Comment by gizas** [comment]
@cmacknz thanks for looking into this. I was having a look into this today and I see that:
Initially (going from bottom to up), you need to modify the [AddOrUpdate function](https://github.com/elastic/elastic-agent/blob/main/internal/pkg/composable/controller.go#L358) and this leads me then to [transpiler](https://github.com/elastic/elastic-agent/blob/main/internal/pkg/agent/transpiler/ast.go#L90) . So I guess you mean to go up all this way :)

**Comment by gizas** [comment]
@cmacknz see my https://github.com/elastic/elastic-agent/commit/f7503fbcf84144f9510f91d20ca796d774697ccd initial effort. At least image builts but parsers are not passed at the moment to composable provider. If you can spot anything missing let me know.

**Comment by gizas** [comment]
@cmacknz one step at a time, I fixed some errors and now at least the functionality now is not broken, autodiscovery works.


1. The autodisovery reads the parsers that I provide with following `annotations`:
```yaml
annotations:
        co.elastic.hints/parsers.ndjson.add_error_key: 'false'
        co.elastic.hints/parsers.ndjson.message_key: "pas"
```

2. Then  `comm.AddOrUpdate` is called with correct data:
https://github.com/elastic/elastic-agent/commit/f7503fbcf84144f9510f91d20ca796d774697ccd#diff-ed933ad9cf09eb9ca797c5c89b5e8991624cbe5301d88f996d9bd947f4e3ea16L504

 
![Screenshot 2023-08-22 at 3 07 04 PM](https://github.com/elastic/elastic-agent/assets/1685415/03f0df21-f5ac-4272-b77e-8a73e130e474)


3. This leads to `/internal/pkg/compsable/controller.go` is called and the dynamicProvider object is passed: 
https://github.com/elastic/elastic-agent/blob/processor_parsers/internal/pkg/composable/controller.go#L397

4. This is the pod that is emmited finally: https://github.com/elastic/elastic-agent/blob/processor_parsers/internal/pkg/composable/providers/kubernetes/pod.go#L247 
![Screenshot 2023-08-22 at 5 26 28 PM](https://github.com/elastic/elastic-agent/assets/1685415/7ed07284-136d-4e49-9d3e-a6f60fd6317e)

5. Then this leads to https://github.com/elastic/elastic-agent-autodiscover/blob/main/kubernetes/watcher.go but from this point on I am loosing track. 

Summary is that the processors are being added from autodiscovery but not parsers. 
Full output for reference
```yaml
- data_stream.namespace: default
  id: hints-filestream-container-logs-62d546c0055ce651842f8ec7b3911439555a66aaf6b238f87e765917a90cef66-kubernetes-e36973fb-debd-4252-a402-f7b185ce286e.nginx
  name: hints-filestream-container-logs
  original_id: hints-filestream-container-logs-62d546c0055ce651842f8ec7b3911439555a66aaf6b238f87e765917a90cef66
  processors:
  - add_fields:
      fields:
        id: 62d546c0055ce651842f8ec7b3911439555a66aaf6b238f87e765917a90cef66
        image:
          name: nginx
        runtime: containerd
      target: container
  - add_fields:
      fields:
        container:
          name: nginx
        ....
  - add_fields:
      fields:
        cluster:
          name: kind
          url: kind-control-plane:6443
      target: orchestrator
  - add_fields:
      fields:
        name: myproject
      target: project
  - rename:
      fail_on_error: "false"
      fields:
        "0":
          from: message
        "1":
          to: pasole
  streams:
  - data_stream:
      dataset: kubernetes.container_logs
      type: logs
    parsers:
    - container:
        format: auto
        stream: all
    paths:
    - /var/log/containers/*62d546c0055ce651842f8ec7b3911439555a66aaf6b238f87e765917a90cef66.log
    prospector:
      scanner:
        symlinks: true
  type: filestream
  use_output: default
outputs:
  default:
    allow_older_versions: true
    hosts:
    - https://elasticsearch:9200
    password: changeme
    ssl:
      verification_mode: none
    type: elasticsearch
    username: elastic
providers:
  kubernetes:
    hints:
      default_container_logs: false
      enabled: true
    node: kind-control-plane
    scope: node
```

cc @ChrsMark for reference
