### ISSUE TITLE
Support flattened `data_stream` fields

### ISSUE THREAD

**Issue by belimawr** [elastic/elastic-agent#3191]
The Elastic-Agent supports flattened YAML keys in its configuration files (e.g: `agent.logging.level`) however the `data_stream` object in input configurations (both the input root and the `streams` array) do not recognise flattened `data_stream.*` keys.

The following does not work:
```yaml
inputs:
  - type: filestream
    id: unique-id-per-input
    data_stream.dataset: mystuff
    paths:
      - /var/log/my-file/my.log*
```

And this works:
```yaml
inputs:
  - type: filestream
    id: unique-id-per-input
    data_stream:
      dataset: mystuff
    paths:
      - /var/log/my-file/my.log*
```

Both notations should work.
