### ISSUE TITLE
[Fleet] Host goes offline and no able to enroll Endpoint integration after implementing some special character like €,Ø,Ę and many other.

### ISSUE THREAD

**Issue by harshitgupta-qasource** [elastic/elastic-agent#324]
**Description:**
  In Endpoint Security, Host goes offline after implementing some special character like €,Ø,Ę and many other are not accepted by Endpoint Policies.

**Build Details:**
```
Kibana VERSION: 8.2.0
BUILD: 51772
COMMIT: 3535a206838845689639344afaf64a58c663b3c1
```

**Browser Details:**
All

**Preconditions:**
1. Kibana user should be logged in.
2. Agent Should be Deployed.

**Steps to Reproduce:**
1. Navigate to Endpoint Tab from the left hand side navigation
2. Click on add Integration and Select Endpoint Security.
3. Configure integration and add integration name with special character like €,Ø,Ę.

**Impacted Test case:**
N/A

**Actual Result:**
  In Endpoint Security, Host goes offline and no able to enroll Endpoint integration after implementing some special character like €,Ø,Ę and many other.

**Expected Result:**
- In Endpoint Security, Host does'nt go offline after implementing some special character like €,Ø,Ę and many other are accepted by Endpoint Policies..

**What's working:**
N/A

**What's not working:**
N/A

**ScreenShots:**
![image](https://user-images.githubusercontent.com/101545338/162678251-06afbf52-b94e-41e4-9777-39da180eb13c.png)
![image](https://user-images.githubusercontent.com/101545338/162680317-9f5c14d7-56d5-4c30-9861-a094f0e471fe.png)

**Logs:**
-Agent Logs:
[Agent Logs.zip](https://github.com/elastic/kibana/files/8461493/Agent.Logs.zip)

-Endpoint Logs:
[Endpoint logs.zip](https://github.com/elastic/kibana/files/8461497/Endpoint.logs.zip)

**Comment by jlind23** [comment]
Thanks @jen-huang for the heads up.

**Comment by jlind23** [comment]
@harshitgupta-qasource I do not see any error messages in logs.
The only thing I found is a bad request:
> {"log.level":"error","@timestamp":"2022-04-11T05:40:27.348Z","log.origin":{"file.name":"fleet/fleet_gateway.go","file.line":206},"message":"Could not communicate with fleet-server Checking API will retry, error: status code: 400, fleet-server returned an error: BadRequest","ecs.version":"1.6.0"}

Could you please test it again and generate a diagnostic on the failing agent AND a diagnostic on the fleet server?

**Comment by ph** [comment]
@jen-huang The YAML configuration shared above was extracted from Fleet UI correctly?

```yaml
    _elastic_agent_checks:
      cluster:
        - monitor
    test€ing:
      indices:
        - names:
            - logs-windows.forwarded-default
          privileges:
            - auto_configure
            - create_doc
        - names:
            - logs-windows.powershell-default
          privileges:
            - auto_configure
```

Why we have `test€ing:` next to indices in the agent policy?
