### ISSUE TITLE
[Kubernetes Provider] Allow wildcards or regex when specifying "include_labels" and "include_annotations"

### ISSUE THREAD

**Issue by gizas** [elastic/elastic-agent#3346]
**Describe the enhancement:**

Currently the [Kubernetes Provider](https://www.elastic.co/guide/en/fleet/current/kubernetes-provider.html#_provider_configuration_2) includes the following config options: `include_annotations`, `include_labels`(and also `exclude_labels`) and allows users to optionally add to the provider config the list of annotations and labels present accordingly. 

Those config options does not support wild cards or regex expressions to dynamically configure the wanted list of annotations or labels. This enhancement request focuses to this functionality.

**Describe a specific use case for the enhancement or feature:**

Lets assume the following pod specification:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: demo
  labels:
    demo-1: production
    demo-2: nginx
```
The user would require to configure "include_labels": ["demo-1", "demo-2"] to match all labels
So the enhancement will allow "include_labels": "demo-*" to match all demo-1 and demo-2 labels of the example pod.

**What is the definition of done?**

- Implement the support of wildcards (or regex) for the `include_annotations`, `include_labels`and also `exclude_labels`
- Test and provide evidence for correct inclusion and exclusion 
- Document the new updates in the https://www.elastic.co/guide/en/fleet/current/kubernetes-provider.html#_provider_configuration_2 section

Relevant Links:
- [Config options of Kubernetes Provider](https://github.com/elastic/elastic-agent/blob/main/internal/pkg/composable/providers/kubernetes/config.go#L31C2-L33)
- [Relevant PR to add functionality in Kubernetes Processor](https://github.com/elastic/beats/pull/4043/files)

**Comment by gizas** [comment]
Added initial effort https://github.com/elastic/elastic-agent-autodiscover/compare/main...regexannotations

We will need to try testing this first effort

**Comment by gizas** [comment]
The PR for elastic-agent-autodiscovery library introduces the functionality. 

- We will need to merge the above PR and then run some manual tests with and updated elastic agent image. 
- Main question for @elastic/obs-cloudnative-monitoring team is whether we want to support regex expression for excluding libraries? 
- Documentation updates to be provided as DoD of this story

**Comment by ChrsMark** [comment]
> * Main question for @elastic/obs-cloudnative-monitoring team is whether we want to support regex expression for excluding libraries?

What kind of libraries? 🤔

**Comment by gizas** [comment]
> What kind of libraries? 🤔

:) Meant to write labels !!! Rephrased it

**Comment by gizas** [comment]
I have run the manual tests end-to-end and I can verify that by adding in state_pod

```yaml
add_resource_metadata:
  namespace:
    use_regex_inlcude: yes
    include_labels: ["kubernetes"]
```
And As you can see below we match only kubernetes* labels

![Screenshot 2023-10-18 at 11 28 11 AM](https://github.com/elastic/elastic-agent/assets/1685415/6ad2822c-53bb-4824-bbdb-6cdfe679d009)


But we hit the bug: https://github.com/elastic/elastic-agent/issues/3636

So we need to fix this bug before retesting this feature

**Comment by gizas** [comment]
The above #3636 has been fixed in https://github.com/elastic/beats/pull/37458, all agent versions with elastic-agent-autodiscovery library >= v0.6.6

I have resumed the tests for the regex support. The functionality is there 

![k8-labels-regex](https://github.com/elastic/elastic-agent/assets/1685415/fab8e445-d393-47a9-afab-6a0f43af42b6)



Draft Documentation RP: https://github.com/elastic/ingest-docs/pull/814

Still I see an issue with mix regex in both namespace and node:

Config:
```yaml
      add_resource_metadata:
        namespace:
          use_regex_include: true
          include_labels:
            - pas
        node:
          use_regex_include: true
          include_labels:
            - kubernetes
```

Output:

![combinationofregex](https://github.com/elastic/elastic-agent/assets/1685415/6aa92b36-c71e-4940-ae16-59aca0db28ed)
Only namespace is honoured. I will keep searching for this
