### ISSUE TITLE
The `agent.download.proxy_url` setting is ignored for Fleet managed agents while it works for standalone

### ISSUE THREAD

**Issue by cmacknz** [elastic/elastic-agent#3560]
Using a standalone agent if I set:

```yaml
agent.download:
#   # source of the artifacts, requires elastic like structure and naming of the binaries
#   # e.g /windows-x86.zip
  sourceURI: "https://artifacts.elastic.co/downloads/beats/"
  proxy_url: http://127.0.0.1:9000/
```

and then run:

`sudo elastic-agent upgrade 8.10.1`

I can see the agent  attempting to download from that location unsuccessfully as expected on my local machine:

```json
{"log.level":"warn","@timestamp":"2023-10-06T20:10:03.432Z","log.origin":{"file.name":"upgrade/step_download.go","file.line":184},"message":"unable to download package: 2 errors occurred:\n\t* package '/Library/Elastic/Agent/data/elastic-agent-471966/downloads/elastic-agent-8.10.1-darwin-aarch64.tar.gz' not found: open /Library/Elastic/Agent/data/elastic-agent-471966/downloads/elastic-agent-8.10.1-darwin-aarch64.tar.gz: no such file or directory\n\t* fetching package failed: Get \"https://artifacts.elastic.co/downloads/beats/beats/elastic-agent/elastic-agent-8.10.1-darwin-aarch64.tar.gz\": proxyconnect tcp: dial tcp 127.0.0.1:9000: connect: connection refused\n\n; retrying (will be retry 5381639) in 0s.","log":{"source":"elastic-agent"},"ecs.version":"1.6.0"}
```

However if I do this from Fleet using the overrides API it does not work. Note that we plan to officially support doing this as described in https://github.com/elastic/kibana/issues/162862

I add the override with:
```json
PUT kbn:/api/fleet/agent_policies/<policy_id>
{
   "name": "Test policy",
    "namespace": "default",
    "overrides": {
         "agent": {
              "download": {
                "proxy_url": "http://127.0.0.1:9000/"
              }
            }
    }
}
```

I confirm the override was applied correctly in the agent policy locally:

```yaml
sudo elastic-agent inspect
agent:
  download:
    proxy_url: http://127.0.0.1:9000
    sourceURI: https://artifacts.elastic.co/downloads/
  features: null
  headers: null
  id: c1124434-dfcc-45ce-b214-3e2e2b92e8c9
  logging:
    level: info
...
```

If I then initiate an upgrade from Fleet it succeeds and the `proxy_url` setting is ignored.
