### ISSUE TITLE
[Elastic Agent] Add conditional process "in" or "any"

### ISSUE THREAD

**Issue by a03nikki** [elastic/elastic-agent#3574]
**Describe the enhancement:**

Please add an "any" or "in" processor conditional.

**Describe a specific use case for the enhancement or feature:**

Currently the processor conditionals for both [Agent](https://www.elastic.co/guide/en/fleet/8.10/processor-syntax.html) and [Beats](https://www.elastic.co/guide/en/beats/winlogbeat/current/defining-processors.html) have `and`, `or`, and `equal`.  The original set of processors appear to be added by https://github.com/elastic/beats/issues/1447.  However, there is not an `any` or `in` conditional. 

For example, currently a list of values to check on a processor would be constructed as

```yaml
winlogbeat.event_logs:
  - name: Application
    ignore_older: 72h
    processors:
      - drop_event.when.or:
        - equals:
            winlog.event_id: 0 
        - equals:
            winlog.event_id: 1
        - equals:
            winlog.event_id: 2
        - equals:
            winlog.event_id: 3
```
and it would be more intuitive and easier to maintain if it could be added similar to this

```yaml
winlogbeat.event_logs:
  - name: Application
    ignore_older: 72h
    processors:
      - drop_event.when:
        - in:
          -  winlog.event_id: [0, 1, 2, 3]
```

or

```yaml
winlogbeat.event_logs:
  - name: Application
    ignore_older: 72h
    processors:
      - drop_event.when:
        - any:
          -  winlog.event_id: [0, 1, 2, 3]
```

**What is the definition of done?**

There exists an easier way to provide a list of values to match a particular field against.
