### ISSUE TITLE
Elastic Agent doesn't update the enrollment token in Kubernetes Deployment statefile

### ISSUE THREAD

**Issue by ch9hn** [elastic/elastic-agent#3586]
- Duplicates https://github.com/elastic/elastic-agent/issues/5187

When a new enrollment token is updated as env or envFrom in Kubernetes Manifest, this new token is not reflected in Elastic Agent.
Reason for that is probably the fact, that Elastic Agent saves the state locally on every Kubernetes Node and doesn't update the new token.
This leads to Unauthorised issues on the Agent - a redeploy with a new token is not possible anymore.

For confirmed bugs, please report:
- Version: 8.10
- Operating System: Ubuntu Linux / Kubernetes 1.27
- Discuss Forum URL: 

- Steps to Reproduce:

1. Install Elastic Agent on Kubernetes Cluster as described in the docs with enrollment-token "ABC"
2. Expire "ABC" and add new token "DEF" 
3. Restart Elastic Agent Daemonset
4. Result: Old token "ABC" is persisted and used for the communication to Elastic Fleet Server

Error logs:

`"Failed to connect to backoff(elasticsearch(https://xxxx.xxxx.cloud.es.io:443)): 401 Unauthorized: {\"error\":{\"root_cause\":[{\"type\":\"security_exception\",\"reason\":\"unable to authenticate with provided credentials and anonymous access is not allowed for this request\",\"additional_unsuccessful_credentials\":\"API key: api key [xxxxxxx] has been invalidated\",\"header\":{\"WWW-Authenticate\":[\"Basic realm=\\\"security\\\" charset=\\\"UTF-8\\\"\",\"Bearer`

How to temporary fix:
When using Kustomize deployment, the hostPath can be overwritten quite easily with the following DaemonSet overwrite:

```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: elastic-agent
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: elastic-agent
  template:
    metadata:
      labels:
        app: elastic-agent
    spec:
      containers:
        - name: elastic-agent
          env:
            - name: FLEET_URL
              $patch: delete
            - name: FLEET_ENROLLMENT_TOKEN
              $patch: delete
            - name: FLEET_INSECURE
              value: "false"
            - name: KIBANA_HOST
              $patch: delete
            - name: KIBANA_FLEET_USERNAME
              $patch: delete
            - name: KIBANA_FLEET_PASSWORD
              $patch: delete
          envFrom:
            - secretRef:
                name: elastic-agent-token
          volumeMounts:
            - name: elastic-agent-state
              mountPath: /usr/share/elastic-agent/state
      volumes:
        - name: elastic-agent-state
          hostPath:
# Change path here to your deployment namespace or use another name
            path: /var/lib/elastic-agent-managed/monitoring/state. 
            type: DirectoryOrCreate

```

**Comment by shubhu934** [comment]
Hello @elastic/elastic-agent Do we have any deadline for the fix of this issue ?

**Comment by HGS9761** [comment]
Hello 
I am affected by this bug and it is not a minor issue.
So this should have high priority.

**Comment by rafaelbattesti** [comment]
Hello folks.
I have come across this issue and reproduced with support.
This has consumed a few days digging into the root cause and I believe we should give this some attention.

**Comment by neu7ron2** [comment]
Thanks @ch9hn , I just spent a day trying to figure out why the Kubernetes elastic agents were working yesterday and not today after I updated the cluster. I uninstalled the agents and installed the previous version with no luck. I finally saw there were some files on the machine in /var/lib/elastic-agent-managed/kube-system/state. I realised the install manifest files had mounted and saved connections details.

Solution: I deleted the whole elastic-agent-managed folder on each machine and reinstalled the Kubernetes agent manifest file and it worked.

@elasticmachine  Elastic team please fix this basic bug!! hours wasted!

**Comment by badele** [comment]
After hours of investigating and reinstalling elastic-agent on kube, and understanding why I had this message "Failed to connect to backoff(elasticsearch(https://244b20202ef45ddb481e55df6b19f4.eu-west-3.aws.elastic-cloud.com:443"

I searched for this error message on the 'elastic-cloud' site but no document ...

On searching, I realized that something was stored persistently, so my suspicions fell on the `/usr/share/elastic-agent/state` directory.

Indeed, in the manifest generated by elastic-cloud, we can see that it mounts the directory of `/var/lib/elastic-agent-managed/kube-system/state` from a kube node

```yaml
        - name : elastic-agent-state
          hostPath :
            path : /var/lib/elastic-agent-managed/kube-system/state
            type : DirectoryOrCreate
```

Personally, I don't like the fact that they use the node's disk space to store persistence data. 

But here's my solution to correct the problem

```bash
for pod in $(kubectl -n kube-system get pod --no-headers -o custom-columns=":metadata.name" -l app=elastic-agent); do kubectl -n kube-system exec $pod -- rm -rf /usr/share/elastic-agent ; done
for pod in $(kubectl -n kube-system get pod --no-headers -o custom-columns=":metadata.name" -l app=elastic-agent); do ;  kubectl -n kube-system delete pods $pod ; done
```

**Comment by michel-laterman** [comment]
Quick recap of the discussion had surrounding this item from our weekly meeting:
- Default behaviour for agent on k8s will be to re-enroll if the enrollment token changes
  - we will store the enrolment token hash in local state to compare when value changes
- some flag/env var to disable this behaviour should be provided i.e. `ELASTIC_AGENT_AUTO_REENROLL`

**Comment by chrko** [comment]
Any updates on this especially regarding prio? We currently in discussion with our managed k8s cluster operator team so that they implement a small operator (taking the fleet url and the enrollment token) as the actual cluster users is not allowed to run any kind privileged pods on their own. Before figuring out workarounds which have only a minimal impact e.g. on shipping logs / log duplication, I would like clarify if and how we can maybe prioritize this upstream or maybe also can contribute.

**Comment by mag-mkorn** [comment]
Another workaround that persists the registry to prevent log duplication:

```
<...>
          volumeMounts:
            - name: elastic-agent-state
              mountPath: /usr/share/elastic-agent/state/data
<...>
      volumes:
        - name: elastic-agent-state
          hostPath:
            path: /var/lib/elastic-agent-managed/monitoring/state/data
            type: DirectoryOrCreate
<...>
```
