### ISSUE TITLE
Include_labels option in add_resource_metadata not working as expected

### ISSUE THREAD

**Issue by gizas** [elastic/elastic-agent#3636]
**Description:**
According to [documentation](https://www.elastic.co/guide/en/beats/filebeat/current/add-kubernetes-metadata.html
) users can configure `include_labels` option to specify and filter  the labels being ingested.

The include_labels option can be configured under namespace and node resources, implying that users can configure seperately the labels they want per kind of resource

See eg. 
```yaml
add_resource_metadata:
        namespace:
          include_labels: ["namespacelabel1"]
          #labels.dedot: true
          #annotations.dedot: true
        node:
          include_labels: ["nodelabel2"]
         ....
```

But the configuration of include_labels under namespace leads to node labels being lost.
All versions of 8.10.2 and above have been verified that showcase above functionality.

**Details:**

- Version of Elastic Agent: [8.10.2](https://github.com/elastic/elastic-agent/blob/1320210da633a0e00da6f5301fcc39c6de29bca8/version/version.go)
- Version of elastic-agent-autodiscover: v0.6.2[https://github.com/elastic/elastic-agent/blob/1320210da633a0e00da6f5301fcc39c6de29bca8/go.mod#L16]  

Steps to reproduce:
1. Install Elastic Stack 8.10.2
2. Install a Kubernetes Integration Policy with Kube-state-metrics datastreams enabled
3. Add a label to your namespace:
```bash
kubectl label namespace kube-system katsoulis=pasole

kubectl  describe namespace kube-system
Name:         kube-system
Labels:       katsoulis=pasole
              kubernetes-1=pasole
              kubernetes.io/metadata.name=kube-system
```

5. With the default configuration you will notice that all namespace and node labels are being collected
![all_labels](https://github.com/elastic/elastic-agent/assets/1685415/c9e201a9-3bb1-47a2-a655-f24e0bdd050e)

6. Edit the advanced options of state_pod dataset inside your Kubernetes Integration Policy
![add_resource](https://github.com/elastic/elastic-agent/assets/1685415/011d6dcc-2997-4430-9688-5e25fbd79c7b)

7. You will notice that include_labels condition applies to both nodes and namespace metadata, resulting to node labels being lost
![filter](https://github.com/elastic/elastic-agent/assets/1685415/c1393973-57c4-452f-88fe-4375946be8c8)

**Comment by gizas** [comment]
cc @bturquet for prioritisation

**Comment by tetianakravchenko** [comment]
some findings:
I've tested it with simple metricbeat configuration - only 1 metricset (`pod`), such as:
```
    - module: kubernetes
      add_metadata: true
      add_resource_metadata:
        namespace:
          include_labels: ["labelName"]
      metricsets:
        - pod
....
```
Already after the config unpacking - [UnpackConfig](https://github.com/elastic/beats/blob/8.9/metricbeat/module/kubernetes/util/kubernetes.go#L508) the configuration is wrong - `Node` part contains the `include_labels` (`Namespace` as well):
<img width="2349" alt="Screenshot 2023-11-23 at 17 27 15" src="https://github.com/elastic/elastic-agent/assets/28299531/405a2d7f-a230-429f-861e-dc5c4b09307e">

`UnpackConfig` calls the `Unpack` on the [rawConfig](https://github.com/elastic/beats/blob/8.9/metricbeat/mb/mb.go#L96) - which is correct, then is called [`Unpack` from the go-ucfg lib ](https://github.com/elastic/go-ucfg/blob/main/reify.go#L137)
 
This issue exists starting from the 17.17.7 (the version it was backported to - relevant [PR](https://github.com/elastic/beats/pull/33165)). Seems that https://github.com/elastic/beats/pull/29133 was not working as expected at least for the k8s module, will check it also for the add_kubernetes_metadata processor and the kubernetes provider

**Comment by tetianakravchenko** [comment]
configuration `add_resource_metadata` 
1. k8s module - from the time it was introduced this was never working as expected.
2. `add_kubernetes_metadata` processor.
tested filebeat with:
```
processors:
        - add_kubernetes_metadata:
            add_resource_metadata:
              namespace:
                include_labels: ["labelName"]
            host: ${NODE_NAME}
            matchers:
            - logs_path:
                logs_path: "/var/log/containers/"
```

In https://github.com/elastic/beats/pull/29133/files was removed ..., in https://github.com/elastic/beats/pull/29329/files `AddResourceMetadata` was added to the default config.

So before the changes above, configuration contained only the values defined in the customer config, default values are not defined:
<img width="2227" alt="Screenshot 2023-12-04 at 22 01 37" src="https://github.com/elastic/elastic-agent/assets/28299531/4a5fe60a-ae09-4f34-913a-239cdd3e21f2">
 
After the changes above - default values are initialized
<img width="2063" alt="Screenshot 2023-12-04 at 22 56 51" src="https://github.com/elastic/elastic-agent/assets/28299531/a919ee80-54a1-43cf-9e1e-6d6b1c6587eb">

and merged during the unpacking in https://github.com/elastic/go-ucfg/blob/main/reify.go#L434 

Seems there is some issue during the merging.
I think the right approach would be to check the merge issue, or other option - use the `replace` merge strategie

3. autodiscover - TODO
