### ISSUE TITLE
Windows: `install` on system with previous uninstalled agent fails with `missing field accessing 'outputs'`

### ISSUE THREAD

**Issue by fearful-symmetry** [elastic/elastic-agent#3672]
Version: 8.10.2/8.11

## Steps to reproduce

1. Install agent 8.10.2 on a system and enroll in fleet
2. Upgrade to 8.11
3. Uninstall via `elastic-agent.exe uninstall`
4. Attempt to install 8.10.2 again in standalone mode with `elastic-agent.yml` provided by the fleet standalone UI
5. Install fails with `Error: failed to uninstall Agent at (C:\Program Files\Elastic): missing field accessing 'outputs'`

Still investigating. The provided yml file you get from fleet has an `outputs` section, which makes me think that it's trying to do something weird with the uninstalled version.

**Comment by cmacknz** [comment]
What is the policy that is failing so this can be reproduced (with the API key redacted)?

**Comment by fearful-symmetry** [comment]
```
id: c058bde0-74e8-11ee-9df2-e7e881d7c634
revision: 1
outputs:
  default:
    type: elasticsearch
    hosts:
      - >-
        https://9d01fefb90e6479ab5de77908b91fd7a.eu-west-1.aws.qa.cld.elstc.co:443
    username: '${ES_USERNAME}'
    password: '${ES_PASSWORD}'
output_permissions:
  default:
    _elastic_agent_monitoring:
      indices:
        - names:
            - logs-elastic_agent.apm_server-default
          privileges: &ref_0
            - auto_configure
            - create_doc
        - names:
            - metrics-elastic_agent.apm_server-default
          privileges: *ref_0
        - names:
            - logs-elastic_agent.auditbeat-default
          privileges: *ref_0
        - names:
            - metrics-elastic_agent.auditbeat-default
          privileges: *ref_0
        - names:
            - logs-elastic_agent.cloud_defend-default
          privileges: *ref_0
        - names:
            - logs-elastic_agent.cloudbeat-default
          privileges: *ref_0
        - names:
            - metrics-elastic_agent.cloudbeat-default
          privileges: *ref_0
        - names:
            - logs-elastic_agent-default
          privileges: *ref_0
        - names:
            - metrics-elastic_agent.elastic_agent-default
          privileges: *ref_0
        - names:
            - metrics-elastic_agent.endpoint_security-default
          privileges: *ref_0
        - names:
            - logs-elastic_agent.endpoint_security-default
          privileges: *ref_0
        - names:
            - logs-elastic_agent.filebeat_input-default
          privileges: *ref_0
        - names:
            - metrics-elastic_agent.filebeat_input-default
          privileges: *ref_0
        - names:
            - logs-elastic_agent.filebeat-default
          privileges: *ref_0
        - names:
            - metrics-elastic_agent.filebeat-default
          privileges: *ref_0
        - names:
            - logs-elastic_agent.fleet_server-default
          privileges: *ref_0
        - names:
            - metrics-elastic_agent.fleet_server-default
          privileges: *ref_0
        - names:
            - logs-elastic_agent.heartbeat-default
          privileges: *ref_0
        - names:
            - metrics-elastic_agent.heartbeat-default
          privileges: *ref_0
        - names:
            - logs-elastic_agent.metricbeat-default
          privileges: *ref_0
        - names:
            - metrics-elastic_agent.metricbeat-default
          privileges: *ref_0
        - names:
            - logs-elastic_agent.osquerybeat-default
          privileges: *ref_0
        - names:
            - metrics-elastic_agent.osquerybeat-default
          privileges: *ref_0
        - names:
            - logs-elastic_agent.packetbeat-default
          privileges: *ref_0
        - names:
            - metrics-elastic_agent.packetbeat-default
          privileges: *ref_0
    _elastic_agent_checks:
      cluster:
        - monitor
    54fd44c8-2dfe-49ca-85da-e296ec2e5f02:
      indices:
        - names:
            - logs-system.auth-default
          privileges: *ref_0
        - names:
            - logs-system.syslog-default
          privileges: *ref_0
        - names:
            - logs-system.application-default
          privileges: *ref_0
        - names:
            - logs-system.security-default
          privileges: *ref_0
        - names:
            - logs-system.system-default
          privileges: *ref_0
        - names:
            - metrics-system.cpu-default
          privileges: *ref_0
        - names:
            - metrics-system.diskio-default
          privileges: *ref_0
        - names:
            - metrics-system.filesystem-default
          privileges: *ref_0
        - names:
            - metrics-system.fsstat-default
          privileges: *ref_0
        - names:
            - metrics-system.load-default
          privileges: *ref_0
        - names:
            - metrics-system.memory-default
          privileges: *ref_0
        - names:
            - metrics-system.network-default
          privileges: *ref_0
        - names:
            - metrics-system.process-default
          privileges: *ref_0
        - names:
            - metrics-system.process.summary-default
          privileges: *ref_0
        - names:
            - metrics-system.socket_summary-default
          privileges: *ref_0
        - names:
            - metrics-system.uptime-default
          privileges: *ref_0
agent:
  download:
    sourceURI: 'https://artifacts.elastic.co/downloads/'
  monitoring:
    enabled: true
    use_output: default
    namespace: default
    logs: true
    metrics: true
  features: {}
  protection:
    enabled: false
    uninstall_token_hash: D7SJZFB0AoCRp93WGCeC3oxqiEjFTBqIzMlB4NoYmgk=
    signing_key: >-
inputs:
  - id: logfile-system-54fd44c8-2dfe-49ca-85da-e296ec2e5f02
    name: system-1
    revision: 1
    type: logfile
    use_output: default
    meta:
      package:
        name: system
        version: 1.47.0
    data_stream:
      namespace: default
    package_policy_id: 54fd44c8-2dfe-49ca-85da-e296ec2e5f02
    streams:
      - id: logfile-system.auth-54fd44c8-2dfe-49ca-85da-e296ec2e5f02
        data_stream:
          dataset: system.auth
          type: logs
        ignore_older: 72h
        paths:
          - /var/log/auth.log*
          - /var/log/secure*
        exclude_files:
          - .gz$
        multiline:
          pattern: ^\s
          match: after
        tags:
          - system-auth
        processors:
          - add_locale: null
          - rename:
              fields:
                - from: message
                  to: event.original
              ignore_missing: true
              fail_on_error: false
          - syslog:
              field: event.original
              ignore_missing: true
              ignore_failure: true
      - id: logfile-system.syslog-54fd44c8-2dfe-49ca-85da-e296ec2e5f02
        data_stream:
          dataset: system.syslog
          type: logs
        paths:
          - /var/log/messages*
          - /var/log/syslog*
          - /var/log/system*
        exclude_files:
          - .gz$
        multiline:
          pattern: ^\s
          match: after
        processors:
          - add_locale: null
        ignore_older: 72h
  - id: winlog-system-54fd44c8-2dfe-49ca-85da-e296ec2e5f02
    name: system-1
    revision: 1
    type: winlog
    use_output: default
    meta:
      package:
        name: system
        version: 1.47.0
    data_stream:
      namespace: default
    package_policy_id: 54fd44c8-2dfe-49ca-85da-e296ec2e5f02
    streams:
      - id: winlog-system.application-54fd44c8-2dfe-49ca-85da-e296ec2e5f02
        name: Application
        data_stream:
          dataset: system.application
          type: logs
        condition: '${host.platform} == ''windows'''
        ignore_older: 72h
      - id: winlog-system.security-54fd44c8-2dfe-49ca-85da-e296ec2e5f02
        name: Security
        data_stream:
          dataset: system.security
          type: logs
        condition: '${host.platform} == ''windows'''
        ignore_older: 72h
      - id: winlog-system.system-54fd44c8-2dfe-49ca-85da-e296ec2e5f02
        name: System
        data_stream:
          dataset: system.system
          type: logs
        condition: '${host.platform} == ''windows'''
        ignore_older: 72h
  - id: system/metrics-system-54fd44c8-2dfe-49ca-85da-e296ec2e5f02
    name: system-1
    revision: 1
    type: system/metrics
    use_output: default
    meta:
      package:
        name: system
        version: 1.47.0
    data_stream:
      namespace: default
    package_policy_id: 54fd44c8-2dfe-49ca-85da-e296ec2e5f02
    streams:
      - id: system/metrics-system.cpu-54fd44c8-2dfe-49ca-85da-e296ec2e5f02
        data_stream:
          dataset: system.cpu
          type: metrics
        metricsets:
          - cpu
        cpu.metrics:
          - percentages
          - normalized_percentages
        period: 10s
      - id: system/metrics-system.diskio-54fd44c8-2dfe-49ca-85da-e296ec2e5f02
        data_stream:
          dataset: system.diskio
          type: metrics
        metricsets:
          - diskio
        diskio.include_devices: null
        period: 10s
      - id: system/metrics-system.filesystem-54fd44c8-2dfe-49ca-85da-e296ec2e5f02
        data_stream:
          dataset: system.filesystem
          type: metrics
        metricsets:
          - filesystem
        period: 1m
        processors:
          - drop_event.when.regexp:
              system.filesystem.mount_point: ^/(sys|cgroup|proc|dev|etc|host|lib|snap)($|/)
      - id: system/metrics-system.fsstat-54fd44c8-2dfe-49ca-85da-e296ec2e5f02
        data_stream:
          dataset: system.fsstat
          type: metrics
        metricsets:
          - fsstat
        period: 1m
        processors:
          - drop_event.when.regexp:
              system.fsstat.mount_point: ^/(sys|cgroup|proc|dev|etc|host|lib|snap)($|/)
      - id: system/metrics-system.load-54fd44c8-2dfe-49ca-85da-e296ec2e5f02
        data_stream:
          dataset: system.load
          type: metrics
        metricsets:
          - load
        condition: '${host.platform} != ''windows'''
        period: 10s
      - id: system/metrics-system.memory-54fd44c8-2dfe-49ca-85da-e296ec2e5f02
        data_stream:
          dataset: system.memory
          type: metrics
        metricsets:
          - memory
        period: 10s
      - id: system/metrics-system.network-54fd44c8-2dfe-49ca-85da-e296ec2e5f02
        data_stream:
          dataset: system.network
          type: metrics
        metricsets:
          - network
        period: 10s
        network.interfaces: null
      - id: system/metrics-system.process-54fd44c8-2dfe-49ca-85da-e296ec2e5f02
        data_stream:
          dataset: system.process
          type: metrics
        metricsets:
          - process
        period: 10s
        process.include_top_n.by_cpu: 5
        process.include_top_n.by_memory: 5
        process.cmdline.cache.enabled: true
        process.cgroups.enabled: false
        process.include_cpu_ticks: false
        processes:
          - .*
      - id: >-
          system/metrics-system.process.summary-54fd44c8-2dfe-49ca-85da-e296ec2e5f02
        data_stream:
          dataset: system.process.summary
          type: metrics
        metricsets:
          - process_summary
        period: 10s
      - id: >-
          system/metrics-system.socket_summary-54fd44c8-2dfe-49ca-85da-e296ec2e5f02
        data_stream:
          dataset: system.socket_summary
          type: metrics
        metricsets:
          - socket_summary
        period: 10s
      - id: system/metrics-system.uptime-54fd44c8-2dfe-49ca-85da-e296ec2e5f02
        data_stream:
          dataset: system.uptime
          type: metrics
        metricsets:
          - uptime
        period: 10s
signed:
  data: >-
     
  signature: >-
    
secret_references: []
```

My theory is that it's improperly detecting that agent is still installed, although not sure why.
