### ISSUE TITLE
Dynamic configuration of prometheus.collector input may cause metadata confusion

### ISSUE THREAD

**Issue by neiljbrookes** [elastic/elastic-agent#3692]
When using the kubernetes provider it is possible to auto-discover pods that may expose a prometheus endpoint that you'd like to collect with the `prometheus.collector`. In this case, a unique input can be generated for each pod/endpoint. Each pod can have the host and period configured as labels/annotations etc.

Given that the `add_metadata: true` is enabled  this can cause confusion with the `add_fields` that are in the configuration blocks generated for each input.

eg
```
- id: prometheus/metrics-prometheus-${kubernetes.pod.name}-${kubernetes.container.id}
        type: prometheus/metrics
        use_output: default
        streams:
          - id: prometheus-metrics-prometheus-${kubernetes.pod.name}-${kubernetes.container.id}
            condition: ${kubernetes.labels.co.elastic.hints/package} == "prometheus"
            data_stream:
              dataset: prometheus.collector
              namespace: ${kubernetes.labels.app.kubernetes.io/name|'default'}
              type: metrics
            hosts:
              - http://${kubernetes.pod.ip}:${kubernetes.labels.co.elastic.hints/port|'8080'}
            metrics_filters.exclude: null
            metrics_filters.include: null
            metrics_path: /metrics
            metricsets:
              - collector
            period: ${kubernetes.labels.co.elastic.hints/period|'10s'}
            rate_counters: true
            use_types: true
```
