### ISSUE TITLE
[Windows integration] Perfmon dataset: `staging_space_in_use` tops out at 32-bit INT_MAX

### ISSUE THREAD

**Issue by ycombinator** [elastic/elastic-agent#3749]
For confirmed bugs, please report:
- Version: 8.9.2
- Operating System: Windows

The `windows.perfmon.metrics.staging_space_in_use` field seems to top out at `2147483647`, which corresponds to the largest signed integer on 32-bit systems (`2^31-1`).  Therefore, for systems that report larger values, the dataset reports incorrect data.

**Comment by ycombinator** [comment]
Is the fix for this issue simply for users to specify `format: large` for the `staging_space_in_use` field in the dataset's configuration?  For example:

```yaml
metricsets:
    - perfmon
perfmon.queries:
    - counters:
      - field: staging_space_in_use
        format: long
        name: Staging Space In Use
```
