### ISSUE TITLE
[doc] document how to run elastic-agent as a sidecar in ECK

### ISSUE THREAD

**Issue by leehinman** [elastic/elastic-agent#3775]
**Describe the enhancement:**

Document how to run elastic-agent as a sidecar in ECK

**Describe a specific use case for the enhancement or feature:**

- air gapped environments

**What is the definition of done?**

External facing documentation exists that can be given to customers

**Comment by gizas** [comment]
For sidecar containers the initial doc of reference is https://kubernetes.io/blog/2023/08/25/native-sidecar-containers/

Currently we deploy agents as a [daemonsets](https://github.com/elastic/elastic-agent/blob/main/deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml#L667) and perform [leader election](https://github.com/elastic/elastic-agent/blob/main/deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml#L32) in order only one agent to collect cluster wide metrics. 

So with sidecar installation we should introduce the 

```yaml
spec:
      containers:
      - name: app1
        image: test:v1
        command: ['sh', '-c', 'echo test']
        volumeMounts:
          - name: data
            mountPath: /opt
      - name: elastic-agent-standalone
        docker.elastic.co/beats/elastic-agent:8.12.0
          args: ["-c", "/etc/elastic-agent/agent.yml", "-e"]
          env:
           ...
        volumeMounts:
         ....
```
(We should include all the info from [manifest](https://github.com/elastic/elastic-agent/blob/main/deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml#L705-L837) in the elastic-agent container part)

There are some initial considerations:
- How we should define the initial deployment/ pod that we are going to inject the elastic-agent container part
- If Cluster-wide metrics are going to be supported with sidecar containers? Maybe a solution here is to inject specific elastic-agent for this seperate to rest of metrics. So are we going to have two groups of side-containers one for logs and metrics for pods and one for cluster wide metrics?
- Also there are performance considerations for using elastic-agent as a sidecar. According to [doc](https://kubernetes.io/blog/2023/08/25/native-sidecar-containers/) `The CPU, memory, device, and topology manager are unaware of the sidecar container lifetime and additional resource usage, and will operate as if the Pod had lower resource requests than it actually does.` This means that probably the initial resource (pod, deployment etc that will define the sidecar container) should reassure enough resources for elastic-agent. This is one of the main points referred to our discussion in slack. This needs thorough testing
- The timing for when the sidecar container starts, comparing to other containers in same pod, can not assured. This means that if we see scenarios that elastic-agent should have eg. some specific mount points ready in advance we should consider initcontainers or some delay times to start
