### ISSUE TITLE
Validate and sanitization of dataset and namespace field

### ISSUE THREAD

**Issue by ruflin** [elastic/elastic-agent#3946]
The fields for the [data stream naming scheme](https://www.elastic.co/guide/en/ecs/master/ecs-data_stream.html) have rules around what chars are valid. One of the goals it so make sure a pattern like `logs-*-*` always applies to the right dataset and namespace. Recently, some configs in helm charts were found that look as following:

```
        streams:
          - id: container-log-${kubernetes.pod.name}-${kubernetes.container.id}
            data_stream:
              dataset: ${kubernetes.labels.app.kubernetes.io/name|'container_logs'}.log
              type: logs
```

This is a valid configuration. But as it turns out, the `name` above can be for example `foo-bar`. This means the value for `data_stream.dataset` becomes `foo-bar`. But for processors like reroute that match on the data stream name with the pattern `logs-*-*`, `foo` is assumed to be the dataset, `bar` and everything afterwards the namespace.

In the context of the reroute processor, these fields are [sanitized](https://github.com/elastic/elasticsearch/blob/c628d1256047d770291609bfbed1fdbfcf87bacb/modules/ingest-common/src/main/java/org/elasticsearch/ingest/common/RerouteProcessor.java#L222-L2299). Unfortunately Elastic Agent (Beats) doesn't do this today but should.

Unfortunately turning on sanitization directly could be considered a breaking change as now suddenly `foo-bar` would become `foo_bar`. At the same time, it is important for the system to function that the values are always the same.

Some ideas for migration users is to at least start logging errors (once) and inform users if this happens and later turn it on by default (with an opt out option).

@axw This might also be relevant in the context of ingesting otel data.
