### ISSUE TITLE
[Self-Managed]: No data for Standalone agent available when configured with logstash output

### ISSUE THREAD

**Issue by harshitgupta-qasource** [elastic/elastic-agent#3959]
**Kibana Build details:**
```
VERSION: 8.12.0 BC3
BUILD: 69985
COMMIT: 2a8afed8572a4c709aa1c64216748197eeb9b18f
```
**Host OS and Browser version:** All, All
**Preconditions:**
1. 8.12.0 Kibana self-managed environment should be available.
2. Logstash should be configured with certs.

**Steps to reproduce:**

1. Navigate to Agent policies.
2. Set output for integrations as Logstash.
3. Install standalone agent using this agent policy.
4. Observe no data for Standalone agent available under Data Streams tab.

**Expected:**
Data for Standalone agent should be available when configured with logstash output

**Screen Shot:**
![image](https://github.com/elastic/elastic-agent/assets/101545338/095bfbe9-b9d4-4e92-846d-34d7c48997e2)

**Logs**
[elastic-agent-diagnostics-2023-12-26T06-20-50Z-00.zip](https://github.com/elastic/elastic-agent/files/13769580/elastic-agent-diagnostics-2023-12-26T06-20-50Z-00.zip)

**Comment by harshitgupta-qasource** [comment]
@amolnater-qasource Kindly review

**Comment by amolnater-qasource** [comment]
Secondary Review for this ticket is Done.

**Comment by cmacknz** [comment]
There is an error in the output configuration:

```yaml
        units:
            input-log-1d4167d9-c043-40c4-97dd-6ac75c2c6a13-logfile-nginx-a7b51d40-b086-41f0-8d65-f43f24abc846:
                message: Starting
                state: 0
            input-log-1d4167d9-c043-40c4-97dd-6ac75c2c6a13-logfile-system-9997e7d1-bb8e-4799-9361-1678ea5e53c1:
                message: Starting
                state: 0
            output-log-1d4167d9-c043-40c4-97dd-6ac75c2c6a13:
                message: 'could not start output: failed to reload output: could not setup output certificates reloader: unpacking ''ssl'' config: key file not configured accessing ''logstash.ssl'''
                state: 4
```

Looks like https://www.elastic.co/guide/en/beats/filebeat/current/configuration-ssl.html#client-key is missing.

How to create it is documented in https://www.elastic.co/guide/en/fleet/current/secure-logstash-connections.html
