### ISSUE TITLE
Properly support disabling providers and changing init time settings in containers

### ISSUE THREAD

**Issue by cmacknz** [elastic/elastic-agent#4145]
Recently there have been several situations where users have needed to disable the leader election provider. Providers in agent cannot be configured in Fleet today, but even if they were they require a restart of the agent to take effect, which also isn't supported through Fleet. The providers are initialized when the composable controller is created at startup:

https://github.com/elastic/elastic-agent/blob/9d25f79b159744801daefca36ae227674e28d920/internal/pkg/composable/controller.go#L52-L71

It is possible to disable providers by editing the elastic-agent.yml file read by the agent container when it starts, which on Kubernetes is most easily accomplished by mounting the file as a ConfigMap. Essentially the process is:
1. Mount the elastic-agent.yml as a ConfigMap in the container.
2. Mount the ConfigMap as a volume
3. Ensure the agent is configured to read the configuration file mounted from that volume.
4. Mounting the ConfigMap as a volume creates a bind mount inside the container, which has the effect that the agent's attempt to overwrite the initial configuration on enrollment fails (because the bind mount is essentially a different file system and we can't move the file) and the flag disabling the providers is preserved. 
5. The enrollment API key and agent ID are stored in the state path which is usually stored on a host path volume, so subsequent restarts of the pod do not attempt to re-enroll and skip over trying to replace the contents of the ConfigMap. This work around does not work if you do not preserve the state path between restarts of the container.

A simplified example follows:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: agent-yml
  namespace: kube-system
  labels:
    app: elastic-agent
data:
  agent.yml: |-
    providers.kubernetes_leaderelection.enabled: false
    fleet.enabled: true
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: elastic-agent
  # ...
spec:
   # ...
    spec:
      containers:
        - name: elastic-agent
          image: docker.elastic.co/beats/elastic-agent:8.12.0
          args: ["-c", "/etc/elastic-agent/agent.yml", "-e"]
          volumeMounts:
            - name: agent-yml
              mountPath: /etc/elastic-agent/agent.yml
              readOnly: true
              subPath: agent.yml
      volumes:
        - name: agent-yml
          configMap:
            defaultMode: 416
            name: agent-yml
```

The problem we hit is that we try to unconditionally replace the local agent configuration (in this case a bind mounted ConfigMap) with [our default Fleet configuration](https://github.com/elastic/elastic-agent/blob/9d25f79b159744801daefca36ae227674e28d920/_meta/elastic-agent.fleet.yml#L1-L7). This is just an empty configuration that sets `fleet.enabled: true`:

We unconditionally try to rotate the file during enrollment, which happens every time the agent container starts when the state path isn't persisted outside of the container file system. This happens in: https://github.com/elastic/elastic-agent/blob/9d25f79b159744801daefca36ae227674e28d920/internal/pkg/agent/cmd/enroll_cmd.go#L173-L178

The code path that does this continues with the `SafeFileRotate` rotate call, which is what fails for the bind mounted ConfigMap: https://github.com/elastic/elastic-agent/blob/9d25f79b159744801daefca36ae227674e28d920/internal/pkg/agent/storage/replace_store.go#L59-L75) 

What we could do is change this to only attempt to replace the file if it doesn't already contain `fleet.enabled: true` (or any other key that isn't commented out in our default fleet configuration).

This would allow overriding the initial contents of the elastic-agent.yml contents in a container in general, regardless of if those settings are available in Fleet.

In the case of providers, even if we did allow disabling leaderelection in the UI it would still be enabled until the agent receives the first policy change from Fleet, so disabling it in the initial configuration like this is likely the preferred route.
