### ISSUE TITLE
[Elastic Agent] Define the syntaxt for processors that would add fields via agent policy

### ISSUE THREAD

**Issue by nimarezainia** [elastic/elastic-agent#4211]
place holder for Agent effort in support of the meta issue linked. All details are in the meta issue.

**Comment by nimarezainia** [comment]
The definition is in the meta issue.

**Comment by cmacknz** [comment]
Referencing the comment from: https://github.com/elastic/elastic-agent/issues/3651#issuecomment-1845418810 on which syntax to use, I think we should just allow the Beats `add_fields` processors in the agent policy. This will be more flexible, and sets us up to support more Beats processors in the future if that becomes important. It also avoids the work of adding a new syntax.

```yaml
processors:
   - add_fields:
      # Beats processor syntax
      fields:
        name: value
inputs:
  - ...
outputs:
  - ...
```

We are already going to have the problem of figuring out how to map Beats processors to OTel as that support comes in, this is not adding a new problem to the system and lets users immediately use the syntax they already use in integrations elsewhere.

**Comment by cmacknz** [comment]
@nimarezainia and I spoke and agreed on the above, we'll add a top level `processors` block for global processors and use the Beats processor syntax in it. The only processor we'll support initially is `add_fields`.

**Comment by nimarezainia** [comment]
@cmacknz additional thought after speaking with @strawgate; could we not just use the processors that exists today in the input section? and manage this all in the fleet when the policy is built. That would also mean no agent work is required for this feature.  In the future this will change to use the OTEL processor.

what do you think?

**Comment by cmacknz** [comment]
That works for Beat inputs with no work, we'd need to confirm the other input types can handle having a `processors` block inserted into their input configuration without issue.

Besides that implementation detail, +1 from to solve this without changing agent or Beats at all.

**Comment by nimarezainia** [comment]
@nfritts we need to ensure that Defend can support what is being [suggested](https://github.com/elastic/elastic-agent/issues/4211#issuecomment-2012846168) particularly if the processor is moved under the input section. Many of the users asking for this are Defend users. Currently doesn't seem as though input processors are exposed to the users. (fyi @caitlinbetz @roxana-gheorghe )

@axw & @florianl I am not sure if this is a concern or an ask from apm-server or profiling users. If there are no user requirements here perhaps what I am asking is a moot point but Similarly  are the processor to add fields supported on the input for your beats? (fyi @simitt )

@eyalkraft @tinnytintin10 @nick-alayil Please let us know if this feature is a requirement for our Cloud security products. and whether the `add_filed` processor is supported by the input you own.

@cmacknz did I miss any?

**Comment by nimarezainia** [comment]
> That works for Beat inputs, we'd need to confirm the other input types can handle having a `processors` block inserted into their input configuration without issue.
> 
> Besides that implementation detail, +1 from to solve this without changing agent or Beats at all.

obviously we would prefer consistency across the board. For now I would suggest we take the path forward and use the input side processor to achieve this which means the work is offloaded from the Agent team and it becomes just a Fleet effort. We will document in product where the tags won't be applied. 

cc: @strawgate

**Comment by axw** [comment]
> @axw & @florianl I am not sure if this is a concern or an ask from apm-server or profiling users. If there are no user requirements here perhaps what I am asking is a moot point but Similarly are the processor to add fields supported on the input for your beats? (fyi @simitt )

apm-server [does not support beats processors](https://github.com/elastic/apm-server/blob/0fbdcc37266e3f6a4388427f309edc1fcbcc86e8/internal/beatcmd/config.go#L120).

**Comment by nfritts** [comment]
@nimarezainia we'll just need more info about the syntax and what it will look like and this should be doable.  Its going to take us a bit more dev time as we will have to do our own implementation of it and validate it matches the output of agent/beats.

**Comment by cmacknz** [comment]
@nimarezainia's proposal is that when a user configures a global [add fields](https://www.elastic.co/guide/en/beats/filebeat/current/add-fields.html) processor, Fleet creates a `processors` key at the root of the input or streams configuration if it doesn't already exist, and then appends the user defined processor to it. 

For Beats this works out of the box with zero changes, that is already how changes are configured.

```yaml
inputs:
- data_stream:
    namespace: default
  id: logfile-system-2c017117-46ea-44ce-9d4b-3414748c7ce2
  meta:
    package:
      name: system
      version: 1.54.0
  package_policy_id: 2c017117-46ea-44ce-9d4b-3414748c7ce2
  streams:
  - data_stream:
      dataset: system.auth
      type: logs
    id: logfile-system.auth-2c017117-46ea-44ce-9d4b-3414748c7ce2
    paths:
    - /var/log/auth.log*
    - /var/log/secure*
    processors: # <--- Already supported
      - add_fields:
          target: tenant
          fields:
            name: mytenant
            id: '574734885120952459'
```


For Endpoint (and others), the change would add a `processors` list at the root of the configuration:

```yaml
inputs:
- data_stream:
    namespace: workstation
    id: 12fc63d1-7fb6-11ee-b0ea-6becf025f1ed
    meta:
    package:
    name: endpoint
    version: 8.12.0
    package_policy_id: 12fc63d1-7fb6-11ee-b0ea-6becf025f1ed
    artifacts:
      # ...
    policy:
      # ...
    revision: 80
    type: endpoint
    processors: # <--- This is new
      - add_fields:
          target: project
          fields:
            name: myproject
            id: '574734885120952459'
```

For inputs that do not implement this, they can either ignore it, or perhaps we can maintain a list of excluded packages in Fleet and the UI can both skip doing this for those packages and inform the user they were excluded.
