### ISSUE TITLE
[Self-Managed]: No system integration data for secondary agent installed on self-managed 8.13.0.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/elastic-agent#4291]
**Kibana Build details:**
```
VERSION: 8.13.0
BUILD: 71738
COMMIT: b036a9705a55f6c81d065011ad8c991cbc3101d9
Artifact Link: https://staging.elastic.co/8.13.0-4304292e/summary-8.13.0.html
```

**Host OS:**  Windows- self-managed, Linux secondary agent

**Preconditions:**
1. 8.13.0-BC1 Kibana cloud environment should be available.
2. 8.13.0- Fleet Server should be installed

**Steps to reproduce:**
1. Install secondary agent on 8.13.0-self managed environment.
2. Observe few data for 8.13.0 under Data Streams tab.
3. Observe no data for System integration.

**Screen Recording:**

https://github.com/elastic/elastic-agent/assets/77374876/8c9a386e-24db-42ff-82c4-c9ee3c81c250

**Expected Result:**
System integration data should be available for secondary agent installed on self-managed 8.13.0.

**Logs:**
[elastic-agent-diagnostics-2024-02-20T11-39-45Z-00.zip](https://github.com/elastic/elastic-agent/files/14343932/elastic-agent-diagnostics-2024-02-20T11-39-45Z-00.zip)

**Comment by amolnater-qasource** [comment]
@manishgupta-qasource Please review.

**Comment by manishgupta-qasource** [comment]
Secondary review for this ticket is Done

**Comment by cmacknz** [comment]
There are no inputs in the agent policy:

```yaml
agent:
    download:
        sourceURI: https://artifacts.elastic.co/downloads/
    features: null
    monitoring:
        enabled: true
        logs: true
        metrics: true
        namespace: agent
        use_output: default
    protection:
        enabled: false
        signing_key: <REDACTED>
        uninstall_token_hash: <REDACTED>
fleet:
    hosts:
        - https://ec2-54-234-236-16.compute-1.amazonaws.com:8220
host:
    id: c083c82af2fe42ff8b8d4e1e93a4e604
id: 33a65a41-50a2-4d13-b211-730758430ca5
outputs:
    default:
        api_key: <REDACTED>
        hosts:
            - https://172.31.29.80:9200
        preset: balanced
        ssl:
            ca_trusted_fingerprint: <REDACTED>
        type: elasticsearch
path:
    config: /opt/Elastic/Agent
    data: /opt/Elastic/Agent/data
    home: /opt/Elastic/Agent/data/elastic-agent-8.13.0-d2c0b8
    logs: /opt/Elastic/Agent
revision: 1
runtime:
    arch: amd64
    native_arch: ""
    os: linux
    osinfo:
        family: suse
        major: 15
        minor: 0
        patch: 0
        type: linux
        version: 15-SP5
signed:
    data: eyJpZCI6IjMzYTY1YTQxLTUwYTItNGQxMy1iMjExLTczMDc1ODQzMGNhNSIsImFnZW50Ijp7ImZlYXR1cmVzIjp7fSwicHJvdGVjdGlvbiI6eyJlbmFibGVkIjpmYWxzZSwidW5pbnN0YWxsX3Rva2VuX2hhc2giOiJyRDZSWGtveUZIZ2s5TktpbzUvUTMzTXZ2ZENQL1VOQlRSRjRIYS9BTHFJPSIsInNpZ25pbmdfa2V5IjoiTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFK1gwWk1yVWRqUy9WMzNvWnJqQnA5YVNOWFRQZkRFdnVhSUxwY0ltYSsvYlpqWDNMOWJ0SzRhVmI2ZG5sU2Rrc09SZkR3WitlZjlUYjJmUldtalBNb1E9PSJ9fSwiaW5wdXRzIjpbXX0=
    signature: MEUCIQD6l5wP2yomZuUe8Jh06h35X3oV+XfJpCPto5WovevasQIgc9dI0UdRh8znkDIqGQ49YRMqwgGZ/ztWKBb5fhlTDiw=
```

I don't see a policy change action in the logs. I think I saw something similar earlier with an agent I deployed locally but it wasn't always reproducable. Transferring to Fleet since I think the agent is sitting here waiting for a policy change to happen.

I see the SETTINGS action changing the log level was received fairly early so we must have been able to check in at least once after being enrolled.

```json
{"log.level":"debug","@timestamp":"2024-02-20T11:38:14.027Z","log.origin":{"file.name":"dispatcher/dispatcher.go","file.line":163},"message":"Successfully dispatched action: 'action_id: c47fcf6f-a413-4adf-9f2d-b7f577e7ddf9, type: SETTINGS, log_level: debug'","log":{"source":"elastic-agent"},"ecs.version":"1.6.0"}
```
