### ISSUE TITLE
Changing output results in reindexing local data

### ISSUE THREAD

**Issue by smnschneider** [elastic/elastic-agent#4553]
When changing the output of an existing policy, somehow the Agent looses his registry and reindexes all the data that he can find locally. In my opinion this should not be the case.

For example when you have some kind of migration ongoing this can be become a problem.

For confirmed bugs, please report:
- Version: 8.6.1, 8.13.2
- Operating System: Windows Server 2019
- Steps to Reproduce:

1. Create a new policy
2. Add Custom Log integration
```
id: 867568e6-ab4e-4ed0-a09a-f1b067a5db23
revision: 4
outputs:
  0eab054c-8d7a-493e-bce0-b9b9c0f5c035:
    type: elasticsearch
    ssl.verification_mode: none
    hosts:
      - 'https://7ccd59b5c7cd463bbc4d7b6ae01075e9.10.10.157.215.ip.es.io:9243'
    preset: balanced
fleet:
  hosts:
    - 'https://5b311424202a4893aae0849ee0c0b3ef.fleet.10.10.157.215.ip.es.io:9243'
output_permissions:
  0eab054c-8d7a-493e-bce0-b9b9c0f5c035:
    _elastic_agent_monitoring:
      indices:
        - names:
            - logs-elastic_agent.apm_server-default
          privileges:
            - auto_configure
            - create_doc
        - names:
            - metrics-elastic_agent.apm_server-default
          privileges:
            - auto_configure
            - create_doc
        - names:
            - logs-elastic_agent.auditbeat-default
          privileges:
            - auto_configure
            - create_doc
        - names:
            - metrics-elastic_agent.auditbeat-default
          privileges:
            - auto_configure
            - create_doc
        - names:
            - logs-elastic_agent.cloud_defend-default
          privileges:
            - auto_configure
            - create_doc
        - names:
            - logs-elastic_agent.cloudbeat-default
          privileges:
            - auto_configure
            - create_doc
        - names:
            - metrics-elastic_agent.cloudbeat-default
          privileges:
            - auto_configure
            - create_doc
        - names:
            - logs-elastic_agent-default
          privileges:
            - auto_configure
            - create_doc
        - names:
            - metrics-elastic_agent.elastic_agent-default
          privileges:
            - auto_configure
            - create_doc
        - names:
            - metrics-elastic_agent.endpoint_security-default
          privileges:
            - auto_configure
            - create_doc
        - names:
            - logs-elastic_agent.endpoint_security-default
          privileges:
            - auto_configure
            - create_doc
        - names:
            - logs-elastic_agent.filebeat_input-default
          privileges:
            - auto_configure
            - create_doc
        - names:
            - metrics-elastic_agent.filebeat_input-default
          privileges:
            - auto_configure
            - create_doc
        - names:
            - logs-elastic_agent.filebeat-default
          privileges:
            - auto_configure
            - create_doc
        - names:
            - metrics-elastic_agent.filebeat-default
          privileges:
            - auto_configure
            - create_doc
        - names:
            - logs-elastic_agent.fleet_server-default
          privileges:
            - auto_configure
            - create_doc
        - names:
            - metrics-elastic_agent.fleet_server-default
          privileges:
            - auto_configure
            - create_doc
        - names:
            - logs-elastic_agent.heartbeat-default
          privileges:
            - auto_configure
            - create_doc
        - names:
            - metrics-elastic_agent.heartbeat-default
          privileges:
            - auto_configure
            - create_doc
        - names:
            - logs-elastic_agent.metricbeat-default
          privileges:
            - auto_configure
            - create_doc
        - names:
            - metrics-elastic_agent.metricbeat-default
          privileges:
            - auto_configure
            - create_doc
        - names:
            - logs-elastic_agent.osquerybeat-default
          privileges:
            - auto_configure
            - create_doc
        - names:
            - metrics-elastic_agent.osquerybeat-default
          privileges:
            - auto_configure
            - create_doc
        - names:
            - logs-elastic_agent.packetbeat-default
          privileges:
            - auto_configure
            - create_doc
        - names:
            - metrics-elastic_agent.packetbeat-default
          privileges:
            - auto_configure
            - create_doc
        - names:
            - logs-elastic_agent.pf_elastic_collector-default
          privileges:
            - auto_configure
            - create_doc
        - names:
            - logs-elastic_agent.pf_elastic_symbolizer-default
          privileges:
            - auto_configure
            - create_doc
        - names:
            - logs-elastic_agent.pf_host_agent-default
          privileges:
            - auto_configure
            - create_doc
    _elastic_agent_checks:
      cluster:
        - monitor
    b1435e8c-3249-4a16-92cc-000e3eef9789:
      indices:
        - names:
            - logs-system.auth-default
          privileges:
            - auto_configure
            - create_doc
        - names:
            - logs-system.syslog-default
          privileges:
            - auto_configure
            - create_doc
        - names:
            - logs-system.application-default
          privileges:
            - auto_configure
            - create_doc
        - names:
            - logs-system.security-default
          privileges:
            - auto_configure
            - create_doc
        - names:
            - logs-system.system-default
          privileges:
            - auto_configure
            - create_doc
        - names:
            - metrics-system.cpu-default
          privileges:
            - auto_configure
            - create_doc
        - names:
            - metrics-system.diskio-default
          privileges:
            - auto_configure
            - create_doc
        - names:
            - metrics-system.filesystem-default
          privileges:
            - auto_configure
            - create_doc
        - names:
            - metrics-system.fsstat-default
          privileges:
            - auto_configure
            - create_doc
        - names:
            - metrics-system.load-default
          privileges:
            - auto_configure
            - create_doc
        - names:
            - metrics-system.memory-default
          privileges:
            - auto_configure
            - create_doc
        - names:
            - metrics-system.network-default
          privileges:
            - auto_configure
            - create_doc
        - names:
            - metrics-system.process-default
          privileges:
            - auto_configure
            - create_doc
        - names:
            - metrics-system.process.summary-default
          privileges:
            - auto_configure
            - create_doc
        - names:
            - metrics-system.socket_summary-default
          privileges:
            - auto_configure
            - create_doc
        - names:
            - metrics-system.uptime-default
          privileges:
            - auto_configure
            - create_doc
    9eb43d78-b9d2-4851-a31f-8016b73e2ac2:
      indices:
        - names:
            - logs-*-*
          privileges:
            - auto_configure
            - create_doc
agent:
  download:
    sourceURI: 'https://artifacts.elastic.co/downloads/'
  monitoring:
    enabled: true
    use_output: 0eab054c-8d7a-493e-bce0-b9b9c0f5c035
    namespace: default
    logs: true
    metrics: true
  features: {}
  protection:
    enabled: false
    uninstall_token_hash: lHLO5sPcL1CdLEDaVATI3A8sSXzLDli9/7IbgkPdDac=
    signing_key: >-
      MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAELP/GMaUMnXp8pP/Q7h58f5eMgscoflFVPOF08IjBHLSBEgEsH8edHWQ6ETLjh98QcymClX511tdYo48XwXH7uw==
inputs:
  - id: logfile-system-b1435e8c-3249-4a16-92cc-000e3eef9789
    name: system-13
    revision: 1
    type: logfile
    use_output: 0eab054c-8d7a-493e-bce0-b9b9c0f5c035
    meta:
      package:
        name: system
        version: 1.54.0
    data_stream:
      namespace: default
    package_policy_id: b1435e8c-3249-4a16-92cc-000e3eef9789
    streams:
      - id: logfile-system.auth-b1435e8c-3249-4a16-92cc-000e3eef9789
        data_stream:
          dataset: system.auth
          type: logs
        ignore_older: 72h
        paths:
          - /var/log/auth.log*
          - /var/log/secure*
        exclude_files:
          - \.gz$
        multiline:
          pattern: ^\s
          match: after
        tags:
          - system-auth
        processors:
          - add_locale: null
          - rename:
              fields:
                - from: message
                  to: event.original
              ignore_missing: true
              fail_on_error: false
          - syslog:
              field: event.original
              ignore_missing: true
              ignore_failure: true
      - id: logfile-system.syslog-b1435e8c-3249-4a16-92cc-000e3eef9789
        data_stream:
          dataset: system.syslog
          type: logs
        paths:
          - /var/log/messages*
          - /var/log/syslog*
          - /var/log/system*
        exclude_files:
          - \.gz$
        multiline:
          pattern: ^\s
          match: after
        processors:
          - add_locale: null
        tags: null
        ignore_older: 72h
  - id: winlog-system-b1435e8c-3249-4a16-92cc-000e3eef9789
    name: system-13
    revision: 1
    type: winlog
    use_output: 0eab054c-8d7a-493e-bce0-b9b9c0f5c035
    meta:
      package:
        name: system
        version: 1.54.0
    data_stream:
      namespace: default
    package_policy_id: b1435e8c-3249-4a16-92cc-000e3eef9789
    streams:
      - id: winlog-system.application-b1435e8c-3249-4a16-92cc-000e3eef9789
        name: Application
        data_stream:
          dataset: system.application
          type: logs
        condition: '${host.platform} == ''windows'''
        ignore_older: 72h
      - id: winlog-system.security-b1435e8c-3249-4a16-92cc-000e3eef9789
        name: Security
        data_stream:
          dataset: system.security
          type: logs
        condition: '${host.platform} == ''windows'''
        ignore_older: 72h
      - id: winlog-system.system-b1435e8c-3249-4a16-92cc-000e3eef9789
        name: System
        data_stream:
          dataset: system.system
          type: logs
        condition: '${host.platform} == ''windows'''
        ignore_older: 72h
  - id: system/metrics-system-b1435e8c-3249-4a16-92cc-000e3eef9789
    name: system-13
    revision: 1
    type: system/metrics
    use_output: 0eab054c-8d7a-493e-bce0-b9b9c0f5c035
    meta:
      package:
        name: system
        version: 1.54.0
    data_stream:
      namespace: default
    package_policy_id: b1435e8c-3249-4a16-92cc-000e3eef9789
    streams:
      - id: system/metrics-system.cpu-b1435e8c-3249-4a16-92cc-000e3eef9789
        data_stream:
          dataset: system.cpu
          type: metrics
        metricsets:
          - cpu
        cpu.metrics:
          - percentages
          - normalized_percentages
        period: 10s
      - id: system/metrics-system.diskio-b1435e8c-3249-4a16-92cc-000e3eef9789
        data_stream:
          dataset: system.diskio
          type: metrics
        metricsets:
          - diskio
        diskio.include_devices: null
        period: 10s
      - id: system/metrics-system.filesystem-b1435e8c-3249-4a16-92cc-000e3eef9789
        data_stream:
          dataset: system.filesystem
          type: metrics
        metricsets:
          - filesystem
        period: 1m
        processors:
          - drop_event.when.regexp:
              system.filesystem.mount_point: ^/(sys|cgroup|proc|dev|etc|host|lib|snap)($|/)
      - id: system/metrics-system.fsstat-b1435e8c-3249-4a16-92cc-000e3eef9789
        data_stream:
          dataset: system.fsstat
          type: metrics
        metricsets:
          - fsstat
        period: 1m
        processors:
          - drop_event.when.regexp:
              system.fsstat.mount_point: ^/(sys|cgroup|proc|dev|etc|host|lib|snap)($|/)
      - id: system/metrics-system.load-b1435e8c-3249-4a16-92cc-000e3eef9789
        data_stream:
          dataset: system.load
          type: metrics
        metricsets:
          - load
        condition: '${host.platform} != ''windows'''
        period: 10s
      - id: system/metrics-system.memory-b1435e8c-3249-4a16-92cc-000e3eef9789
        data_stream:
          dataset: system.memory
          type: metrics
        metricsets:
          - memory
        period: 10s
      - id: system/metrics-system.network-b1435e8c-3249-4a16-92cc-000e3eef9789
        data_stream:
          dataset: system.network
          type: metrics
        metricsets:
          - network
        period: 10s
        network.interfaces: null
      - id: system/metrics-system.process-b1435e8c-3249-4a16-92cc-000e3eef9789
        data_stream:
          dataset: system.process
          type: metrics
        metricsets:
          - process
        period: 10s
        process.include_top_n.by_cpu: 5
        process.include_top_n.by_memory: 5
        process.cmdline.cache.enabled: true
        process.cgroups.enabled: false
        process.include_cpu_ticks: false
        processes:
          - .*
      - id: >-
          system/metrics-system.process.summary-b1435e8c-3249-4a16-92cc-000e3eef9789
        data_stream:
          dataset: system.process.summary
          type: metrics
        metricsets:
          - process_summary
        period: 10s
      - id: >-
          system/metrics-system.socket_summary-b1435e8c-3249-4a16-92cc-000e3eef9789
        data_stream:
          dataset: system.socket_summary
          type: metrics
        metricsets:
          - socket_summary
        period: 10s
      - id: system/metrics-system.uptime-b1435e8c-3249-4a16-92cc-000e3eef9789
        data_stream:
          dataset: system.uptime
          type: metrics
        metricsets:
          - uptime
        period: 10s
  - id: logfile-logs-9eb43d78-b9d2-4851-a31f-8016b73e2ac2
    name: log-3
    revision: 1
    type: logfile
    use_output: 0eab054c-8d7a-493e-bce0-b9b9c0f5c035
    meta:
      package:
        name: log
        version: 2.3.1
    data_stream:
      namespace: default
    package_policy_id: 9eb43d78-b9d2-4851-a31f-8016b73e2ac2
    streams:
      - id: logfile-log.logs-9eb43d78-b9d2-4851-a31f-8016b73e2ac2
        data_stream:
          dataset: generic2
        paths:
          - 'c:\tmp\test.txt'
        ignore_older: 72h
signed:
  data: >-
    eyJpZCI6Ijg2NzU2OGU2LWFiNGUtNGVkMC1hMDlhLWYxYjA2N2E1ZGIyMyIsImFnZW50Ijp7ImZlYXR1cmVzIjp7fSwicHJvdGVjdGlvbiI6eyJlbmFibGVkIjpmYWxzZSwidW5pbnN0YWxsX3Rva2VuX2hhc2giOiJsSExPNXNQY0wxQ2RMRURhVkFUSTNBOHNTWHpMRGxpOS83SWJna1BkRGFjPSIsInNpZ25pbmdfa2V5IjoiTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFTFAvR01hVU1uWHA4cFAvUTdoNThmNWVNZ3Njb2ZsRlZQT0YwOElqQkhMU0JFZ0VzSDhlZEhXUTZFVExqaDk4UWN5bUNsWDUxMXRkWW80OFh3WEg3dXc9PSJ9fSwiaW5wdXRzIjpbeyJpZCI6ImxvZ2ZpbGUtc3lzdGVtLWIxNDM1ZThjLTMyNDktNGExNi05MmNjLTAwMGUzZWVmOTc4OSIsIm5hbWUiOiJzeXN0ZW0tMTMiLCJyZXZpc2lvbiI6MSwidHlwZSI6ImxvZ2ZpbGUifSx7ImlkIjoid2lubG9nLXN5c3RlbS1iMTQzNWU4Yy0zMjQ5LTRhMTYtOTJjYy0wMDBlM2VlZjk3ODkiLCJuYW1lIjoic3lzdGVtLTEzIiwicmV2aXNpb24iOjEsInR5cGUiOiJ3aW5sb2cifSx7ImlkIjoic3lzdGVtL21ldHJpY3Mtc3lzdGVtLWIxNDM1ZThjLTMyNDktNGExNi05MmNjLTAwMGUzZWVmOTc4OSIsIm5hbWUiOiJzeXN0ZW0tMTMiLCJyZXZpc2lvbiI6MSwidHlwZSI6InN5c3RlbS9tZXRyaWNzIn0seyJpZCI6ImxvZ2ZpbGUtbG9ncy05ZWI0M2Q3OC1iOWQyLTQ4NTEtYTMxZi04MDE2YjczZTJhYzIiLCJuYW1lIjoibG9nLTMiLCJyZXZpc2lvbiI6MSwidHlwZSI6ImxvZ2ZpbGUifV19
  signature: >-
    MEUCIQCZXcEV15ooh6MCvtuNL4hWWHnMmiTGHYm37BCtK9U5bgIgbAwwLPsZeri/KVLTGU8DYLkGba8294A+tmxTu0N+QKk=
secret_references: []
```

5. Ingest some data from disk. I used a small textfile.
6. Create a second Output in Fleet Settings. Can be the same destination.
![image](https://github.com/elastic/elastic-agent/assets/95302847/99e2571c-1949-4f48-ac01-6da9073205a9)

7. Change output of Agent Policy to second one.
![image](https://github.com/elastic/elastic-agent/assets/95302847/72818ea0-a3f8-45b8-8422-3d99758c60e9)

8. Check Discover and find duplicated events
![image](https://github.com/elastic/elastic-agent/assets/95302847/401be151-d4d6-452c-81e5-18bba5d87653)
