### ISSUE TITLE
[Fleet] The agent upgrade download timeout should be configurable.

### ISSUE THREAD

**Issue by cmacknz** [elastic/elastic-agent#4580]
In https://github.com/elastic/elastic-agent/pull/1666 we increased the default agent upgrade artifact download timeout from 10 minutes to 2 hours. This was done because we were observing upgrade attempts that time out due to poor network conditions.

I recently observed a failed upgrade attempt from a connection with a download speed as low as 33.74kBps. With a 274.9MB download size this would take 274.9MB / 33.74kBps = 138 minutes = 2 hours 18 minutes to complete. At this speed the increased 2 hour limit is still not enough.

```json
{
    "agent": {
      "version": "8.6.1"
    },
    "message": "download progress from https://artifacts.elastic.co/downloads/beats/elastic-agent/elastic-agent-8.7.1-windows-x86_64.zip is 1.012MB/274.9MB (0.37% complete) @ 33.74kBps",
    "@timestamp": "2023-05-09T18:15:10.070Z"
}
{
    "agent": {
      "version": "8.6.1"
    },
    "message": "download from https://artifacts.elastic.co/downloads/beats/elastic-agent/elastic-agent-8.7.1-windows-x86_64.zip failed at 39.19MB/274.9MB (14.26% complete) @ 65.43kBps: net/http: request canceled (Client.Timeout or context cancellation while reading body)",
    "@timestamp": "2023-05-09T17:21:40.219Z"
}
```

For a standalone agent the upgrade download timeout can be controlled with the `agent.download.timeout` parameter: https://github.com/elastic/elastic-agent/blob/29bf0ab601895fc498abf8724fc1918783956de5/elastic-agent.reference.yml#L70-L77

```yaml
agent.download:
  # source of the artifacts, requires elastic like structure and naming of the binaries
  # e.g /windows-x86.zip
  sourceURI: "https://artifacts.elastic.co/downloads/beats/"
  # path to the directory containing downloaded packages
  target_directory: "${path.data}/downloads"
  # timeout for downloading package
  timeout: 120s
```

For Fleet managed agents we should allow configuring the download timeout to use. It is not possible for us to know what the download timeout for a particular network should be, and we should make sure users with poor connections that are slightly over the limit to adjust this easily.

I suggest adding the download timeout under the existing Agent Binary Download Settings configuration:

<img width="1277" alt="Screen Shot 2023-05-10 at 3 37 21 PM" src="https://github.com/elastic/kibana/assets/3466215/030f60b1-5641-415a-90e7-b64528dae4e2">
