### ISSUE TITLE
Elastic:agent Allow disabling add_x_metadata default global processors

### ISSUE THREAD

**Issue by gizas** [elastic/elastic-agent#4670]
Edited by @cmacknz to generalize to all add_x_metadata processors and include the suggested approach from https://github.com/elastic/elastic-agent/issues/4670

**Describe the enhancement:**

The default set of processors for each Beat, when they are started by agent, is defined in the code and is not configurable. Here is the definition for [Metricbeat](https://github.com/elastic/beats/blob/main/x-pack/metricbeat/cmd/root.go#L74-L78). Same default config stands for rest of beats.

For example the `add_kubernetes_metadata` processor is used to enrich kubernetes events with extra metadata fields. This results in the number of k8s API calls being proportional to the number of inputs in the agent policy. In this case the same functionality is also present through `enrichers` and start by default in code of beats as described [here-see enrichers](https://github.com/elastic/beats/blob/main/metricbeat/module/kubernetes/pod/pod.go#L104).

This enhancement will allow disabling or configuring any of the default beat global processors. This will be done by defining a new type of [provider](https://www.elastic.co/guide/en/fleet/current/providers.html) , an event_data provider, which controls the behavior of the event metadata processors added by each beat.

We will additionally expose the entire contents of the [providers](https://www.elastic.co/guide/en/fleet/current/providers.html) section of the agent policy in Fleet to allow configuring this. Here is a sample of the intended configuration:

```yaml
providers:
     event_metadata:
         # The default value would be true to avoid a breaking change when they aren't specified.
         host: # controls add_host_metadata
             enabled: true
         kubernetes: # controls add_kubernetes_metadata
             enabled: false
         cloud: # controls add_cloud_metadata
             enabled: true
         docker: # controls add_docker_metadata 
             enabled: false
```

**Describe a specific use case for the enhancement or feature:**

All the elastic-agent Kubernetes deployments experience the default enablement of processor in the background, which can be "expensive" (as far as extra memory and number of API calls) that the agent has to do, especially in big Kubernetes deployments

## Related Issues:
- https://github.com/elastic/integrations/issues/8176
- https://github.com/elastic/sdh-beats/issues/3863

## Definition of Done:
- Allow disabling the add_kubernetes_metadata processor for all Beats run by Elastic Agent.
- Provide tests that showcase the same functionality and enrichment with/without processor enabled
- Demonstrate the event metadata processors can be disabled from Fleet.
- Document the new functionality
