### ISSUE TITLE
Add per-platform sample OTel configurations

### ISSUE THREAD

**Issue by strawgate** [elastic/elastic-agent#4785]
We should include a folder in the Agent distribution called something like `otel_samples` or similiar that contains per-platform use-case based configurations.

Each config should have a name and there should be a readme which indicates what each config is used for.

During onboarding we will provide installation instructions that copy the chosen use-case-specific config out of the samples folder, replace otel.yml with it, and populate it with keys/endpoints:
```
curl --proto '=https' --tlsv1.2 -fOL https://snapshots.elastic.co/8.14.0-6b2f3648/downloads/beats/elastic-agent/elastic-agent-8.14.0-SNAPSHOT-darwin-x86_64.tar.gz
tar -xvf elastic-agent-8.13.4-darwin-x86_64.tar.gz
rm elastic-agent-8.13.4-darwin-x86_64/otel.yml && cp elastic-agent-8.13.4-darwin-x86_64/otel_templates/logs_hostmetrics.yaml elastic-agent-8.13.4-darwin-x86_64/otel.yml
sed -i '' 's/<<ES_ENDPOINT>>/'$elasticsearch_url'/g' elastic-agent-8.13.4-darwin-x86_64/otel.yml && sed -i '' 's/<<ES_API_KEY>>/'$api_key'/g' elastic-agent-8.13.4-darwin-x86_64/otel.yml

elastic-agent-8.13.4-darwin-x86_64/elastic-agent otel
```

Here are two examples of macOS sample configurations. I have not tested these and we should assume these will need to be updated and that we will need to provide platform specific working configurations.

**Logs and Host Metrics**
```
receivers:

  # Receiver for platform specific log files
  filelog/platformlogs:
    include: [ /var/log/*.log ]
#    start_at: beginning

  # Receiver for CPU, Disk, Memory, and Filesystem metrics
  hostmetrics/system:
    collection_interval: 30s
    scrapers:
      disk:
      filesystem:
      cpu:
      memory:

processors:
  elasticinframetrics:

exporters:

  elasticsearch/bulk:
    endpoints: [<<ES_ENDPOINT>>]
    api_key: <<ES_API_KEY>>
    logs_index: logs-generic-default
    metrics_index: metrics-generic-default

service:
  pipelines:
    metrics/hostmetrics:
      receivers: [hostmetrics/system]
      processors: [elasticinframetrics]
      exporters: [elasticsearch/bulk]

    logs/platformlogs:
      receivers: [filelog/platformlogs]
      processors: []
      exporters: [elasticsearch/bulk]

```

**Logs, metrics, and traces**:
```
receivers:

  # Receiver for platform specific log files
  filelog/platformlogs:
    include: [ /var/log/*.log ]
#    start_at: beginning

  # Receiver for CPU, Disk, Memory, and Filesystem metrics
  hostmetrics/system:
    collection_interval: 30s
    scrapers:
      disk:
      filesystem:
      cpu:
      memory:

  # Receiver for logs, traces, and metrics from SDKs
  otlp/fromsdk:
    protocols:
      grpc:
      http:

processors:
  elasticinframetrics:

exporters:

  otlp/apm:
    endpoint: <<APM_ENDPOINT>>
    headers:
    # Elastic APM Server secret token or API key
      Authorization: "Bearer <<APM_SECRET_KEY>>"

  elasticsearch/bulk:
    endpoints: [<<ES_ENDPOINT>>]
    api_key: <<ES_API_KEY>>
    logs_index: logs-generic-default
    metrics_index: metrics-generic-default

service:
  pipelines:
    traces/fromsdk:
      receivers: [otlp/fromsdk]
      processors: []
      exporters: [otlp/apm]

    metrics/fromsdk:
      receivers: [otlp/fromsdk]
      processors: []
      exporters: [otlp/apm]

    metrics/hostmetrics:
      receivers: [hostmetrics/system]
      processors: [elasticinframetrics]
      exporters: [elasticsearch/bulk]

    logs/fromsdk:
      receivers: [otlp/fromsdk]
      processors: []
      exporters: [otlp/apm]

    logs/platformlogs:
      receivers: [filelog/platformlogs]
      processors: []
      exporters: [elasticsearch/bulk]
```
