### ISSUE TITLE
[MAC aarch64]: Endpoint doesn't get updated on Assigning agent to new policy with Defend integration.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/elastic-agent#5089]
**Kibana Build details:**
```
VERSION: 8.15.0 BC1
BUILD: 76008
COMMIT: c616ed3da09e04c766be0d791373dc78c1231e12
```

Artifact Link: https://staging.elastic.co/8.15.0-c7717606/downloads/beats/elastic-agent/elastic-agent-8.15.0-darwin-aarch64.tar.gz  

**Preconditions:**
1. 8.15.0 BC1 Kibana cloud environment should be available.
2. MAC aarch64 agent should be installed with Elastic Defend integration.

**Steps to reproduce:**
1. Navigate to Agents tab.
2. Assign agent to different policy having Elastic Defend integration.
3. Observe MAC endpoint didn't get update and remains Out of date for over 10 minutes under Endpoints tab.
4. Further observe Endpoint folder gets removed from installation directory.

**Expected Result:**
Endpoint should get updated on Assigning agent to new policy with Defend integration.

**NOTE:**
- Issue is not observed on any other platforms.

**Screenshot:**
![1](https://github.com/elastic/elastic-agent/assets/77374876/dbb6316f-2130-431b-b200-2be0779701cf)
![2](https://github.com/elastic/elastic-agent/assets/77374876/cb1238c5-c284-4eee-91e5-6019ae360651)

**Agent Logs:**
[elastic-agent-diagnostics-2024-07-09T11-26-41Z-00.zip](https://github.com/user-attachments/files/16142705/elastic-agent-diagnostics-2024-07-09T11-26-41Z-00.zip)

**New policy:**
[elastic-agent (1).zip](https://github.com/user-attachments/files/16142743/elastic-agent.1.zip)

**Comment by amolnater-qasource** [comment]
@manishgupta-qasource Please review.

**Comment by intxgo** [comment]
Looks like Agent bug. I can see Agent successfully installing Endpoint, then detecting error on the bootstrap pipe and uninstalling Endpoint. I'm not sure if the bootstrap pipe "error" was the reason of Endpoint removal, we can see "endpoint service has checked in, send stopping state to service" so those services did connected to each over on the bootstrap pipe.

```
{"log.level":"error","@timestamp":"2024-07-09T11:15:47.300Z","log.logger":"component.runtime.endpoint-default.service_runtime","log.origin":{"function":"github.com/elastic/elastic-agent/pkg/component/runtime.executeCommand.func2","file.name":"runtime/service_command.go","file.line":69},"message":"2024-07-09 11:15:47: info: Exec.cpp:1177 Successfully ran /bin/launchctl load -w /Library/LaunchDaemons/co.elastic.endpoint.plist","context":"command output","ecs.version":"1.6.0"}

{"log.level":"error","@timestamp":"2024-07-09T11:17:43.731Z","log.logger":"component.runtime.endpoint-default.service_runtime","log.origin":{"function":"github.com/elastic/elastic-agent/pkg/component/runtime.newConnInfoServer.func1","file.name":"runtime/conn_info_server.go","file.line":56},"message":"failed accept conn info connection: accept unix /Library/Elastic/Agent/.eaci.sock: use of closed network connection","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2024-07-09T11:17:43.731Z","log.logger":"component.runtime.endpoint-default.service_runtime","log.origin":{"function":"github.com/elastic/elastic-agent/pkg/component/runtime.(*serviceRuntime).stop","file.name":"runtime/service.go","file.line":376},"message":"stopping endpoint service runtime","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2024-07-09T11:17:43.731Z","log.logger":"component.runtime.endpoint-default.service_runtime","log.origin":{"function":"github.com/elastic/elastic-agent/pkg/component/runtime.(*serviceRuntime).stop","file.name":"runtime/service.go","file.line":392},"message":"endpoint service has checked in, send stopping state to service","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2024-07-09T11:17:43.731Z","log.logger":"component.runtime.endpoint-default.service_runtime","log.origin":{"function":"github.com/elastic/elastic-agent/pkg/component/runtime.(*serviceRuntime).stop","file.name":"runtime/service.go","file.line":400},"message":"uninstall endpoint service","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2024-07-09T11:17:43.993Z","log.logger":"component.runtime.endpoint-default.service_runtime","log.origin":{"function":"github.com/elastic/elastic-agent/pkg/component/runtime.executeCommand.func2","file.name":"runtime/service_command.go","file.line":69},"message":"2024-07-09 11:17:43: info: MainPosix.cpp:262 Executing uninstall","context":"command output","ecs.version":"1.6.0"}

```

**Comment by cmacknz** [comment]
It looks to me like we only got a policy change to uninstall endpoint, but not one for re-installing it. The last change in the sequence contains `"removed":["log-default","system/metrics-default","endpoint-default"`.

```json
{"log.level":"info","@timestamp":"2024-07-09T11:15:39.177Z","log.origin":{"function":"github.com/elastic/elastic-agent/internal/pkg/agent/application/coordinator.(*Coordinator).checkAndLogUpdate","file.name":"coordinator/coordinator.go","file.line":1479},"message":"component model updated","log":{"source":"elastic-agent"},"changes":{"components":{"updated":["beat/metrics-monitoring: [(beat/metrics-monitoring-metrics-monitoring-beats: updated)]","http/metrics-monitoring: [(http/metrics-monitoring-metrics-monitoring-agent: updated)]"],"count":4},"outputs":{}},"ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2024-07-09T11:15:47.414Z","log.origin":{"function":"github.com/elastic/elastic-agent/internal/pkg/agent/application/coordinator.(*Coordinator).checkAndLogUpdate","file.name":"coordinator/coordinator.go","file.line":1479},"message":"component model updated","log":{"source":"elastic-agent"},"changes":{"components":{"updated":["beat/metrics-monitoring: [(beat/metrics-monitoring-metrics-monitoring-beats: updated)]","http/metrics-monitoring: [(http/metrics-monitoring-metrics-monitoring-agent: updated)]"],"count":6},"outputs":{}},"ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2024-07-09T11:16:11.718Z","log.origin":{"function":"github.com/elastic/elastic-agent/internal/pkg/agent/application/coordinator.(*Coordinator).checkAndLogUpdate","file.name":"coordinator/coordinator.go","file.line":1479},"message":"component model updated","log":{"source":"elastic-agent"},"changes":{"components":{"added":["system/metrics-monitoring"],"updated":["beat/metrics-monitoring: [(beat/metrics-monitoring-metrics-monitoring-beats: updated)]","http/metrics-monitoring: [(http/metrics-monitoring-metrics-monitoring-agent: updated)]"],"count":7},"outputs":{}},"ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2024-07-09T11:17:42.999Z","log.origin":{"function":"github.com/elastic/elastic-agent/internal/pkg/agent/application/coordinator.(*Coordinator).checkAndLogUpdate","file.name":"coordinator/coordinator.go","file.line":1479},"message":"component model updated","log":{"source":"elastic-agent"},"changes":{"components":{"removed":["log-default","system/metrics-default","endpoint-default","system/metrics-monitoring"],"updated":["http/metrics-monitoring: [(http/metrics-monitoring-metrics-monitoring-agent: updated)]","filestream-monitoring: [(filestream-monitoring-filestream-monitoring-agent: updated)]","beat/metrics-monitoring: [(beat/metrics-monitoring-metrics-monitoring-beats: updated)]"],"count":3},"outputs":{}},"ecs.version":"1.6.0"}
```

I had thought this might be a problem re-binding to the unix socket, but we have logic to remove it before creating and binding to it again: https://github.com/elastic/elastic-agent/blob/d09ef623edfda136dd7392042f2020e4326a45c9/pkg/ipc/listener.go#L27-L33

Problems re-binding to the unix socket would also be reproducible on Linux if this were the root cause.

**Comment by cmacknz** [comment]
The policy in the diagnostics is actually missing endpoint as suspected, so we uninstalled endpoint as instructed, and at the point in time in the diagnostics, agent wasn't told to install it again.

```yaml
agent:
    download:
        sourceURI: https://staging.elastic.co/8.15.0-c7717606/downloads/
    features: null
    monitoring:
        enabled: true
        logs: true
        metrics: true
        namespace: mac
        use_output: default
    protection:
        enabled: false
        signing_key: <REDACTED>
        uninstall_token_hash: <REDACTED>
fleet:
    hosts:
        - https://0ea335ba862e49e18458a3ef58111cc8.fleet.us-west2.gcp.elastic-cloud.com:443
host:
    id: 298365BA-DC99-512C-9E42-026403F89999
id: 30e3cb63-3e88-448d-ad4b-a392fe117849
outputs:
    default:
        api_key: <REDACTED>
        hosts:
            - https://aa6a148468024c99b25c706c496ece04.us-west2.gcp.elastic-cloud.com:443
        preset: balanced
        type: elasticsearch
path:
    config: /Library/Elastic/Agent
    data: /Library/Elastic/Agent/data
    home: /Library/Elastic/Agent/data/elastic-agent-8.15.0-b7f8e2
    logs: /Library/Elastic/Agent
revision: 1
runtime:
    arch: arm64
    native_arch: arm64
    os: darwin
    osinfo:
        family: darwin
        major: 14
        minor: 5
        patch: 0
        type: macos
        version: "14.5"
signed:
    data: eyJpZCI6IjMwZTNjYjYzLTNlODgtNDQ4ZC1hZDRiLWEzOTJmZTExNzg0OSIsImFnZW50Ijp7ImZlYXR1cmVzIjp7fSwicHJvdGVjdGlvbiI6eyJlbmFibGVkIjpmYWxzZSwidW5pbnN0YWxsX3Rva2VuX2hhc2giOiJINEdsamk0SGI3UlQyVVVLOC9jakxFTlFzVzFHSUx6eW1ac0o4c3NVWllBPSIsInNpZ25pbmdfa2V5IjoiTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFdER3MHVRWWRySTg1akdSNzBsTGhWNjdJOHcrc0VxL2RQQmNnVlozV2xpRHF6c1hobCtLVHBMNFNhTStYN3FldUNHRWZrUnk4NU9vK1pGN01Od3ArZFE9PSJ9fSwiaW5wdXRzIjpbXX0=
    signature: MEYCIQCTZ9D2JuolFBk2W5REVzC3Yo8+DEDyk4+9YCmX7dSumQIhAKaWnb8xuk9lqhydJEdg2Dtm9IqNv57W+faf3CMS/r3U
```
