### ISSUE TITLE
[k8s provider] Look up metadata based on file path

### ISSUE THREAD

**Issue by ycombinator** [elastic/elastic-agent#5164]
**Describe the enhancement:**

Have the [Kubernetes provider](https://www.elastic.co/guide/en/fleet/current/kubernetes-provider.html) look up metadata based on file path, similar to what the `add_kubernetes_metadata` provider in Beats is [capable](https://github.com/elastic/beats/pull/7072) of doing.

**Describe a specific use case for the enhancement or feature:**

From @henrikno:

> We have this bug where we lose logs from short lived containers (e.g. if they're crashing). It seems to be like it happens when there's some delay in autodiscover, i.e. by the time it has discovered the container via k8s, and updated the policy to filebeat, the file has been rotated to the new "attempt", which has a new container id.
> So I was looking if it's possible to "reverse" it, and look for the files, and look up metadata based on the file path. And that looks like what `add_kubernetes_metadata` is doing.

**Comment by pchila** [comment]
I had a look at the kubernetes provider and the inputs generated to ingest logs for containers and there may be a simpler solution to ensure that agents generates filestream inputs that match rotated container log files for container that crash/terminate quickly.

Currently elastic-agent creates an `input` per pod and then one datastream per container see https://github.com/elastic/elastic-agent/blob/eedce01997b3b38e45bbd0949c2bfe1b082ed4b7/deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml#L353-L381

The files in `/var/log/containers` are symlinks to the actual container logs under `/var/log/pods/<namespace>_<pod name>_<pod_uid>/<container name>/*.log`.

For example for pod `fritzy-printer-6d65dcc658-mpzpr` in namespace `default` container logs for `echoer` container are:
```shell
root@fastcontainers-control-plane:/var/log# ll containers/fritzy-printer-*.log
lrwxrwxrwx 1 root root 104 Jan 23 12:23 containers/fritzy-printer-6d65dcc658-mpzpr_default_echoer-3b25af57297705d7c0986df8e4817e1225c212d5df6dad27104b17357de92c9e.log -> /var/log/pods/default_fritzy-printer-6d65dcc658-mpzpr_67f3da94-d6d0-47b7-a60b-ea715174927c/echoer/56.log
```
The directory `/var/log/pods/default_fritzy-printer-6d65dcc658-mpzpr_67f3da94-d6d0-47b7-a60b-ea715174927c/echoer/` contains all the available logs for the same container (even the rotated ones from previous container runs until they are deleted by kubelet).

In order to capture all the available logs it should be enough to change the `paths` in the container logs input, so it would generate something similar to the yaml below

```yaml
      # Input ID allowing Elastic Agent to track the state of this input. Must be unique.
      - id: container-log-${kubernetes.pod.namespace}-${kubernetes.pod.name}-${kubernetes.container.id}
        type: filestream
        use_output: default
        ...
        streams:
          # Stream ID for this data stream allowing Filebeat to track the state of the ingested files. Must be unique.
          # Each filestream data stream creates a separate instance of the Filebeat filestream input.
          - id: container-log-${kubernetes.pod.namespace}-${kubernetes.pod.name}-${kubernetes.container.id}
            data_stream:
              dataset: kubernetes.container_logs
              type: logs
            parsers:
              - container: ~
              # - ndjson:
              #     target: json
              # - multiline:
              #     type: pattern
              #     pattern: '^\['
              #     negate: true
              #     match: after
            paths:
              - /var/log/pods/${kubernetes.pod.namespace}_${kubernetes.pod.name}_${kubernetes.pod.uid}/${kubernetes.container.name}/*.log
```

Note the addition of ${kubernetes.pod.namespace} in the input and stream id to ensure that agent can distinguish between pods with the same name specifying a container with the same name in different namespaces (could happen in case of pods with predictable network name like statefulsets).

I am going to modify the elastic-agent helm chart to check that the new input spec works as expected.

Huge props to @pkoutsovasilis that assisted me in the analysis of kubernetes provider and suggested looking into adjusting the paths passed to filebeat
