### ISSUE TITLE
Elastic Agent - Agent ID is not retained in kubernetes elastic agent daemonset

### ISSUE THREAD

**Issue by jade-lucas** [elastic/elastic-agent#5185]
## Bug Report
**What did you do?**

Installed elastic agents on kubneretes cluster via DaemonSet as directed by the Fleet UI. Every time an elastic-agent pod is restarted, the agent ID changes which I think results many offline agents showing in the Fleet UI over time.

**What did you expect to see?**
The agent to retain its Id thus only one agent to appear in Fleet UI. 

**What did you see instead? Under which circumstances?**
After every pod restart, a new agent appears even though it is on the same host. 

* Kubernetes information:

	* On premise kubernetes
	* Kubernetes distribution: Vanilla v4.5.7
	* kubectl version: 1.25

**Comment by cmacknz** [comment]
Thanks, the fleet.enc file should probably just be moved into the state path of the container to simplify the amount of configuration that needs to happen.

**Comment by TsengSR** [comment]
@cmacknz 

> Thanks, the fleet.enc file should probably just be moved into the state path of the container to simplify the amount of configuration that needs to happen.

Anything happened there? Running in same issue, after restart pods stuck in updating and having the agents multiply in the Kibana Fleet UI.

**Comment by cmacknz** [comment]
Since this was filed we now have an Elastic Agent specific Helm chart that should do the right thing and can generate CRDs for ECK if you are using that e.g. what is described in https://github.com/elastic/elastic-agent/issues/6204#issuecomment-3104555307

**Comment by TsengSR** [comment]
No, just using the eck-operator

```yaml
apiVersion: agent.k8s.elastic.co/v1alpha1
kind: Agent
metadata:
  name: elastic-agent
  namespace: monitoring
spec:
  version: 9.0.3
  kibanaRef:
    name: elk-default
    namespace: monitoring
  fleetServerRef:
    name: fleet-server
    namespace: monitoring
  mode: fleet
  policyID: eck-agent
  daemonSet:
    podTemplate:
      spec:
        serviceAccountName: elastic-agent
        automountServiceAccountToken: true
        hostNetwork: true
        dnsPolicy: ClusterFirstWithHostNet
        securityContext:
          runAsUser: 0
        containers:
        - name: agent
          env:
          - name: CONFIG_PATH
            value: /usr/share/elastic-agent/state
```

only setting the `CONFIG_PATH` fixed that , as `/usr/share/elastic-agent/` is outside the hostPath (hostPath points to `/usr/share/elastic-agent/state`). Its somewhat of a pain and huge source of errors/mistakes, so IMHO either the default should be changed to be inside state or at least the eck-operator being adjusted to use a `CONFIG_PATH` that's inside (or change its hostPath to `/usr/share/elastic-agent/` if there are no good reasons against it.

**Comment by cmacknz** [comment]
Thanks for the clear example, I see what is going on now. Elastic Agent on its own defaults the config path to the state path

https://github.com/elastic/elastic-agent/blob/d92a33139bd74cb6619b0982c2ba0ad8a90e3e15/internal/pkg/agent/cmd/container.go#L816-L819

This is also observable by exec-ing into a running agent container:

```yaml
bash-5.1$ cat state/container-paths.yml
state_path: /usr/share/elastic-agent/state
config_path: /usr/share/elastic-agent/state
socket_path: unix:///usr/share/elastic-agent/state/data/Td8I7R-Zby36_zF_IOd9QVNlFblNEro3.sock
```

I can now see that it is ECK that is configuring the config path and the state path to be different: https://github.com/elastic/cloud-on-k8s/blob/1832f4bbc4e280ffeff5df96fd4ce3bf503899b4/pkg/controller/agent/pod.go#L196-L203

So this could be fixed in ECK, but it is probably be less disruptive for us to move the file that matters into the state path instead because it is intended to have to persist across restarts.

CC @pkoutsovasilis for a second look

**Comment by TsengSR** [comment]
I'm also having a similar issue with the agent that is in fleet-mode, for it the CONFIG_PATH workaround didn't work and everytime the pod restarts a new agent pops up while the previous one goes offline and I have to unenroll the offline agents. 

<img width="1434" height="376" alt="Image" src="https://github.com/user-attachments/assets/dfad63aa-ce2d-4281-91e5-27728de5a453" />

Any pointers for that?

**Comment by cmacknz** [comment]
Just to double check these agents have different IDs, or the same IDs with different names (which look like the pod names)?

**Comment by TsengSR** [comment]
Not sure how to check, but the displayed names are podnames yes. The elastic-agents initially did have pod names as hosts too, until I did the CONFIG_PATH workaround mentioned above. Now the elastic-agents have the node names instead (`my-homelab-1`, `my-homelab-2`, `my-homelab-3`, `my-homelab-4`)

This are my ECK manifests for Kibana and Fleet Agent (and 2 posts above is the elastic-agent one)

```yaml
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: elk-default
spec:
  version: 9.0.4
  count: 1
  elasticsearchRef:
    name: elk-default
  http:
    tls:
      certificate:
        secretName: kibana-dashboard-tls
  config:
    xpack.encryptedSavedObjects.encryptionKey: <masked>
    xpack.fleet.agents.enabled: true
    xpack.fleet.agents.elasticsearch.hosts: ["https://elk-default-es-http.monitoring.svc:9200"]
    xpack.fleet.agents.fleet_server.hosts: ["https://fleet-server-agent-http.monitoring.svc:8220"]
    xpack.fleet.agents.kibana.host: "https://elk-default-kb-http.monitoring.svc:5601"
    server.publicBaseUrl: "https://kibana.example.local:8443"
    xpack.fleet.packages:
      - name: system
        version: latest
      - name: elastic_agent
        version: latest
      - name: fleet_server
        version: latest
    xpack.fleet.agentPolicies:
      - name: Fleet Server on ECK policy
        id: eck-fleet-server
        namespace: default
        is_managed: false
        monitoring_enabled:
          - logs
          - metrics
        unenroll_timeout: 900
        package_policies:
        - name: fleet_server-1
          id: fleet_server-1
          package:
            name: fleet_server
      - name: Elastic Agent on ECK policy
        id: eck-agent
        namespace: default
        is_managed: false
        monitoring_enabled:
          - logs
          - metrics
        unenroll_timeout: 900
        package_policies: []
  podTemplate:
    spec:
      containers:
      - name: kibana
        env:
          - name: NODE_OPTIONS
            value: "--max-old-space-size=1024"
        resources:
          requests:
            memory: 0.5Gi
            cpu: 0.25
          limits:
            memory: 2Gi
            cpu: 1
---
apiVersion: agent.k8s.elastic.co/v1alpha1
kind: Agent
metadata:
  name: fleet-server
  namespace: monitoring
spec:
  version: 9.0.4
  kibanaRef:
    name: elk-default
    namespace: monitoring
  elasticsearchRefs:
  - name: elk-default
    namespace: monitoring
  mode: fleet
  fleetServerEnabled: true
  policyID: eck-fleet-server
  deployment:
    replicas: 1
    podTemplate:
      spec:
        serviceAccountName: elastic-agent
        automountServiceAccountToken: true
        securityContext:
          runAsUser: 0
        containers:
        - name: agent
          env:
          - name: CONFIG_PATH # This one didn't help it stay stable
            value: /usr/share/elastic-agent/state
```

However, it seems one of my very old pods the fleet agent did had the host name `my-homelab-3` as name/id.

<img width="1875" height="72" alt="Image" src="https://github.com/user-attachments/assets/3c0afcf5-9ad4-4f6e-806c-9d68968daf12" />

But it doesn't have any last activity though.

**Comment by pkoutsovasilis** [comment]
@cmacknz regarding the CONFIG_PATH behaviour – by default, Elastic Agent already sets the config_path inside the state_path. Supporting an override that is then automatically copied into the state path feels like it defeats the original purpose of having a configurable CONFIG_PATH. My current thinking is that this should ideally be addressed on the ECK side of the code, since it is the component that sets these paths differently. That said, I’m happy to discuss further if there’s a strong reason to handle it from the Agent side. 

---
@TsengSR I notice that your Fleet-server bootstrapping Agent is running as a Deployment. Specifying CONFIG_PATH was meant as a workaround to ensure that the fleet.enc file resides in a persisted state path. In your scenario, the critical question is: how is the state being persisted?
- If your state volume is an EmptyDir, all state is lost whenever the Pod restarts, which causes a new Agent enrollment and leads to the “zombie” agents you’re seeing.
- If your state volume is a hostPath, the state persists only on that node. If the Pod is rescheduled to a different node, the previous state (and enrollment) is lost.

**Comment by TsengSR** [comment]
@pkoutsovasilis 

Most of the above configuration is slightly adjusted [Quickstart](https://www.elastic.co/docs/deploy-manage/deploy/cloud-on-k8s/quickstart-fleet) examples and they mention nothing about having to configure anything, neither do the other 3 sections on the docs. hostPath vs non-root is briefly explained, but the examples refer to elastic-agents mostly, not to the fleet agent. 

Personally I always assume that that the default configuration is with persistance in mind, unless explicitely stated otherwise. That's the case for elastic-agents already (they persist to hostPath), but do not seem to be the case for fleet agent.

So, I assume I have to add a [VolumeClaimTemplate](https://www.elastic.co/docs/deploy-manage/deploy/cloud-on-k8s/volume-claim-templates) to the fleet-agent then? Where would it mount too? If it mounts to  `/usr/share/elastic-agent/state`, then the same issue as above would apply, that the fleet.enc is outside of the state folder (dunno if CONFIG_PATH still would apply to it, but I believe it would?). If it would mount to `/usr/share/elastic-agent` it seems problematic too as /data has 1.4G of files which s eem to be related to the agent executable itself, would there issue apply changing/upgrading versions then via Custom Resource update? (i.e. changing the version in the custom resource)?

I think the docs would need to be updated to be more clear on the k8s setup of it as the [Recipes](https://raw.githubusercontent.com/elastic/cloud-on-k8s/3.1/config/recipes/elastic-agent/fleet-kubernetes-integration-nonroot.yaml) also contain no hint of having to define a persistent volume. 

Imho it should be be best, if it would create an PV/PVC by default and only require volume claim template if one wants to customize it?

**Comment by pebrc** [comment]
> I can now see that it is ECK that is configuring the config path and the state path to be different: https://github.com/elastic/cloud-on-k8s/blob/1832f4bbc4e280ffeff5df96fd4ce3bf503899b4/pkg/controller/agent/pod.go#L196-L203

> So this could be fixed in ECK, but it is probably be less disruptive for us to move the file that matters into the state path instead because it is intended to have to persist across restarts.

@cmacknz @pkoutsovasilis The reason ECK sets up the paths the way it does is because in an environment like Kubernetes you are typically sourcing configuration from a ConfigMap or Secret which needs to be mounted readonly into the container (I think here this is mainly for advanced configuration of Fleet-managed agents). The state path however needs to a writable directory for Elastic Agent. These are conflicting requirements that we addressed by separating the two. Overlaying the read-only configuration file onto the writable (hostPath) mount for the state directory sounds messy and a bit complicated?

**Comment by pkoutsovasilis** [comment]
@pebrc I hear your point, but I think there is some misalignment here, likely because of the two modes Elastic Agent can operate in: standalone vs managed (Fleet).

Yes, what you mention about configuration being sourced from ConfigMaps or Secrets (and needing to be mounted read-only) is true. However, in managed mode, the Agent also receives configuration from Fleet, and this configuration needs to reside in the state path so that it persists across restarts.

For that reason, it is generally more convenient to:
- Keep CONFIG_PATH pointing to the state path.
- If a user/ECK operator wants to mount additional static config into the Pod, they can do that and they can point to it using the `-c` argument to `elastic-agent container ...` cmd, and this can safely live outside the state path.

This way, the Agent’s runtime and Fleet-managed state remain persistent, and static overrides are still possible without overlaying read-only and writable paths.

**Comment by pkoutsovasilis** [comment]
@TsengSR I can’t speak for the ECK team (maybe @pebrc can 🙂), and maybe it’s just me, but `Quickstart` examples are usually meant as minimal snippets to showcase functionality rather than cover the full spectrum of production-ready configurations.

Regarding the Deployment option for Fleet Server: my recommendation would be to switch the Fleet Server bootstrapping Agent to a StatefulSet (@pebrc keep me honest here). Then:
1. Define a PVC and mount it to the container at: `/usr/share/elastic-agent/state`
2. Set the CONFIG_PATH env var to: `/usr/share/elastic-agent/state`

This should ensure that fleet.enc and the Agent state persist across restarts and reschedules

**Comment by pebrc** [comment]
> I hear your point, but I think there is some misalignment here

@pkoutsovasilis we can definitely revisit our implementation choices in ECK. I mistakenly thought we were following an approved approach (and you reviewed it as well https://github.com/elastic/cloud-on-k8s/pull/8623/) I think it is also worth calling out these expectations in the docs.

**Comment by pkoutsovasilis** [comment]
> [@pkoutsovasilis](https://github.com/pkoutsovasilis) we can definitely revisit our implementation choices in ECK. I mistakenly thought we were following an approved approach (and you reviewed it as well [elastic/cloud-on-k8s#8623](https://github.com/elastic/cloud-on-k8s/pull/8623)) I think it is also worth calling out these expectations in the docs.

Sorry if I missed it @pebrc, but I do remember my review and I specifically remember looking at [this line](https://github.com/elastic/cloud-on-k8s/pull/8623/files#diff-4df662e0c3607749f3636339227faa2f180610a399151e31d0a1600312bd545fR157), which aligns with the `-c argument` approach.

I hadn’t realized that CONFIG_PATH is also exposed as an env var. From what I understand, this wasn’t introduced in [#8623](https://github.com/elastic/cloud-on-k8s/pull/8623) but was already present, originally pointing to /usr/share/elastic-agent, and then changed to /etc/agent for Fleet user advanced configuration. Reviewing existing logic under a PR like this can sometimes be tricky, so that detail didn’t fully register.

Either way, I think there’s a clear path forward to align expectations and reduce confusion for managed agents.

**Comment by TsengSR** [comment]
> Regarding the Deployment option for Fleet Server: my recommendation would be to switch the Fleet Server bootstrapping Agent to a StatefulSet ([@pebrc](https://github.com/pebrc) keep me honest here). Then:
> 
> 1. Define a PVC and mount it to the container at: `/usr/share/elastic-agent/state`
> 2. Set the CONFIG_PATH env var to: `/usr/share/elastic-agent/state`
> 
> This should ensure that fleet.enc and the Agent state persist across restarts and reschedules

This doesn't seem to work.

```yaml

apiVersion: agent.k8s.elastic.co/v1alpha1
kind: Agent
metadata:
  name: fleet-server
  namespace: monitoring
spec:
  version: 9.0.4
  kibanaRef:
    name: elk-default
    namespace: monitoring
  elasticsearchRefs:
  - name: elk-default
    namespace: monitoring
  mode: fleet
  fleetServerEnabled: true
  policyID: eck-fleet-server
  statefulSet:
    replicas: 1
    volumeClaimTemplates:
    - metadata:
        name: fleet-agent-state
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 64Mi
        storageClassName: longhorn
    podTemplate:
      spec:
        serviceAccountName: elastic-agent
        automountServiceAccountToken: true
        securityContext:
          runAsUser: 0
        containers:
        - name: agent
          volumeMounts:
          - name: fleet-agent-state
            mountPath: /usr/share/elastic-agent/state
          env:
          - name: CONFIG_PATH
            value: /usr/share/elastic-agent/state
          resources:
            requests:
              memory: 256Mi
              cpu: 0.2
            limits:
              memory: 512Mi
              cpu: 0.5
```

I see that the volume was mounted 

```bash
[root@fleet-server-agent-0 elastic-agent]# df -h
Filesystem                                              Size  Used Avail Use% Mounted on
overlay                                                 233G   26G  208G  11% /
tmpfs                                                    64M     0   64M   0% /dev
tmpfs                                                   512M  4.0K  512M   1% /etc/agent.yml
/dev/nvme0n1p6                                          233G   26G  208G  11% /etc/hosts
shm                                                      64M     0   64M   0% /dev/shm
/dev/longhorn/pvc-1c1dcdb5-3276-4747-bb5f-f51e6a4c17d8   56M  1.1M   54M   2% /usr/share/elastic-agent/state
tmpfs                                                   512M   12K  512M   1% /usr/share/fleet-server/config/http-certs
tmpfs                                                   512M   12K  512M   1% /run/secrets/kubernetes.io/serviceaccount
tmpfs                                                   512M  8.0K  512M   1% /mnt/elastic-internal/elasticsearch-association/monitoring/elk-default/certs
tmpfs                                                    16G     0   16G   0% /proc/scsi
tmpfs                                                    16G     0   16G   0% /sys/firmware
```

`CONFIG_PATH` is also correctly set within the pod. 

But new agents keep getting listed

<img width="1880" height="344" alt="Image" src="https://github.com/user-attachments/assets/0c0928c7-d1df-4e73-a273-b486e654c89e" />
