### ISSUE TITLE
[Kubernetes manifest] Use unique identifier for the state file path

### ISSUE THREAD

**Issue by tetianakravchenko** [elastic/elastic-agent#5187]
**Describe the enhancement:**

in manifest we have `elastic-agent-state` and the hostPath is predefined:
```
        # Mount /var/lib/elastic-agent-managed/kube-system/state to store elastic-agent state
        # Update 'kube-system' with the namespace of your agent installation
        - name: elastic-agent-state
          hostPath:
            path: /var/lib/elastic-agent-managed/kube-system/state
            type: DirectoryOrCreate
```
as a result when customer want to remove installation `kubectl delete -f manifest.yaml` and install a new one (with the different `FLEET_URL` and `FLEET_ENROLLMENT_TOKEN`) existing state file will be used, that leads to the next error:

```
"message":"Possible transient error during checkin with fleet-server, retrying","log":{"source":"elastic-agent"},"error":{"message":"fail to checkin to fleet-server: all hosts failed: 1 error occurred:\n\t* requester 0/1 to host https://XXXXXX.fleet.region.aws.found.io:443 ...
```

**What is the definition of done?**
- create 2 elastic stack deployments: stack1, stack 2
- install elastic-agent to the k8s cluster (with stack1 credentials)
- delete it
- install elastic-agent to the k8s cluster (with stack2 credentials)
- no errors occure

Few ideas:
we can use fleet url as: `/var/lib/elastic-agent-managed/<fleet_url>/kube-system/state` (like: `/var/lib/elastic-agent-managed/f437b90409bb4804b1647665fa19f7a0.fleet.us-central1.gcp.cloud.es.io/kube-system/state`, for local setup: `/var/lib/elastic-agent-managed/fleet-serverkube-system/state`)
but what to do we there is no fleet server? fallback to default - `/var/lib/elastic-agent-managed/kube-system/state` ?
