### ISSUE TITLE
Ensure no log duplication happens with Hints based autodiscovery

### ISSUE THREAD

**Issue by ChrsMark** [elastic/elastic-agent#5254]
The default configuration of [standalone Elastic Agent](https://www.elastic.co/guide/en/fleet/8.14/running-on-kubernetes-standalone.html) enables the `container_logs`  data stream with https://github.com/elastic/elastic-agent/blob/v8.14.3/deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml#L365-L380.

However, when using the [Hints based autodiscovery with standalone Agent](https://www.elastic.co/guide/en/fleet/current/hints-annotations-autodiscovery.html) we should ensure that the default input is removed if `hints.default_container_logs` is enabled (which under the hood enables https://github.com/elastic/elastic-agent/blob/v8.14.3/deploy/kubernetes/elastic-agent-standalone/templates.d/container_logs.yml for all of the discovered pods/containers). Otherwise we have 2 defined inputs doing the same thing.

In addition, we should ensure that once a Pod/container is discovered the generic `container_logs` input is disabled for that container/pod if there are provided Hints that enable a log input. This should be already supported based on the [implementation](https://github.com/elastic/elastic-agent/blob/8531f4f3ae147502dcd6f0a97ca4e7216f988660/internal/pkg/composable/providers/kubernetes/pod.go#L471) but make it would worth verifying and explicitly mentioning that in the docs.

The outcome here should be that only one input is enabled per container to avoid log duplication.

ToDos:
1) verify that log duplication is properly handled when Agent runs on Hints based autodiscovery mode.
2) Update the docs wherever it is required. 
3) Cover the above with tests.

@flash1293 @gizas

**Comment by akhileshpok** [comment]
@ChrsMark - What should be the priority of this issue? Thanks

**Comment by flash1293** [comment]
@gizas could you take a look at this?

**Comment by gizas** [comment]
@chris I run the test with nginx and I can confirm that no duplicates are present

When the nginx is enabled with the annotations (co.elastic.hints/package: "nginx"), we have only logs in nginx datastreams.

<img width="2056" alt="Screenshot 2024-08-12 at 4 26 08 PM" src="https://github.com/user-attachments/assets/a232c516-8e6a-4e58-b188-59a70a35cc53">


When I remove the annotation the logs appear in kubernets.container_logs datastream as a fallback

See below manifests
<details><summary>Agent standalone config with container_logs and nginx input enabled. I only add here the agent part</summary>

```yaml

  agent.yml: |-
    id: 67744860-95e9-457b-80b8-90688e0a4b14
    outputs:
      default:
        type: elasticsearch
        hosts:
          - 'https://elasticsearch:9200'
        ssl.ca_trusted_fingerprint: C9C8F331A525B904397B972B3006829BC68E654E628C9299FB64898E0B8D29F1
        api_key: '${API_KEY}'
        preset: balanced
    providers.kubernetes:
      node: ${NODE_NAME}
      scope: node
      hints.enabled: true
      hints.default_container_logs: true
    inputs:
      - name: hints-filestream-container-logs
        id: hints-filestream-container-logs-${kubernetes.hints.container_id}
        type: filestream
        use_output: default
        streams:
          - condition: ${kubernetes.hints.container_logs.enabled} == true
            data_stream:
              dataset: kubernetes.container_logs
              type: logs
            parsers:
              - container:
                  format: auto
                  stream: ${kubernetes.hints.container_logs.stream|'all'}
            paths:
              - /var/log/containers/*${kubernetes.hints.container_id}.log
            prospector:
              scanner:
                symlinks: true
        data_stream.namespace: default
      - name: httpjson-nginx
        id: httpjson-nginx-${kubernetes.hints.container_id}
        type: httpjson
        use_output: default
        streams:
          - auth.basic.password: ${kubernetes.hints.nginx.access.password|kubernetes.hints.nginx.password|''}
            auth.basic.user: ${kubernetes.hints.nginx.access.username|kubernetes.hints.nginx.username|''}
            condition: ${kubernetes.hints.nginx.access.enabled} == true and ${kubernetes.hints.nginx.enabled} == true
            config_version: 2
            cursor:
              index_earliest:
                  value: '[[.last_event.result.max_indextime]]'
            data_stream:
              dataset: nginx.access
              type: logs
            interval: 10s
            request.method: POST
            request.transforms:
              - set:
                  target: url.params.search
                  value: search sourcetype=nginx:plus:access | streamstats max(_indextime) AS max_indextime
              - set:
                  target: url.params.output_mode
                  value: json
              - set:
                  default: '[[(now (parseDuration "-10s")).Unix]]'
                  target: url.params.index_earliest
                  value: '[[ .cursor.index_earliest ]]'
              - set:
                  target: url.params.index_latest
                  value: '[[(now).Unix]]'
              - set:
                  target: header.Content-Type
                  value: application/x-www-form-urlencoded
            request.url: https://server.example.com:8089/services/search/jobs/export
            response.decode_as: application/x-ndjson
            response.split:
              delimiter: |4+
              target: body.result._raw
              type: string
            tags:
              - forwarded
              - nginx-access
          - auth.basic.password: ${kubernetes.hints.nginx.error.password|kubernetes.hints.nginx.password|''}
            auth.basic.user: ${kubernetes.hints.nginx.error.username|kubernetes.hints.nginx.username|''}
            condition: ${kubernetes.hints.nginx.error.enabled} == true and ${kubernetes.hints.nginx.enabled} == true
            config_version: 2
            cursor:
              index_earliest:
                  value: '[[.last_event.result.max_indextime]]'
            data_stream:
              dataset: nginx.error
              type: logs
            interval: 10s
            request.method: POST
            request.transforms:
              - set:
                  target: url.params.search
                  value: search sourcetype=nginx:plus:error | streamstats max(_indextime) AS max_indextime
              - set:
                  target: url.params.output_mode
                  value: json
              - set:
                  default: '[[(now (parseDuration "-10s")).Unix]]'
                  target: url.params.index_earliest
                  value: '[[ .cursor.index_earliest ]]'
              - set:
                  target: url.params.index_latest
                  value: '[[(now).Unix]]'
              - set:
                  target: header.Content-Type
                  value: application/x-www-form-urlencoded
            request.url: https://server.example.com:8089/services/search/jobs/export
            response.decode_as: application/x-ndjson
            response.split:
              delimiter: |4+
              target: body.result._raw
              type: string
            tags:
              - forwarded
              - nginx-error
        data_stream.namespace: default
      - name: nginx/metrics-nginx
        id: nginx/metrics-nginx-${kubernetes.hints.container_id}
        type: nginx/metrics
        use_output: default
        streams:
          - condition: ${kubernetes.hints.nginx.stubstatus.enabled} == true or ${kubernetes.hints.nginx.enabled} == true
            data_stream:
              dataset: nginx.stubstatus
              type: metrics
            hosts:
              - ${kubernetes.hints.nginx.stubstatus.host|kubernetes.hints.nginx.host|'http://127.0.0.1:80'}
            metricsets:
              - stubstatus
            period: ${kubernetes.hints.nginx.stubstatus.period|kubernetes.hints.nginx.period|'10s'}
            server_status_path: /nginx_status
        data_stream.namespace: default
      - name: filestream-nginx
        id: filestream-nginx-${kubernetes.hints.container_id}
        type: filestream
        use_output: default
        streams:
          - condition: ${kubernetes.hints.nginx.access.enabled} == true or ${kubernetes.hints.nginx.enabled} == true
            data_stream:
              dataset: nginx.access
              type: logs
            exclude_files:
              - .gz$
            ignore_older: 72h
            parsers:
              - container:
                  format: auto
                  stream: ${kubernetes.hints.nginx.access.stream|'all'}
            paths:
              - /var/log/containers/*${kubernetes.hints.container_id}.log
            processors:
              - add_locale: null
            prospector:
              scanner:
                  symlinks: true
            tags:
              - nginx-access
          - condition: ${kubernetes.hints.nginx.error.enabled} == true or ${kubernetes.hints.nginx.enabled} == true
            data_stream:
              dataset: nginx.error
              type: logs
            exclude_files:
              - .gz$
            ignore_older: 72h
            multiline:
              match: after
              negate: true
              pattern: '^\d{4}\/\d{2}\/\d{2} '
            parsers:
              - container:
                  format: auto
                  stream: ${kubernetes.hints.nginx.error.stream|'all'}
            paths:
              - /var/log/containers/*${kubernetes.hints.container_id}.log
            processors:
              - add_locale: null
            prospector:
              scanner:
                  symlinks: true
            tags:
              - nginx-error
        data_stream.namespace: default
      
    secret_references: []
    revision: 2
```
</details>


<details><summary>Nginx Manifest</summary>

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
      annotations:
        pas: 'true'
        #co.elastic.hints/enabled: 'true'
        co.elastic.hints/package: "nginx"
        # co.elastic.hints/streams: 'error'
    spec:
      containers:
      - image: nginx
        name: nginx
        resources:
          limits:
            memory: 80Mi
            cpu: 300m
          requests:
            cpu: 100m
            memory: 70Mi

```
</details>


I think we can close this for now. (as this functionality will also be tested with https://github.com/elastic/elastic-agent/issues/5289). So I dont see a blocker here. @ChrsMark was there a reason or did we witness anything with a specific template? Lets wait for last clarification and the close it
