### ISSUE TITLE
Consider collecting (by-default) all underlying host's processes in K8s

### ISSUE THREAD

**Issue by ChrsMark** [elastic/elastic-agent#5256]
In Agent standlone on K8s the `process` datastream is enabled by default: https://github.com/elastic/elastic-agent/blob/6aa581cbec8e6f8063571048e52a3b9f0b352c80/deploy/kubernetes/elastic-agent-standalone/elastic-agent-standalone-daemonset-configmap.yaml#L492

However it does not collect the underlying host's processes. 

Would that make sense to collect the underlying system's processes (and possibly metrics) instead of those of the Agent container's scope?

I tried the following:

```yaml
- id: system/metrics-system.process-52c2cd5b-0cff-4060-b0ad-a2f533124165
  data_stream:
    type: metrics
    dataset: system.process
  metricsets:
    - process
  period: 10s
  hostfs: "/hostfs"
  process.include_top_n.by_cpu: 5
  process.include_top_n.by_memory: 5
  process.cmdline.cache.enabled: true
  process.cgroups.enabled: false
  process.include_cpu_ticks: false
  processes:
    - .*
```

(note the `hostfs: "/hostfs"`) part.
To get the desired result:

![k8ssystemprocesses](https://github.com/user-attachments/assets/fbc64c7a-5712-432e-ad81-d42b62eae51f)

After the addition of the `hostfs: "/hostfs"` setting I could see the processes of the underlying host, like `kubelet` etc.
We can consider if this should be the default or at least make the switch easier for the users with and/or commented out sections.

/cc @flash1293
