### ISSUE TITLE
Event log file gets flooded with `copy_fields` processor error

### ISSUE THREAD

**Issue by belimawr** [elastic/elastic-agent#5299]
For confirmed bugs, please report:
- Version: 8.15.0

The `filestream-monitoring` deployed by Elastic-Agent to collect its own logs is flooding the event logs with an `copy_fields` processor error:
```json
{
  "log.level": "debug",
  "@timestamp": "2024-08-14T13:40:27.920Z",
  "message": "Failed to copy fields in copy_fields processor: target field data_stream.dataset already exists, drop or rename this field first",
  "component": {
    "binary": "filebeat",
    "dataset": "elastic_agent.filebeat",
    "id": "filestream-monitoring",
    "type": "filestream"
  },
  "log": {
    "source": "filestream-monitoring"
  },
  "log.type": "event",
  "ecs.version": "1.6.0",
  "log.logger": "copy_fields",
  "log.origin": {
    "file.line": 81,
    "file.name": "actions/copy_fields.go",
    "function": "github.com/elastic/beats/v7/libbeat/processors/actions.(*copyFields).Run"
  },
  "service.name": "filebeat"
}
```

On my test, that accounted for about 38% of the entries in the event log.

This seems to be coming from the following chain of processors (from `components/filestream-monitoring/beat-rendered-config.yml`):
```yaml
        - copy_fields:
            fields:
                - from: data_stream.dataset
                  to: data_stream.dataset_original
        - drop_fields:
            fields:
                - data_stream.dataset
        - copy_fields:
            fail_on_error: false
            fields:
                - from: component.dataset
                  to: data_stream.dataset
            ignore_missing: true
        - copy_fields:
            fail_on_error: false
            fields:
                - from: data_stream.dataset_original
                  to: data_stream.dataset
```

The third and forth processors copy different fields to the same destination, so if the third runs successfully, then the forth will always fail and generate the log message above.

While this can be the intended behaviour (trying to set `data_stream.dataset` from multiple sources), it is flooding our logs.

We can use some [processor conditions](https://www.elastic.co/guide/en/beats/filebeat/current/defining-processors.html#conditions) to avoid running the `copy_fields` processor if the field is already present, thus avoiding the flood of debug logs.

## Steps to reproduce
- Generate logs with a reasonable rate for testing, like 1 event per second, keep it running
- Add the Custom Logs integration to an Elastic-Agent policy to ingest the log file
- Let the Elastic-Agent run for a minute or so
- Collect the diagnostics
- Inspect the event log file (`logs/elastic-agent-8.15.0-25075f/events/*.ndjosn`)
