### ISSUE TITLE
Document how the agent translates it's policy into a graph of started processes 

### ISSUE THREAD

**Issue by cmacknz** [elastic/elastic-agent#536]
With the V2 architecture changes and new people on the team ramping up on the agent it would be extremely helpful if documentation existed showing how an agent policy with multiple integrations installed were translated into a graph of running processes.

For example, consider the simplified agent policy below with two log inputs:

```yml
  - id: logfile-system-IDA
    name: system-1
    type: logfile
    use_output: default
    data_stream:
      namespace: default
    streams:
      - id: logfile-system.auth-IDA
        data_stream:
          dataset: system.auth
          type: logs
        paths:
          - /var/log/auth.log*
        processors:
          - add_locale: null
  - id: logfile-system-IDB
    name: system-2
    type: logfile
    use_output: default
    data_stream:
      namespace: default
    streams:
      - id: logfile-system.auth-IDB
        data_stream:
          dataset: system.auth
          type: logs
        paths:
          - /var/log/secure*
        processors:
          - decode_json_fields:
            fields: ["inner"]
      - id: logfile-system.syslog-IDB
        data_stream:
          dataset: system.syslog
          type: logs
        paths:
          - /var/log/syslog*
```

It is not clear reading this that the two `logfile` inputs will be configured to run from a single filebeat process. The introduction of the https://github.com/elastic/elastic-agent-shipper further complicates this in that the filebeat process will be wired to a shipper instance per configured output.
