### ISSUE TITLE
Kubernetes Provider Leader Election Allow Scoping Possible Leaders

### ISSUE THREAD

**Issue by BenB196** [elastic/elastic-agent#5406]
**Describe the enhancement:**

It should be possible to configure "conditions" for when an Elastic Agent should try and compete for [Kubernetes Provider Leader Election](https://www.elastic.co/guide/en/fleet/current/kubernetes_leaderelection-provider.html) and be elected leader.

**Describe a specific use case for the enhancement or feature:**

Currently, when you define a Daemonset of Elastic Agents on a Kubernetes cluster, and have leader election enabled, it is possible for any of the pods to be elected leader. This "issue" here, is that in a Kubernetes cluster, there is often multiple different node types/sizes and an Elastic Agent could be elected leader on a less than ideal node (because the leader require [more resources](https://www.elastic.co/guide/en/fleet/current/scaling-on-kubernetes.html#_specifying_resources_and_limits_in_agent_manifests)).

It should be possible to configure an Elastic Agent to only try to become leader if the agent's underlying info meets specific "conditions".

Example, if I have a k8s cluster with two different node types, one labeled `usage: general` and another labeled `usage: xsmall`. I want to restrict the Elastic Agent to only try and run the Kubernetes Leader Election Provider on the `usage: general`, and not `usage: xsmall` as there isn't enough resources to properly work.

**What is the definition of done?**

The Elastic Agent Leader Election should be configurable to only run on specific nodes, (possibly leveraging, https://www.elastic.co/guide/en/fleet/current/dynamic-input-configuration.html?).

**Comment by BenB196** [comment]
In the event anyone else comes across this issue, the current work around I've come up with is the modify the `command` with a condition.

Create a secret that disables leader election:

```yaml
apiVersion: v1
data:
  agent.yml: |
    providers.kubernetes_leaderelection.enabled: false
    fleet.enabled: true
kind: Secret
metadata:
  name: disable-leader-election
type: secret
```

Abridged Daemonset

```yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: monitoring
spec:
  template:
    spec:
     # init container which pulls the specific label(s) wanted
     # store them under /tmp/node-labels for the agent container to use
      initContainers:
        - command:
            - sh
            - '-c'
            - >
              set -ex

              NODE_GROUP=$(kubectl get node $NODE_NAME -o
              jsonpath='{.metadata.labels.domain\.com/nodegroup}')

              echo "$NODE_GROUP" > /tmp/node-labels/node-group
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
          image: bitnami/kubectl:latest
          name: get-node-labels
          volumeMounts:
            - mountPath: /tmp/node-labels/
              name: node-labels
      containers:
        # Override the normal entry point
        # if the label (in this case node group) doesn't match, load the policy with leader election disabled.
        - command:
            - sh
            - '-c'
            - |
              NODE_GROUP=$(cat /tmp/node-labels/node-group)
              echo "$NODE_GROUP"
              if [ "$NODE_GROUP" != "general" ]; then
                /usr/bin/tini -- /usr/local/bin/docker-entrypoint -c /etc/elastic-agent/disable-leader-election/agent.yml -e
              else
                /usr/bin/tini -- /usr/local/bin/docker-entrypoint
              fi
          env:
          envFrom:
            - secretRef:
                name: elastic-agent-monitoring-secrets
          image: docker.elastic.co/beats/elastic-agent:8.16.2
          imagePullPolicy: IfNotPresent
          name: agent
          volumeMounts:
            - mountPath: /tmp/node-labels/
              name: node-labels
            - mountPath: /etc/elastic-agent/disable-leader-election/agent.yml
              name: disable-leader-election
              readOnly: true
              subPath: agent.yml
      volumes:
        - emptyDir: {}
          name: node-labels
        - name: disable-leader-election
          secret:
            defaultMode: 420
            secretName: disable-leader-election
  updateStrategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
```
