### ISSUE TITLE
Agent is unable to connect to kafka instance with authentication.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/elastic-agent#5514]
**Kibana Build details:**
```
VERSION: 8.16.0-SNAPSHOT
BUILD: 78101
COMMIT: f51481d4d697ae23260d2b46ceae7545d3571e95
```

**Preconditions:**
1. 8.16.0 SNAPSHOT Kibana cloud environment should be available.
2. Kafka broker should be available.

**Steps to reproduce:**
1. Add a no auth kafka output under Settings>Agent output: `<public-ip>:9092`
2. Add another kafka output with auth: `<public-ip>:9093`
3. Under agent policy select no auth kafka and observe data under the kafka topic.
4. Now connect the agent with the auth kafka and observe errors like: `[elastic_agent.metricbeat][error] Kafka (topic=qa-test5): kafka: client has run out of available brokers to talk to (Is your cluster reachable?)`

**Note:**
- The issue is reproducible on 8.15.x too.

**Expected Result:**
Agent should be able to connect to kafka instance with authentication.

**Logs:**
[elastic-agent-diagnostics-2024-09-11T11-12-33Z-00.zip](https://github.com/user-attachments/files/16962804/elastic-agent-diagnostics-2024-09-11T11-12-33Z-00.zip)

**Screenshot:**
![Image](https://github.com/user-attachments/assets/be2d4885-4e7e-43ee-93c9-9015795a2f4d)

![Image](https://github.com/user-attachments/assets/ce0c7127-5908-44bb-9cfd-d6d1869e8506)

**Data for no auth:**
![Image](https://github.com/user-attachments/assets/b5336355-d82d-4c32-99a9-51bbfd99782a)

**Previously reported:**
https://github.com/elastic/elastic-agent/issues/4254

**Comment by amolnater-qasource** [comment]
@muskangulati-qasource Please review.

**Comment by amolnater-qasource** [comment]
JFI @cavokz

**Comment by muskangulati-qasource** [comment]
Secondary review on this ticket is done!

**Comment by cmacknz** [comment]
There have been no changes to the Kafka output that could plausibly cause this recently, here's the configuration I see:

```yaml
    8ced6dba-2e37-45e6-95ab-2b53bcb57418:
        broker_timeout: 30
        client_id: Elastic
        compression: none
        headers: []
        hosts:
            - amol-nater-kafka.qasource.elastic.dev:9093
        partition:
            random:
                group_events: 1
        password: <REDACTED>
        required_acks: 1
        sasl:
            mechanism: PLAIN
        ssl:
            verification_mode: full
        timeout: 30
        topic: qa-test5
        type: kafka
        username: elastic
        version: 2.6.0
```

My initial guess would be this is a TLS certificate issue and the logs just aren't telling us. Does changing `verification_mode: none` fix it? 

Along those lines I don't see a CA configured here so if the cert is self-signed agent won't trust it.
