### ISSUE TITLE
Fleet-URL for agnet Is not using what is in configuration yaml

### ISSUE THREAD

**Issue by Thor192** [elastic/elastic-agent#6040]
Please post all questions and issues concerning the Elastic Agent on https://discuss.elastic.co/c/beats
before opening a Github Issue. Your questions will reach a wider audience there,
and if we confirm that there is a bug, then you can open a new issue.

For security vulnerabilities please only send reports to security@elastic.co.
See https://www.elastic.co/community/security for more information.

Please include configurations and logs if available.

For confirmed bugs, please report:
- Version:
- Operating System:
- Discuss Forum URL:
- Steps to Reproduce:
```
Client Version: v1.29.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.1
Talos
Server:
        NODE:        192.168.0.85
        Tag:         v1.7.4
https://discuss.elastic.co/t/agent-fleet-url-not-taking-what-is-in-the-yaml-config/370278
```
First of all I would like to say if anyone reads this or take the time I appreciate it. I'm trying to deploy on a Kubernetes cluster and I cannot get agents that sit inside the kube-system namespace to register with the fleet server that is in a different namespace (eck). I have checked both the flint configuration page and the yaml file that has been provided by the integration. Below is that configuration section.
```
      containers:
        - name: elastic-agent
          image: docker.elastic.co/beats/elastic-agent:8.15.4
          env:
            # Set to 1 for enrollment into Fleet server. If not set, Elastic Agent is run in standalone mode
            - name: FLEET_ENROLL
              value: "1"
            # Set to true to communicate with Fleet with either insecure HTTP or unverified HTTPS
            - name: FLEET_INSECURE
              value: "true"
            # Fleet Server URL to enroll the Elastic Agent into
            # FLEET_URL can be found in Kibana, go to Management > Fleet > Settings
            - name: FLEET_URL
              value: "https://fleet-server-agent-http.eck.svc:8220"
```

Logs indicate that the URL is not being used. 
```
{"log.level":"error","@timestamp":"2024-11-15T08:20:10.159Z","message":"Error dialing lookup elasticsearch-es-http.elastic-system.svc on 10.96.0.10:53: no such host","component":{"binary":"filebeat","dataset":"elastic_agent.filebeat","id":"filestream-monitoring","type":"filestream"},"log":{"source":"filestream-monitoring"},"network.transport":"tcp","server.address":"elasticsearch-es-http.elastic-system.svc:9200","ecs.version":"1.6.0","log.logger":"esclientleg","log.origin":{"file.line":39,"file.name":"transport/logging.go","function":"github.com/elastic/elastic-agent-libs/transport/httpcommon.(*HTTPTransportSettings).RoundTripper.LoggingDialer.func2"},"service.name":"filebeat","ecs.version":"1.6.0"}
```

I'm happy to respond with any information that is needed or even acknowledgement that I'm doing something dumb.
