### ISSUE TITLE
Selective monitoring of Kubernetes workloads from the resource side for agent standalone

### ISSUE THREAD

**Issue by mlunadia** [elastic/elastic-agent#613]

**Comment by ruflin** [comment]
> However could you elaborate more on how a user journey would look like in that case? I guess users would need to download the templates (in batch) from Fleet UI in a second step after the standalone policy and extract them into the inputs.d directory?

You have a good point here. It is really neat that we can offer the user a single yml file to download and it just works. For the Elastic Agent configs, I started to think about separating output configs from input configs. Output config in the standalone case rarely change, inputs much more often and are likely managed by the user eventually in Git or similar. Could still have a single yaml but with multiple sections inside? Have some questions around this, will ping you directly.

**Comment by mlunadia** [comment]
@ChrsMark looking at the user journey, how do we satisfy the two items below?

> Acceptance criteria
On top of the outcome described above
> - Application operator (developer) should have an accessible way to find the list of available hints
> - Application operator (developer) should receive feedback for when a hint is not valid

**Comment by ph** [comment]
@ruflin Yes we do have support for `input.d`, but as I mentioned having the possibility of making the configuration atomic and a single thing to deploy make sense to reduce the possible error to ensure that the right thing at the right version is deployed.

We can support both worklow without too much trouble the IAC and a more click and get.

@chrsmark I am +1 for the proposal above.

Concerning 2, we might want to cleanup the log to make sure we reduce the noise to problem ratio.

**Comment by kpollich** [comment]
> Update Fleet UI accordingly to produce the inputs.d ConfigMap that will then be placed inside the [elastic-agent-standalone/elastic-agent-standalone-daemonset-configmap.yaml](https://github.com/elastic/elastic-agent/blob/main/deploy/kubernetes/elastic-agent-standalone/elastic-agent-standalone-daemonset-configmap.yaml)

Just wanted to chime in from the Fleet UI side of things and make sure I'm understanding correctly. At first glance this looks reasonable. 

So, Fleet UI would be responsible for generating a `ConfigMap` similar to how we currently generate the `manifest` file in the "Add Agent" flyout, e.g. 

<img width="894" alt="image" src="https://user-images.githubusercontent.com/6766512/176020054-1e85ff20-eb24-494a-8491-2d4cd3b830d9.png">

Then, the user will be responsible for manually managing the `ConfigMap` and placing it correctly within the `inputs.d` directory. 

For context, here's an example standalone manifest generated today by Fleet for an integration policy with `system`, `redis`, and `kubernetes` installed: 

<details>

<summary>Show full YML block</summary>

```yml
apiVersion: v1
kind: ConfigMap
metadata:
  name: agent-node-datastreams
  namespace: kube-system
  labels:
    k8s-app: elastic-agent
data:
  agent.yml: |-
    id: d3a50f00-f64c-11ec-82c5-8b396fc6520e
    outputs:
      default:
        type: elasticsearch
        hosts:
          - 'http://192.168.65.2:9200'
        username: '{ES_USERNAME}'
        password: '{ES_PASSWORD}'
    inputs:
      - id: logfile-system-e7822224-fa5c-4291-acd8-49b69e4a44ac
        revision: 1
        name: system-6
        type: logfile
        data_stream:
          namespace: default
        use_output: default
        streams:
          - id: logfile-system.auth-e7822224-fa5c-4291-acd8-49b69e4a44ac
            data_stream:
              type: logs
              dataset: system.auth
            paths:
              - /var/log/auth.log*
              - /var/log/secure*
            exclude_files:
              - .gz$
            multiline:
              pattern: ^\s
              match: after
            processors:
              - add_locale: null
          - id: logfile-system.syslog-e7822224-fa5c-4291-acd8-49b69e4a44ac
            data_stream:
              type: logs
              dataset: system.syslog
            paths:
              - /var/log/messages*
              - /var/log/syslog*
            exclude_files:
              - .gz$
            multiline:
              pattern: ^\s
              match: after
            processors:
              - add_locale: null
        meta:
          package:
            name: system
            version: 1.16.2
      - id: winlog-system-e7822224-fa5c-4291-acd8-49b69e4a44ac
        revision: 1
        name: system-6
        type: winlog
        data_stream:
          namespace: default
        use_output: default
        streams:
          - id: winlog-system.application-e7822224-fa5c-4291-acd8-49b69e4a44ac
            data_stream:
              type: logs
              dataset: system.application
            name: Application
            condition: '${host.platform} == ''windows'''
            ignore_older: 72h
          - id: winlog-system.security-e7822224-fa5c-4291-acd8-49b69e4a44ac
            data_stream:
              type: logs
              dataset: system.security
            name: Security
            condition: '${host.platform} == ''windows'''
            ignore_older: 72h
          - id: winlog-system.system-e7822224-fa5c-4291-acd8-49b69e4a44ac
            data_stream:
              type: logs
              dataset: system.system
            name: System
            condition: '${host.platform} == ''windows'''
            ignore_older: 72h
        meta:
          package:
            name: system
            version: 1.16.2
      - id: system/metrics-system-e7822224-fa5c-4291-acd8-49b69e4a44ac
        revision: 1
        name: system-6
        type: system/metrics
        data_stream:
          namespace: default
        use_output: default
        streams:
          - id: system/metrics-system.fsstat-e7822224-fa5c-4291-acd8-49b69e4a44ac
            data_stream:
              type: metrics
              dataset: system.fsstat
            metricsets:
              - fsstat
            period: 1m
            processors:
              - drop_event.when.regexp:
                  system.fsstat.mount_point: ^/(sys|cgroup|proc|dev|etc|host|lib|snap)($|/)
          - id: >-
              system/metrics-system.filesystem-e7822224-fa5c-4291-acd8-49b69e4a44ac
            data_stream:
              type: metrics
              dataset: system.filesystem
            metricsets:
              - filesystem
            period: 1m
            processors:
              - drop_event.when.regexp:
                  system.filesystem.mount_point: ^/(sys|cgroup|proc|dev|etc|host|lib|snap)($|/)
          - id: system/metrics-system.diskio-e7822224-fa5c-4291-acd8-49b69e4a44ac
            data_stream:
              type: metrics
              dataset: system.diskio
            metricsets:
              - diskio
            diskio.include_devices: null
            period: 10s
          - id: system/metrics-system.cpu-e7822224-fa5c-4291-acd8-49b69e4a44ac
            data_stream:
              type: metrics
              dataset: system.cpu
            metricsets:
              - cpu
            cpu.metrics:
              - percentages
              - normalized_percentages
            period: 10s
          - id: system/metrics-system.process-e7822224-fa5c-4291-acd8-49b69e4a44ac
            data_stream:
              type: metrics
              dataset: system.process
            metricsets:
              - process
            period: 10s
            process.include_top_n.by_cpu: 5
            process.include_top_n.by_memory: 5
            process.cmdline.cache.enabled: true
            process.cgroups.enabled: false
            process.include_cpu_ticks: false
            processes:
              - .*
          - id: system/metrics-system.memory-e7822224-fa5c-4291-acd8-49b69e4a44ac
            data_stream:
              type: metrics
              dataset: system.memory
            metricsets:
              - memory
            period: 10s
          - id: system/metrics-system.network-e7822224-fa5c-4291-acd8-49b69e4a44ac
            data_stream:
              type: metrics
              dataset: system.network
            metricsets:
              - network
            period: 10s
            network.interfaces: null
          - id: >-
              system/metrics-system.socket_summary-e7822224-fa5c-4291-acd8-49b69e4a44ac
            data_stream:
              type: metrics
              dataset: system.socket_summary
            metricsets:
              - socket_summary
            period: 10s
          - id: >-
              system/metrics-system.process.summary-e7822224-fa5c-4291-acd8-49b69e4a44ac
            data_stream:
              type: metrics
              dataset: system.process.summary
            metricsets:
              - process_summary
            period: 10s
          - id: system/metrics-system.load-e7822224-fa5c-4291-acd8-49b69e4a44ac
            data_stream:
              type: metrics
              dataset: system.load
            metricsets:
              - load
            condition: '${host.platform} != ''windows'''
            period: 10s
          - id: system/metrics-system.uptime-e7822224-fa5c-4291-acd8-49b69e4a44ac
            data_stream:
              type: metrics
              dataset: system.uptime
            metricsets:
              - uptime
            period: 10s
        meta:
          package:
            name: system
            version: 1.16.2
      - id: kubernetes/metrics-kubelet-1e00917a-19e7-4c02-8050-c21ba0578e27
        revision: 1
        name: kubernetes-1
        type: kubernetes/metrics
        data_stream:
          namespace: default
        use_output: default
        streams:
          - id: >-
              kubernetes/metrics-kubernetes.container-1e00917a-19e7-4c02-8050-c21ba0578e27
            data_stream:
              type: metrics
              dataset: kubernetes.container
            metricsets:
              - container
            add_metadata: true
            hosts:
              - 'https://${env.NODE_NAME}:10250'
            period: 10s
            bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
            ssl.verification_mode: none
          - id: >-
              kubernetes/metrics-kubernetes.node-1e00917a-19e7-4c02-8050-c21ba0578e27
            data_stream:
              type: metrics
              dataset: kubernetes.node
            metricsets:
              - node
            add_metadata: true
            hosts:
              - 'https://${env.NODE_NAME}:10250'
            period: 10s
            bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
            ssl.verification_mode: none
          - id: >-
              kubernetes/metrics-kubernetes.pod-1e00917a-19e7-4c02-8050-c21ba0578e27
            data_stream:
              type: metrics
              dataset: kubernetes.pod
            metricsets:
              - pod
            add_metadata: true
            hosts:
              - 'https://${env.NODE_NAME}:10250'
            period: 10s
            bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
            ssl.verification_mode: none
          - id: >-
              kubernetes/metrics-kubernetes.system-1e00917a-19e7-4c02-8050-c21ba0578e27
            data_stream:
              type: metrics
              dataset: kubernetes.system
            metricsets:
              - system
            add_metadata: true
            hosts:
              - 'https://${env.NODE_NAME}:10250'
            period: 10s
            bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
            ssl.verification_mode: none
          - id: >-
              kubernetes/metrics-kubernetes.volume-1e00917a-19e7-4c02-8050-c21ba0578e27
            data_stream:
              type: metrics
              dataset: kubernetes.volume
            metricsets:
              - volume
            add_metadata: true
            hosts:
              - 'https://${env.NODE_NAME}:10250'
            period: 10s
            bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
            ssl.verification_mode: none
        meta:
          package:
            name: kubernetes
            version: 1.21.1
      - id: kubernetes/metrics-kube-apiserver-1e00917a-19e7-4c02-8050-c21ba0578e27
        revision: 1
        name: kubernetes-1
        type: kubernetes/metrics
        data_stream:
          namespace: default
        use_output: default
        streams:
          - id: >-
              kubernetes/metrics-kubernetes.apiserver-1e00917a-19e7-4c02-8050-c21ba0578e27
            data_stream:
              type: metrics
              dataset: kubernetes.apiserver
            metricsets:
              - apiserver
            hosts:
              - >-
                https://${env.KUBERNETES_SERVICE_HOST}:${env.KUBERNETES_SERVICE_PORT}
            period: 30s
            condition: '${kubernetes_leaderelection.leader} == true'
            bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
            ssl.certificate_authorities:
              - /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        meta:
          package:
            name: kubernetes
            version: 1.21.1
      - id: kubernetes/metrics-kube-proxy-1e00917a-19e7-4c02-8050-c21ba0578e27
        revision: 1
        name: kubernetes-1
        type: kubernetes/metrics
        data_stream:
          namespace: default
        use_output: default
        streams:
          - id: >-
              kubernetes/metrics-kubernetes.proxy-1e00917a-19e7-4c02-8050-c21ba0578e27
            data_stream:
              type: metrics
              dataset: kubernetes.proxy
            metricsets:
              - proxy
            hosts:
              - 'localhost:10249'
            period: 10s
        meta:
          package:
            name: kubernetes
            version: 1.21.1
      - id: kubernetes/metrics-events-1e00917a-19e7-4c02-8050-c21ba0578e27
        revision: 1
        name: kubernetes-1
        type: kubernetes/metrics
        data_stream:
          namespace: default
        use_output: default
        streams:
          - id: >-
              kubernetes/metrics-kubernetes.event-1e00917a-19e7-4c02-8050-c21ba0578e27
            data_stream:
              type: metrics
              dataset: kubernetes.event
            metricsets:
              - event
            period: 10s
            add_metadata: true
            skip_older: true
            condition: '${kubernetes_leaderelection.leader} == true'
        meta:
          package:
            name: kubernetes
            version: 1.21.1
      - id: filestream-container-logs-1e00917a-19e7-4c02-8050-c21ba0578e27
        revision: 1
        name: kubernetes-1
        type: filestream
        data_stream:
          namespace: default
        use_output: default
        streams:
          - id: >-
              filestream-kubernetes.container_logs-1e00917a-19e7-4c02-8050-c21ba0578e27
            data_stream:
              type: logs
              dataset: kubernetes.container_logs
            paths:
              - '/var/log/containers/*${kubernetes.container.id}.log'
            prospector.scanner.symlinks: true
            parsers:
              - container:
                  stream: all
                  format: auto
        meta:
          package:
            name: kubernetes
            version: 1.21.1
      - id: logfile-redis-fc56b140-3154-4907-9eb3-991ea4ab6569
        revision: 1
        name: redis-1
        type: logfile
        data_stream:
          namespace: default
        use_output: default
        streams:
          - id: logfile-redis.log-fc56b140-3154-4907-9eb3-991ea4ab6569
            data_stream:
              type: logs
              dataset: redis.log
            paths:
              - /var/log/redis/redis-server.log*
              - /var/log/redis/my-cool-redis.log*
            tags:
              - redis-log
            exclude_files:
              - .gz$
            exclude_lines:
              - '^\s+[\-`(''.|_]'
        meta:
          package:
            name: redis
            version: 1.3.1
      - id: redis-redis-fc56b140-3154-4907-9eb3-991ea4ab6569
        revision: 1
        name: redis-1
        type: redis
        data_stream:
          namespace: default
        use_output: default
        streams:
          - id: redis-redis.slowlog-fc56b140-3154-4907-9eb3-991ea4ab6569
            data_stream:
              type: logs
              dataset: redis.slowlog
            hosts:
              - '127.0.0.1:6379'
              - 'https://my.redis:6379'
            password: ''
        meta:
          package:
            name: redis
            version: 1.3.1
      - id: redis/metrics-redis-fc56b140-3154-4907-9eb3-991ea4ab6569
        revision: 1
        name: redis-1
        type: redis/metrics
        data_stream:
          namespace: default
        use_output: default
        streams:
          - id: redis/metrics-redis.info-fc56b140-3154-4907-9eb3-991ea4ab6569
            data_stream:
              type: metrics
              dataset: redis.info
            metricsets:
              - info
            hosts:
              - '127.0.0.1:6379'
              - 'https://my.redis:6379'
            idle_timeout: 20s
            maxconn: 10
            network: tcp
            period: 10s
          - id: redis/metrics-redis.key-fc56b140-3154-4907-9eb3-991ea4ab6569
            data_stream:
              type: metrics
              dataset: redis.key
            metricsets:
              - key
            hosts:
              - '127.0.0.1:6379'
              - 'https://my.redis:6379'
            idle_timeout: 20s
            key.patterns:
              - limit: 20
                pattern: '*'
            maxconn: 10
            network: tcp
            period: 10s
          - id: redis/metrics-redis.keyspace-fc56b140-3154-4907-9eb3-991ea4ab6569
            data_stream:
              type: metrics
              dataset: redis.keyspace
            metricsets:
              - keyspace
            hosts:
              - '127.0.0.1:6379'
              - 'https://my.redis:6379'
            idle_timeout: 20s
            maxconn: 10
            network: tcp
            period: 10s
        meta:
          package:
            name: redis
            version: 1.3.1
    revision: 3
    agent:
      monitoring:
        namespace: default
        use_output: default
        enabled: true
        logs: true
        metrics: true
    output_permissions:
      default:
        _elastic_agent_monitoring:
          indices:
            - names:
                - logs-elastic_agent.apm_server-default
              privileges: &ref_0
                - auto_configure
                - create_doc
            - names:
                - metrics-elastic_agent.apm_server-default
              privileges: *ref_0
            - names:
                - logs-elastic_agent.auditbeat-default
              privileges: *ref_0
            - names:
                - metrics-elastic_agent.cloudbeat-default
              privileges: *ref_0
            - names:
                - metrics-elastic_agent.elastic_agent-default
              privileges: *ref_0
            - names:
                - logs-elastic_agent.cloudbeat-default
              privileges: *ref_0
            - names:
                - metrics-elastic_agent.endpoint_security-default
              privileges: *ref_0
            - names:
                - logs-elastic_agent-default
              privileges: *ref_0
            - names:
                - metrics-elastic_agent.auditbeat-default
              privileges: *ref_0
            - names:
                - logs-elastic_agent.endpoint_security-default
              privileges: *ref_0
            - names:
                - logs-elastic_agent.filebeat-default
              privileges: *ref_0
            - names:
                - metrics-elastic_agent.filebeat-default
              privileges: *ref_0
            - names:
                - logs-elastic_agent.fleet_server-default
              privileges: *ref_0
            - names:
                - logs-elastic_agent.heartbeat-default
              privileges: *ref_0
            - names:
                - metrics-elastic_agent.fleet_server-default
              privileges: *ref_0
            - names:
                - logs-elastic_agent.metricbeat-default
              privileges: *ref_0
            - names:
                - metrics-elastic_agent.metricbeat-default
              privileges: *ref_0
            - names:
                - metrics-elastic_agent.heartbeat-default
              privileges: *ref_0
            - names:
                - logs-elastic_agent.osquerybeat-default
              privileges: *ref_0
            - names:
                - logs-elastic_agent.packetbeat-default
              privileges: *ref_0
            - names:
                - metrics-elastic_agent.osquerybeat-default
              privileges: *ref_0
            - names:
                - metrics-elastic_agent.packetbeat-default
              privileges: *ref_0
        _elastic_agent_checks:
          cluster:
            - monitor
        system-6:
          indices:
            - names:
                - logs-system.auth-default
              privileges: *ref_0
            - names:
                - logs-system.syslog-default
              privileges: *ref_0
            - names:
                - logs-system.application-default
              privileges: *ref_0
            - names:
                - logs-system.security-default
              privileges: *ref_0
            - names:
                - logs-system.system-default
              privileges: *ref_0
            - names:
                - metrics-system.fsstat-default
              privileges: *ref_0
            - names:
                - metrics-system.filesystem-default
              privileges: *ref_0
            - names:
                - metrics-system.diskio-default
              privileges: *ref_0
            - names:
                - metrics-system.cpu-default
              privileges: *ref_0
            - names:
                - metrics-system.process-default
              privileges: *ref_0
            - names:
                - metrics-system.memory-default
              privileges: *ref_0
            - names:
                - metrics-system.network-default
              privileges: *ref_0
            - names:
                - metrics-system.socket_summary-default
              privileges: *ref_0
            - names:
                - metrics-system.process.summary-default
              privileges: *ref_0
            - names:
                - metrics-system.load-default
              privileges: *ref_0
            - names:
                - metrics-system.uptime-default
              privileges: *ref_0
        kubernetes-1:
          indices:
            - names:
                - metrics-kubernetes.container-default
              privileges: *ref_0
            - names:
                - metrics-kubernetes.node-default
              privileges: *ref_0
            - names:
                - metrics-kubernetes.pod-default
              privileges: *ref_0
            - names:
                - metrics-kubernetes.system-default
              privileges: *ref_0
            - names:
                - metrics-kubernetes.volume-default
              privileges: *ref_0
            - names:
                - metrics-kubernetes.apiserver-default
              privileges: *ref_0
            - names:
                - metrics-kubernetes.proxy-default
              privileges: *ref_0
            - names:
                - metrics-kubernetes.event-default
              privileges: *ref_0
            - names:
                - logs-kubernetes.container_logs-default
              privileges: *ref_0
        redis-1:
          indices:
            - names:
                - logs-redis.log-default
              privileges: *ref_0
            - names:
                - logs-redis.slowlog-default
              privileges: *ref_0
            - names:
                - metrics-redis.info-default
              privileges: *ref_0
            - names:
                - metrics-redis.key-default
              privileges: *ref_0
            - names:
                - metrics-redis.keyspace-default
              privileges: *ref_0

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: elastic-agent
  namespace: kube-system
  labels:
    app: elastic-agent
spec:
  selector:
    matchLabels:
      app: elastic-agent
  template:
    metadata:
      labels:
        app: elastic-agent
    spec:
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
      serviceAccountName: elastic-agent
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: elastic-agent
          image: docker.elastic.co/beats/elastic-agent:8.4.0
          args: [
            "-c", "/etc/agent.yml",
            "-e",
            "-d", "'*'",
          ]
          env:
            - name: ES_USERNAME
              value: "elastic"
            - name: ES_PASSWORD
              value: "changeme"
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          securityContext:
            runAsUser: 0
          resources:
            limits:
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 200Mi
          volumeMounts:
            - name: datastreams
              mountPath: /etc/agent.yml
              readOnly: true
              subPath: agent.yml
            - name: proc
              mountPath: /hostfs/proc
              readOnly: true
            - name: etc-kubernetes
              mountPath: /hostfs/etc/kubernetes
            - name: var-lib
              mountPath: /hostfs/var/lib
              readOnly: true
            - name: cgroup
              mountPath: /hostfs/sys/fs/cgroup
              readOnly: true
            - name: varlibdockercontainers
              mountPath: /var/lib/docker/containers
              readOnly: true
            - name: varlog
              mountPath: /var/log
              readOnly: true
            - name: passwd
              mountPath: /hostfs/etc/passwd
              readOnly: true
            - name: group
              mountPath: /hostfs/etc/group
              readOnly: true
            - name: systemd
              mountPath: /hostfs/etc/systemd
              readOnly: true
      volumes:
        - name: datastreams
          configMap:
            defaultMode: 0640
            name: agent-node-datastreams
        - name: proc
          hostPath:
            path: /proc
        - name: etc-kubernetes
          hostPath:
            path: /etc/kubernetes
        - name: var-lib
          hostPath:
            path: /var/lib
        - name: passwd
          hostPath:
            path: /etc/passwd
        - name: group
          hostPath:
            path: /etc/group
        - name: cgroup
          hostPath:
            path: /sys/fs/cgroup
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
        - name: varlog
          hostPath:
            path: /var/log
        - name: systemd
          hostPath:
            path: /etc/systemd
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: elastic-agent
subjects:
  - kind: ServiceAccount
    name: elastic-agent
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: elastic-agent
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: kube-system
  name: elastic-agent
subjects:
  - kind: ServiceAccount
    name: elastic-agent
    namespace: kube-system
roleRef:
  kind: Role
  name: elastic-agent
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: elastic-agent-kubeadm-config
  namespace: kube-system
subjects:
  - kind: ServiceAccount
    name: elastic-agent
    namespace: kube-system
roleRef:
  kind: Role
  name: elastic-agent-kubeadm-config
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: elastic-agent
  labels:
    k8s-app: elastic-agent
rules:
  - apiGroups: [""]
    resources:
      - nodes
      - namespaces
      - events
      - pods
      - services
      - configmaps
      - serviceaccounts
    verbs: ["get", "list", "watch"]
  # Enable this rule only if planing to use kubernetes_secrets provider
  #- apiGroups: [""]
  #  resources:
  #  - secrets
  #  verbs: ["get"]
  - apiGroups: ["extensions"]
    resources:
      - replicasets
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources:
      - statefulsets
      - deployments
      - replicasets
    verbs: ["get", "list", "watch"]
  - apiGroups: ["batch"]
    resources:
      - jobs
      - cronjobs
    verbs: ["get", "list", "watch"]
  - apiGroups:
      - ""
    resources:
      - nodes/stats
    verbs:
      - get
  # required for apiserver
  - nonResourceURLs:
      - "/metrics"
    verbs:
      - get
  # required for cloudbeat
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources:
      - clusterrolebindings
      - clusterroles
      - rolebindings
      - roles
    verbs: ["get", "list", "watch"]
  - apiGroups: ["networking.k8s.io"]
    resources:
      - ingressclasses
      - ingresses
    verbs: ["get", "list", "watch"]
  - apiGroups: ["policy"]
    resources:
      - podsecuritypolicies
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: elastic-agent
  # should be the namespace where elastic-agent is running
  namespace: kube-system
  labels:
    k8s-app: elastic-agent
rules:
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs: ["get", "create", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: elastic-agent-kubeadm-config
  namespace: kube-system
  labels:
    k8s-app: elastic-agent
rules:
  - apiGroups: [""]
    resources:
      - configmaps
    resourceNames:
      - kubeadm-config
    verbs: ["get"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: elastic-agent
  namespace: kube-system
  labels:
    k8s-app: elastic-agent
---
```

</details>

The relevant section is probably the various redis inputs, e.g. 

```yml
- id: logfile-redis-fc56b140-3154-4907-9eb3-991ea4ab6569
  revision: 1
  name: redis-1
  type: logfile
  data_stream:
    namespace: default
  use_output: default
  streams:
    - id: logfile-redis.log-fc56b140-3154-4907-9eb3-991ea4ab6569
      data_stream:
        type: logs
        dataset: redis.log
      paths:
        - /var/log/redis/redis-server.log*
        - /var/log/redis/my-cool-redis.log*
      tags:
        - redis-log
      exclude_files:
        - .gz$
      exclude_lines:
        - '^\s+[\-`(''.|_]'
  meta:
    package:
      name: redis
      version: 1.3.1
  - id: redis-redis-fc56b140-3154-4907-9eb3-991ea4ab6569
  revision: 1
  name: redis-1
  type: redis
  data_stream:
    namespace: default
  use_output: default
  streams:
    - id: redis-redis.slowlog-fc56b140-3154-4907-9eb3-991ea4ab6569
      data_stream:
        type: logs
        dataset: redis.slowlog
      hosts:
        - '127.0.0.1:6379'
        - 'https://my.redis:6379'
      password: ''
  meta:
    package:
      name: redis
      version: 1.3.1
  - id: redis/metrics-redis-fc56b140-3154-4907-9eb3-991ea4ab6569
  revision: 1
  name: redis-1
  type: redis/metrics
  data_stream:
    namespace: default
  use_output: default
  streams:
    - id: redis/metrics-redis.info-fc56b140-3154-4907-9eb3-991ea4ab6569
      data_stream:
        type: metrics
        dataset: redis.info
      metricsets:
        - info
      hosts:
        - '127.0.0.1:6379'
        - 'https://my.redis:6379'
      idle_timeout: 20s
      maxconn: 10
      network: tcp
      period: 10s
    - id: redis/metrics-redis.key-fc56b140-3154-4907-9eb3-991ea4ab6569
      data_stream:
        type: metrics
        dataset: redis.key
      metricsets:
        - key
      hosts:
        - '127.0.0.1:6379'
        - 'https://my.redis:6379'
      idle_timeout: 20s
      key.patterns:
        - limit: 20
          pattern: '*'
      maxconn: 10
      network: tcp
      period: 10s
    - id: redis/metrics-redis.keyspace-fc56b140-3154-4907-9eb3-991ea4ab6569
      data_stream:
        type: metrics
        dataset: redis.keyspace
      metricsets:
        - keyspace
      hosts:
        - '127.0.0.1:6379'
        - 'https://my.redis:6379'
      idle_timeout: 20s
      maxconn: 10
      network: tcp
      period: 10s
  meta:
    package:
      name: redis
      version: 1.3.1
```

So, rather than a block like this, which uses the [Redis integration's stream template](https://github.com/elastic/integrations/blob/f49a09de586201a7b08157032eae914a8ffce79f/packages/redis/data_stream/info/agent/stream/stream.yml.hbs#L2-L5)

```yml
hosts:
  - '127.0.0.1:6379'
  - 'https://my.redis:6379'
```

Fleet would output a block like this:

```yml
hosts:
  - "${docker.hints.redis.info.host|kubernetes.hints.redis.info.host|'127.0.0.1:6379'}"
```

My question here is how does "know" about the hint string? Is it included in the package definition somewhere? e.g. would the `redis` package include a `k8s/templates/info.yml` file or something like that for the `info` input? I'm imagining a workflow like 

```
Fleet shows "add agent" flyout
User selects standalone option
Fleet generates ConfigMap YML block
  for each integration policy on the current agent policy:
    if the package exports a k8's input template:
      append a compiled input block to the ConfigMap YML based on the exported template
Fleet renders ConfigMap YML block
```

Also, do we ignore user input in cases where we're using these hint strings instead, or are they intended to solve as default values overridden by the user? e.g. should the `127.0.0.1:6379` string at the end of the hint string honor user input or is it just a hardcoded default?

**Comment by gizas** [comment]
> * Application operator (developer) should have an accessible way to find the list of available hints

For the first I was thinking that as long as we produce the templates of input.d directory we can also produce the list of available hints to be used. But this can be done as even in later stages of project. We can even render only the relevant template according only to the integrations enabled per case if makes sense.

**Comment by ChrsMark** [comment]
Thanks for the extra feedback folks!

@kpollich trying to answer your questions below:

> Then, the user will be responsible for manually managing the ConfigMap and placing it correctly within the inputs.d directory.

In k8s we can avoid having the users to manually place the `ConfigMap` in the `inputs.d` directory since we can define the file "tree" inside the `ConfigMap` like what we do at https://github.com/elastic/beats/blob/main/deploy/kubernetes/metricbeat/metricbeat-daemonset-configmap.yaml#L79
which is then mounted in Metrcibeat's Pod at https://github.com/elastic/beats/blob/main/deploy/kubernetes/metricbeat-kubernetes.yaml#L198. 

The only thing FleetUI needs to do is to produce sth like the following:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: elastic-agent-standalone-inputs
data:
  redis.yml: |-
    - data_stream: ...
  ....
  apache.yml: |-
  ....
  nginx.yml: |-
  ....
```
Then we just need to mount it inside the Agent's Pod as a directory using sth like the following:

```yml
...
   volumeMounts:
     - name: inputs
          mountPath: /usr/share/elastic-agent/inputs.d
          readOnly: true
   volumes:
      - name: modules
        configMap:
          defaultMode: 0640
          name: elastic-agent-standalone-inputs
...
```

See https://github.com/elastic/beats/blob/main/deploy/kubernetes/metricbeat-kubernetes.yaml#L197-L220 for a complete example.


In terms of UX, since we are maintaining all those manifests I see 2 possible paths that could be supported at the same time.

1. If users use the `generate the manifest file in the "Add Agent" flyout, e.g.` then everything will be constructed by Fleet UI and users just get the manifest with everything needed inside.
2. If users are downloading the manifests from our upstream following https://www.elastic.co/guide/en/fleet/current/running-on-kubernetes-standalone.html, then we can just add an extra step to our docs to point them to go to Fleet UI and generate only the `inputs` `ConfigMap`. This will be a single ConfigMap with only the "templates" inside (it is the same in step 1 too) which then users should place in the same directory with where they have the `elastic-agent-standalone-kubernetes.yaml` manifest and `deploy` this `ConfigMap` first before deploying Agent.

Ofc we can improve the UX a lot here but this can happen on top of the basic/core implementation. At some point we could even provide the users to only use step 1 instead of downloading the manifests from the upstream. I would leave it to @mlunadia to provide better directions here but as I mentioned for now we can just expose it with the 2 simple ways provided above.


>  My question here is how does "know" about the hint string? Is it included in the package definition somewhere? e.g. would the redis package include a k8s/templates/info.yml file or something like that for the info input?

The current idea is to only provide support for a specific set/list of hints like `host`, `period`, `timeout`, `data_stream`, `log_stream` etc. This is how the feature was supported in [Beats](https://www.elastic.co/guide/en/beats/metricbeat/current/configuration-autodiscover-hints.html) and we didn't have any big indicator that users would need sth different. 

Also keeping the list of hints specific provides more control to what we accept as inputs from the users and also it's more secure than providing the full flexibility to set everything via the hints. Keep in mind that this mechanism will be exposed to everyone that has access to `deploy` Pods on the cluster. 

So to answer your question if we have a specific set of hints that we support then Fleet UI can just look and replace the respective settings, leveraging their default values etc. Nothing changes in the way packages are developed. I guess this would be doable?


> Also, do we ignore user input in cases where we're using these hint strings instead, or are they intended to solve as default values overridden by the user? e.g. should the 127.0.0.1:6379 string at the end of the hint string honor user input or is it just a hardcoded default?

For all the settings that will not be exposed as hints we will use the default values as defined in the packages' specs. For those that are exposed as hints (as proposed above) we will have a logic to set them like `"${kubernetes.hints.redis.info.host|'127.0.0.1:6379'}"`. So in that case we imply that for this setting we will either use the hint if provided or we will use the default value of the package.
Tbh I don't see how users could overwrite those :thinking_face: , the idea here is that we generate the "templates" in a low level format compatible to be populated by hints mechanism. So since we have conditions like  `condition: "${kubernetes.hints.redis.key.enabled|}"` it's almost impossible this input block to be enabled by anything else other than the "hints" mechanism. 



Since I have already started experimenting a bit with the backend implementation here is a ConfigMap that we would need to have:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: elastic-agent-standalone-inputs
data:
  redis.yml: |-
    inputs:
     - name: templates.d/redis/0.3.6
       type: redis/metrics
       data_stream.namespace: default
       use_output: default
       streams:
         - data_stream:
             dataset: redis.info
             type: metrics
           metricsets:
           - info
           hosts:
           - "${kubernetes.hints.redis.info.host|'127.0.0.1:6379'}"
           idle_timeout: 20s
           maxconn: 10
           network: tcp
           period: "${kubernetes.hints.redis.info.period|'10s'}"
           condition: ${kubernetes.hints.redis.info.enabled} == true
         - data_stream:
             dataset: redis.key
             type: metrics
           metricsets:
           - key
           hosts:
           - "${kubernetes.hints.redis.key.host|'127.0.0.1'}:${kubernetes.hints.redis.info.port|'6379'}"
           idle_timeout: 20s
           key.patterns:
             - limit: 20
               pattern: '*'
           maxconn: 10
           network: tcp
           period: "${kubernetes.hints.redis.key.period|'10s'}"
           condition: ${kubernetes.hints.redis.key.enabled} == true
```
