### ISSUE TITLE
otel: trim non-otel configuration from when validating the otel configuration

### ISSUE THREAD

**Issue by mauri870** [elastic/elastic-agent#6235]
Now with the groundwork for the hybrid agent done in https://github.com/elastic/elastic-agent/issues/5796 it is possible to have a yaml config file with both beats and otel configuration, for example:

<details>
<summary>hybrid-agent-config.yml</summary>

```yml
# normal agent config
filebeat.inputs:
  - type: filestream
    id: filestream-filebeat
    enabled: true
    paths:
      - /tmp/filebeat.log
output.elasticsearch:
  hosts:
    - https://esendpoint
  api_key: api-key
  index: filebeat-index
# and otel config on the same file
receivers:
  filebeatreceiver:
    filebeat:
      inputs:
        - type: filestream
          id: filestream-fbreceiver
          enabled: true
          paths:
            - /tmp/fbreceiver.log
    output:
      otelconsumer:
    logging:
      level: info
      selectors:
        - '*'
    path.home: /tmp
    queue.mem.flush.timeout: 0s
exporters:
  elasticsearch/log:
    endpoints:
      - https://esendpoint
    api_key: api-key
    logs_index: fbreceiver-index
    batcher:
      enabled: true
      flush_timeout: 1s
    mapping:
      mode: bodymap
service:
  pipelines:
    logs:
      receivers:
        - filebeatreceiver
      exporters:
        - elasticsearch/log
```

</details>

When running `./elastic-agent otel validate --config=./hybrid-agent-config.yml` I get the following error:

```txt
failed to get config: cannot unmarshal the configuration: decoding failed due to the following error(s):

'' has invalid keys: filebeat.inputs, output.elasticsearch
```

When validating this file, we need to remove any top-level Beats-specific configuration to ensure that only the OpenTelemetry-specific components are validated.
