### ISSUE TITLE
`:` character in dynamic variables breaks the rendering

### ISSUE THREAD

**Issue by ChrsMark** [elastic/elastic-agent#624]
It seems that having `:` character as part of dynamic variables' default value breaks the whole rendering.

A configuration like the following are not able to get rendered:
```yml
inputs:
  - name: templates.d/redis/0.3.6
    type: redis/metrics
    data_stream.namespace: default
    use_output: default
    streams:
      - data_stream:
          dataset: redis.info
          type: metrics
        metricsets:
         - info
        hosts:
          - "${kubernetes.hints.redis.info.host|'127.0.0.1:6379'}"
```

Running `./elastic-agent -e -c ./elastic-agent.yml inspect output -o default` I get the following:

```console
{"log.level":"error","@timestamp":"2022-06-27T15:31:21.461+0300","log.origin":{"file.name":"emitter/controller.go","file.line":123},"message":"Failed to render configuration with latest context from composable controller: starting ${ is missing ending }","ecs.version":"1.6.0"}
```

This is important in order to define default values for `hosts` settings.
