### ISSUE TITLE
[Helm] Enable leader election by default for Fleet Managed agent installation with perNode preset

### ISSUE THREAD

**Issue by eedugon** [elastic/elastic-agent#6284]
When following the instructions at https://www.elastic.co/guide/en/fleet/current/example-kubernetes-fleet-managed-agent-helm.html and installing a Fleet Managed with preset `perNode` with something like:

```
helm install demo ./deploy/helm/elastic-agent \
--set agent.fleet.enabled=true \
--set agent.fleet.url=https://fleet-svc.default.svc \
--set agent.fleet.token=myToken \
--set agent.fleet.preset=perNode \
--set agent.fleet.insecure=true
```

We get the following `agent.yml` generated in a secret:

```
  agent.yml: |-
    fleet:
      enabled: true
    providers:
      kubernetes:
        node: ${NODE_NAME}
        scope: node
      kubernetes_leaderelection:
        enabled: false
        leader_lease: demo-pernode
```

If the helm chart disables the leader election then we shouldn't continue with the documentation instructions as the `kubernetes integration` default settings are intended for agents with the `leader` mechanism enabled.

I suggest to keep leader election enabled for this use case: fleet.enabled=true and fleet.preset=perNode

Of course the user could disable leaderElection if not needed / wanted.

cc: @pkoutsovasilis

**Comment by strawgate** [comment]
In this case, do we need to touch the providers configuration at all?

```
    providers:
      kubernetes:
        node: ${NODE_NAME}
        scope: node
      kubernetes_leaderelection:
        enabled: false
        leader_lease: demo-pernode
```

Wouldn't leader election be enabled by the Kubernetes integration if it was setup?
