### ISSUE TITLE
[Bug] Elastic Agent higher "Unhealthy" rates of Kubernetes Agents in `8.17.1`

### ISSUE THREAD

**Issue by BenB196** [elastic/elastic-agent#6596]
For confirmed bugs, please report:
- Version: 8.17.1
- Operating System: Kubernetes/AWS EKS (1.31)
- Steps to Reproduce:
  1. Create an Elastic Agent policy
  2. Define a Kubernetes Integration policy
     - Currently using `v1.70.0`
     - Only the "Kubernetes Container Logs" part of the integration needs to be defined
       - (Below is an example config)
  3. Deploy an Elastic Agent DaemonSet to a Kubernetes cluster (that has active pods that logs can be collected from)
  4. Observe that the Elastic Agent will randomly/occasionally enter an unhealthy state because the Filestream integration can report the following error:
     - `status: (DEGRADED) error while reading from source: context canceled`

This issue has mainly surfaced in 8.17.x (I never ran 8.17.0, so my observations come only from 8.17.1), this issue was not observed in 8.16.2. I'm not sure if this is a new "issue", or just because there is now better health reporting in the Elastic Agent.

"Higher" unhealthy rates in this case means: I have 1 environment that is still on a lower (8.14.3) version, that is reporting 0 unhealthy agent, out of 43. But in an environment that has been upgraded to 8.17.1, of the 39 agents running, 32 agents are reporting unhealthy with various instances of the error/issue below.

`elastic-agent status` output example

```
/usr/share/elastic-agent# elastic-agent status
┌─ fleet
│  └─ status: (HEALTHY) Connected
└─ elastic-agent
   ├─ status: (DEGRADED) 1 or more components/units in a degraded state
   └─ filestream-a5dd7be0-64fe-11ed-ab11-d7fe3acf785c
      ├─ status: (HEALTHY) Healthy: communicating with pid '30'
      ├─ filestream-a5dd7be0-64fe-11ed-ab11-d7fe3acf785c-filestream-container-logs-45ab39df-294d-403d-bd66-67a27ff0412c-kubernetes-7acaaf99-ff64-4393-8142-90525e4aac54.aws-cluster-autoscaler
      │  └─ status: (DEGRADED) error while reading from source: context canceled
      └─ filestream-a5dd7be0-64fe-11ed-ab11-d7fe3acf785c-filestream-container-logs-45ab39df-294d-403d-bd66-67a27ff0412c-kubernetes-f1a3a7e8-7dc3-4a31-a7a4-be9dcafe3e0b.apm-server
         └─ status: (DEGRADED) error while reading from source: context canceled
```

Integration policy definition:

```yaml
- id: filestream-container-logs-45ab39df-294d-403d-bd66-67a27ff0412c
    name: container-logs-generic
    revision: 40
    type: filestream
    use_output: a5dd7be0-64fe-11ed-ab11-d7fe3acf785c
    meta:
      package:
        name: kubernetes
        version: 1.70.0
    data_stream:
      namespace: private.default.development
    package_policy_id: 45ab39df-294d-403d-bd66-67a27ff0412c
    streams:
      - id: >-
          kubernetes-container-logs-${kubernetes.pod.name}-${kubernetes.container.id}
        data_stream:
          dataset: kubernetes.container_logs
        paths:
          - '/var/log/containers/*${kubernetes.container.id}.log'
        prospector.scanner.symlinks: true
        file_identity.fingerprint: null
        prospector:
          scanner:
            fingerprint:
              enabled: true
              offset: 0
              length: 64
        condition: '${kubernetes.annotations.co.elastic.logs/enabled} != ''false'''
        parsers:
          - container:
              stream: all
              format: auto
          - multiline:
              type: pattern
              pattern: >-
                ^(\[[0-9]{2}:[0-9]{2}:[0-9]{2}
                [a-zA-Z]{3}\]|(time="|\s)?(\[)?[0-9]{4}[/-][0-9]{2}[/-][0-9]{2}|[A-Za-z]+:\s+[0-9(]|\w+\s+([0-9]{4}[/-][0-9]{2}[/-][0-9]{2}\s+)?[0-9]{2}:[0-9]{2}:[0-9]{2}|\{\"|\w+:\w+\s[0-9]{2}\s+\w+\s+[0-9]{4}\s+|Caching\sschedule\.\.\.|RetryCount=[0-9]+\s|Failed\sto\s|Executing\sbatch\s|Done\sBulk\sUpload\s|level=\w+\sts=[0-9]{4}-[0-9]{2}-[0-9]{2})
              negate: true
              match: after
        processors:
          - add_fields:
              target: kubernetes
              fields:
                annotations.elastic_co/dataset: '${kubernetes.annotations.elastic.co/dataset|""}'
                annotations.elastic_co/namespace: '${kubernetes.annotations.elastic.co/namespace|""}'
                annotations.elastic_co/preserve_original_event: >-
                  ${kubernetes.annotations.elastic.co/preserve_original_event|""}
          - drop_fields:
              fields:
                - kubernetes.annotations.elastic_co/dataset
              when:
                equals:
                  kubernetes.annotations.elastic_co/dataset: ''
              ignore_missing: true
          - drop_fields:
              fields:
                - kubernetes.annotations.elastic_co/namespace
              when:
                equals:
                  kubernetes.annotations.elastic_co/namespace: ''
              ignore_missing: true
          - drop_fields:
              fields:
                - kubernetes.annotations.elastic_co/preserve_original_event
              when:
                equals:
                  kubernetes.annotations.elastic_co/preserve_original_event: ''
              ignore_missing: true
          - add_tags:
              tags:
                - preserve_original_event
              when:
                and:
                  - has_fields:
                      - >-
                        kubernetes.annotations.elastic_co/preserve_original_event
                  - regexp:
                      kubernetes.annotations.elastic_co/preserve_original_event: ^(?i)true$
          - add_fields:
              target: service
              fields:
                name: >-
                  ${kubernetes.labels.app|kubernetes.labels.app.kubernetes.io/name|kubernetes.deployment.name|kubernetes.statefulset.name|kubernetes.replicaset.name|"unknown"}
```

**Comment by jlind23** [comment]
> This issue has mainly surfaced in 8.17.x (I never ran 8.17.0, so my observations come only from 8.17.1), this issue was not observed in 8.16.2. I'm not sure if this is a new "issue", or just because there is now better health reporting in the Elastic Agent.

I bet that's the reason but @belimawr might be best to answer here.

**Comment by drew-cccs** [comment]
Chiming in to say that I'm observing this as well across three clusters.

**Comment by belimawr** [comment]
I've been investigating it and the good news is that I managed to reproduce the issue 🎉. However it'snot related to the version, at least in the way I reproduced it.

I'm doing my tests on my development machine running kind  and kubernetes in the following versions:
```
tiago@millennium-falcon /tmp % kind version
kind v0.26.0 go1.23.4 linux/amd64
tiago@millennium-falcon /tmp % k version
Client Version: v1.32.1
Kustomize Version: v5.5.0
Server Version: v1.32.0
tiago@millennium-falcon /tmp % 
```

In my case the issue only happens when I overload my machine (all CPUs at 95%+ utilisation) with a deployment that generates a lot of logs, for that I used [flog](https://github.com/mingrammer/flog):
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flog-deployment
  labels:
    app: flog
spec:
  replicas: 5
  selector:
    matchLabels:
      app: flog
  template:
    metadata:
      labels:
        app: flog
    spec:
      containers:
      - name: flog
        image: mingrammer/flog
        command:
          - 'flog'
          - '-l'
          - '-t' # output type
          - 'stdout' # the default, but let's be explicit
          # - '-s'
          # - '1'
          # - '-d'
          # - '1'
```
When the last 4 lines are commented out, it will generate logs as quick as possible, uncommenting them brings the log rate to one line a second.

When the log throughput is high my Elastic-Agent/Filebeat reaches and stays on this degraded state, once I bring the load back to levels my machine can handle, the Elastic-Agent goes back to a healthy state.

The error itself is indeed quite unusual for the Filestream input and I did not see any other related error logs from Filebeat.

I also looked at the resource consumption, the difference in CPU usage returned by `kubectl top pods` was `< 50m`, with `v8.17.1` having the slightly higher usage. I would not say that `v8.17.1` performs worse because my whole machine was overloaded and I only collected a few data points.

With that all said, I'd try looking at the resource consumption of the host or even the Elastic-Agent pod to see if any of them are reaching their limits. If the Elastic-Agent is reaching their CPU limits, try increasing the limit.

Also, take a look at your logs to see if you can spot any other errors.
