### ISSUE TITLE
Support probabilistic_sampler for EDOT Collector

### ISSUE THREAD

**Issue by yomduf** [elastic/elastic-agent#6617]
**Describe the enhancement:**

**Describe a specific use case for the enhancement or feature:**

**What is the definition of done?**

The goal is to support the probabilistic_sampler for elastic agent as described here https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/processor/probabilisticsamplerprocessor/README.md 
```
processors:
  memory_limiter:
  ...
  probabilistic_sampler:
    sampling_percentage: 50
    hash_seed: 22
  ...
```
