### ISSUE TITLE
Elastic-Agent does not seem to support all of Beats processor features

### ISSUE THREAD

**Issue by belimawr** [elastic/elastic-agent#6820]
While I was working on https://github.com/elastic/elastic-agent/pull/6730, I tried to create the following processor logic for the filebeat-monitoring (the processors there are placeholders):
```
        - if:
            has_fields:
              - "data_stream.dataset"
          then:
            - add_fields:
                fields:
                  then_run: true
          else:
            - add_fields:
                fields:
                  then_run: false
                  else_run: true
```

It can be translated to the Go code to generate the monitoring configuration:
```
				map[string]interface{}{
					"if": map[string]interface{}{
						"has_fields": []interface{}{
							"component.dataset",
						},
					}, // condition
					"then": []map[string]interface{}{
						{
							"copy_fields": map[string]interface{}{
								"fields": []interface{}{
									map[string]interface{}{
										"from": "component.dataset",
										"to":   "data_stream.dataset",
									},
								},
							},
						},
					},
					"else": []map[string]interface{}{
						{
							"copy_fields": map[string]interface{}{
								"fields": []interface{}{
									map[string]interface{}{
										"from": "data_stream.dataset_original",
										"to":   "data_stream.dataset",
									},
								},
								"ignore_missing": true,
							},
						},
					},
				},
```

This code can be added somewhere in the `v1_monitoring.go`:
https://github.com/elastic/elastic-agent/blob/45e3abf15c0fd1a351c5820646b5bd2eff6ce46b/internal/pkg/agent/application/monitoring/v1_monitor.go#L437-L461

This generates the following error:
```
   ├─ filestream-monitoring
   │  ├─ status: (HEALTHY) Healthy: communicating with pid '4169'
   │  ├─ filestream-monitoring
   │  │  ├─ status: (HEALTHY) Healthy
   │  │  └─ type: OUTPUT
   │  └─ filestream-monitoring-filestream-monitoring-agent
   │     ├─ status: (FAILED) proto: invalid type: []map[string]interface {}
   │     └─ type: INPUT
```

```
{"log.level":"error","@timestamp":"2025-02-11T20:29:57.198Z","log.origin":{"function":"github.com/elastic/elastic-agent/internal/pkg/agent/application/coordinator.(*Coordinator).watchRuntimeComponents","file.name":"coordinator/coordinator.go","file.line":671},"message":"Spawned new unit filestream-monitoring-filestream-monitoring-agent: proto: invalid type: []map[string]interface {}","log":{"source":"elastic-agent"},"component":{"id":"filestream-monitoring","state":"STARTING"},"unit":{"id":"filestream-monitoring-filestream-monitoring-agent","type":"input","state":"FAILED"},"ecs.version":"1.6.0"}
```
