### ISSUE TITLE
Add `rollback_available` fields in upgrade marker

### ISSUE THREAD

**Issue by pchila** [elastic/elastic-agent#6884]
Requires #6880 

Add the following fields to the upgrade marker definition:
- `rollback_available`: contains the list of versions still present on disk that the agent can rollback to (in the first implementation limited to 1 element max)
- Versions are composed by the following fields:
  -  `version`: version string corresponding to the instance of agent 
  -  `home`: path relative to Elastic Agent top directory pointing to the instance of agent
  - `valid_until`: timestamp in RFC 3339 format indicating until when this instance should be kept on disk 

For example:
```yaml
prev_version: 8.16.0-SNAPSHOT 
prev_hash: b65953 
prev_versioned_home: data/elastic-agent-8.16.0-SNAPSHOT-b65953 
updated_on: 2024-11-14T14:42:21.082601803Z 
version: 9.0.0-SNAPSHOT 
hash: 1d8229 
versioned_home: data/elastic-agent-9.0.0-SNAPSHOT-1d8229 
acked: true 
action: <action id>
details: 
  target_version: 9.0.0 
  state: UPG_WATCHING
# dedicated key for available rollbacks in upgrade marker
rollback_available:
  - version: 8.16.0-SNAPSHOT,
    home: data/elastic-agent-8.16.0-SNAPSHOT-b65953
    valid_until: "2024-11-21T14:42:21Z"
```
