### ISSUE TITLE
Mac agent installed with Elastic Defend gets unhealthy with proxy setup.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/elastic-agent#7226]
**Kibana Build details:**
```
VERSION: 9.0.0-rc1-BC1
BUILD: 83822
COMMIT: 07dc0afa460bddff658ee6d5342ad1f087fc766b
```
Artifact Link: https://staging.elastic.co/9.0.0-rc1-bd80e8a3/downloads/beats/elastic-agent/elastic-agent-9.0.0-rc1-darwin-x86_64.tar.gz

**Preconditions:**
1. 9.0.0-rc1 Kibana cloud environment should be available.
2. Proxy setup must be done as per https://github.com/elastic/ingest-dev/wiki/Fleet-Platform-testing-guide#set-up-fleet-server-and-an-output-using-proxies

**Steps to reproduce:**
1. Install mac agent with Elastic Defend integration.
2. Observe mac agent gets unhealthy with proxy setup.

**Expected Results**
Mac agent installed with Elastic Defend should remain healthy with proxy setup.

**Logs:**
[elastic-agent-diagnostics-2025-03-05T16-19-40Z-00.zip](https://github.com/user-attachments/files/19101929/elastic-agent-diagnostics-2025-03-05T16-19-40Z-00.zip)
[elastic-agent-diagnostics-2025-03-05T16-35-59Z-00.zip](https://github.com/user-attachments/files/19101928/elastic-agent-diagnostics-2025-03-05T16-35-59Z-00.zip)

**Agent JSON:**
[CASTORCLIENT-ML4.local-agent-details.zip](https://github.com/user-attachments/files/19101931/CASTORCLIENT-ML4.local-agent-details.zip)

**Whats working fine**
- Issue is not reproduced for 8.17.3 agent with same proxy setup.

**Agent JSON for 8.17.3 agent:**
[CASTORCLIENT-ML4.local-agent-details (1).zip](https://github.com/user-attachments/files/19101965/CASTORCLIENT-ML4.local-agent-details.1.zip)

**Comment by amolnater-qasource** [comment]
@muskangulati-qasource Please review.

**Comment by jlind23** [comment]
@intxgo I might be wrong but isn't this something you recently fixed?

**Comment by muskangulati-qasource** [comment]
Secondary review is Done for this ticket!

**Comment by intxgo** [comment]
> [@intxgo](https://github.com/intxgo) I might be wrong but isn't this something you recently fixed?

I don't think so, as the ticket state that the test scenario was working before.

PS. I made a fix for specific environment proxy case, not proxy via policy.

Looking through the artifacts

**Comment by intxgo** [comment]
The test set up https proxy on Endpoint output
```
output:
  elasticsearch:
    api_key: <REDACTED>
    hosts:
    - <REDACTED>
    preset: balanced
    proxy_url: https://192.168.29.204:8080
    ssl.certificate_authorities:
    - <REDACTED>
    type: elasticsearch
```

> "level":"error","origin":{"file":{"line":313,"name":"MessageHelpers.cpp"}}},"message":"MessageHelpers.cpp:313 CURL error: SSL peer certificate or SSH remote key was not OK [SSL certificate problem: unable to get local issuer certificate]"

The problem is definitely related to certificate trust and it could be confirmed by running `test output` on Endpoint. I vaguely remember seeing some recent issue or SDH related to changes in Sequoia.

The test run on macOS version is 15.3.1, @ricardo-estc anything stands out to you?

**Comment by amolnater-qasource** [comment]
@intxgo We retested on the same Hardware mac machine and on same kibana, for which we have shared the logs in the reported issue.

**Comment by amolnater-qasource** [comment]
Hi @ricardo-estc 

We have retested this issue and successfully reproduced it.

Please find the debug-level logs from the latest tests below:

**9.0rc1 BC2:**
[elastic-agent-diagnostics-2025-03-11T06-17-51Z-00.zip](https://github.com/user-attachments/files/19176971/elastic-agent-diagnostics-2025-03-11T06-17-51Z-00.zip)

[CASTORCLIENT-ML4.local-agent-details (1).zip](https://github.com/user-attachments/files/19177160/CASTORCLIENT-ML4.local-agent-details.1.zip)

Artifact Link: https://staging.elastic.co/9.0.0-rc1-c8334d32/downloads/beats/elastic-agent/elastic-agent-9.0.0-rc1-darwin-x86_64.tar.gz

**8.17.3:**
[elastic-agent-diagnostics-2025-03-11T06-24-08Z-00.zip](https://github.com/user-attachments/files/19177060/elastic-agent-diagnostics-2025-03-11T06-24-08Z-00.zip)

[CASTORCLIENT-ML4.local-agent-details.zip](https://github.com/user-attachments/files/19177049/CASTORCLIENT-ML4.local-agent-details.zip)

Please let us know if anything else is required from our end.
Thanks!

**Comment by amolnater-qasource** [comment]
Hi @ricardo-estc 

We have also tested the same on 9.0-SNAPSHOT with BC2 artifact because of same issue.

As per https://github.com/elastic/ingest-dev/wiki/Fleet-Platform-testing-guide#set-up-fleet-server-and-an-output-using-proxies

We are adding below data under Elasticsearch YAML configuration:
```
ssl.certificate_authorities:
  - /Users/hostname/.mitmproxy/mitmproxy-ca-cert.pem
```

![Image](https://github.com/user-attachments/assets/cc12b4b6-be38-44ae-bbd9-61bc16147780)

For adding proxy we are not adding certs under Certificate authorities section while adding proxy:
- We are also using `https` proxy. The agent is installed on same host where proxy is setup.

![Image](https://github.com/user-attachments/assets/f6c226d9-4309-443c-9254-b0983782d94e)

Please let us know if we are missing anything here.

Thanks!

**Comment by nfritts** [comment]
What seems to be happening is that when QA source tests this, they are setting the proxy in the ES output, but then adding the CA cert chain via the advanced YAML box by filling in something like:
```ssl.certificate_authorities:
- [path]
```
When this reaches Endpoint on 8.X, It ends up in the ES output as:
```
ssl:
   certificate_authorities: [path]
```
On 9.0 It's coming to endpoint as:
```
ssl.certificate_authorities: [path]
```


Unsure what has changed between 8.X and 9.0, but `ssl.certificate_authorities: [path]` is not "spec compliant" YAML for referencing 
```
ssl:
  certificate_authorities: [path]
```


Ideally the fix for this would be Agent passes Endpoint properly formatted YAML?  I think this means fleet has changed and is now sending the invalid YAML to Agent, but the custom parsing library that Agent and Beats use are successfully parsing it?  Its unclear if this behavior change would have affected anything else or any other integrations.  

CC: @cmacknz @ebeahan @pierrehilbert

**Comment by cmacknz** [comment]
I can confirm this is reproducible. I used Fleet in a Serverless observability project for testing with the output for integrations in the policy configured as:

<img width="769" alt="Image" src="https://github.com/user-attachments/assets/a2a2efa4-e576-47ee-a4d6-d377d634a6ef" />

See `ssl.certificate_authorities: ca.crt` at the bottom. For both agents, the Fleet policy is generated to contain exactly this in the output:

```yaml
id: 337782de-6ebd-4608-b697-888dddc36e63
revision: 3
outputs:
  f41a0165-7185-403b-bdff-e65f56fafb20:
    type: elasticsearch
    ssl.certificate_authorities: ca.crt
    hosts:
      - >-
        https://abdd9f80010a426d9ccf14f183cc1fad.es.eu-central-1.aws.staging.elastic.cloud:443
    preset: balanced
```

In the diagnostics of both agents, I see it formatted "correctly" in pre-config.yaml:

```yaml
    f41a0165-7185-403b-bdff-e65f56fafb20:
        api_key: <REDACTED>
        hosts:
            - https://abdd9f80010a426d9ccf14f183cc1fad.es.eu-central-1.aws.staging.elastic.cloud:443
        preset: balanced
        ssl:
            certificate_authorities: <REDACTED>
        type: elasticsearch
```

The difference only shows up diagnostics in `components-expected.yaml`.

In 8.18.0 we have:

```yaml
                    ssl:
                        kind:
                            structvalue:
                                fields:
                                    certificate_authorities:
                                        kind:
                                            stringvalue: ca.crt
                    type:
                        kind:
                            stringvalue: elasticsearch
```

In 9.0.0 we have:

```yaml
                    ssl.certificate_authorities:
                        kind:
                            stringvalue: ca.crt
                    type:
                        kind:
                            stringvalue: elasticsearch
```

So something has indeed changed in agent here. Also I suspect our `pre-config.yaml` file is reformatting the YAML vs what the policy is sending us, because it looks different than what is in Fleet.

**Comment by cmacknz** [comment]
There are 400+ commits worth of differences between these two versions https://github.com/elastic/elastic-agent/compare/8.18...9.0

My bet though is it will be a dependency upgrade that is directly used in how we marshal the checkin expected message or parse the policy.

**Comment by cmacknz** [comment]
`google.golang.org/protobuf` went from v1.34.2 to v1.36.5

**Comment by cmacknz** [comment]
Build an agent from the head of the 8.18 branch I observe the same behavior as https://github.com/elastic/elastic-agent/issues/7226#issuecomment-2719189051 where the `expected-config.yaml` has the indented formatting.

```yaml
                    ssl:
                        kind:
                            structvalue:
                                fields:
                                    certificate_authorities:
                                        kind:
                                            stringvalue: ca.crt
                    type:
                        kind:
                            stringvalue: elasticsearch
```
