### ISSUE TITLE
Support list expansion based on dynamic variables

### ISSUE THREAD

**Issue by ChrsMark** [elastic/elastic-agent#735]
**Describe the enhancement:**
As a user I would like to have the option for expanding a `yml` list using a list coming from a dynamic provider.

**Describe a specific use case for the enhancement or feature:**
In case I want to expand the list of processors with processors coming from a dynamic provider, I'm not able to achieve this.

Example:

```yml
providers:
  local_dynamic:
    items:
      - vars:
          key: value1
          procs:
             - add_fields:
                  fields:
                    custom: bar
                  target: dynamic  
             - add_fields:
                  fields:
                    hints: true
                  target: kubernetes

inputs:
  - type: logfile
    enabled: true
    streams:
      - paths:
          - /var/log/${local_dynamic.key}
        processors:
          - add_fields:
              fields:
                custom2: foo
              target: baz
         ${local_dynamic.procs}
```

In the above example I would like to expand the `processors` list with the list coming from the local provider.
