### ISSUE TITLE
[Flaky Test]: TestAuditdCorrectBinaries – could not fetch events for auditd_manager

### ISSUE THREAD

**Issue by pkoutsovasilis** [elastic/elastic-agent#7813]
### Failing test case

TestAuditdCorrectBinaries

### Error message

could not fetch events for auditd_manager

### Build

https://buildkite.com/elastic/elastic-agent-extended-testing/builds/8384#01961f11-6d8a-4727-a056-5327d390021b/145-227

### OS

Linux

### Stacktrace and notes

```markdown
=== FAIL: testing/integration TestAuditdCorrectBinaries (unknown)
    tools.go:105: Creating enrollment API key...
    tools.go:96: Creating enrollment API key...
    fixture_install.go:199: [test TestAuditdCorrectBinaries] Inside fixture install function
    fixture_install.go:227: [test TestAuditdCorrectBinaries] Inside fixture installNoPkgManager function
    fetcher.go:93: Using existing artifact elastic-agent-9.0.0-SNAPSHOT-linux-x86_64.tar.gz
    fixture.go:295: Extracting artifact elastic-agent-9.0.0-SNAPSHOT-linux-x86_64.tar.gz to /tmp/TestAuditdCorrectBinaries4248908402
    fixture.go:313: Completed extraction of artifact elastic-agent-9.0.0-SNAPSHOT-linux-x86_64.tar.gz to /tmp/TestAuditdCorrectBinaries4248908402
    fixture.go:997: Components were not modified from the fetched artifact
    fixture.go:670: >> running binary with: [/tmp/TestAuditdCorrectBinaries4248908402/elastic-agent-9.0.0-SNAPSHOT-linux-x86_64/elastic-agent install --force --non-interactive --url https://e1e03ad61a50f135454f817ba150fdf4.fleet.us-west2.gcp.elastic-cloud.com:443 --enrollment-token MHd3b0g1WUJzNHlCMTJPRERHMUY6UkZBSENTTHkyOGFqVDlJZ3BLRkJuZw==]
    tools.go:96: >>> Enroll succeeded. Output: Installing in non-interactive mode.
[==  ] Service Started  [3s] Elastic Agent successfully installed, starting enrollment.
[==  ] Waiting For Enroll...  [3s] {"log.level":"info","@timestamp":"2025-04-10T10:04:18.663Z","log.origin":{"function":"github.com/elastic/elastic-agent/internal/pkg/agent/cmd.(*enrollCmd).enrollWithBackoff","file.name":"cmd/enroll_cmd.go","file.line":534},"message":"Starting enrollment to URL: https://e1e03ad61a50f135454f817ba150fdf4.fleet.us-west2.gcp.elastic-cloud.com:443/","ecs.version":"1.6.0"}
        {"log.level":"info","@timestamp":"2025-04-10T10:04:20.124Z","log.origin":{"function":"github.com/elastic/elastic-agent/internal/pkg/agent/cmd.(*enrollCmd).daemonReloadWithBackoff","file.name":"cmd/enroll_cmd.go","file.line":497},"message":"Restarting agent daemon, attempt 0","ecs.version":"1.6.0"}
        {"log.level":"info","@timestamp":"2025-04-10T10:04:20.126Z","log.origin":{"function":"github.com/elastic/elastic-agent/internal/pkg/agent/cmd.(*enrollCmd).Execute","file.name":"cmd/enroll_cmd.go","file.line":315},"message":"Successfully triggered restart on running Elastic Agent.","ecs.version":"1.6.0"}
        Successfully enrolled the Elastic Agent.
[  ==] Done  [5s]
        Elastic Agent has been successfully installed.
    fixture.go:670: >> running binary with: [/opt/Elastic/Agent/elastic-agent status --output json]
    tools.go:96: >>> Enrolled Agent ID: 900bd104-80f2-4bd6-8ccb-633e78aee03c
    fixture.go:670: >> running binary with: [/opt/Elastic/Agent/elastic-agent status --output json]
    fixture_install.go:310: [test TestAuditdCorrectBinaries] Inside fixture cleanup function
    fixture_install.go:326: collecting diagnostics; test failed
panic: Fail in goroutine after TestAuditdCorrectBinaries/TestBeatsMetrics has completed
goroutine 524 [running]:
testing.(*common).Fail(0xc000003a40)
	/opt/buildkite-agent/.asdf/installs/golang/1.24.1/go/src/testing/testing.go:988 +0xcb
testing.(*common).Errorf(0xc000003a40, {0xd802156?, 0x2?}, {0xc000d04ed0?, 0xcb7bf80?, 0x13b7aa40?})
	/opt/buildkite-agent/.asdf/installs/golang/1.24.1/go/src/testing/testing.go:1111 +0x5e
github.com/stretchr/testify/assert.Fail({0xe6b1ba0, 0xc000003a40}, {0xc001d8c370, 0x47}, {0x0, 0x0, 0x0})
	/opt/buildkite-agent/.asdf/installs/golang/1.24.1/packages/pkg/mod/github.com/stretchr/testify@v1.10.0/assert/assertions.go:369 +0x370
github.com/stretchr/testify/assert.NoError({0xe6b1ba0, 0xc000003a40}, {0xe6b2100, 0xc000e83320}, {0x0, 0x0, 0x0})
	/opt/buildkite-agent/.asdf/installs/golang/1.24.1/packages/pkg/mod/github.com/stretchr/testify@v1.10.0/assert/assertions.go:1586 +0x125
github.com/stretchr/testify/require.NoError({0xe6e42d0, 0xc000003a40}, {0xe6b2100, 0xc000e83320}, {0x0, 0x0, 0x0})
	/opt/buildkite-agent/.asdf/installs/golang/1.24.1/packages/pkg/mod/github.com/stretchr/testify@v1.10.0/require/require.go:1354 +0xb0
github.com/elastic/elastic-agent/testing/integration.(*AuditDRunner).TestBeatsMetrics.func2()
	/opt/buildkite-agent/builds/bk-agent-prod-gcp-1744278251335066685/elastic/elastic-agent-extended-testing/testing/integration/auditd_monitoring_test.go:116 +0x6ba
github.com/stretchr/testify/assert.Eventually.func1()
	/opt/buildkite-agent/.asdf/installs/golang/1.24.1/packages/pkg/mod/github.com/stretchr/testify@v1.10.0/assert/assertions.go:1949 +0x23
created by github.com/stretchr/testify/assert.Eventually in goroutine 388
	/opt/buildkite-agent/.asdf/installs/golang/1.24.1/packages/pkg/mod/github.com/stretchr/testify@v1.10.0/assert/assertions.go:1949 +0x20e
    auditd_monitoring_test.go:108: starting to ES for metrics at 2025-04-10T10:04:42.688181576Z
    auditd_monitoring_test.go:109:
        	Error Trace:	/opt/buildkite-agent/builds/bk-agent-prod-gcp-1744278251335066685/elastic/elastic-agent-extended-testing/testing/integration/auditd_monitoring_test.go:109
        	Error:      	Condition never satisfied
        	Test:       	TestAuditdCorrectBinaries/TestBeatsMetrics
        	Messages:   	could not fetch events for auditd_manager
    auditd_monitoring_test.go:103: executed at 2025-04-10T10:14:42.689565173Z: query: {"query":{"bool":{"must":[{"match":{"agent.id":"900bd104-80f2-4bd6-8ccb-633e78aee03c"}},{"exists":{"field":"auditd.summary.actor.primary"}}]}}}
```

**Comment by pkoutsovasilis** [comment]
another occurrence [here](https://buildkite.com/elastic/elastic-agent/builds/25513#0198c3fa-984c-412f-b5bc-5692ff6ea212/81-915)

**Comment by cmacknz** [comment]
We could relax these tests to make sure we can start the input and have it be healthy, instead of making sure the underlying beat can ship data. That is coupling us to bugs in the beats.

These tests were introduced to make sure the basic+extended flavors worked and didn't corrupt the binaries or forget to preserve a file they needed to work.

**Comment by pchila** [comment]
New occurrence here https://buildkite.com/elastic/elastic-agent/builds/26673#01993b75-cc37-4647-a460-53576cf3fd03/266-398

**Comment by straistaru** [comment]
New occurrence [here](https://buildkite.com/elastic/elastic-agent/builds/27845#01999d4f-dafe-4125-9c3d-33bcfab6f74f)

**Comment by swiatekm** [comment]
More occurences: https://buildkite.com/elastic/elastic-agent/builds/29428#019a25fa-04b8-48e5-866e-beb596d0239c https://buildkite.com/elastic/elastic-agent/builds/29436#019a2597-2bf5-437c-bd99-565a1e63038a. Seems to be happening quite consistently on Debian.

Looking at the diagnostics, the stream is stuck in the STARTING state, but agent logs don't show any obvious problem:

```yaml
    - id: audit/auditd-default
      state:
        component:
            apmconfig: null
            limits:
                gomaxprocs: 0
                source:
                    fields:
                        go_max_procs:
                            kind:
                                numbervalue: 0
        component_idx: 2
        features_idx: 2
        message: 'Healthy: communicating with pid ''76646'''
        pid: 0
        state: 2
        units:
            input-audit/auditd-default-audit/auditd-auditd-76bb5cae-26d2-4ff3-b3ea-f093a163c93e:
                message: Healthy
                payload:
                    streams:
                        audit/auditd-auditd_manager.auditd-346b3488-8f0b-4557-84f4-638e3d968af9:
                            error: auditd/auditd is starting
                            status: STARTING
                state: 2
            output-audit/auditd-default:
                message: Healthy
                state: 2
```
