### ISSUE TITLE
[beats receivers] OTel based pipeline must continue to report queue metrics for the elastic_agent integration

### ISSUE THREAD

**Issue by cmacknz** [elastic/elastic-agent#8032]
The primary queue when using Beats receivers is the one in the collector. We need to export queue metrics as part of self-monitoring. 

<img width="854" alt="Image" src="https://github.com/user-attachments/assets/dc8ce152-ce65-40ae-b595-28670530752c" />

Ideally they are backwards compatible with the existing metrics for queue depth. If they cannot have the same names then the same semantic meaning.

`libbeat.pipeline.events.active` measures the number of events in the processing pipeline including those in processors, and has a value that can be slightly above the queue size because of this.

https://github.com/elastic/integrations/blob/037cda7c46f84ca7c1d8055105f5d7fab59fda50/packages/elastic_agent/data_stream/filebeat_logs/fields/fields.yml#L48-L57

```yaml
- name: monitoring.metrics.libbeat.pipeline
  type: group
  fields:
    - name: events
      type: group
      fields:
        - name: active
          type: long
          metric_type: gauge
          description: Number of events currently in the pipeline. The maximum size is the configured queue size plus one event per event pipeline client.
```

Direct measurements of the data in the queue were added recently, specifically with `queue.filled.pct.events` giving the queue fill level in percent directly.

https://github.com/elastic/integrations/blob/037cda7c46f84ca7c1d8055105f5d7fab59fda50/packages/elastic_agent/data_stream/filebeat_logs/fields/fields.yml#L66-L77

```yaml
    - name: queue.acked
      type: long
      metric_type: counter
      description: Number of events successfully acknowledged by the output
    - name: queue.max_events
      type: long
      metric_type: counter
      description: Maximum number of events in a queue
    - name: queue.filled.pct.events
      type: float
      metric_type: gauge
      description: Maximum number of events in a queue
```
