### ISSUE TITLE
[beats receivers] OTel based pipeline must continue to report output metrics for the elastic_agent integration

### ISSUE THREAD

**Issue by cmacknz** [elastic/elastic-agent#8033]
The Beat pipeline and output produce detailed metrics, when using a collector based pipeline we must produce equivalent or similar metrics from the exporter. The output metrics related to errors, retries, etc are heavily featured in the elastic_agent integration. 

Ideally the metrics from the collector are backwards compatible with the existing metrics. If they cannot have the same names then the same semantic meaning is the next best thing but we will have to propose the changes to the breaking changes committee.

<img width="2294" alt="Image" src="https://github.com/user-attachments/assets/dd3400e0-f125-4c5a-acde-16f547c55de9" />

https://github.com/elastic/integrations/blob/037cda7c46f84ca7c1d8055105f5d7fab59fda50/packages/elastic_agent/data_stream/filebeat_metrics/fields/beat-stats-fields.yml#L229-L279

```yaml
        - name: output
          type: group
          fields:
            - name: type
              type: keyword
              description: >
                Type of output
            - name: events
              type: group
              fields:
                - name: acked
                  type: long
                  metric_type: counter
                  description: >
                    Number of events acknowledged

                - name: active
                  type: long
                  metric_type: counter
                  description: >
                    Number of active events
                - name: batches
                  type: long
                  metric_type: counter
                  description: >
                    Number of event batches
                - name: dropped
                  type: long
                  metric_type: counter
                  description: >
                    Number of events dropped
                - name: duplicates
                  type: long
                  metric_type: counter
                  description: >
                    Number of events duplicated
                - name: failed
                  type: long
                  metric_type: counter
                  description: >
                    Number of events failed
                - name: toomany
                  type: long
                  metric_type: counter
                  description: >
                    Number of too many events
                - name: total
                  type: long
                  metric_type: counter
                  description: >
                    Total number of events processed by the output
```
