### ISSUE TITLE
[filebeat] Number of inputs enabled is incorrectly logged

### ISSUE THREAD

**Issue by khushijain21** [elastic/elastic-agent#8119]
Steps to reproduce

Start agent with 
```
agent.grpc:
  port: 6794
inputs:
   - type: filestream
     # Input ID allowing Elastic Agent to track the state of this input. Must be unique.
     id: your-input-id
     streams:
       # Stream ID for this data stream allowing Filebeat to track the state of the ingested files. Must be unique.
       # Each filestream data stream creates a separate instance of the Filebeat filestream input.
       - id: your-filestream-stream-id
         data_stream:
           dataset: generic
         paths:
           - /var/log/*.log    
outputs:
  default:
    type: elasticsearch
    hosts: ["XXX"]
    preset: "balanced"
    username: "elastic"
    password: "XXX"
agent.monitoring:
   enabled: false
```

Even when filestream input is enabled, the logs show "Enabled Inputs: 0". 

```json
{"log.level":"info","@timestamp":"2025-05-08T12:21:41.959+0530","message":"Loading Inputs: 0","component":{"binary":"filebeat","dataset":"elastic_agent.filebeat","id":"filestream-default","type":"filestream"},"log":{"source":"filestream-default"},"ecs.version":"1.6.0","log.logger":"crawler","log.origin":{"file.line":72,"file.name":"beater/crawler.go","function":"github.com/elastic/beats/v7/filebeat/beater.(*crawler).Start"},"service.name":"filebeat","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2025-05-08T12:21:41.959+0530","message":"Loading and starting Inputs completed. Enabled inputs: 0","component":{"binary":"filebeat","dataset":"elastic_agent.filebeat","id":"filestream-default","type":"filestream"},"log":{"source":"filestream-default"},"log.origin":{"file.line":107,"file.name":"beater/crawler.go","function":"github.com/elastic/beats/v7/filebeat/beater.(*crawler).Start"},"service.name":"filebeat","ecs.version":"1.6.0","log.logger":"crawler","ecs.version":"1.6.0"}
```

This is because filebeat crawler is started with an empty config first. And when an updated config is passed down to beats - it uses reloadable inputs to
