### ISSUE TITLE
ECK Operator sets the ELASTICSEARCH_CA environment variable

### ISSUE THREAD

**Issue by ak1008** [elastic/elastic-agent#8161]
Enhancement Description:
When deploying Agent or Agent-Fleet using the ECK Operator in non-root mode, the following limitation arises: as outlined in the [ECK documentation](https://www.elastic.co/docs/deploy-manage/deploy/cloud-on-k8s/quickstart-fleet#CO18-1), root privileges are required to persist state using a hostPath volume and to trust the Elasticsearch Certificate Authority (CA) in Fleet mode.

Upon analysis, it appears that the ECK Operator mounts the auto-generated Elasticsearch CA at /usr/local/share/ca-certificates. The root user requirement likely stems from the fact that the update-ca-certificates command—used to incorporate this CA into the system’s trust store—can only be executed with root privileges. Elastic Agent, by default, relies on the operating system's trusted certificate authorities.

Currently, when running Elastic Agent in Fleet mode as a non-root user, users must explicitly configure the certificate_authorities.ssl field in each xpack.fleet.outputs configuration to manually trust the Elasticsearch CA.

Use Case:
To improve usability and streamline deployment, especially in automated or Helm-based setups (e.g., [elastic/cloud-on-k8s](https://github.com/elastic/cloud-on-k8s)), the ECK Operator could mitigate this limitation by setting the ELASTICSEARCH_CA environment variable to point to the mounted Elasticsearch CA file. This would eliminate the need for manual xpack.fleet.outputs configuration, particularly useful when the ES CA is generated dynamically by ECK and not known at deployment time.

Definition of Done:
The ECK Operator sets the ELASTICSEARCH_CA environment variable to the path of the Elasticsearch CA file it mounts, thereby allowing non-root Fleet Agents to trust the Elasticsearch cluster without requiring manual certificate configuration.

**Comment by ak1008** [comment]
Actually another solution as per https://github.com/elastic/cloud-on-k8s/blob/main/config/recipes/elastic-agent/fleet-kubernetes-integration-nonroot.yaml is setting xpack.fleet.outputs.ssl.certificate_authorities. Since this can also reference a file (I mistakenly thought it supports the PEM certificate only), we can use the ECK operated mounted CA. I am closing this issue then since it has worked in our test environment. 

``` YAML
xpack.fleet.outputs:
    - id: eck-fleet-agent-output-elasticsearch
      is_default: true
      name: eck-elasticsearch
      type: elasticsearch
      hosts: ["https://elasticsearch-es-http.default.svc:9200"]
      ssl:
        certificate_authorities: ["/mnt/elastic-internal/elasticsearch-association/default/elasticsearch/certs/ca.crt"]
```
