### ISSUE TITLE
Ensure that diagnostics contain all information necessary to debug beat receivers when using the OTel runtime

### ISSUE THREAD

**Issue by cmacknz** [elastic/elastic-agent#8208]
- [x] The Beat logs should be included in the logs/elastic-agent-* log files, they will just be emitted by the collector instead. The component metadata should be the same as it was before. (https://github.com/elastic/elastic-agent/pull/8606)
- [x] The Beat state should appear in state.yaml, and degraded or failed Beat inputs must appear here. A system/metrics input in a Metricbeat receiver with a permissions error must continue to be visible.
- [x] The generated OTel collector configuration file must be present, likely in a new file. Existing files containing computed, expected, and actual agent configuration should account for the otel runtime mode.
  - Failure to generate the OTel collector configuration should be obvious and include the error.
- [x] Beat input metrics should continue to be captured and included.
- [x] The Filebeat registry and state should continue to be captured and included.
- [x] CPU and heap profiles should continue to be captured, just for fewer processes.
- [x] Consider including snapshots of OTel collector specific debug zpages https://github.com/open-telemetry/opentelemetry-specification/blob/main/development/trace/zpages.md

Changes to diagnostics should be reflected in our documentation and communicated to the agent-analyzer team:
- https://github.com/elastic/agent-analyzer
- https://github.com/elastic/ingest-docs/blob/main/docs/en/ingest-management/commands.asciidoc#elastic-agent-diagnostics-command

**Comment by lucabelluccini** [comment]
> Changes to diagnostics should be reflected in our documentation and communicated to the agent-analyzer team

\+ Support please (keep us in the loop)

**Comment by swiatekm** [comment]
Let's see where we are and what we need to do here.

> * [ ]  The Beat logs should be included in the logs/elastic-agent-* log files, they will just be emitted by the collector instead. The component metadata should be the same as it was before.

This is already the case, although it looks like we have some repeated fields. I'll see if I can normalize it. It would also be nice to have a test comparing these.

> * [x]  The Beat state should appear in state.yaml, and degraded or failed Beat inputs must appear here. A system/metrics input in a Metricbeat receiver with a permissions error must continue to be visible.

This is already the case insofar as beats receiver status appears in that file. The status does not include per-stream status at this time, but we should track that in a separate issue imo.

> * [ ]  The generated OTel collector configuration file must be present, likely in a new file. Existing files containing computed, expected, and actual agent configuration should account for the otel runtime mode.
>         * Failure to generate the OTel collector configuration should be obvious and include the error.

We currently emit two files:
* `otel.yml`, which contains just the hybrid mode config provided by the user.
* `otel-final.yml`, which contains the full config used by the otel collector, including beats receivers.

We could also include the config with just the beats receiver definitions, but I'm not sure that's necessary. I would like to put some thought into the file names though, so it's obvious what they contain even to users without any in-depth knowledge of the architecture. @lucabelluccini any thoughts about this?

> * [ ]  Beat input metrics should continue to be captured and included.

This doesn't exist. For beats processes, beats themselves register doing this as a diagnostic hook and get the metrics straight from the registry. There's several ways agent could get these metrics:

* Directly ping the beats metrics endpoint.
* Inject a file exporter into the pipeline carrying beats metrics and attach the file to the diagnostics.
* Have beats receivers emit them into the otel collector's internal telemetry.

> * [ ]  The Filebeat registry and state should continue to be captured and included.

We don't currently collect the state, just the registry. This is done via a custom hook in beats, but isn't overly complex. Agent can do it on its own, though it'll introduce more unfortunate coupling between agent and beats.

> * [ ]  CPU and heap profiles should continue to be captured, just for fewer processes.

This currently works correctly, but after https://github.com/elastic/elastic-agent/pull/8248, agent will have to use the otel collector's pprof endpoint.

> * [ ]  Consider including snapshots of OTel collector specific debug zpages https://github.com/open-telemetry/opentelemetry-specification/blob/main/development/trace/zpages.md

From what I can see, these barely contain any information not already present in the collector status.

**Comment by lucabelluccini** [comment]
> We could also include the config with just the beats receiver definitions, but I'm not sure that's necessary. I would like to put some thought into the file names though, so it's obvious what they contain even to users without any in-depth knowledge of the architecture. [@lucabelluccini](https://github.com/lucabelluccini) any thoughts about this?

Would those be the equivalent of the `beats-rendered-config.yml` files we generate under each `/component/<unit or component ID>/` in Elastic Agent now? 
But in EDOT case, it would be the `yaml` of the Beat receiver generated for each integration/component?

I would agree on having those for 2 reasons:
- We can determine if there has been a problem in "generating" the config from the policy (generated config is empty => something big really happened)
- We can really see how they got translated into actual config and if maybe something was "generated" wrongly (generated config is there, but is partial or wrong)

Please correct me if my assumptions are wrong.

**Comment by swiatekm** [comment]
> > We could also include the config with just the beats receiver definitions, but I'm not sure that's necessary. I would like to put some thought into the file names though, so it's obvious what they contain even to users without any in-depth knowledge of the architecture. [@lucabelluccini](https://github.com/lucabelluccini) any thoughts about this?
> 
> Would those be the equivalent of the `beats-rendered-config.yml` files we generate under each `/component/<unit or component ID>/` in Elastic Agent now? But in EDOT case, it would be the `yaml` of the Beat receiver generated for each integration/component?
> 
> I would agree on having those for 2 reasons:
> 
>     * We can determine if there has been a problem in "generating" the config from the policy (generated config is empty => something big really happened)
> 
>     * We can really see how they got translated into actual config and if maybe something was "generated" wrongly (generated config is there, but is partial or wrong)
> 
> 
> Please correct me if my assumptions are wrong.

It would be the functional equivalent of those files, but as they're all running as part of the same otel collector, it's actually just one config file. 

In addition, the user can provide otel configuration directly, which currently appears in a separate `otel.yml` file.

I think we could reproduce the current state, where each component gets its own (partial) otel config, although these wouldn't be what the otel collector actually runs. Do you think that would be useful?

**Comment by lucabelluccini** [comment]
> I think we could reproduce the current state, where each component gets its own (partial) otel config, although these wouldn't be what the otel collector actually runs. Do you think that would be useful?

Sorry for my probably silly question, but do you have any example?
I think having the "expected" and "actual" config would be beneficial to have (especially if merging and/overrides of `yml` are involved).

**Comment by swiatekm** [comment]
> > I think we could reproduce the current state, where each component gets its own (partial) otel config, although these wouldn't be what the otel collector actually runs. Do you think that would be useful?
> 
> Sorry for my probably silly question, but do you have any example? I think having the "expected" and "actual" config would be beneficial to have (especially if merging and/overrides of `yml` are involved).

Let me provide an end-to-end example of how this works for components running inside the otel collector. Let's take the following standalone agent configuration file:

```yaml
outputs:
  default:
    type: elasticsearch
    hosts: [127.0.0.1:9200]
    username: ""
    password: ""

agent:
  monitoring:
    enabled: false

inputs:
- id: system-metrics
  _runtime_experimental: otel
  streams:
  - data_stream:
      dataset: system.cpu
    metricsets:
    - cpu
  type: system/metrics
- id: filestream-system-logs
  _runtime_experimental: otel
  streams:
  - data_stream:
      dataset: system.log
    paths:
    - /var/log/system.log
  type: filestream

# Embedded Otel configuration
receivers:
  nop:
exporters:
  nop:
service:
  pipelines:
    logs:
      receivers: [nop]
      exporters: [nop]
```

This file defines:
1. An elasticsearch output
2. A filestream input running as a beats receiver
3. A system/metrics input running as a beats receiver
4. An otel pipeline composed of the nop receiver and exporter

Elastic-agent will translate 1. into:

```yaml
  elasticsearch/_agent-component/default:
    batcher:
      enabled: true
      max_size: 1600
      min_size: 0
    endpoints:
    - http://127.0.0.1:9200
    idle_conn_timeout: 3s
    logs_dynamic_id:
      enabled: true
    logs_dynamic_index:
      enabled: true
    logs_index: ""
    mapping:
      mode: bodymap
    password: <REDACTED>
    retry:
      enabled: true
      initial_interval: 1s
      max_interval: 1m0s
      max_retries: 3
    timeout: 1m30s
    user: elastic
```

2. into

```yaml
  filebeatreceiver/_agent-component/filestream-default:
    filebeat:
      inputs:
      - data_stream:
          dataset: system.log
        index: logs-system.log-default
        paths:
        - /var/log/system.log
        processors:
        - add_fields:
            fields:
              input_id: filestream-system-logs
            target: '@metadata'
        - add_fields:
            fields:
              dataset: system.log
              namespace: default
              type: logs
            target: data_stream
        - add_fields:
            fields:
              dataset: system.log
            target: event
        - add_fields:
            fields:
              id: d70e2c38-25b3-4b48-8240-7c55b90055dc
              snapshot: true
              version: 9.1.0
            target: elastic_agent
        - add_fields:
            fields:
              id: d70e2c38-25b3-4b48-8240-7c55b90055dc
            target: agent
        type: filestream
    http:
      enabled: true
      host: unix:///tmp/elastic-agent/7uyxrneW50ZMk_CZbrE0Hjg3idmd7AzZ.sock
    logging:
      with_fields:
        component:
          binary: filebeat
          dataset: elastic_agent.filebeat
          id: filestream-default
          type: filestream
        log:
          source: filestream-default
        service_name: filebeat
    output:
      otelconsumer: { }
    path:
      data: ...
```

3. into

```yaml
  metricbeatreceiver/_agent-component/system/metrics-default:
    http:
      enabled: true
      host: unix:///tmp/elastic-agent/iThI_df0cBKC6YUNGGlKscMkOfz3FBH3.sock
    logging:
      with_fields:
        component:
          binary: metricbeat
          dataset: elastic_agent.metricbeat
          id: system/metrics-default
          type: system/metrics
        log:
          source: system/metrics-default
        service_name: metricbeat
    metricbeat:
      modules:
      - data_stream:
          dataset: system.cpu
        index: metrics-system.cpu-default
        metricsets:
        - cpu
        module: system
        processors:
        - add_fields:
            fields:
              input_id: system-metrics
            target: '@metadata'
        - add_fields:
            fields:
              dataset: system.cpu
              namespace: default
              type: metrics
            target: data_stream
        - add_fields:
            fields:
              dataset: system.cpu
            target: event
        - add_fields:
            fields:
              id: d70e2c38-25b3-4b48-8240-7c55b90055dc
              snapshot: true
              version: 9.1.0
            target: elastic_agent
        - add_fields:
            fields:
              id: d70e2c38-25b3-4b48-8240-7c55b90055dc
            target: agent
    output:
      otelconsumer: { }
    path:
      data: ...
```

and it will leave 4. as is. 

In diagnostics as they are right now, we'll get two configuration files:

`otel.yaml`, which is just the direct otel configuration
```yaml
exporters:
  nop: null
receivers:
  nop: null
service:
  pipelines:
    logs:
      exporters:
      - nop
      receivers:
      - nop
```

`otel-final.yaml`, which contains everything merged together:

```yaml
exporters:
  elasticsearch/_agent-component/default:
    batcher:
      enabled: true
      max_size: 1600
      min_size: 0
    endpoints:
    - http://127.0.0.1:9200
    idle_conn_timeout: 3s
    logs_dynamic_id:
      enabled: true
    logs_dynamic_index:
      enabled: true
    logs_index: ""
    mapping:
      mode: bodymap
    password: <REDACTED>
    retry:
      enabled: true
      initial_interval: 1s
      max_interval: 1m0s
      max_retries: 3
    timeout: 1m30s
    user: elastic
  nop: null
receivers:
  filebeatreceiver/_agent-component/filestream-default:
    filebeat:
      inputs:
      - data_stream:
          dataset: system.log
        index: logs-system.log-default
        paths:
        - /var/log/system.log
        processors:
        - add_fields:
            fields:
              input_id: filestream-system-logs
            target: '@metadata'
        - add_fields:
            fields:
              dataset: system.log
              namespace: default
              type: logs
            target: data_stream
        - add_fields:
            fields:
              dataset: system.log
            target: event
        - add_fields:
            fields:
              id: d70e2c38-25b3-4b48-8240-7c55b90055dc
              snapshot: true
              version: 9.1.0
            target: elastic_agent
        - add_fields:
            fields:
              id: d70e2c38-25b3-4b48-8240-7c55b90055dc
            target: agent
        type: filestream
    http:
      enabled: true
      host: unix:///tmp/elastic-agent/7uyxrneW50ZMk_CZbrE0Hjg3idmd7AzZ.sock
    logging:
      with_fields:
        component:
          binary: filebeat
          dataset: elastic_agent.filebeat
          id: filestream-default
          type: filestream
        log:
          source: filestream-default
        service_name: filebeat
    output:
      otelconsumer: { }
    path:
      data: ...
  metricbeatreceiver/_agent-component/system/metrics-default:
    http:
      enabled: true
      host: unix:///tmp/elastic-agent/iThI_df0cBKC6YUNGGlKscMkOfz3FBH3.sock
    logging:
      with_fields:
        component:
          binary: metricbeat
          dataset: elastic_agent.metricbeat
          id: system/metrics-default
          type: system/metrics
        log:
          source: system/metrics-default
        service_name: metricbeat
    metricbeat:
      modules:
      - data_stream:
          dataset: system.cpu
        index: metrics-system.cpu-default
        metricsets:
        - cpu
        module: system
        processors:
        - add_fields:
            fields:
              input_id: system-metrics
            target: '@metadata'
        - add_fields:
            fields:
              dataset: system.cpu
              namespace: default
              type: metrics
            target: data_stream
        - add_fields:
            fields:
              dataset: system.cpu
            target: event
        - add_fields:
            fields:
              id: d70e2c38-25b3-4b48-8240-7c55b90055dc
              snapshot: true
              version: 9.1.0
            target: elastic_agent
        - add_fields:
            fields:
              id: d70e2c38-25b3-4b48-8240-7c55b90055dc
            target: agent
    output:
      otelconsumer: { }
    path:
      data: ...
  nop: null
service:
  pipelines:
    logs:
      exporters:
      - nop
      receivers:
      - nop
    logs/_agent-component/filestream-default:
      exporters:
      - elasticsearch/_agent-component/default
      receivers:
      - filebeatreceiver/_agent-component/filestream-default
    logs/_agent-component/system/metrics-default:
      exporters:
      - elasticsearch/_agent-component/default
      receivers:
      - metricbeatreceiver/_agent-component/system/metrics-default
```

The question I have, is whether I should put the receiver configurations in separate files, similar to `beats-rendered-config.yml`? Should I also put the exporter in there? For beats processes each beat gets its own output, but with beats receivers the exporter is shared, so this would be something of a misrepresentation.

Does this help @lucabelluccini ?
