### ISSUE TITLE
[agent.monitoring] configuration does not return to default value

### ISSUE THREAD

**Issue by khushijain21** [elastic/elastic-agent#8260]
Steps to Reproduce:

`agent.monitoring` is enabled by default. If we start elastic-agent with monitoring disabled like below

```
agent.grpc:
  port: 6799  

agent.monitoring:
  enabled: false
          
outputs:
  default:
    type: elasticsearch
    hosts: [http://localhost:9200]
    username: "admin"
    password: "testing"
    preset: balanced
```

and then remove this section 

```
agent.monitoring:
  enabled: false
```

we would expect monitoring to be enabled back again. But that is not what happens. If we want to enable monitoring again, we explicitly provide following value

```
agent.monitoring:
  enabled: true
```

This is true for all fields under `agent.monitoring`. Setting a field different from its default value - then removing it entirely - does not reset the field to its default value.
