### ISSUE TITLE
When using the OTel runtime, status of non-otel inputs is hidden

### ISSUE THREAD

**Issue by cmacknz** [elastic/elastic-agent#8381]
I think this likely a bug in https://github.com/elastic/elastic-agent/pull/8273

If you have an agent configuration where self-monitoring is configured to use the experimental otel runtime but contains other non-otel inputs, the status of the non-otel inputs is no longer reported.

```sh
❯ sudo elastic-development-agent version
Binary: 9.1.0-SNAPSHOT (build: 14a599750d1e8cccfd1666d34e6862a147ff7e59 at 2025-06-06 19:05:32 +0000 UTC)
Daemon: 9.1.0-SNAPSHOT (build: 14a599750d1e8cccfd1666d34e6862a147ff7e59 at 2025-06-06 19:05:32 +0000 UTC)

❯ sudo elastic-development-agent inspect
agent:
  logging:
    to_stderr: true
  monitoring:
    _runtime_experimental: otel
    enabled: true
    logs: true
    metrics: true
inputs:
- data_stream:
    namespace: default
  id: unique-system-metrics-input
  streams:
  - data_stream:
      dataset: system.cpu
    metricsets:
    - cpu
  - data_stream:
      dataset: system.memory
    metricsets:
    - memory
  - data_stream:
      dataset: system.network
    metricsets:
    - network
  - data_stream:
      dataset: system.filesystem
    metricsets:
    - filesystem
  type: system/metrics
  use_output: default
outputs:
  default:
    api_key: <REDACTED>
    hosts:
    - 127.0.0.1:9200
    preset: balanced
    type: elasticsearch
```

When running the status command with this configuration, the status of the `system/metrics` input is no longer reported:

```sh
❯ sudo elastic-development-agent status --output=full
┌─ fleet
│  └─ status: (STOPPED) Not enrolled into Fleet
└─ elastic-agent
   ├─ status: (HEALTHY) Running
   ├─ info
   │  ├─ id: fd0baf0c-e7dd-479b-ae1b-057e92270e1c
   │  ├─ version: 9.1.0
   │  └─ commit: 14a599750d1e8cccfd1666d34e6862a147ff7e59
   ├─ beat/metrics-monitoring
   │  ├─ status: (HEALTHY) HEALTHY
   │  ├─ beat/metrics-monitoring
   │  │  ├─ status: (HEALTHY) Healthy
   │  │  └─ type: OUTPUT
   │  └─ beat/metrics-monitoring-metrics-monitoring-beats
   │     ├─ status: (HEALTHY) Healthy
   │     └─ type: INPUT
   ├─ filestream-monitoring
   │  ├─ status: (HEALTHY) HEALTHY
   │  ├─ filestream-monitoring
   │  │  ├─ status: (HEALTHY) Healthy
   │  │  └─ type: OUTPUT
   │  └─ filestream-monitoring-filestream-monitoring-agent
   │     ├─ status: (HEALTHY) Healthy
   │     └─ type: INPUT
   └─ http/metrics-monitoring
      ├─ status: (HEALTHY) HEALTHY
      ├─ http/metrics-monitoring
      │  ├─ status: (HEALTHY) Healthy
      │  └─ type: OUTPUT
      └─ http/metrics-monitoring-metrics-monitoring-agent
         ├─ status: (HEALTHY) Healthy
         └─ type: INPUT
```

**Comment by swiatekm** [comment]
I can't reproduce this based on the provided config:

```
➜  elastic-agent git:(14a599750d) ✗ sudo bin/elastic-agent-9.1.0-SNAPSHOT-linux-x86_64/elastic-agent version --binary-only
Binary: 9.1.0-SNAPSHOT (build: 14a599750d1e8cccfd1666d34e6862a147ff7e59 at 2025-06-09 08:18:56 +0000 UTC)
➜  elastic-agent git:(14a599750d) ✗ sudo bin/elastic-agent-9.1.0-SNAPSHOT-linux-x86_64/elastic-agent status --output full
┌─ fleet
│  └─ status: (STOPPED) Not enrolled into Fleet
└─ elastic-agent
   ├─ status: (HEALTHY) Running
   ├─ info
   │  ├─ id: 98be2d91-cefc-4db2-bfee-5205b85231c9
   │  ├─ version: 9.1.0
   │  └─ commit: 14a599750d1e8cccfd1666d34e6862a147ff7e59
   ├─ beat/metrics-monitoring
   │  ├─ status: (HEALTHY) HEALTHY
   │  ├─ beat/metrics-monitoring
   │  │  ├─ status: (HEALTHY) Healthy
   │  │  └─ type: OUTPUT
   │  └─ beat/metrics-monitoring-metrics-monitoring-beats
   │     ├─ status: (HEALTHY) Healthy
   │     └─ type: INPUT
   ├─ filestream-monitoring
   │  ├─ status: (HEALTHY) HEALTHY
   │  ├─ filestream-monitoring
   │  │  ├─ status: (HEALTHY) Healthy
   │  │  └─ type: OUTPUT
   │  └─ filestream-monitoring-filestream-monitoring-agent
   │     ├─ status: (HEALTHY) Healthy
   │     └─ type: INPUT
   ├─ http/metrics-monitoring
   │  ├─ status: (HEALTHY) HEALTHY
   │  ├─ http/metrics-monitoring
   │  │  ├─ status: (HEALTHY) Healthy
   │  │  └─ type: OUTPUT
   │  └─ http/metrics-monitoring-metrics-monitoring-agent
   │     ├─ status: (HEALTHY) Healthy
   │     └─ type: INPUT
   └─ system/metrics-default
      ├─ status: (HEALTHY) Healthy: communicating with pid '157184'
      ├─ system/metrics-default
      │  ├─ status: (HEALTHY) Healthy
      │  └─ type: OUTPUT
      └─ system/metrics-default-unique-system-metrics-input
         ├─ status: (HEALTHY) Healthy
         └─ type: INPUT
```

The code in https://github.com/elastic/elastic-agent/pull/8273 is also almost completely additive, with component status reporting independent per-component, and I can't figure out how we could drop a status. Can you reproduce this yourself?

**Comment by cmacknz** [comment]
I can still reproduce it with a fresh build from main, I have diagnostics now and I can see the system/metrics input being stopped which probably shouldn't be happening.

**Comment by cmacknz** [comment]
[elastic-agent-diagnostics-2025-06-09T13-36-53Z-00.zip](https://github.com/user-attachments/files/20655742/elastic-agent-diagnostics-2025-06-09T13-36-53Z-00.zip)

Diagnostics from my local machine attached, the system/metrics input gets stopped without explanation.

Some of the processors on the monitoring Beats are also wrong, they are getting `system/metrics` added which isn't right and perhaps related to this problem.

```yaml
                - data_stream:
                    dataset: elastic_agent.metricbeat
                    namespace: default
                    type: metrics
                  failure_threshold: 5
                  hosts:
                    - http+unix:///Library/Elastic/Agent-Development/data/tmp/iThI_df0cBKC6YUNGGlKscMkOfz3FBH3.sock
                  id: metrics-monitoring-metricbeat
                  index: metrics-elastic_agent.metricbeat-default
                  metricsets:
                    - stats
                  module: beat
                  period: 1m0s
                  processors:
                    # ...
                    - add_fields:
                        fields:
                            id: 1d705753-2b9a-4b5b-9512-04e2faf36736
                            process: metricbeat
                            snapshot: true
                            version: 9.1.0
                        target: elastic_agent
                    - add_fields:
                        fields:
                            binary: metricbeat
                            id: system/metrics-default # <-- Not correct
                        target: component
```
