### ISSUE TITLE
k8sobjectsreceiver - Update component

### ISSUE THREAD

**Issue by syepes** [elastic/elastic-agent#8587]
**Describe the enhancement:**
It would be great if we could have the last version of the `k8sobjectsreceiver` as the k8sobject receiver support leader election (https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/39054)

**Describe a specific use case for the enhancement or feature:**
This prevent the duplication of events when enabled:

```
      k8sobjects:
        auth_type: serviceAccount
        k8s_leader_elector: k8s_leader_elector
        objects:
          - name: events
            mode: "watch"
            group: "events.k8s.io"
            exclude_watch_type:
              - "DELETED"
```
